### ISSUE TITLE
Menu: Customize user.el

### ISSUE THREAD

**Issue by devonwa** [jkitchin/scimax#10]
When I click on `Customize user.el` under the `Scimax` menu at the top of the emacs window, I get the following:
```
let: Symbol's value as variable is void: starter-kit-dir
```

A similar issue happens with the `Help with scimax` option:
```
command-execute: Symbol's function definition is void: scimax-help
```

**Comment by jkitchin** [comment]
Thanks for reporting this. I think I just fixed it.

**Comment by devonwa** [comment]
`user.el` still needs the /user/user.example file.

`Help` works now. Just fyi, I get a warning about importing local variables.

**Comment by jkitchin** [comment]
thanks. I added the user.example file.

The importing local variables is expected. It comes from this at the end of
the help file.

# Local Variables:

# eval: (progn (require 'emacs-keybinding-command-tooltip-mode)
(emacs-keybinding-command-tooltip-mode +1))

# End:

John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu
