### ISSUE TITLE
scimax-autoformat

### ISSUE THREAD

**Issue by prtkm** [jkitchin/scimax#100]
Hi John,

I updated scimax today after quite a while. Looks like you have defined some autoformatting vars in scimax-org. It would be great to have a way to disable it interactively in a buffer. Also, it should probably not autoformat inside code blocks, tblnames, etc. 

Everytime I type in 'N2' as part of a variable or string in python, it autoformats to 'N_{2}'.

**Comment by jkitchin** [comment]
I think the two commits above address this issue. The abbreviations are not enabled by default. See https://github.com/jkitchin/scimax/blob/master/scimax.org#autoformat for details. Try it out and let me know if it works for you.

**Comment by prtkm** [comment]
I can toggle the variables now, but there is still a little issue with the behavior when emacs is started. When I first start emacs, the variables seem enabled. Then when I try to toggle the variable, I get the message that the variable is enabled, and the abbreviations are still active. If I toggle again, the variable gets disabled.

**Comment by jkitchin** [comment]
The enabled message is coming from scimax-src-keymap-mode being activated. 

You should look at M-x edit-abbrevs

and see if those are defined and saved. you may have to manually delete them from the abbrev file using the edit-abbrevs and saving it.

**Comment by prtkm** [comment]
They were saved in the abbrev file. Deleting them resolved the issue
