### ISSUE TITLE
Autocomplete isn't capitalizing correctly

### ISSUE THREAD

**Issue by jboes** [jkitchin/scimax#101]
When looking for a file using C-x C-f keystroke, hitting tab to autocomplete over a selected file does not return the capitalization correctly. For example, if I try and autocomplete into path '/DFT', emacs returns '/dft' and then tells me there's nothing in that directory.

Also, I feel the right/left arrows used to move back and forth through the directory tree as well, but do not any longer. This would be a nice feature to have back.

**Comment by jkitchin** [comment]
the left arrow should work as it did before. I don't know what happened to the right arrow, but I think I have pushed that back. 

I can't reproduce the capitalization issue.  How sure are you that there is not an empty directory called dft in that directory?

**Comment by jboes** [comment]
There doesn' seem to be. Could it be specific to MacOS?

**Comment by jkitchin** [comment]
I doubt it. If I try this on my mac in a directory containing DFT, and type in dft, It selects the correct entry. On the other hand, if you are typing /dft at the prompt I do get an empty directory. Are you putting a / at the beginning?

**Comment by jboes** [comment]
Double checked and there's definitely no dft directory. 

Type 'D', ivy shows one directory: 'DFT/'
press 'tab', autocomplete returns 'dft/'

Interestingly, I just found out that if I press 'd' and hit 'tab' twice, then autocomplete returns 'DFT'

**Comment by jkitchin** [comment]
Is this still an issue? (with updated ivy?)
