### ISSUE TITLE
Labeling and captioning figures for latex export

### ISSUE THREAD

**Issue by roblem** [jkitchin/scimax#102]
I have been unsuccessful labeling and captioning a figure produced by an src block in latex output much like I have done in the past using techniques like [this](https://emacs.stackexchange.com/questions/12150/add-caption-to-an-image-generated-by-a-code-block). 

If I `:export both`, I have been able to produce a pdf that labels and captions the figure but instead of it being Figure 1, it says Listing 1.  Am I on the wrong track trying to do it this way?

**Comment by jkitchin** [comment]
Can you post a minimal example of what you are trying to do, e.g. a small org-file?

**Comment by jkitchin** [comment]
One of these methods might work for you:

```
* caption

** Method 1 with value
   
1. [[first]]
2. [[second]]

<<second>> Setup the caption and label and the named results. When you run the code block it will put the results here.

#+CAPTION: Org Fig
#+LABEL: fig:org-fig
#+ATTR_LATEX: :width 0.5\textwidth
#+RESULTS: fig:org_fig
[[file:myfig.pdf]]



<<first>>
First make a src block, give it a name and put it somewhere.

#+NAME: fig:org_fig
#+BEGIN_SRC python :results value file myfig.pdf
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
fig=plt.figure(figsize=(3,2))
plt.plot([1,3,2])
fig.tight_layout()
plt.savefig('myfig.pdf')
return 'myfig.pdf' # return this to org-mode
#+END_SRC


** Alternative

Here you just print what you want to a named result

#+RESULTS: fig-w-caption
:RESULTS:
#+CAPTION: Some caption
#+LABEL: fig-2
#+ATTR_LATEX: :width 0.5\textwidth
[[./myfig-2.pdf]]
:END:


#+NAME: fig-w-caption
#+BEGIN_SRC python :results org drawer :exports results
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
fig=plt.figure(figsize=(3,2))
plt.plot([1,3,2,5,6])
fig.tight_layout()

fname = 'myfig-2.pdf'
plt.savefig(fname)
print('#+CAPTION: {}'.format('Some caption'))
print('''#+LABEL: fig-2
,#+ATTR_LATEX: :width 0.5\\textwidth
[[./{}]]'''.format(fname))
#+END_SRC


```

**Comment by roblem** [comment]
Thanks and apologies for not providing examples.  The methods you propose above definitely work.  I was hoping it would be possible to use the existing latex export machinery by wrapping environments around figures, since the code already has mechanisms for saving png's in the ipython-inline-images folder and using those for exports. I was trying things like these 3 methods (none work):

```emacs-lisp
See figure ref:fig:1, ref:fig:2, and ref:fig:3 for the results.

** Method 1

#+NAME: happy-angel-grey-Ten
#+CAPTION: My Histogram
#+LABEL: fig:1
#+BEGIN_SRC ipython :session :ob-ipython-results image/png :exports results
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
x = np.random.randn(1000) * 40 + 500
plt.hist(x)
#+END_SRC

#+RESULTS: happy-angel-grey-ten
:RESULTS:
[[file:ipython-inline-images/ob-ipython-e0f39cd07629d8a37fe26d5e118a7803.png]]
:End:

** Method 2

#+NAME: sodium-quiet-wyoming-one
#+BEGIN_SRC ipython :session :ob-ipython-results image/png :exports results
x = np.random.randn(1000) * 40 + 1000
plt.hist(x)
#+END_SRC

#+RESULTS: sodium-quiet-wyoming-one
#+CAPTION: My Second Histogram
#+LABEL: fig:2
:RESULTS:
[[file:ipython-inline-images/ob-ipython-6a7303ed9b01f1c72057414ed8a26ff6.png]]
:End:

** Method 3

#+NAME: minnesota-johnny-eleven-london
#+CAPTION: My Third Histogram
#+LABEL: fig:3
#+BEGIN_SRC ipython :session :ob-ipython-results image/png :exports both
x = np.random.randn(1000)
plt.hist(x)
#+END_SRC

#+RESULTS: minnesota-johnny-eleven-london
:RESULTS:
[[file:ipython-inline-images/ob-ipython-a2f91cbc65e63d68c0704f0770e3b715.png]]
:END:
```

- Method 1 doesn't work at all
- Method 2 references work, but there is no figure header/caption
- Method 3 (note, you have to use `:exports both`) wraps the results in a listings environment behind the scenes and is successfully referenced in latex using `ref:fig:3`, but it is called "Listing 1" rather than "Figure 1". 

And it is worth mentioning that if some of the src blocks are re-executed, the caption/label environments are detached from the results or additional figures are generated so even the partially successful results (Method 3) is broken after that.

**Comment by jkitchin** [comment]
Method 1 would not work. There you are labeling a src block, and I would expect you get a Listing reference to that label. Try something like this:

```
#+NAME: sodium-quiet-wyoming-one
#+BEGIN_SRC ipython :results raw :ob-ipython-results image/png :exports results
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

x = np.random.randn(1000) * 40 + 1000
plt.hist(x);

print('#+NAME: fig-2')
print('#+CAPTION: My Second Histogram', end='')
#+END_SRC

#+RESULTS: sodium-quiet-wyoming-one
#+NAME: fig-2
#+CAPTION: My Second Histogram
[[file:ipython-inline-images/ob-ipython-221e68ff7d74d74143cc2c8fb67d96c8.png]]


See Fig. ref:fig-2.

```

This will only work with one figure per src block though.

**Comment by roblem** [comment]
That is exactly what I am trying to accomplish.  Thanks.
