### ISSUE TITLE
C-s is not functioning in latest commit

### ISSUE THREAD

**Issue by jboes** [jkitchin/scimax#103]
The search command is not working properly in the latest commit.

When using C-s on MacOS, I get "error 2" after entering the first two letters.

 After mashing the key for a bit, the Ivy interface will stop eating the input and keep typing. Attempting to search down the list of results with the arrow keys results in:

``` sh
redisplay--pre-redisplay-functions: (args-out-of-range 1185 1185)
```

Which then exits the Ivy interface without any result returned. 

This does not happen in commit e87f376, which was the last instance of Scimax I was using.

**Comment by jkitchin** [comment]
I can't reproduce that. I tried with a new elpa and fresh pull. Not sure why any changes would cause that. redisplay--pre-redisplay-functions is a function deep in emacs. What version of emacs are you using, and where did you get it?

**Comment by prtkm** [comment]
I get the same error as Jake with Homebrew emacs 26.0.50

**Comment by jboes** [comment]
I think homebrew? I still don't fully understand my Mac....

 version 25.2

**Comment by jkitchin** [comment]
I wonder if this is due to scimax-src-keymap-mode. If you turn this off (M-x scimax-src-keymap-mode) should toggle it off, does this go away?

**Comment by jboes** [comment]
Yup, that seems to have fixed it.

**Comment by jkitchin** [comment]
ok, thanks. I will remove the code that defaults it to be on.

**Comment by prtkm** [comment]
works for me too
