### ISSUE TITLE
async ipython stderr as results?

### ISSUE THREAD

**Issue by prtkm** [jkitchin/scimax#104]
Hi John,

Is there a way to make async ipython behave like async python when the code block returns an error? For async python, I really like that I am able to click on the link to the exact line of the file where the error occurred. For async ipython, the error traceback is in a separate buffer (which is ok), but its just plain text which cannot be interacted with.

**Comment by jkitchin** [comment]
What happens when you press q in the exception buffer? It should bury it and jump to the line with the error.

**Comment by prtkm** [comment]
Hmm. Pressing q does return to the line with the error, but burying the exception buffer makes the traceback disappear, which is a little inconvenient for debugging.

**Comment by jkitchin** [comment]
Fair point. I added "j" to jump without closing the window, and "q" to jump and bury the buffer.

**Comment by prtkm** [comment]
That seems to be working
