### ISSUE TITLE
Seeking ideas for selective exporting of org blocks to ipynbs

### ISSUE THREAD

**Issue by singletS** [jkitchin/scimax#105]
As ox-ipynb has grown, so have my class materials. Thanks! A side-effect is that my org file structure is getting more complex. I'm still tinkering with how to use a single org file to generate ipynbs for both assignments and answer keys (analogous to LaTeX version blocks).  I really like the idea of "solution" cells appearing right after the problem statement so students don't have to scroll up and down the notebook. I've tinkered with heading tags, TODO types, drawers, and special blocks. Each seems to have shortcomings, but I'm probably missing a clever feature of org-mode.

(I currently use dynamic blocks to auto-number exercises and problems, but in the snippets below, I just manually numbered them.)

## Heading tags and TODO types
This is just wrong from a document structure standpoint. Exercise 2 is a child of Solution, not Exercises, so folding (both org and ipynb) is messed up (so is TOC numbering, but I rarely use that.)

```
#+EXCLUDE_TAGS: key

* Exercises
1. Write a python function that squares an argument.
#+BEGIN_SRC ipython :eval no
def square(x):
    "write your function"
    return
#+END_SRC

** Solution :key:
Here's one way to do it if x is a number.
#+BEGIN_SRC ipython
def square(x):
    "return the square of an argument"

    return x*x
#+END_SRC

2. Write a function that cubes an argument.

   #+BEGIN_SRC ipython :session
   def cube(x):
       return
   #+END_SRC
```

## Drawers 
Drawers cannot be nested so can't contain an ipython block:

```
:SOLUTION:
Here's one way to do is if x is a number.
#+BEGIN_SRC ipython
def square(x):
    "return the square of an argument"

    return x*x
#+END_SRC

#+RESULTS:
:RESULTS:

:END:

:end:  # of :SOLUTION:
```

## Special blocks
Requires the backend(s) understands what to do with them and know the exact name of the special blocks (custom def?). Seems a fragile solution to me. One possibly useful thing is that special blocks could be exported as css-styled cells in the ipynb..."solution" cells could have a consistent background color, but this can be accomplished through other means in org mode.

Do any other approaches come to mind? Maybe students/instructors have different ideas for designing assignments and solution keys?

Thanks

**Comment by jkitchin** [comment]
I use tags and a simpler document structure. Every problem is defined as a headline, and the solution as a subheading of that headline. You might be able to put solutions into an inline task and not mess up the hierarchy.

You could use a custom block with different filters that selectively set the output to nil or to the solution.

**Comment by singletS** [comment]
Your mention of headings got me re-thinking my approach. The notebooks are getting rather complex and should probably be refactored into smaller, flatter chunks.

Thanks for the useful suggestions (inline tasks are yet another feature of org mode I haven't explored).

**Comment by singletS** [comment]
Another alternative:
```
(require 'ox-extra)
(ox-extras-activate '(ignore-headlines))
```
and add tag `ignore` to headline.
From https://emacs.stackexchange.com/questions/9492/is-it-possible-to-export-content-of-subtrees-without-their-headings
