### ISSUE TITLE
Space after ref behaves like return

### ISSUE THREAD

**Issue by prtkm** [jkitchin/scimax#107]
Hi John,

If I try to write something like "Figure ref:some-fig" and then press space after the reference my point moves to the next line instead of inserting a space. Is is a recent change/bug?

**Comment by jkitchin** [comment]
It is a recent bug. I have not been able to figure it out though. It's really weird. High priority to fix too! I think it is something in scimax.

**Comment by jkitchin** [comment]
The real issue seems to be something is triggering a save-buffer call when point is after a ref link. that was triggering the ws-butler issue.

**Comment by jkitchin** [comment]
and it seems that was something in org-ref. I just pushed a commit that removes those. Should fix it up. Thanks for reporting it.

**Comment by prtkm** [comment]
This works now. :)
