### ISSUE TITLE
Typing in a different python / ipython block when an ipython block is running

### ISSUE THREAD

**Issue by prtkm** [jkitchin/scimax#108]
Hi John,

If I edit a python/ipython block while running some ipython block, I get the message "Contacting host: localhost:9988" and my emacs gets frozen. 

I think this is related to some elpy completion requests ( https://github.com/jkitchin/scimax/issues/95), turning company-mode off seems to fix the problem.

**Comment by jkitchin** [comment]
That is annoying. You can turn off completion with (setq org-babel-ipython-completion nil). I guess the kernel server can't handle multiple requests, but I am not sure. I added some code to avoid completion when a cell is running for now.
