### ISSUE TITLE
"comment-or-uncomment-region" command looses cursor position

### ISSUE THREAD

**Issue by jboes** [jkitchin/scimax#11]
I noticed that the comment-or-uncomment-region "works" in org-mode now. Unfortunately, it also resets cursor to the beginning of the code block which is disruptive. Any way to have this information stored and later returned before switching into python mode?

**Comment by jkitchin** [comment]
I think you want comment-dwim (M-;) It seems to "do what I mean" without moving the point. The only way I know to fix the comment-or-uncomment-region command is to "advise" it by wrapping it with save-excursion.

**Comment by jboes** [comment]
Comment-dwin seems to work well enough. Thanks!
