### ISSUE TITLE
`Eager macro-expansion failure` when starting emacs

### ISSUE THREAD

**Issue by et2010** [jkitchin/scimax#110]
After emacs started, I can see following error message in the `*Message*` buffer:

```
Eager macro-expansion failure: (wrong-number-of-arguments (lambda (val x) (\` (setf (gethash (ob-ipython-get-kernel-name) *org-babel-async-ipython-queue*) (\, val)))) 1)
```

I think it is caused by https://github.com/jkitchin/scimax/blob/master/scimax-org-babel-ipython.el#L641, but I don't know how to fix it.

**Comment by jkitchin** [comment]
it could be the extra x arg. I pushed a commit to remove that. hopefully everything else still works.

**Comment by et2010** [comment]
It works! Thanks for the quick fix!
