### ISSUE TITLE
Line numbers stick around too long after failed asynchronous python runs.

### ISSUE THREAD

**Issue by jboes** [jkitchin/scimax#112]
Running a code block asynchronously will result in line numbers being displayed within the code block and the cursor is moved to the point of failure.

However, after reentering the code block to make changes, the line numbers will persist. This occasionally interferes with the perceived indentation of the code and can make editing quite difficult and obnoxious. 

Running any code block successfully (even an empty one) will remove the line numbers, but this is a hassle as well.

![screen shot 2017-07-18 at 14 24 39](https://user-images.githubusercontent.com/2288204/28340651-5a798d70-6bc5-11e7-8b23-e8ce90048775.png)

**Comment by jkitchin** [comment]
I see what you mean. This is a tricky issue I think. You can click on the numbers and they will go away, and as you noted, running a code block will also make them go away.

This tricky part is getting them to go away when you want them too. As it is, they don't update, and your numbers above are not correct. I tried one way to get them to update, but it appears there are many corner cases to consider like adding lines, deleting lines, cutting lines, pasting lines, ... to get it to work flawlessly.

How useful are the line numbers? you can turn them off with (setq org-babel-async-python-show-line-numbers nil)

**Comment by prtkm** [comment]
I personally don't find the line numbers to be particularly useful, but the visual cue that shows the line of failure is helpful.

A possible solution may be to make it so that the line numbers go away once the code block is edited (since the line numbers don't update and are no longer meaningful), not sure how easy that is to implement.

**Comment by jkitchin** [comment]
If you don't like them, then just turn them off! That shouldn't change the visual cue of what line caused the problem. It is possible to get them to update sometimes, but getting them to update the right way all the time isn't straight forward I think.

**Comment by jboes** [comment]
I vaguely remember these numbers removing themselves following any modification to the code block, which was ideal, imho.

Not using them at all is also suitable, but since it isn't obvious that you can just click the numbers to have them removed, it may be more user-friendly to have this off by default.

**Comment by jkitchin** [comment]
I pushed something that should make the lines update.

**Comment by jkitchin** [comment]
although, I now see that doing that will make them not agree with the error message anymore! Maybe it is best to just turn them off if you don't like them. What I had in mind is you would just fix one line where the error was and the updates wouldn't matter.

**Comment by jboes** [comment]
That will be true whether you use the line numbers or not though, so it's not really a failure of the line numbering after that point.

As long as it doesn't garble the indentation, I'd be happy.

**Comment by jboes** [comment]
Very happy with the updating line numbers in the new commit and I no longer seem to notice any poorly formatted indentations. 

However, C-c C-c no longer seems to work... So that's a bit of a deal breaker.

**Comment by jkitchin** [comment]
weird. I pushed another fix that might address that for you.

**Comment by jboes** [comment]
Haha. C-c C-c works again, but now the line numbers are not updating like they did in the previous commit.

**Comment by jkitchin** [comment]
Ok, take here take 3.

**Comment by jboes** [comment]
Wonderful, my compliments to the chef.
