### ISSUE TITLE
Simple spelling corrections need to be off in code block

### ISSUE THREAD

**Issue by jboes** [jkitchin/scimax#115]
There are simple capitalization corrections which are not compatible with the code blocks.

i.e. defining a variable named 'whos' in a code block will automatically replace itself with 'who is'.

Convenient when typing text, but not for code. Org-mode is also attempting to be intelligent about capitalization in the same way, which is also incredibly frustrating when defining variables with multiple capitalized letters.

**Comment by prtkm** [comment]
M-x dubcaps-mode can toggle the auto capitalization. The 'whos' formatting may be related to this issue https://github.com/jkitchin/scimax/issues/100

**Comment by jboes** [comment]
Thanks, that solved it.
