### ISSUE TITLE
Supress requests to execute iPython cells during `ox-ipynb` export.

### ISSUE THREAD

**Issue by chase-dwelle** [jkitchin/scimax#116]
Thank you for the great tool. Right now, exporting to `ipynb` format requests an answer for 

> Evaluate this ipython code block on your system? (yes or no)

For every ipython cell involved in export. This can be tedious for notebooks with a lot of cells. I don't necessarily see the reason for evaluation, since the cells need to be evaluated in the Jupyter notebook anyway.

Is there a way to set default behavior, either "execute all" or "don't execute all"?

**Comment by singletS** [comment]
org-babel settings control execution of source blocks; `(org-confirm-babel-evaluate nil)` will turn off the prompt when executing code cells.

To prevent evaluation of particular source blocks, a header arg can be used:
`#+BEGIN_SRC ipython :eval no`

If you don't want any ipython blocks evaluated, you might try (not tested) setting a file property:
`#+PROPERTY: header-args:ipython  :eval no`

or set  `org-babel-default-header-args` as desired:
http://orgmode.org/manual/Header-arguments.html

**Comment by chase-dwelle** [comment]
Thanks for the fast response, setting the file property to 
`#+PROPERTY: header-args:ipython :eval no` did suppress the output on export, which solved my issue.
