### ISSUE TITLE
Latex Export: *Org PDF LaTeX Output* Empty 

### ISSUE THREAD

**Issue by roblem** [jkitchin/scimax#118]
Export this org file (using either C-c C-e l-o (latex) or  C-c C-e j-o (ox-manuscript)):
```lisp
\begin{equation}
a = \frac{b}{c
\end{equation}
```
Of course the export fails due to the syntax error and the missing closing bracket, and this shows in the messages buffer:
```
org-compile-file: File "/some/directory/debug_latex.pdf" wasn’t produced.  See "*Org PDF LaTeX Output*" for details
```
Opening the `*Org PDF LaTeX Output*` buffer reveals it is empty with no information for debugging issues with the latex code.

**Comment by jkitchin** [comment]
I don't think this is a scimax issue, I think that is in org-mode. I recommend in a case like this to run M-x ox-manuscript-toggle-interactive-build, and try the export again. This will show you more information that is useful.

**Comment by roblem** [comment]
Thanks, that helps with the output. 

I should mention that *Org PDF LaTeX Output* contains the full latex build log on stand-alone emacs (read as no scimax) on my machine.

**Comment by Cumol** [comment]
I have the same issue and it seems to be scimax-specific.

When I export a file (that has some error) using scimax, the buffer is empty. If I export the same file using vanilla emacs, I get a full buffer.

Any idea what is happening here?

**Comment by jkitchin** [comment]
in scimax I use `(setq org-latex-pdf-process 'ox-manuscript-latex-pdf-process)` which outputs to different buffers, e.g. *latex*, *bibtex*, etc. This gets called in the native org export function, e.g. C-c C-e lo. 

I did this so I could add some conditional things like building a glossary or index, and some other debugging kinds of things. I am looking through this code again, and it looks like it could use some redesign perhaps, or some separation from C-c C-e lo at least, or to put output in *Org PDF LaTeX Output*.

It will take me some time to go through this. ox-manuscript is also able to do some munging for making latex files for some special situations and I want to make sure that is preserved.

**Comment by Cumol** [comment]
Does it mean that the function splits the normal _Org PDF LaTeX Output_ into different buffers? I only found *makeglossary* but no buffer containing the output to debug. 

How do you deal with this currently? Do you simply go to the .log file and check there or is there a workaround?

**Comment by jkitchin** [comment]
I usually run M-x ox-manuscript-toggle-interactive-build on troublesome builds, which is not perfect, but which usually shows me the output of the problematic command and prompts me to continue. 

Sometimes I also just export to tex, and then run the commands in shell. This is also more tedious than i would prefer.

You can get the original behavior with:

```
(setq org-latex-pdf-process '("%latex -shell-escape -interaction nonstopmode -output-directory %o %f"
			      "%bibtex -output-directory %o %f"
			      "%latex -shell-escape -interaction nonstopmode -output-directory %o %f"
			      "%latex -shell-escape -interaction nonstopmode -output-directory %o %f")
      org-latex-remove-logfiles t
      org-latex-logfiles-extensions '("aux" "bcf" "blg" "fdb_latexmk" "fls"
				      "figlist" "idx" "log" "nav" "out" "ptc"
				      "run.xml" "snm" "toc" "vrb" "xdv"))
```

I think a lot of what is in ox-manuscript needs some review and probably at least a little fixing up.
