### ISSUE TITLE
Emacs help-for-help function does not work

### ISSUE THREAD

**Issue by oolivier107** [jkitchin/scimax#119]
I have installed scimax on my PC (windows 7 - 64) and when I try to launch the help on help (C-h C-h) emacs I get  a "wrong-type-argument stringp, nil". Here are some more details after invoquing the debugger (M-x toggle-debug-on-error) :

Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("%THIS-KEY%" nil)
  help-for-help()
  funcall-interactively(help-for-help)
  call-interactively(help-for-help nil nil)
  command-execute(help-for-help)

I have checked with the emacs-25.2.exe executable file from http://ftp.gnu.org/gnu/emacs/windows/ and the help-for-help function is fine. 
I suppose the issue could be due to some specific settings of the emacs distributed with scimax but I have no idea where and how to solve the problem. 
Does anyone has the same trouble ?

**Comment by jkitchin** [comment]
I can confirm that is a bug in the emacs provided in the emacs-win repo (https://github.com/jkitchin/emacs-win). It is not necessary to use that emacs, it is just provided for convenience since it comes bundled with a lot of libraries that the gnu site doesn't provide I think.

**Comment by oolivier107** [comment]
Thanks for your prompt answer and I appreciate the bundle of libraries provided with the emacs executable. I will do with this (very small) issue (all the other help commands work) and continue my tests with scimax; seems to be a very nice package.

**Comment by jkitchin** [comment]
I think if you just add (load-library "help") to your init file then C-h C-h will work. I don't know why it isn't loaded correctly from the start though.

**Comment by jkitchin** [comment]
I just pushed a commit that loads that library.
