### ISSUE TITLE
Recent org update breaks scimax

### ISSUE THREAD

**Issue by et2010** [jkitchin/scimax#120]
It's this commit:
http://orgmode.org/cgit.cgi/org-mode.git/commit/?id=b862c24b9fb2591dc6240bfbd3a9829c72d9b970

that is causing async run of ipython block to hang. But I haven't figure out how.

**Comment by et2010** [comment]
In case you have already updated org, you can revert this commit:

```sh
patch -R -i 0001-ob-core-Fix-org-babel-goto-named-src-block-at-point-.patch
```

**patch file:**
[0001-ob-core-Fix-org-babel-goto-named-src-block-at-point-.zip](https://github.com/jkitchin/scimax/files/1226215/0001-ob-core-Fix-org-babel-goto-named-src-block-at-point-.zip)

**Comment by jackmcrider** [comment]
Thank you, et2010, for helping out with that.

I don't know if this is related to your issue, but I still observe strange behaviour in asynchronous blocks.
Whenever point is not in the #+NAME: <name> line of a SRC block, the very first SRC block in the buffer is unfolded (if it was folded) and the [async-queued: <name> output] message appears in the results drawer of the block that I intended to execute, but it never actually runs. If point is placed in the #+NAME: <name> line, C-c C-c executes the block asynchronously.

Because both issues are related to block names, perhaps there is a single fix for both problems.

**Comment by et2010** [comment]
I think we're having the same issue. And I think that the reason why you can execute succsessfully when the point is in the `#+NAME:` line is because you are actually executing the block synchronously.

My speculation is based on this observation:

If you execute following block asynchronously:
``` org
#+name: my-example
#+begin_src ipython
print(1)
#+end_src
```
the result will be like:
``` org
#+RESULTS: my-example
:RESULTS:
1
:END:
```
If you execute synchronously (i.e. when run from `#+name:` line) you will get:

```
#+RESULTS: my-example
:RESULTS:
1

:END:
```
They are different! As there is an extra blank line following the actual result when you do it synchronously.

**Comment by roblem** [comment]
I am also seeing this issue.   As @jackmcrider shows above, need to C-c C-c on `#+name` to execute codeblocks.  This workaround works for me without the patch.  Org mode version 9.0.9 20170814.

**Comment by jkitchin** [comment]
How funny. @et2010, you are right. C-c C-c executes scimax-execute-ipython-block, and in the first line when you are on the #name block (org-in-src-block-p) evaluates to nil so the whole block is executed synchronously.

**Comment by roblem** [comment]
Another piece of the puzzle perhaps:

Run this
```
#+NAME: kansas-jersey-november-november
#+BEGIN_SRC ipython :session
import pandas as pd
print("Hey")
#+END_SRC
```
gets this after executing on `#+NAME`
```
#+RESULTS: kansas-jersey-november-november
:RESULTS:
Hey

:END:
```
Now execute some code that throws a debug error:
```
#+NAME: lion-magnesium-sodium-louisiana
#+BEGIN_SRC ipython :session
print("Obvious syntax error"
#+END_SRC
```
leads to the debug output in the *previous* results block and overwriting everything:
```
#+RESULTS: kansas-jersey-november-november
:RESULTS:
[[elisp:(progn (ob-ipython-jump "nil" "nil" 1)(forward-char 28))][  File "<ipython-input-6-13c978ab1a11>", line 1]]
    print("Obvious syntax error"
                                ^
SyntaxError: unexpected EOF while parsing

:END:
```

**Comment by et2010** [comment]
@roblem I can confirm. The debug output just overwrites the result of  the first ipython block in current buffer. And I have my org-mode patched.

**Comment by et2010** [comment]
The original issue has been fixed upstream: http://orgmode.org/cgit.cgi/org-mode.git/commit/?id=21a8ec1c0f4d1797288a12cd9bfc6446a2ac03cb

**Comment by et2010** [comment]
It seems that the recent org 9.1 is a major release and a lot of breaking changes have been made. So I'm reopening this. 

If you want to use scimax, **do not** update to org 9.1. At least not for now. You've been warned.

**Comment by et2010** [comment]
Sorry, my bad. 

I feel stupid...
