### ISSUE TITLE
Code Completion Overwriting Code

### ISSUE THREAD

**Issue by roblem** [jkitchin/scimax#121]
This may be an upstream issue or expected behavior.  When in an org src codeblock, I am doing something in python like this:
```
import pandas as pd
df = pd.DataFrame([[1,2],[3,4]],co
```
and the completion system suggest `columns=`, which is what I need so I "enter complete" it, and I get this:
```
df = pd.DataFrame([[1,2],columns= 
```
which overwrites part of my dataframe definition.  Things work fine if
1. In an org src python block I add spaces after commas, so
     ```
     import pandas as pd 
     df = pd.DataFrame([[1,2],[3,4]], co
     ```
     completes to the correct
     ```
     df = pd.DataFrame([[1,2],[3,4]], columns=
     ```
2. I edit the original codeblock (note no space after comma) using `org-edit-src-code`
     ```
     import pandas as pd 
     df = pd.DataFrame([[1,2],[3,4]],co 
     ```
     completes to the correct
     ```
     df = pd.DataFrame([[1,2],[3,4]],columns=    
     ```
I should also mention this isn't only a pandas issue.  While I generally clean code using autopep8 and try to put spaces after commas, I sometimes forget and I am finding myself having botched completions more than I'd like.

**Comment by jkitchin** [comment]
This sounds like a but. If you set org-babel-ipython-completion to nil, does the problem go away? Alternatively, you might be able to turn it off with (company-mode -1).

I guess the problem might be in the ob-ipython-company-backend function.

I am in the middle of a move to start a sabbatical, so it could take a while before I can investigate. I can't think of what would cause that though, I think it is setup to use regular company completion.

**Comment by roblem** [comment]
Packing to return from a sabbatical, so I know where you are coming from as far as time goes.

> If you set org-babel-ipython-completion to nil, does the problem go away?

No

> Alternatively, you might be able to turn it off with (company-mode -1)

This turns off autocompletion completely, which I use alot, so not really an option for me.  

Not much of a lisp programmer, but I'll poke around the function you mentioned.

**Comment by jkitchin** [comment]
you would have to restart emacs after changing that variable. Alternatively, you might try removing 'ob-ipython-company-backend from the company-backends list.

**Comment by roblem** [comment]
> If you set org-babel-ipython-completion to nil, does the problem go away? you would have to restart emacs after changing that variable.

Made the change and restarted emacs and completion in an org buffer src block is turned off (completion in org-edit-src-code still works).

**Comment by roblem** [comment]
I think if the regex in [ob-ipython-company-backend](https://github.com/jkitchin/scimax/blob/e432c34c5006b0cb77efaef60afeb0d1e14c5c9e/scimax-org-babel-ipython.el#L645) is changed to something like this (adds commas to the reverse search)
```bash
" \\|[[,({]\\|^"
```
and p (or point) is incremented by +1 (I am a lisp idiot, so apologies I don't have time to figure out how to code this and submit a full PR for fixing this) it should work based on my limited testing, since with the above regular expression change
```
df = pd.DataFrame([[1,2],[3,4]],col
``` 
completes to 
```
df = pd.DataFrame([[1,2],[3,4]]columns=
```

**Comment by jkitchin** [comment]
Thanks. that looks correct. I pushed a fix for it. Let me know if that solves the problem for you.

**Comment by roblem** [comment]
This is working for me noting that:
1. Whitespaces at the beginning of the completion (even pep8 compliant ones) are stripped.  You can just `autopep8` the codeblock afterwards, so no big deal.  
2. Beginning of line completions (ones with no `=`) have issues:
    ```
    df.hea
    ```
    completes to
    ```
    ddf.head()
    ```
These are very minor and the completion system is working much better for me now.
