### ISSUE TITLE
Adding User Customizations to scimax

### ISSUE THREAD

**Issue by shamindras** [jkitchin/scimax#123]
I am new to relatively new to emacs but have really enjoyed working with scimax so far.

I wanted to understand how to add **user customizations** to scimax. For example, I wanted to customize latex using `AucTeX` by adding [this snippet](https://github.com/Schnouki/dotfiles/blob/master/emacs/init-20-tex.el) in the `init.el`

I dug through the scimax codebase and it appears that we need to update the `user.example` file [here](https://github.com/jkitchin/scimax/blob/be97e7733f3950040e09c0a3dcbf727602947a7d/user/user.example#L1) with customizations.

I pasted the above snippet in the `user.example` but had the following issues/ questions:

1. Is `user.example` the correct place to add customized snippets? I tried it and it doesn't seem to show `AucTeX` when I reload emacs and a new `tex` file.
2. I noticed that the entire `user/` folder is in [gitignore](https://github.com/jkitchin/scimax/blob/be97e7733f3950040e09c0a3dcbf727602947a7d/.gitignore#L6). Is there anywhere else I should be pasting the above AucTeX snippet so that I can make persistent customizations i.e. changes I can commit?

Could anyone please offer guidance on the above or direct me to an appropriate section in the manual? Apologies if these queries are already answered elsewhere.

**Comment by roblem** [comment]
All of my customizations are in `user/user.el` and customizations are picked up by scimax just fine.

**Comment by jkitchin** [comment]
You should rename user.example to user.el

The changes should be persistent without committing them to the repo. You can either remover user from gitignore to make it easy to add, or use the -f option on git add to force them to be added.

I think the only place you would find this is under the scimax menu: Customize user.el, which would probably create the user.el file for you.

**Comment by shamindras** [comment]
Thanks @roblem  and @jkitchin - that worked well. 

@jkitchin Forcing the user.el to be added was a great suggestion. This way I can replicate my setup across computers easily. Also thank you for creating and sharing `scimax` it is a wonderful resource.

**Comment by jkitchin** [comment]
Thanks for letting us know that worked! I am glad you find scimax useful!
