### ISSUE TITLE
Add a column in hydra for foreground main colors

### ISSUE THREAD

**Issue by hisnawi** [jkitchin/scimax#130]
I see myself doing this more than highlighting and I prefer rather have a separate column in hydra for quick access.

**Comment by jkitchin** [comment]
Hydras arent that easy to configure on the user side. The best thing would be to create your own (maybe using the one in this package as a template, or adding to it). see all the lines with ov-make-highlight in them to see how to make the highlight commands.

**Comment by hisnawi** [comment]
Yup figured how to do that, thank you.
