### ISSUE TITLE
Keep the ov-highlighter metadata at the top of the file and not bottom

### ISSUE THREAD

**Issue by hisnawi** [jkitchin/scimax#131]
Adding content continuously to the file I have to keep pushing the mata-data down. Where if it was at the top it won't interfere with any editing flow.

**Comment by jkitchin** [comment]
I am not sure this can be done in a robust way. There are only two ways to put file variables in: in the first line (which might conflict with some users who have other values there), and in a section that pretty much has to be at the end of the file (at least within 3000 characters of the end).

**Comment by hisnawi** [comment]
Got it. No problem.
