### ISSUE TITLE
Any future plans to add ov-highlighter to melpa?

### ISSUE THREAD

**Issue by hisnawi** [jkitchin/scimax#132]
This is a very useful package and having it on melpa (even if not ready for prime time) will allow more people to test it.

**Comment by jkitchin** [comment]
How about if you work with it for a while and if you don't find any deal breaking bugs, I will work on transferring it to MELPA. It isn't a package I use much so it doesn't get much attention!

**Comment by hisnawi** [comment]
Sounds good. Thanks.

**Comment by hisnawi** [comment]
Just a quick note. I have been testing ov-highlighter extensively for the last 3 weeks or so and have no bugs whatsoever. I would really love to see it in Melpa.

**Comment by jkitchin** [comment]
Inching forward. Check out https://github.com/jkitchin/ov-highlight. I had to do some refactoring to be melpa compliant. the font size changing functions are a little janky, but kind of work like they should. I think it should be backwards compatible with the previous version, but some function names have changed lightly.

**Comment by hisnawi** [comment]
Thanks. Will start testing it.

**Comment by jkitchin** [comment]
This package has some fragile parts that I think limit its usefulness. I think it works great if you don't do much text rearranging. But, if you do much text rearranging, there is a lot of risk of losing annotations, e.g. moving org sections around with org commands, refiling, etc. I am going to leave the repo up, but for now I don't think I will put in MELPA until a more robust solution is made.
