### ISSUE TITLE
Enhancement: Have an undo option in ov-highlighter list

### ISSUE THREAD

**Issue by hisnawi** [jkitchin/scimax#133]
I pressed "k" by mistake on some of my highlighted notes in the list view, unfortunately there was no way for me to undo that. Would be great if this option is integrated.

**Comment by jkitchin** [comment]
Seems like a good idea. I have implemented a version that I am pretty sure enables this. Let me know if it works for you.

**Comment by hisnawi** [comment]
Undo/redo works now when editing the file. But I was actually referring to the list of all highlights that you get from hydra "_l_:list" Is it possible to undo accidental deletions there?

**Comment by jkitchin** [comment]
I tried to implement that, but it did not work well. Another day I will try it again when I have more time.

**Comment by jkitchin** [comment]
I am not sure this undo is possible.
