### ISSUE TITLE
Scimax installation on Win10:  "start: invalid option: -1"

### ISSUE THREAD

**Issue by willtm** [jkitchin/scimax#136]
Hello,

I'm attempting to install scimax on Windows 10 64-bit and appear to be successful (git cloning, package downloading appears to proceed normally).  However, the automatic startup process that occurs after installation ends fails with the following message:

`Opening scimax.  Be patient.`
`start: invalid option: -l`
`Try start --help for more information.`

I've tried starting Emacs by invoking `.../scimax/emacs-win/bin/runemacs.exe` but it also results in an error.

Can you provide any troubleshooting tips for what might be happening?  I don't think this is a scimax problem but I can't figure out what the Windows issue might be.

[scimax-startup-error.txt](https://github.com/jkitchin/scimax/files/1347605/scimax-startup-error.txt)

**Comment by jkitchin** [comment]
I guess it is choking on a -l option to emacs, e.g. in a line like:
https://github.com/jkitchin/scimax/blob/master/install-scimax-win.sh#L35

**Comment by willtm** [comment]
Interesting.  Could it be a problem with `git` or `bash` on Windows?

**Comment by jkitchin** [comment]
It is hard to say. I have no access to a windows machine these days to try it out. It was working fine on git-bash a few months ago for me.

**Comment by willtm** [comment]
Yeah, it was working fine for me until about an hour ago.  I'm only rebuilding `scimax` after having my Emacs packages update break.

**Comment by jkitchin** [comment]
Is this still an issue? It seems to be working fine on a windows machine right now.
