### ISSUE TITLE
python-indent-left/right function improvement?

### ISSUE THREAD

**Issue by jboes** [jkitchin/scimax#139]
I have been using the following commands as shortcuts for a long time now and have come to rely on them quite a lot:

``` lisp
(global-set-key (kbd "C-c <left>") 'python-indent-shift-left)
(global-set-key (kbd "C-c <right>") 'python-indent-shift-right)
```

Problem is I  just recently made the transition to Python 3, and when working in org-mode these functions will add tabs instead of spaces behind the lines, so nearly all of my python code started throwing exceptions.

I noticed that this is not a problem when using TAB in a python block in org-mode, so I assume you've previously cooked up some magic which does this correctly. If so, is there an easy way to extend that to the indent-left/right functions?

**Comment by jkitchin** [comment]
You can write a function1 that does what you want, and then add a function to org-shiftleft-hook and org-shiftright-hook that runs function1 if the context is correct, e.g. cursor is in a python block.
