### ISSUE TITLE
Disable forceful lisp editing

### ISSUE THREAD

**Issue by devonwa** [jkitchin/scimax#14]
Is the comment completion and parenthesis generation from the lispy mode package?

How can you remove the lambda hooks [found in packages.el](https://github.com/jkitchin/scimax/blob/e8233a91eee95d62328b58d1f527970cbb983747/packages.el#L289) after they have been created?

**Comment by jkitchin** [comment]
Parenthesis generation is probably from lispy. I am not sure about comment completion. Here is how to remove a hook.

First, we list the contents of the hook
#+BEGIN_SRC emacs-lisp :results code
emacs-lisp-mode-hook
#+END_SRC

#+RESULTS:
#+BEGIN_SRC emacs-lisp
(lisp-outline-setup
 (lambda nil
   (lispy-mode)
   (eldoc-mode))
 ac-emacs-lisp-mode-setup)
#+END_SRC

Now remove what you want:

#+BEGIN_SRC emacs-lisp
(remove-hook 'emacs-lisp-mode-hook (lambda () (lispy-mode) (eldoc-mode)))
#+END_SRC

#+RESULTS:
| lisp-outline-setup | ac-emacs-lisp-mode-setup |

#+BEGIN_SRC emacs-lisp :results code
emacs-lisp-mode-hook
#+END_SRC

#+RESULTS:
#+BEGIN_SRC emacs-lisp
(lisp-outline-setup ac-emacs-lisp-mode-setup)
#+END_SRC

**Comment by jkitchin** [comment]
There is also aggressive-indent-mode you may want to disable: https://github.com/jkitchin/scimax/blob/master/packages.el#L39

**Comment by devonwa** [comment]
Thanks! Without lispy and aggressive-indent, editing lisp works how I'd expect (which I concede may be less efficient).
