### ISSUE TITLE
How to preserve leading whitespace for ob-ipython-results :text/plain?

### ISSUE THREAD

**Issue by singletS** [jkitchin/scimax#140]
With header args "ob-ipython-results :text/plain", results have the leading whitespace stripped before being inserted into the buffer. This breaks the alignment of formatted output like that from pandas, leading to confusing column name alignment. In the example below, the index column doesn't have a name, but "a b c" should align with the respective column as in the second print(df) output.

I'm not sure which "layer" (org mode, scimax-org-babel-ipython.el, ob-ipython) is responsible for cleaning up the output before inserting into the buffer.  Suggestions?
```
#+PROPERTY: header-args:ipython :session
#+PROPERTY: header-args :exports both

#+NAME: mirror-november
#+BEGIN_SRC ipython
import pandas as pd
import numpy as np
#+END_SRC

#+NAME: five-indigo
#+BEGIN_SRC ipython :ob-ipython-results text/plain
df = pd.DataFrame({'a':[1.2343, 2.33333], 'b':[3,4], 'c':[5.3333,6.66666]})

print(df)
print(df)
#+END_SRC

#+RESULTS: five-indigo
:RESULTS:
a  b        c
0  1.23430  3  5.33330
1  2.33333  4  6.66666
         a  b        c
0  1.23430  3  5.33330
1  2.33333  4  6.66666
:END:


```

**Comment by jkitchin** [comment]
This is happening in ob-ipython--async-callback in the third line of this:

```
(when (not (string= "" (s-trim res)))
              (org-babel-insert-result
               (s-trim res)
               (cdr (assoc :result-params (third (org-babel-get-src-block-info))))))
```

I don't know why it seemed like a good idea to trim it. Presumably there were leading spaces that were not desirable?

**Comment by singletS** [comment]
Thanks for the pointer.  In modest testing, removing this s-trim fixes the issue and hasn't shown new problems with unwanted spaces.  I vaguely recall an issue with extra carriage returns, but that was a while ago (before async stuff was added, I think).  I'll update if anything negative arises from removing the s-trim.
