### ISSUE TITLE
volunteering to be a collaborator

### ISSUE THREAD

**Issue by et2010** [jkitchin/scimax#141]
Hi, John

I'm volunteering to be a collaborator to do refactoring or maintainence job.  Currently I've got quite a few commits addressing various kinds of issues (mostly on scimax-org-babel-ipython). I've been using them for months so I think they are pretty stable. Some of the improvements are:

* fixed some bugs 
* improved completion performance
* support :noweb syntax
* better results format
* etc ...

Please let me know if you are interested. Thanks!

**Comment by jkitchin** [comment]
Sounds good. I am always happy to see bug fixes and improvements.

**Comment by et2010** [comment]
Great! I'll format my PR as soon as I have some spare time.  And please consider adding me as the collaborator of this project.

**Comment by et2010** [comment]
OK, it's done! https://github.com/jkitchin/scimax/pull/145

Sorry for the delay
