### ISSUE TITLE
Tentative fix to make =org-ref= work using the latest scimax version

### ISSUE THREAD

**Issue by oolivier107** [jkitchin/scimax#142]
What I describe here is how to make =org-ref= work using the latest scimax repo (https://github.com/jkitchin/scimax) on a PC running windows 7-64.

Starting from a fresh scimax install, I could'nt get =org-ref= work with the following error after trying to insert a new reference (with C-c ]) : "No PDF(s) found." displayed in the minibuffer and no reference inserted in the text file. Searching for this error message brought me to the file =bibtex-completion.el= located in the scimax elpa directory in which the =helm-bibtex= package was.

In order to find a solution I have followed the instructions given by John [[http://kitchingroup.cheme.cmu.edu/blog/2015/12/22/org-ref-is-on-Melpa/][here]] where a demo of =org-ref= is given in a specific setup with the following emacs invocation =emacs -Q -l org-ref-melpa.el=. 
In this case, =org-ref= works fine as expected but it is not the "regular" scimax setup. At the first launch of emacs, an =elpa= directory is created containing the following packages which are more recent than those provided by the scimax repo:
async-20171015.2239
biblio-20161014.1604
biblio-core-20160901.1115
dash-20171010.131
f-20170404.1039
helm-20171021.2119
helm-bibtex-20171022.220
helm-core-20171020.1124
hydra-20170924.2259
ivy-20171021.207
key-chord-20160227.438
org-plus-contrib-20171016
org-ref-20171019.724
parsebib-20170501.347
pdf-tools-20171012.2226
popup-20160709.729
s-20170922.900
tablist-20170219.1935

After copying all these packages (except =ivy-20171021.207= which causes a problem when searching text in files) to the =scimax/elpa= directory and removing the older versions, =org-ref= finally has started to work.

Maybe a more elegant way would have been an upgrade within emacs of the outdated packages but I didn't know what packages to update. I have tried to update each upgradable packages but it has broken my scimax ecosystem.

Another approach would be an update of the bundle of package prepared by John for users of windows (https://github.com/jkitchin/scimax-win-elpa) but I do not know how to do this.

Finally =org-ref= is really a great feature for writing scientific document. Thank you John.
Olivier

**Comment by jkitchin** [comment]
The best solution might be to just eliminate the scimax-win-elpa directory. The only reason it exists is that at the time I made it, installing scimax was not very reliable, and often hung during the installation of all those packages, or some versions were not correct.  

Unfortunately, I don't have access to a windows machine to test this. If I made a branch that eliminated this dependency, could you test it out for me?

**Comment by oolivier107** [comment]
Yes, please though I must say that I have only a very basic proficiency with git (and also emacs lisp)
Olivier

**Comment by jkitchin** [comment]
I have pushed a very small change to this. It will only affect new installations of scimax though. It could be tricky to update an existing installation. It probably goes something like:

Delete the relevant section from the .gitmodules file.
Stage the .gitmodules changes: git add .gitmodules.
Delete the relevant section from .git/config .

Run git rm --cached path_to_submodule (no trailing slash).

This should leave the elpa directory intact, so you should not lose anything, but it will no longer be under version control, so it might be easier to update it.
