### ISSUE TITLE
HOW to make a double-click application for Scimax?

### ISSUE THREAD

**Issue by sanvva** [jkitchin/scimax#143]
By change the suffix of "Scimax.sh" to .desktop, double-click works but terminal opened by the same time. 
I've also tried Platypus,  no luck.

**Comment by roblem** [comment]
I am assuming you are running scimax on linux.  My scimax.desktop launcher looks like this:

```
[Desktop Entry]
Type=Application
Name=EMACS Scimax
Comment="Scimax for Emacs"
Icon=/path/to/icon/icon.png
Exec=/path/to/scimax/scimax.sh
Terminal=false
Categories=Development;Research
```

**Comment by sanvva** [comment]
@roblem sorry to mention the system, Mac OS.

**Comment by AKielhorn** [comment]
> Am 23.10.2017 um 16:46 schrieb sanvva <notifications@github.com>:
> 
> @roblem sorry to mention the system, Mac OS.

I’m using an automator workflow:

export PATH=/Users/axel/Library/Haskell/bin:/opt/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/Library/TeX/texbin
/Applications/Emacs\ 25.3.app/Contents/MacOS/Emacs   -l ~/src/Emacs/scimax/init.el "$*“ &

Automator options:
Execute shell script
Shell: /bin/bash
Use input: as argument.

You may have to adjust the PATHs, especially the one for Emacs.
It will probably just /Applications/Emacs.app/Contents/MacOS/Emacs for you.

This works as a drop target, but you get an error message when $* is empty.
You can just ignore that message.

Axel

**Comment by sanvva** [comment]
@AKielhorn Very helpful! Many thanks!
