### ISSUE TITLE
Installation failure on Mac High Sierra

### ISSUE THREAD

**Issue by Arjay-El** [jkitchin/scimax#144]
I wiped my disk on my Macbook air(2013) and loaded High sierra. I followed your instruction for loading using the command in terminal. I then used ./scimax.sh to load scimax and received this message 
"Error(use-package) scimax-mode :init: Cannot open load file: No such file or directory, esup"
Scimax does not appear on the menu line. Any idea what I should do to correct this?

**Comment by jkitchin** [comment]
I added this package to packages.el. You may be able to just package-install it though.

**Comment by jkitchin** [comment]
Did this get resolved?
