### ISSUE TITLE
scimax/org-return does not work well for lists

### ISSUE THREAD

**Issue by prtkm** [jkitchin/scimax#147]
In org mode, want to have a list like this:
- item 1
- item 2
....

But once I press return after "item 1" scimax/org-return automatically starts a new headline with "*" instead of going to the next line (or ideally inserting a "-"). Using a prefix argument to before hitting return seems to fix this, but it is tedious to press C-u everytime!

**Comment by jkitchin** [comment]
hm. I don't see that behavior. I get a new list item. If you press enter again, it deletes the new item. you should be able to type C-j to add a new line from there too.

**Comment by prtkm** [comment]
That's strange. Just to double check, since github markdown did not render that correctly the first time, I was  making lists with a "-"

![screen shot 2017-11-14 at 9 33 04 pm](https://user-images.githubusercontent.com/2263899/32815723-72b5243c-c983-11e7-8882-dbe6859254a9.png)

As you can see org-return inserted a "**" instead of a "-"

I get the same behavior you do for headings / lists that begin with * or **.
![screen shot 2017-11-14 at 9 36 01 pm](https://user-images.githubusercontent.com/2263899/32815827-dcd5b5f2-c983-11e7-8a66-47586a2d7beb.png)
