### ISSUE TITLE
Projectile: adding existing project

### ISSUE THREAD

**Issue by Cumol** [jkitchin/scimax#148]
I tried to add an existing project to projectile through `projectile-add-known-project`. When I invoke `nb-open` the project is shown in the list.

However, after restarting scimax, the project is no longer in the list. It seems like only project that are added using `nb-new` are kept in the list.

Is that intended behavior?

**Comment by jkitchin** [comment]
I guess not. It should just be adding a project to the list of projectile projects. Is that not what you see?

**Comment by Cumol** [comment]
No. I just tried it again and the same thing happened. 'projectile-add-known-project' does not add a project to the list permanently as the project is not in the list after restarting scimax/emacs.

Do you think that this is a general issue with Projectile or something that the scimax setup is doing?

**Comment by jkitchin** [comment]
hm. I am not sure. I would have thought projectile would remember it because that directory should be a git repo I think. I will look into it a little more.
