### ISSUE TITLE
Fresh install of emacs throws exception of missing diminish package

### ISSUE THREAD

**Issue by jboes** [jkitchin/scimax#150]
A fresh installation of emacs results in the following error:

```
eval-buffer: Cannot open load file: No such file or directory, diminish
```

```
M-x package-install
diminish
```

Will resolve the issue but I would have expected this to be handled automatically.

**Comment by jkitchin** [comment]
Thanks. It took a few tries, but I think I finally fixed it.

**Comment by Cumol** [comment]
I am still getting a diminish-related error when doing a fresh install
`
package-compute-transaction: Package ‘diminish-’ is unavailable
`

**Comment by jkitchin** [comment]
I am sure this related to a MELPA/ELPA failure. What emacs version and OS are you using?

**Comment by Cumol** [comment]
Emacs 26.3 and Ubuntu 18.04

**Comment by jkitchin** [comment]
Do you see any other messages that suggest something like ELPA could not be downloaded?

I have this in bootstrap.el to deal with a version 26 problem. But, maybe there is some other issue on ubuntu that I am not aware of. 

```
(require 'gnutls)
(when (and (string= "26" (substring emacs-version 0 2))
	   (null gnutls-algorithm-priority))
  ;; This appears to be a bug in emacs 26 that prevents the gnu archive from being downloaded.
  ;; This solution is from https://www.reddit.com/r/emacs/comments/cdf48c/failed_to_download_gnu_archive/
  (setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3"))
```

**Comment by Cumol** [comment]
The problem is probably related to this here and it suggests going down to an older TLS version
