### ISSUE TITLE
Symbol's value as variable is void error after scimax-update

### ISSUE THREAD

**Issue by Cumol** [jkitchin/scimax#151]
I did M-x scimax-update yesterday and when I restarted Emacs I got the following error:

```
/Users/muadabdelhay/cloud/scimax/elpa/mustache-20131117.1407/mustache-render.el (source)...
Loading /Users/muadabdelhay/cloud/scimax/elpa/mustache-20131117.1407/mustache-lex.el (source)...done
Loading /Users/muadabdelhay/cloud/scimax/elpa/mustache-20131117.1407/mustache-parse.el (source)...done
Loading /Users/muadabdelhay/cloud/scimax/elpa/mustache-20131117.1407/mustache-render.el (source)...done
load-with-code-conversion: Symbol’s value as variable is void: <<<<<<<
```

Any idea what is happening?

**Comment by jkitchin** [comment]
I guess you have some kind of merge conflict. Maybe you changed some file?  Search for <<<<<< in your scimax directory.

**Comment by Cumol** [comment]
Good guess. I had this set up in the previous scimax-notebook.el:
```

(defvar nb-master-file "index.org"
  "Name of the master file in each project")

```

Which collided with the standard:

```
(defvar nb-master-file "README.org"
  "Name of the master file in each project")
```
How do I set this variable in my uses.el instead of scimax-notebook.el?

**Comment by Cumol** [comment]
Found out how. Added it to a file user/preload.el to set it before any packages are loaded.

**Comment by jkitchin** [comment]
Indeed. Just put (setq nb-master-file "index.org") before loading the file.
