### ISSUE TITLE
`ob-ipython-results text/plain` not working?

### ISSUE THREAD

**Issue by timehaven** [jkitchin/scimax#152]
Great work, scimax team!

I am trying to recreate the output from this blog post:

http://kitchingroup.cheme.cmu.edu/org/2017/05/26/Org-mode-and-ipython-enhancements-in-scimax.org

When I execute an ipython src block and just try to get the plain text output, I still receive the html output.

On my Mac, I cloned the latest scimax in a new temp directory and started Emacs via:

    /Applications/Emacs.app/Contents/MacOS/Emacs -q -l scimax/init.el

I created a new .org file and added this block:

```
#+BEGIN_SRC ipython :session anewsession
import pandas as pd
df = pd.DataFrame([1, 2])
df
#+END_SRC
```

I execute that block with `org-babel-execute-async:ipython`.  It runs and produces 

```
#+RESULTS: uranus-mango-xray-low
:RESULTS:
#+BEGIN_EXAMPLE
   0
0  1
1  2
#+END_EXAMPLE

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>0</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2</td>
    </tr>
  </tbody>
</table>
</div>
:END:
```
I then execute this next block and get the same output:

```
#+BEGIN_SRC ipython :session anewsession :ob-ipython-results text/plain
df
#+END_SRC
```

Am I missing something?

Thank you.

**Comment by timehaven** [comment]
A quick hack, if you will is to use:
```
#+BEGIN_SRC ipython
pd.options.display.notebook_repr_html = False
#+END_SRC
```
This will simply make pandas not send any html output.

**Comment by jkitchin** [comment]
It does appear this was not working as advertised. That part of the code has changed a few times since the blog post I guess and that feature got lost for async execution. I think I have pushed a fix back for it. Let me know if it fixes it for you.

**Comment by timehaven** [comment]
Perfect!  Thank you.



```
#+NAME: beryllium-two-thirteen-india
#+BEGIN_SRC ipython :session anewsession :ob-ipython-results text/plain
df
#+END_SRC

#+RESULTS: beryllium-two-thirteen-india
:RESULTS:
#+BEGIN_EXAMPLE
   0
0  1
1  2
#+END_EXAMPLE
:END:
```

**Comment by timehaven** [comment]
Seems to be an issue again with new branch:

https://github.com/jkitchin/scimax/tree/ob-ipython-upstream

The hack of

```
pd.options.display.notebook_repr_html = False
```

works fine but without it, I get the issue as described at top of this page.

I know you were allowing multiple output types in this new branch so not sure if this is intended or not.

**Comment by jkitchin** [comment]
The header changed a little.

Try:

```
#+BEGIN_SRC ipython :display text/plain
import pandas as pd
df = pd.DataFrame([1, 2])
df
#+END_SRC

#+RESULTS:
:RESULTS:
# Out[4]:
# text/plain
#+BEGIN_EXAMPLE
  0
  0  1
  1  2
#+END_EXAMPLE
:END:
```

**Comment by timehaven** [comment]
Nice, that does indeed work.  Thanks.  

Your example, though, reminds me of something else I noticed concerning the alignment of column names.  Without `print`, it seems that the initial white space at the beginning of the top row of the output is being stripped.  With `print`, alignment is correct:

```

#+BEGIN_SRC ipython :display text/plain
import pandas as pd
df = pd.DataFrame([1, 2], columns=['widecolumn'])
df.index.name = 'indexname'
df
#+END_SRC

#+RESULTS:
:RESULTS:
# Out[7]:
# text/plain
#+BEGIN_EXAMPLE
  widecolumn
  indexname
  0                   1
  1                   2
#+END_EXAMPLE
:END:

#+BEGIN_SRC ipython  :display text/plain
print(df)
#+END_SRC

#+RESULTS:
:RESULTS:
# Out[8]:
# output
           widecolumn
indexname            
0                   1
1                   2
:END:
```

**Comment by jkitchin** [comment]
indeed it was. I pushed a fix for that. I am planning to refactor the output function to make user-customizable functions for each mime-type and output. There will be defaults for the main ones that are in there now, but it will be easy to customize it if desired.
