### ISSUE TITLE
Create a better-org-return package

### ISSUE THREAD

**Issue by Somelauw** [jkitchin/scimax#153]
Hi, I saw your [blog post](http://kitchingroup.cheme.cmu.edu/blog/2017/04/09/A-better-return-in-org-mode/) and noticed that you are working on a better-org-return function.
I included something based on your blog post in [evil-org](https://github.com/Somelauw/evil-org-mode/blob/5c01f573920e4794f812c30e7fd8f0bfb9734286/evil-org.el#L274), but I was wondering whether it would be better to split this functionality off in a new package and making it fully configurable.
It can also encompass https://github.com/calvinwyoung/org-autolist by @calvinwyoung or even be contributed directly to his package.

**Comment by jkitchin** [comment]
I don't think a separate package makes sense. My function meets my needs most of the time,  and for those whos needs it doesn't meet, they tend to use something like org-autolist. I don't have time to look into the differences right now, or to think about what a fully configurable version might look like. What did you have in mind for that?
