### ISSUE TITLE
image scaling with mogrify did not work

### ISSUE THREAD

**Issue by Hagopian** [jkitchin/scimax#155]
Hello,

I was struggling today to get the image scaling like 
#+attr_org: :width 20%
to work. 
It did not work although eimp was able to rescale images, suggesting that my ImageMagick installation was correct. Scaling also did not work in the scimax.org manual.

I now find out [here](https://stackoverflow.com/questions/11670654/how-to-resize-images-in-org-mode) that 
(setq org-image-actual-width nil)
needs to be set to allow image scaling, but this is set to
(setq org-image-actual-width t)
in scimax-org.el essentially preventing the expected behavior for image scaling.
Maybe this could either be changed or added to the scimax.org

**Comment by jkitchin** [comment]
Thanks for noting this. I also came across it last week. I have changed the default setting, and updated the manual. Hopefully it works better for you and others in the future.
