### ISSUE TITLE
Package ‘help-fns+-’ is unavailable

### ISSUE THREAD

**Issue by timehaven** [jkitchin/scimax#156]
Create fresh temp dir, clone scimax repo, start with:

```
/Applications/Emacs.app/Contents/MacOS/Emacs -q -l scimax/init.el
```

and receive error message:

```
Error (use-package): Failed to install help-fns+: Package ‘help-fns+-’ is unavailable
Error (use-package): Cannot load help-fns+
```

Commenting out 

https://github.com/jkitchin/scimax/blob/master/packages.el#L312

```
(use-package help-fns+)
```

fixes the issue. 

Is this related to https://github.com/melpa/melpa/pull/5008 ?

That package is listed in comment on that page:

https://github.com/melpa/melpa/pull/5008#issuecomment-329982690

Here is the source of that package on emacswiki:

https://github.com/emacsmirror/emacswiki.org/blob/master/help-fns%2b.el

**Comment by jkitchin** [comment]
That is indeed due to the emacswiki issue. I will post a fix to it tonight. That solution will be to just put a local copy of the code in scimax (https://github.com/emacsmirror/emacswiki.org/blob/master/help-fns%2b.el).

**Comment by linchen2chris** [comment]
I still have this issue 
![image](https://user-images.githubusercontent.com/3970087/36083438-25bff944-0fed-11e8-8e3e-f777f18cbd1f.png)

**Comment by jkitchin** [comment]
The package is part of scimacs now. This is how it gets loaded.

```
(use-package help-fns+
  :load-path scimax-dir)

```
maybe you need to add :ensure nil to the use-package?
