### ISSUE TITLE
central hydra and f12

### ISSUE THREAD

**Issue by Cumol** [jkitchin/scimax#157]
I wanted to try the built-in hydras that are supposedly mapped to f12. When I click f12 in an org-buffer it takes to the navy hydra, not the the behavior described in the manual (f12 RET saving a file or f12 ff opening a file).

Am I misunderstanding something or is that meant to be like this?

**Comment by jkitchin** [comment]
You did not misunderstand anything. The code was still pointing to the old navy hydra. I just pushed an update that should fix that.

**Comment by Cumol** [comment]
I can confirm that it is working now, thank you for the quick fix! 👍
