### ISSUE TITLE
Problem exporting underscore ("_") in figure address to LaTeX

### ISSUE THREAD

**Issue by haditim** [jkitchin/scimax#158]
Hello,

I have a figure with the following address:
 #+CAPTION: TM54 Gd-NO distance measurements.
 [[file:./54_Nb/54+Nb_measurements_PLOT.pdf]]

And when I publish it for PDF via Latex I get the following:
\begin{figure}[htbp]
\centering
\includegraphics[width=.9\linewidth]{/mnt/HADI/54_Nb71/TM54+Nb(Gd-DOTA)_Gd-Gd_DEER_distance_measurements_PLOT.pdf}
\caption{TM54 Gd-NO distance measurements.}
\end{figure}

But I get the following in \*latex\*:
LaTeX Warning: File `./54_Nb/54+Nb_measureme
nts_PLOT.pdf' not found on input line 145.

! Package pdftex.def Error: File `./TM54\unhbox \voidb@x \penalty \@M \hskip \z
@skip \T1\textunderscore \discretionary {-}{}{}\penalty \@M \hskip \z@skip Nb
/54+Nb\unhbox \voidb@x \p
enalty \@M \hskip \z@skip \T1\textunderscore \discretionary {-}{}{}\penalty \@M
 \hskip \z@skip measurements\unhbox \voidb@x \penalty \@M \hskip \z@skip \T1\te
xtunderscore \discretionary {-}{}{}\penalty \@M \hskip \z@skip PLOT.pdf' not fo
und.

I have no idea why this happens although it looks to be underscore problem. I tries escaping that with no luck. I also added:
`#+OPTIONS: _:t TeX:_t LaTeX:_t`
with no difference.

Could you please help me in this?
Thanks in advance.

**Comment by jkitchin** [comment]
This is a latex problem; underscores in filenames in latex are generally a problem. My advice is rename the file using a - instead of _. If the _ is totally unavoidable, you might be able to use grffile: https://ctan.org/pkg/grffile. I

**Comment by haditim** [comment]
Thanks a lot for the reply. I added `#+LATEX_HEADER: \usepackage[encoding,filenameencoding=utf8]{grffile}` to the document but the same happens. Unfortunately, I cannot change the project structure and we have underscores in the folder name.
I know that this is not related to scimax, therefore I close this issue.

BTE, thanks for the amazing Scimax.

**Comment by jkitchin** [comment]
The internet is full of ways to deal with underscores in latex, so I guess a day of googling will lead to a solution. People do it. You will have to dig into the latex side to get there.

Depending on your pdf style needs, you could try exporting to html and saving as pdf, or maybe pandoc can get something that looks ok. 

You could always write a script that preprocesses the org file, makes copies of the the image files with no _ in them, and replaces the links with them before exporting. Check out https://github.com/jkitchin/scimax/blob/master/ox-manuscript/ox-manuscript.el#L655 which does the copying part.

**Comment by haditim** [comment]
Thanks again for your reply. In this line:
[line 742](https://github.com/jkitchin/scimax/blob/master/ox-manuscript/ox-manuscript.el#L742)
Could I say replace all the "\_" with "\script\_"? That'd solve my problem and probably others' (this is my one day googling result :D). But I have no experience in elisp. I export both PDF and html and if I replace underscores in the org file, latex works but html export fails.

**Comment by jkitchin** [comment]
There are a few places you have to do something. Around line 716 is where the idea starts. You have to find the image file names, then copy the file and replace the path in the tex tile. The code I sent you only copies and replaces the path, but otherwise doesn't change the file name.

how does the html export fail?

**Comment by haditim** [comment]
When I put [[file:./271\string_Nb/271+Nb\string_PLOT.pdf]] (\_ replaced by \string\_) of course it cannot find the file and the image does not get produced. Also another annoying thing is that I need to put pdf files for latex and png files for html exports which is a bit time consuming. For example doconce generates png files out of pdf file automatically for exports to html.

**Comment by jkitchin** [comment]
I would create a little src block in the document for latex export, and for html export. Something like this maybe:


```
* export                                                           :noexport:
#+BEGIN_SRC emacs-lisp
(let ((org-export-before-parsing-hook '((lambda (backend)
					  (let ((links (reverse (org-element-map (org-element-parse-buffer) 'link
								  (lambda (link)
								    (when (and (string= "file" (org-element-property :type link))
									       (f-ext? (org-element-property :path link) "pdf"))
								      link))))))
					    (cl-loop for link in links do
						     (let ((path (org-element-property :path link)))
						       (setq path (replace-regexp-in-string "_" "\\\\\\\\string_" path))
						       (goto-char (org-element-property :begin link))
						       (re-search-forward (org-element-property :path link))
						       (replace-match path))))))))
  (org-latex-export-to-pdf))
#+END_SRC
 
```


This is more or less what ox-manuscript was designed for. I use png in org-mode, but if an eps/pdf is available it is preferred in LaTeX. ox-manuscript automates stripping the png off the filenames  for latex.

**Comment by haditim** [comment]
Thanks a lot Prof. Kitchin. I appreciate your time. This solved my problem. Please keep up the amazing work on Scimax.
