### ISSUE TITLE
org elpa repository and GnuTLS

### ISSUE THREAD

**Issue by Hagopian** [jkitchin/scimax#159]
Since today I have a problem starting emacs/scimax on Win7. I also installed a fresh copy on a Win7 VM and it reproduces the same problem.

emacs crashes with the last message in the minibuffer being
error in process filter: could not create connection to orgmode.org:443
This seems to be related to http://irreal.org/blog/?p=6899 
because changing 
(add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/") t) in the init.el to
(add-to-list 'package-archives '("org" . "http<b>s</b>://orgmode.org/elpa/") t)
at least gets emacs to start again.
I also noticed, that http://orgmode.org/elpa/ redirects to https://orgmode.org/elpa/

With the above change now the org repository is not loaded, because in the message buffer I see

gnutls.c: [1] (Emacs) GnuTLS library not found
Contacting host: melpa.org:80
Contacting host: orgmode.org:443
Opening TLS connection to ‘orgmode.org’...
Opening TLS connection with ‘gnutls-cli --x509cafile nil -p 443 orgmode.org’...failed
Opening TLS connection with ‘gnutls-cli --x509cafile nil -p 443 orgmode.org --protocols ssl3’...failed
Opening TLS connection with ‘openssl s_client -connect orgmode.org:443 -no_ssl2 -ign_eof’...failed
Opening TLS connection to ‘orgmode.org’...failed
Package refresh done
Failed to download ‘org’ archive.

although libgnutls-30.dll is installed and the variable dynamic-library-alist contains

((xpm "libxpm.dll" "xpm4.dll" "libXpm-nox4.dll") (png "libpng16.dll"
 "libpng16-16.dll") (tiff "libtiff-5.dll" "libtiff3.dll"
 "libtiff.dll") (jpeg "libjpeg-8.dll") (gif "libgif-7.dll") (svg
 "librsvg-2-2.dll") (gdk-pixbuf "libgdk_pixbuf-2.0-0.dll") (glib
 "libglib-2.0-0.dll") (gobject "libgobject-2.0-0.dll") **(gnutls
 "libgnutls-30.dll")** (libxml2 "libxml2-2.dll" "libxml2.dll") (zlib
 "zlib1.dll" "libz-1.dll"))

also the variable gnutls-available-p is not defined
I also downloaded emacs-25-x86_64-deps.zip to see whether any files are missing, but everything seems to be included.

Whether GnuTLS ever worked in my installation I cannot say, maybe the issue just surfaced because http repository support was ceased for orgmode?

Hope the above informaton helps ...

**Comment by jkitchin** [comment]
Thanks for reporting this. The issue seems related to ssl/https, but as you can see above, I have not been able to resolve the issues. A little progress was made, but still the test does not pass, and I guess it still does not work in windows. I don't have a Windows machine to work on. I guess emacs-win needs to be updated because of some openssl change.

A workaround might be to get your own emacs distribution on windows, and launch scimax with

your-emacs -l /path/to/scimax/init.el

**Comment by jkitchin** [comment]
I was not able to get the Appveyor tests to pass, but I did successfully build scimax on a windows machine. I didn't get a chance to test it out much past the successful build.

**Comment by Hagopian** [comment]
As a another try I just copied emacs-25-x86_64-deps.zip ( from https://ftp.gnu.org/gnu/emacs/windows/?C=N;O=D ) into the emacs-win folder replacing all existing files and that apparently completely solves the issue. Also evalualtion of (gnutls-available-p) returns t now.

I dismissed this option yesterday, as my filesync said that the files were all up to date, the reason might be that the files of my scimax installation have a newer date than those in emacs-25-x86_64-deps.zip (which are from 2016-08-25).

**Comment by Hagopian** [comment]
I also tried to install the new build using GIT bash

bash -c "$(curl -fsSL https://raw.githubusercontent.com/jkitchin/scimax/ob-ipython-upstream/install-scimax-win.sh)"

but the changes don't seem to be included in this build, am I doing something wrong?

**Comment by jkitchin** [comment]
No probably not. I made those all in another branch, and that install script works on the master branch.

Now that you mention that though, it makes me wonder why my install on windows worked, since it also used that script.

Glad to hear yours is working again though.

**Comment by Hagopian** [comment]
yeah I saw that it was in the ob-ipython-upstream branch, thats why i changed the bash path accordingly, but still the changes were not in there ...

**Comment by Hagopian** [comment]
just to give you an update. The issue seems to be connected with hunspell. After I copied the depndencies into the emacs-win folder hunspell does not work any more, if I then copy hunspell over the existing files, emacs crashes (with https for org-mode). I did not have the time to look into which file(s) cause this behaviour or how to work around it, if I manage to get both working, I'll let you know.

**Comment by jkitchin** [comment]
Interesting. I tried taking it out in the tests, but it doesn't seem to make much difference in making the tests pass.

**Comment by Hagopian** [comment]
ok maybe I was not really clear in what I was writing. So I did some further tests and this is the current status. (all only tested on Win7)

1) scimax out of the box (via Git bash) crashes with “error in process filter: Could not create connection to orgmode.org:443
2) changing (add-to-list
 'package-archives
 '("org"         . "http://orgmode.org/elpa/")
 t)
to https in the init.el resolves the crash, but then GnuTLS does not work (or maybe never worked)
3) copying emacs-25-x86_64-deps.zip into the emacs-win folder resolves the GnuTLS issue
4) but then hunspell exits with code 123, once flyspell-mode is activated
5) copying the complete hunspell installation into emacs-win brings hunspell back to life, but then GnuTLS does not work anymore
6) I could trace this down to two dlls in the emacs-win\bin directory: libiconv-2.dll and libintl-8.dll. If the versions from the dependencies are copied in, then GnuTLS works but hunspell not, if the versions from hunspell are copied in then hunspell works but GnuTLS fails (maybe a 32-bit vs 64-bit problem???, because hunspell is 32-bit)

my current workaround is to copy the dependencies into emacs-win (which kills hunspell) and have hunspell in a seperate directory and set (setq ispell-program-name "yourpathtohunspell") as described [here ](https://emacs.stackexchange.com/questions/14952/how-do-i-set-up-hunspell-on-a-windows-pc) . That works fine for me.
My only problem now is that on fresh scimax installations these hunspell settings in the user.el are  not evaluated only if I but them into the *scratch* and evaluate them with C-x C-e. Not sure why this is, because on my old installations it works, maybe some packages needs to be upgraded or installed ...
Let me know, whether my explanations are clear.

**Comment by jkitchin** [comment]
That seems pretty clear. I guess the Windows version of scimax will be broken for a few months. I don't have a windows machine to work all this out on at the moment. Thanks for the clear solution!

**Comment by jkitchin** [comment]
Is this still an issue for you? The tests seem to be passing since they fixed something on the org-mode server.

**Comment by Hagopian** [comment]
I just tested it and a out-of-the box scimax does not crash anymore .. so it indeed seem to be solved.

**Comment by Hagopian** [comment]
I just found that hunspell does not work in this installation, which I had not tested in the morning. so unfortunately the issue is not really solved.

this is what i get

`Starting new Ispell process e:/scimax180406/scimax/emacs-win/bin/hunspell with english dictionary...
Error enabling Flyspell mode:
(e:/scimax180406/scimax/emacs-win/bin/hunspell exited with code 123)`

**Comment by Cumol** [comment]
I was getting some issues with certificates recently for some reason.

I needed to require gnutls in the preload.el to make everything work again. Bascially following this advice: https://blog.vifortech.com/posts/emacs-tls-fix/

**Comment by jkitchin** [comment]
Thanks for posting your solution!
