### ISSUE TITLE
Checkbox colors

### ISSUE THREAD

**Issue by devonwa** [jkitchin/scimax#16]
I noticed a little while ago that the checkbox colors were updated after a commit. The change went from grey backgrounds to white. It worked for blank and done boxes, but missed intermediates. [See this pic](http://imgur.com/a/6nWYD).

Was this scimax coloring or did a theme maker change this?

**Comment by jkitchin** [comment]
I am not sure what could be causing that.

**Comment by jkitchin** [comment]
This seems to be gone now.
