### ISSUE TITLE
Warning (emacs): Unrecognized key: _x_

### ISSUE THREAD

**Issue by roblem** [jkitchin/scimax#161]
Using [the upstream ob-ipython branch](https://github.com/jkitchin/scimax/tree/ob-ipython-upstream) and getting this warning on scimax startup:

`Warning (emacs): Unrecognized key: _x_`

This isn't impacting functionality for me so far.

**Comment by jkitchin** [comment]
That will probably be fixed with a new pull. That was a bug I fixed in c6b62d75c21bd31ae5 I think.

**Comment by roblem** [comment]
Yes.  Thanks.
