### ISSUE TITLE
Export to ipynb failing

### ISSUE THREAD

**Issue by singletS** [jkitchin/scimax#163]
Trying to export to jupyter notebook (or as buffer, notebook>open) fails pretty much silently.  The only hint I'm finding is in the Message buffer
```json-encode-array: Wrong type argument: listp,```
followed by a long encoded string.
No .ipynb file is created, though an export buffer does appear.  The notebook server never gets started.  All of the ipython src blocks evaluate fine in the org file buffer.

Environment:
scimax branches master or ob-ipython-upstream
emacs 25.3 linux
(require 'ox-ipynb) added to scimax/user/user.el
jupyter --version 4.4.0 (anaconda)

**Comment by jkitchin** [comment]
that is a mystery. Seems like something has changed. The issue seems to be related to inline images. I haven't figured it out yet though.

**Comment by jkitchin** [comment]
Maybe this is fixed now.

**Comment by singletS** [comment]
Looks to be fixed.  Thanks!
