### ISSUE TITLE
Magit Commit Error

### ISSUE THREAD

**Issue by roblem** [jkitchin/scimax#164]
Staged a few files with `magit-status` and trying to commit from there.  Getting this error:
```
1 git … commit --
Waiting for Emacs...
*ERROR*: Auth Error: "Token not found"
error: There was a problem with the editor '/usr/bin/emacsclient --socket-name=/tmp/emacs1000/server'.
Please supply the message using either -m or -F option.
```
Besides being nearly identical to [this bug report at magit](https://github.com/magit/magit/issues/3154), it seems like this was already addressed in #106 where the decision was to disable magithub by default.  Has this  been reverted on the ob-ipython-upstream branch?  In any event, the token exists in `~/.authinfo`, `~/.authinfo.gpg`, and `~/.gitconfig` to no avail.

Running
```emacs-lisp
(setq ghub-username "user"
      ghub-token "your token here")
``` 
as suggested in #106 allows me to proceed without the error.  Since nearly all of my work is on local repos, I don't really need magithub/ghub functionality.

**Comment by jkitchin** [comment]
There is no intentional change I know of for magithub. I am no sure what would cause that.

**Comment by roblem** [comment]
Once I establish the credentials, things are working.  It seems like it is checking the credentials when committing even when the repos are local.
