### ISSUE TITLE
htmlized org emails using mu4e [probably ob-ipython-upstream]

### ISSUE THREAD

**Issue by roblem** [jkitchin/scimax#167]
Not sure if the problem I describe here is due to upstream ipython or not, but I suspect yes.  Using techniques described in [your blog post on org email integration](http://kitchingroup.cheme.cmu.edu/blog/2016/10/29/Sending-html-emails-from-org-mode-with-org-mime/#orgheadline2).  Things like hmlizing codeblocks, rendering latex inline, bullets, headings, etc. work fine.

The problem is with inline attachments results from ipython src blocks. An org code sample, send using `org-mime-org-buffer-htmlize`:
```
Here is some latex math:

$$
\mathbf{y = x\beta + \epsilon} 
$$

Bullet points
- Seem
- To
- Work

** Headers Work

#+BEGIN_SRC ipython :display image/png
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

x = np.random.randn(100)

plt.hist(x)
#+END_SRC
```
This produces a file that is nearly correct. The problem is in the attachment paths at the bottom:
```{html}
<#/multipart>
<#part type="image/png" filename="/tmp/obipy-resources/980ba2a6d62a02a198358eaa90257878-26640uSs.png" disposition=inline id="<_tmp_obipy-resources_980ba2a6d62a02a198358eaa90257878-26640uSs.png>">
<#/part>

<#part type="image/png" filename="/tmp/ltximg/latex26640UFU_0947d14d7bb3d6bb49a1d4783d457ef887715672.png" disposition=inline id="<_tmp_ltximg_latex26640UFU_0947d14d7bb3d6bb49a1d4783d457ef887715672.png>">
<#/part>
<#part filename="/home/username/Downloads/obipy-resources/980ba2a6d62a02a198358eaa90257878-26640uSs.png" disposition=attachment>
<#/part>
```
the inline ipython directory path should be `/home/username/Downloads/obipy-resources` rather than `/tmp/obipy-resources`.  If I manually change the path and send the mail, it renders fine in gmail: 
![render_test](https://user-images.githubusercontent.com/1871086/36586775-317b29a4-1883-11e8-9db1-60953d93b044.png)

This also happens with using `mu4e-compose-org-mail`.  BTW, this is an awesome feature that will really help me respond to my students' technical questions.

**Comment by johnrkitchin** [comment]
I will take a look at this over the weekend. It would help me a lot too!

**Comment by jkitchin** [comment]
I think this was an issue in the scimax/org-mime.el library. I think I have pushed a fix for it in the ob-ipython-upstream branch. It will probably merge with master in the next week or so.

**Comment by jkitchin** [comment]
Probably once i merge ipython-upstream, I will work on taking org-mime out of scimax, and relying on the one that is currently maintained at https://github.com/org-mime/org-mime by @redguardtoo.

**Comment by roblem** [comment]
This is working now. Thanks.
