### ISSUE TITLE
Leuven defaulting to white text/black background

### ISSUE THREAD

**Issue by Arjay-El** [jkitchin/scimax#168]
[Win10 PC]: Is the white text/black background default for scimax? I have attempted to switch to black text/whitish background but it makes some highlighting invisible. I am hesitant to change your default theme settings as I do not want to disturb your excellent formatting, just wanted a paper color background with black normal text. Thanks.

**Comment by jkitchin** [comment]
The default theme is Leuven. On my machine it looks like white background with black text. I don't know how you would get any other theme without loading it yourself somewhere in your init files. Are you running emacs in a terminal?

**Comment by Arjay-El** [comment]
I am using scimax.bat to run my installation. The only customization I did was to add recentf.el and code to split the frames vertically rather than horizontal. The behaviour is that emacs opens with a white background but switches to black when the scimax menus load. I did have a previous installation Goulet's R focussed emacs. Is it possible the registry contains a setting doing this? Does Scimax write settings to the registry?

**Comment by jkitchin** [comment]
There should not be anything in the registry from scimax as far as I know. It is possible you have some custom.el file somewhere though that has that information in it. Are those the colors of the previous installation?

**Comment by Arjay-El** [comment]
Thanks John I will hunt it down, perhaps there are remnants I missed. please close this issue.

**Comment by jkitchin** [comment]
you might look for something like a ~/.emacs.d directory. It could also be you can just reload leuven:

(load-theme 'leuven)

that might reset your colors.
