### ISSUE TITLE
org-src-mode autocompletion clashes with elpy

### ISSUE THREAD

**Issue by prtkm** [jkitchin/scimax#17]
Hi John,

If I do C-c ' to go into python-mode, both elpy and org_src autocompetion seem to be on, resulting in weird conflicts. See snapshot below. What do you think is a good fix?

![screen shot 2016-08-26 at 4 54 25 pm](https://cloud.githubusercontent.com/assets/2263899/18020161/08623f90-6bae-11e6-8d18-f9c3c3fd9978.png)

**Comment by jkitchin** [comment]
I have experienced that too. I am not sure how to fix it.

**Comment by jkitchin** [comment]
I don't think this is an issue anymore. Reopen if it is.
