### ISSUE TITLE
Keybinding for ob-ipython-inspect [ob-ipython-upstream]

### ISSUE THREAD

**Issue by roblem** [jkitchin/scimax#172]
Didn't `M-.` open info on a python object?
It is prompting me to visit a tags table.

**Comment by jkitchin** [comment]
ob-ipython-inspect is currently bound to H-/. I don't recall if it used to be on M-., but it probably shouldn't be there by default.

M-. would usually jump to a definition, which is why you are getting prompted for a tags table.

**Comment by roblem** [comment]
Sorry.  Lazy on my part for not checking keybindings.  Seems like I've been using it for awhile since reading:
http://kitchingroup.cheme.cmu.edu/blog/2017/05/26/Org-mode-and-ipython-enhancements-in-scimax/#orgef414e8

**Comment by jkitchin** [comment]
No worries. I probably should not have made that binding since it changes default expectations. I don't use M-. in python mode a lot, but I do use it in elisp all the time.
