### ISSUE TITLE
pandoc 2 interface changes break ox-word

### ISSUE THREAD

**Issue by dangom** [jkitchin/scimax#174]
> --smart/-S has been removed.  Use +smart or -smart extension instead.
> For example: pandoc -f markdown+smart -t markdown-smart.
> Try pandoc --help for more information.
> 

A possible fix  for those using newer versions of pandoc would be changing [ox-word's pandoc command](https://github.com/jkitchin/scimax/blob/master/ox-word.el#L66) to `""pandoc -s %s%s\"%s\" --to=docx+smart -o \"%s\"""`.

**Comment by jkitchin** [comment]
Is there a way to check for the pandoc version?
