### ISSUE TITLE
Update Scimax asks for identification

### ISSUE THREAD

**Issue by Arjay-El** [jkitchin/scimax#178]
When I invoke Update from the Scimax menu, it asks who I am. I have copied the text below. Have a damaged/deleted an identification file. I did note that when I installed it, it did not ask for an email address or name. What can I fix to satisfy this message?

---x---
(Shell command succeeded with no output)
*** Please tell me who you are.
Run
  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.
fatal: unable to auto-detect email address (got 'Arjay@(my desktop name redacted).(none)')
(Shell command succeeded with no output)
Loading c:/scimax/init.el (source)...
(Shell command succeeded with no output)
Loading help...done
Loading c:/scimax/init.el (source)...done

**Comment by jkitchin** [comment]
you should run these in a terminal:

git config --global user.email "you@example.com"
git config --global user.name "Your Name"

substituting your details.
