### ISSUE TITLE
super and hyper keys

### ISSUE THREAD

**Issue by AKielhorn** [jkitchin/scimax#179]
You are using super and hyper key bindings.

Maybe you should add information about how to define these modifiers, since most keyboards don't have them.

I found the instructions here:
<http://ergoemacs.org/emacs/emacs_hyper_super_keys.html>

For some reasons that doesn't work an Win 10.
I can't bind the Windows key, Windows always interferes.

**Comment by jkitchin** [comment]
Where would you find it most useful for this to be documented?

**Comment by AKielhorn** [comment]
Right at the top of scimax.org

<code>
** Modifier Keys

Emacs uses many modifier keys:

| S | shift    |
| M | alt/meta |
| C | Ctrl     |
| s | super    |
| H | hyper    |

While most keyboards have =shift=, =alt= and =CTRL= keys, =super= and
=hyper= keys are rare.

Emacs is able to remap some keys to act as these additional modifiers.

... Insert commands to remap here  ...

** Markup shortcuts
</code>

**Comment by jkitchin** [comment]
I did this for Mac. Any chance you would share what commands you used on your platform?

**Comment by AKielhorn** [comment]
Well, my platform is the Mac as well.
But I have to use Windows (7) at work.
I'll look into it, even if it will not work on Win 10.

BTW, today I discovered two keyboards which didn't have an "apps" key.
(The function was available via Fn + some key, different key on different keyboards.)

With the inability to map "Windows" and the unavailability of "apps" it may be difficult to use additional modifier keys on Windows.

**Comment by AKielhorn** [comment]
I have tested the windows key as super setup on Windows 7 and 10.
The results are included in the patch to scimax.org.

While the Windows key is barely usable on Windows 7 it is completely unusable on Windows 10.
This leaves one modifier key bound to the apps key.

Maybe someone who knows more about Windows can offer a solution.

[patch.txt](https://github.com/jkitchin/scimax/files/1790356/patch.txt)

**Comment by jkitchin** [comment]
Thanks. I added this information to the manual.
