### ISSUE TITLE
Incorrect path for SCIMAX_ROOT with portable Git on Win 7

### ISSUE THREAD

**Issue by AKielhorn** [jkitchin/scimax#18]
I installed portable git as a regular user on Win 7.

(You may add to the instructions that one should configure the User Name and E-Mail address in git before installing scimax.) 

Inside the bash I ran the recommended incantation.

The SCIMAX_ROOT was `"s:imacs ..."` because the result of `pwd` was `/scimax`
Maybe I should have `cd`ed to `~` first.
(Using the non-portable version gives the right path.)

I added a `cd` to my documents folder in front of the `runemacs` thus I start at the right place.

So far everything else looks good.

Axel

**Comment by jkitchin** [comment]
Thanks for the tip about the git configuration. I added that to the windows install script.

I wasn't able to reproduce the second issue. Is there something unusual about where you portable git?

**Comment by AKielhorn** [comment]
Last week I installed a more recent version of portable git on my work computer.
When I click on the bash icon to open a shell my cwd is `/` instead of `~`.

This is on Windows 7 Pro.
I install portable git in `%USERPROFILE%`

There is nothing in my startup files that influences this, just a `PATH` setting and an `alias`.
