### ISSUE TITLE
Can't open agents view TODO (ipython?)

### ISSUE THREAD

**Issue by AKielhorn** [jkitchin/scimax#181]
When I call the agenda with `C-c a t` I get the following error:
`
Debugger entered--Lisp error: (json-readtable-error)
  signal(json-readtable-error nil)
  json-read()
  json-read-from-string("/bin/bash: jupyter: command not found\n")
  (car (json-read-from-string (shell-command-to-string (s-concat ob-ipython-command " kernelspec list --json"))))
  (cdr (car (json-read-from-string (shell-command-to-string (s-concat ob-ipython-command " kernelspec list --json")))))
  (let ((kernelspecs (cdr (car (json-read-from-string (shell-command-to-string (s-concat ob-ipython-command " kernelspec list --json"))))))) (-map (function (lambda (spec) (cons (symbol-name (car spec)) (cdr (assoc (quote language) (cdr ...)))))) kernelspecs))
  (and ob-ipython-command (let ((kernelspecs (cdr (car (json-read-from-string (shell-command-to-string ...)))))) (-map (function (lambda (spec) (cons (symbol-name (car spec)) (cdr (assoc ... ...))))) kernelspecs)))
  ob-ipython--get-kernels()
  (-map (quote ob-ipython--configure-kernel) (ob-ipython--get-kernels))
  (setq ob-ipython-configured-kernels (-map (quote ob-ipython--configure-kernel) (ob-ipython--get-kernels)))
  (progn (setq ob-ipython-configured-kernels (-map (quote ob-ipython--configure-kernel) (ob-ipython--get-kernels))))
  (if (or replace (not ob-ipython-configured-kernels)) (progn (setq ob-ipython-configured-kernels (-map (quote ob-ipython--configure-kernel) (ob-ipython--get-kernels)))))
  ob-ipython-auto-configure-kernels()
  run-hooks(change-major-mode-after-body-hook text-mode-hook outline-mode-hook org-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook text-mode-hook outline-mode-hook org-mode-hook))
  run-mode-hooks(org-mode-hook)
  org-mode()
  set-auto-mode-0(org-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer Arbeit.org> "~/org/Arbeit.org" nil nil "~/org/Arbeit.org" (987705 16777227))
  find-file-noselect("~/org/Arbeit.org")
  org-get-agenda-file-buffer("~/org/Arbeit.org")
  org-agenda-prepare-buffers(("~/org/Arbeit.org" "~/org/HSHB.org" "~/org/Geburtstag.org" "~/org/Termine.org"))
  (if org-agenda-multi (progn (setq buffer-read-only nil) (goto-char (point-max)) (if (or (bobp) org-agenda-compact-blocks (not org-agenda-block-separator)) nil (insert "\n" (if (stringp org-agenda-block-separator) org-agenda-block-separator (make-string (window-width) org-agenda-block-separator)) "\n")) (narrow-to-region (point) (point-max))) (setq org-done-keywords-for-agenda nil) (org-agenda-prepare-window (get-buffer-create org-agenda-buffer-name) filter-alist) (setq buffer-read-only nil) (org-agenda-reset-markers) (let ((inhibit-read-only t)) (erase-buffer)) (org-agenda-mode) (setq org-agenda-buffer (current-buffer)) (setq org-agenda-contributing-files nil) (setq org-agenda-columns-active nil) (org-agenda-prepare-buffers (org-agenda-files nil (quote ifmode))) (setq org-todo-keywords-for-agenda (org-uniquify org-todo-keywords-for-agenda)) (setq org-done-keywords-for-agenda (org-uniquify org-done-keywords-for-agenda)) (setq org-agenda-last-prefix-arg current-prefix-arg) (setq org-agenda-this-buffer-name org-agenda-buffer-name) (and name (not org-agenda-name) (set (make-local-variable (quote org-agenda-name)) name)))
  (if (org-agenda-use-sticky-p) (progn (put (quote org-agenda-tag-filter) :preset-filter nil) (put (quote org-agenda-category-filter) :preset-filter nil) (put (quote org-agenda-regexp-filter) :preset-filter nil) (org-agenda-prepare-window (get-buffer org-agenda-buffer-name) filter-alist) (message "Sticky Agenda buffer, use `r' to refresh") (or org-agenda-multi (org-agenda-fit-window-to-buffer)) (throw (quote exit) "Sticky Agenda buffer, use `r' to refresh")) (setq org-todo-keywords-for-agenda nil) (put (quote org-agenda-tag-filter) :preset-filter org-agenda-tag-filter-preset) (put (quote org-agenda-category-filter) :preset-filter org-agenda-category-filter-preset) (put (quote org-agenda-regexp-filter) :preset-filter org-agenda-regexp-filter-preset) (put (quote org-agenda-effort-filter) :preset-filter org-agenda-effort-filter-preset) (if org-agenda-multi (progn (setq buffer-read-only nil) (goto-char (point-max)) (if (or (bobp) org-agenda-compact-blocks (not org-agenda-block-separator)) nil (insert "\n" (if (stringp org-agenda-block-separator) org-agenda-block-separator (make-string (window-width) org-agenda-block-separator)) "\n")) (narrow-to-region (point) (point-max))) (setq org-done-keywords-for-agenda nil) (org-agenda-prepare-window (get-buffer-create org-agenda-buffer-name) filter-alist) (setq buffer-read-only nil) (org-agenda-reset-markers) (let ((inhibit-read-only t)) (erase-buffer)) (org-agenda-mode) (setq org-agenda-buffer (current-buffer)) (setq org-agenda-contributing-files nil) (setq org-agenda-columns-active nil) (org-agenda-prepare-buffers (org-agenda-files nil (quote ifmode))) (setq org-todo-keywords-for-agenda (org-uniquify org-todo-keywords-for-agenda)) (setq org-done-keywords-for-agenda (org-uniquify org-done-keywords-for-agenda)) (setq org-agenda-last-prefix-arg current-prefix-arg) (setq org-agenda-this-buffer-name org-agenda-buffer-name) (and name (not org-agenda-name) (set (make-local-variable (quote org-agenda-name)) name))) (setq buffer-read-only nil))
  (let ((filter-alist (if org-agenda-persistent-filter (save-current-buffer (set-buffer (get-buffer-create org-agenda-buffer-name)) (list (cons (quote tag) org-agenda-tag-filter) (cons (quote re) org-agenda-regexp-filter) (cons (quote effort) org-agenda-effort-filter) (cons (quote cat) org-agenda-category-filter)))))) (if (org-agenda-use-sticky-p) (progn (put (quote org-agenda-tag-filter) :preset-filter nil) (put (quote org-agenda-category-filter) :preset-filter nil) (put (quote org-agenda-regexp-filter) :preset-filter nil) (org-agenda-prepare-window (get-buffer org-agenda-buffer-name) filter-alist) (message "Sticky Agenda buffer, use `r' to refresh") (or org-agenda-multi (org-agenda-fit-window-to-buffer)) (throw (quote exit) "Sticky Agenda buffer, use `r' to refresh")) (setq org-todo-keywords-for-agenda nil) (put (quote org-agenda-tag-filter) :preset-filter org-agenda-tag-filter-preset) (put (quote org-agenda-category-filter) :preset-filter org-agenda-category-filter-preset) (put (quote org-agenda-regexp-filter) :preset-filter org-agenda-regexp-filter-preset) (put (quote org-agenda-effort-filter) :preset-filter org-agenda-effort-filter-preset) (if org-agenda-multi (progn (setq buffer-read-only nil) (goto-char (point-max)) (if (or (bobp) org-agenda-compact-blocks (not org-agenda-block-separator)) nil (insert "\n" (if (stringp org-agenda-block-separator) org-agenda-block-separator (make-string ... org-agenda-block-separator)) "\n")) (narrow-to-region (point) (point-max))) (setq org-done-keywords-for-agenda nil) (org-agenda-prepare-window (get-buffer-create org-agenda-buffer-name) filter-alist) (setq buffer-read-only nil) (org-agenda-reset-markers) (let ((inhibit-read-only t)) (erase-buffer)) (org-agenda-mode) (setq org-agenda-buffer (current-buffer)) (setq org-agenda-contributing-files nil) (setq org-agenda-columns-active nil) (org-agenda-prepare-buffers (org-agenda-files nil (quote ifmode))) (setq org-todo-keywords-for-agenda (org-uniquify org-todo-keywords-for-agenda)) (setq org-done-keywords-for-agenda (org-uniquify org-done-keywords-for-agenda)) (setq org-agenda-last-prefix-arg current-prefix-arg) (setq org-agenda-this-buffer-name org-agenda-buffer-name) (and name (not org-agenda-name) (set (make-local-variable (quote org-agenda-name)) name))) (setq buffer-read-only nil)))
  org-agenda-prepare("TODO")
  (catch (quote exit) (if org-agenda-sticky (setq org-agenda-buffer-name (if (stringp org-select-this-todo-keyword) (format "*Org Agenda(%s:%s)*" (or org-keys "t") org-select-this-todo-keyword) (format "*Org Agenda(%s)*" (or org-keys "t"))))) (org-agenda-prepare "TODO") (org-compile-prefix-format (quote todo)) (org-set-sorting-strategy (quote todo)) (setq org-agenda-redo-command (list (quote org-todo-list) (list (quote or) (quote (and (numberp current-prefix-arg) current-prefix-arg)) org-select-this-todo-keyword (quote current-prefix-arg) arg))) (setq files (org-agenda-files nil (quote ifmode)) rtnall nil) (while (setq file (car-safe (prog1 files (setq files (cdr files))))) (catch (quote nextfile) (org-check-agenda-file file) (setq rtn (org-agenda-get-day-entries file date :todo)) (setq rtnall (append rtnall rtn)))) (cond ((not org-agenda-overriding-header) (insert (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn ... ... ... ... ... ... ... ...) (and ... ...)))))) ((equal org-agenda-overriding-header "") nil) ((stringp org-agenda-overriding-header) (insert (propertize org-agenda-overriding-header (quote face) (quote org-agenda-structure)) "\n")) (t (user-error "Invalid value for `org-agenda-overriding-header': %S" org-agenda-overriding-header))) (org-agenda-mark-header-line (point-min)) (if rtnall (progn (insert (org-agenda-finalize-entries rtnall (quote todo)) "\n"))) (goto-char (point-min)) (or org-agenda-multi (org-agenda-fit-window-to-buffer)) (add-text-properties (point-min) (point-max) (list (quote org-agenda-type) (quote todo) (quote org-last-args) arg (quote org-redo-cmd) org-agenda-redo-command (quote org-series-cmd) org-cmd)) (org-agenda-finalize) (setq buffer-read-only t))
  (let* ((today (org-today)) (date (calendar-gregorian-from-absolute today)) (kwds org-todo-keywords-for-agenda) (completion-ignore-case t) (org-select-this-todo-keyword (if (stringp arg) arg (and arg (integerp arg) (> arg 0) (nth (1- arg) kwds)))) rtn rtnall files file pos) (if (equal arg (quote (4))) (progn (setq org-select-this-todo-keyword (completing-read "Keyword (or KWD1|K2D2|...): " (mapcar (function list) kwds) nil nil)))) (and (equal 0 arg) (setq org-select-this-todo-keyword nil)) (catch (quote exit) (if org-agenda-sticky (setq org-agenda-buffer-name (if (stringp org-select-this-todo-keyword) (format "*Org Agenda(%s:%s)*" (or org-keys "t") org-select-this-todo-keyword) (format "*Org Agenda(%s)*" (or org-keys "t"))))) (org-agenda-prepare "TODO") (org-compile-prefix-format (quote todo)) (org-set-sorting-strategy (quote todo)) (setq org-agenda-redo-command (list (quote org-todo-list) (list (quote or) (quote (and (numberp current-prefix-arg) current-prefix-arg)) org-select-this-todo-keyword (quote current-prefix-arg) arg))) (setq files (org-agenda-files nil (quote ifmode)) rtnall nil) (while (setq file (car-safe (prog1 files (setq files (cdr files))))) (catch (quote nextfile) (org-check-agenda-file file) (setq rtn (org-agenda-get-day-entries file date :todo)) (setq rtnall (append rtnall rtn)))) (cond ((not org-agenda-overriding-header) (insert (let ((temp-buffer ...)) (save-current-buffer (set-buffer temp-buffer) (unwind-protect ... ...))))) ((equal org-agenda-overriding-header "") nil) ((stringp org-agenda-overriding-header) (insert (propertize org-agenda-overriding-header (quote face) (quote org-agenda-structure)) "\n")) (t (user-error "Invalid value for `org-agenda-overriding-header': %S" org-agenda-overriding-header))) (org-agenda-mark-header-line (point-min)) (if rtnall (progn (insert (org-agenda-finalize-entries rtnall (quote todo)) "\n"))) (goto-char (point-min)) (or org-agenda-multi (org-agenda-fit-window-to-buffer)) (add-text-properties (point-min) (point-max) (list (quote org-agenda-type) (quote todo) (quote org-last-args) arg (quote org-redo-cmd) org-agenda-redo-command (quote org-series-cmd) org-cmd)) (org-agenda-finalize) (setq buffer-read-only t)))
  org-todo-list(nil)
  funcall-interactively(org-todo-list nil)
  call-interactively(org-todo-list)
  (cond ((setq entry (assoc org-keys org-agenda-custom-commands)) (if (or (symbolp (nth 2 entry)) (functionp (nth 2 entry))) (progn (setq type (nth 2 entry) org-match (eval (nth 3 entry)) lprops (nth 4 entry)) (if org-agenda-sticky (setq org-agenda-buffer-name (or (and ... ...) (format "*Org Agenda(%s)*" org-keys)))) (put (quote org-agenda-redo-command) (quote org-lprops) lprops) (cond ((eq type (quote agenda)) (org-let lprops (quote ...))) ((eq type (quote agenda*)) (org-let lprops (quote ...))) ((eq type (quote alltodo)) (org-let lprops (quote ...))) ((eq type (quote search)) (org-let lprops (quote ...))) ((eq type (quote stuck)) (org-let lprops (quote ...))) ((eq type (quote tags)) (org-let lprops (quote ...))) ((eq type (quote tags-todo)) (org-let lprops (quote ...))) ((eq type (quote todo)) (org-let lprops (quote ...))) ((eq type (quote tags-tree)) (org-check-for-org-mode) (org-let lprops (quote ...))) ((eq type (quote todo-tree)) (org-check-for-org-mode) (org-let lprops (quote ...))) ((eq type (quote occur-tree)) (org-check-for-org-mode) (org-let lprops (quote ...))) ((functionp type) (org-let lprops (quote ...))) ((fboundp type) (org-let lprops (quote ...))) (t (user-error "Invalid custom agenda command type %s" type)))) (org-agenda-run-series (nth 1 entry) (cdr (cdr entry))))) ((equal org-keys "C") (setq org-agenda-custom-commands org-agenda-custom-commands-orig) (customize-variable (quote org-agenda-custom-commands))) ((equal org-keys "a") (call-interactively (quote org-agenda-list))) ((equal org-keys "s") (call-interactively (quote org-search-view))) ((equal org-keys "S") (org-call-with-arg (quote org-search-view) (or arg (quote (4))))) ((equal org-keys "t") (call-interactively (quote org-todo-list))) ((equal org-keys "T") (org-call-with-arg (quote org-todo-list) (or arg (quote (4))))) ((equal org-keys "m") (call-interactively (quote org-tags-view))) ((equal org-keys "M") (org-call-with-arg (quote org-tags-view) (or arg (quote (4))))) ((equal org-keys "e") (call-interactively (quote org-store-agenda-views))) ((equal org-keys "?") (org-tags-view nil "+FLAGGED") (add-hook (quote post-command-hook) (function (lambda nil (if (current-message) nil (let* (... ...) (if note ...))))) t t)) ((equal org-keys "#") (call-interactively (quote org-agenda-list-stuck-projects))) ((equal org-keys "/") (call-interactively (quote org-occur-in-agenda-files))) ((equal org-keys "!") (customize-variable (quote org-stuck-projects))) (t (user-error "Invalid agenda key")))
  (let* ((prefix-descriptions nil) (org-agenda-buffer-name org-agenda-buffer-name) (org-agenda-window-setup (if (equal (buffer-name) org-agenda-buffer-name) (quote current-window) org-agenda-window-setup)) (org-agenda-custom-commands-orig org-agenda-custom-commands) (org-agenda-custom-commands (delq nil (mapcar (function (lambda (x) (cond ... ... ... ...))) org-agenda-custom-commands))) (org-agenda-custom-commands (org-contextualize-keys org-agenda-custom-commands org-agenda-custom-commands-contexts)) (buf (current-buffer)) (bfn (buffer-file-name (buffer-base-buffer))) entry key type org-match lprops ans) (if org-agenda-overriding-restriction nil (if org-agenda-keep-restricted-file-list nil (put (quote org-agenda-files) (quote org-restrict) nil)) (setq org-agenda-restrict nil) (move-marker org-agenda-restrict-begin nil) (move-marker org-agenda-restrict-end nil)) (put (quote org-agenda-redo-command) (quote org-lprops) nil) (put (quote org-agenda-redo-command) (quote last-args) nil) (setq org-agenda-last-dispatch-buffer (current-buffer)) (if org-keys nil (setq ans (org-agenda-get-restriction-and-command prefix-descriptions) org-keys (car ans) restriction (cdr ans))) (if org-agenda-sticky (setq org-agenda-buffer-name (format "*Org Agenda(%s)*" org-keys))) (if (and (not org-agenda-overriding-restriction) restriction) (progn (put (quote org-agenda-files) (quote org-restrict) (list bfn)) (cond ((eq restriction (quote region)) (setq org-agenda-restrict (current-buffer)) (move-marker org-agenda-restrict-begin (region-beginning)) (move-marker org-agenda-restrict-end (region-end))) ((eq restriction (quote subtree)) (save-excursion (setq org-agenda-restrict (current-buffer)) (org-back-to-heading t) (move-marker org-agenda-restrict-begin (point)) (move-marker org-agenda-restrict-end (progn ...))))))) (cond ((setq entry (assoc org-keys org-agenda-custom-commands)) (if (or (symbolp (nth 2 entry)) (functionp (nth 2 entry))) (progn (setq type (nth 2 entry) org-match (eval (nth 3 entry)) lprops (nth 4 entry)) (if org-agenda-sticky (setq org-agenda-buffer-name (or ... ...))) (put (quote org-agenda-redo-command) (quote org-lprops) lprops) (cond ((eq type ...) (org-let lprops ...)) ((eq type ...) (org-let lprops ...)) ((eq type ...) (org-let lprops ...)) ((eq type ...) (org-let lprops ...)) ((eq type ...) (org-let lprops ...)) ((eq type ...) (org-let lprops ...)) ((eq type ...) (org-let lprops ...)) ((eq type ...) (org-let lprops ...)) ((eq type ...) (org-check-for-org-mode) (org-let lprops ...)) ((eq type ...) (org-check-for-org-mode) (org-let lprops ...)) ((eq type ...) (org-check-for-org-mode) (org-let lprops ...)) ((functionp type) (org-let lprops ...)) ((fboundp type) (org-let lprops ...)) (t (user-error "Invalid custom agenda command type %s" type)))) (org-agenda-run-series (nth 1 entry) (cdr (cdr entry))))) ((equal org-keys "C") (setq org-agenda-custom-commands org-agenda-custom-commands-orig) (customize-variable (quote org-agenda-custom-commands))) ((equal org-keys "a") (call-interactively (quote org-agenda-list))) ((equal org-keys "s") (call-interactively (quote org-search-view))) ((equal org-keys "S") (org-call-with-arg (quote org-search-view) (or arg (quote (4))))) ((equal org-keys "t") (call-interactively (quote org-todo-list))) ((equal org-keys "T") (org-call-with-arg (quote org-todo-list) (or arg (quote (4))))) ((equal org-keys "m") (call-interactively (quote org-tags-view))) ((equal org-keys "M") (org-call-with-arg (quote org-tags-view) (or arg (quote (4))))) ((equal org-keys "e") (call-interactively (quote org-store-agenda-views))) ((equal org-keys "?") (org-tags-view nil "+FLAGGED") (add-hook (quote post-command-hook) (function (lambda nil (if (current-message) nil (let* ... ...)))) t t)) ((equal org-keys "#") (call-interactively (quote org-agenda-list-stuck-projects))) ((equal org-keys "/") (call-interactively (quote org-occur-in-agenda-files))) ((equal org-keys "!") (customize-variable (quote org-stuck-projects))) (t (user-error "Invalid agenda key"))))
  (catch (quote exit) (let* ((prefix-descriptions nil) (org-agenda-buffer-name org-agenda-buffer-name) (org-agenda-window-setup (if (equal (buffer-name) org-agenda-buffer-name) (quote current-window) org-agenda-window-setup)) (org-agenda-custom-commands-orig org-agenda-custom-commands) (org-agenda-custom-commands (delq nil (mapcar (function (lambda ... ...)) org-agenda-custom-commands))) (org-agenda-custom-commands (org-contextualize-keys org-agenda-custom-commands org-agenda-custom-commands-contexts)) (buf (current-buffer)) (bfn (buffer-file-name (buffer-base-buffer))) entry key type org-match lprops ans) (if org-agenda-overriding-restriction nil (if org-agenda-keep-restricted-file-list nil (put (quote org-agenda-files) (quote org-restrict) nil)) (setq org-agenda-restrict nil) (move-marker org-agenda-restrict-begin nil) (move-marker org-agenda-restrict-end nil)) (put (quote org-agenda-redo-command) (quote org-lprops) nil) (put (quote org-agenda-redo-command) (quote last-args) nil) (setq org-agenda-last-dispatch-buffer (current-buffer)) (if org-keys nil (setq ans (org-agenda-get-restriction-and-command prefix-descriptions) org-keys (car ans) restriction (cdr ans))) (if org-agenda-sticky (setq org-agenda-buffer-name (format "*Org Agenda(%s)*" org-keys))) (if (and (not org-agenda-overriding-restriction) restriction) (progn (put (quote org-agenda-files) (quote org-restrict) (list bfn)) (cond ((eq restriction (quote region)) (setq org-agenda-restrict (current-buffer)) (move-marker org-agenda-restrict-begin (region-beginning)) (move-marker org-agenda-restrict-end (region-end))) ((eq restriction (quote subtree)) (save-excursion (setq org-agenda-restrict ...) (org-back-to-heading t) (move-marker org-agenda-restrict-begin ...) (move-marker org-agenda-restrict-end ...)))))) (cond ((setq entry (assoc org-keys org-agenda-custom-commands)) (if (or (symbolp (nth 2 entry)) (functionp (nth 2 entry))) (progn (setq type (nth 2 entry) org-match (eval ...) lprops (nth 4 entry)) (if org-agenda-sticky (setq org-agenda-buffer-name ...)) (put (quote org-agenda-redo-command) (quote org-lprops) lprops) (cond (... ...) (... ...) (... ...) (... ...) (... ...) (... ...) (... ...) (... ...) (... ... ...) (... ... ...) (... ... ...) (... ...) (... ...) (t ...))) (org-agenda-run-series (nth 1 entry) (cdr (cdr entry))))) ((equal org-keys "C") (setq org-agenda-custom-commands org-agenda-custom-commands-orig) (customize-variable (quote org-agenda-custom-commands))) ((equal org-keys "a") (call-interactively (quote org-agenda-list))) ((equal org-keys "s") (call-interactively (quote org-search-view))) ((equal org-keys "S") (org-call-with-arg (quote org-search-view) (or arg (quote (4))))) ((equal org-keys "t") (call-interactively (quote org-todo-list))) ((equal org-keys "T") (org-call-with-arg (quote org-todo-list) (or arg (quote (4))))) ((equal org-keys "m") (call-interactively (quote org-tags-view))) ((equal org-keys "M") (org-call-with-arg (quote org-tags-view) (or arg (quote (4))))) ((equal org-keys "e") (call-interactively (quote org-store-agenda-views))) ((equal org-keys "?") (org-tags-view nil "+FLAGGED") (add-hook (quote post-command-hook) (function (lambda nil (if ... nil ...))) t t)) ((equal org-keys "#") (call-interactively (quote org-agenda-list-stuck-projects))) ((equal org-keys "/") (call-interactively (quote org-occur-in-agenda-files))) ((equal org-keys "!") (customize-variable (quote org-stuck-projects))) (t (user-error "Invalid agenda key")))))
  org-agenda(nil)
  funcall-interactively(org-agenda nil)
  call-interactively(org-agenda nil nil)
  command-execute(org-agenda)
` 
When I continue I finally get:
`
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  looking-at(nil)
  (save-excursion (goto-char p) (looking-at comment-start-skip))
  (or (save-excursion (goto-char p) (looking-at comment-start-skip)) (and org-agenda-skip-archived-trees (not org-agenda-archives-mode) (get-text-property p :org-archived) (org-end-of-subtree t)) (and org-agenda-skip-comment-trees (get-text-property p :org-comment) (org-end-of-subtree t)) (and (setq to (or (org-agenda-skip-eval org-agenda-skip-function-global) (org-agenda-skip-eval org-agenda-skip-function))) (goto-char to)) (org-in-src-block-p t))
  (if (or (save-excursion (goto-char p) (looking-at comment-start-skip)) (and org-agenda-skip-archived-trees (not org-agenda-archives-mode) (get-text-property p :org-archived) (org-end-of-subtree t)) (and org-agenda-skip-comment-trees (get-text-property p :org-comment) (org-end-of-subtree t)) (and (setq to (or (org-agenda-skip-eval org-agenda-skip-function-global) (org-agenda-skip-eval org-agenda-skip-function))) (goto-char to)) (org-in-src-block-p t)) (progn (throw :skip t)))
  (let ((p (point-at-bol)) to) (if (or (save-excursion (goto-char p) (looking-at comment-start-skip)) (and org-agenda-skip-archived-trees (not org-agenda-archives-mode) (get-text-property p :org-archived) (org-end-of-subtree t)) (and org-agenda-skip-comment-trees (get-text-property p :org-comment) (org-end-of-subtree t)) (and (setq to (or (org-agenda-skip-eval org-agenda-skip-function-global) (org-agenda-skip-eval org-agenda-skip-function))) (goto-char to)) (org-in-src-block-p t)) (progn (throw :skip t))))
  org-agenda-skip()
`

I don't use ipython and have nothing configured.
This happens with my home system with org from git on Mac OS X and at work with org from elpa and Windows.

**Comment by jkitchin** [comment]
i haven't been able to reproduce this, but I have jupyter installed, and use ipython all the time.

I don't know what could be causing it though. Can you check what files are in org-agenda-files?

Also, is this a relatively new thing that has happened?

**Comment by AKielhorn** [comment]
f0e23fc <2018-02-16> does work.
512ce7b does not.

Which is strange, since it only changes a key binding.

**Comment by AKielhorn** [comment]
After updating to f81fba7 and looking at cc2f311 I narrowed it down to:

```
 ;; this is a git submodule
-(use-package ob-ipython
-  :ensure nil
-  :load-path (lambda () (expand-file-name "ob-ipython-upstream" scimax-dir))
-  :init (add-to-list 'load-path (expand-file-name "ob-ipython-upstream" scimax-dir))
-  (require 'ob-ipython))
+; (use-package ob-ipython
+;   :ensure nil
+;   :load-path (lambda () (expand-file-name "ob-ipython-upstream" scimax-dir))
+;   :init (add-to-list 'load-path (expand-file-name "ob-ipython-upstream" scimax-dir))
+;  (require 'ob-ipython))
```

With this change, `scimax` works fine even when no jupyter is found.

Is there a way to only load `ob-python` when jupyter is in the path?

**Comment by jkitchin** [comment]
commit e8d5d32 should make this loading conditional. Thanks for tracking down and reporting the issue.

**Comment by AKielhorn** [comment]
Thanks,

I now get a message
```
jupyter was not found on your path. ob-ipython was not loaded.
```

and everything works as expected.
