### ISSUE TITLE
Convert to latex/pdf gives error but no message

### ISSUE THREAD

**Issue by Arjay-El** [jkitchin/scimax#184]
I have text that has a few equations and a list. When I send it to Latex/pdf, it states the pdf was not generated and to check "*Org PDF LaTeX Ouputs*. That buffer is empty. Is there suppose to be a message there? Is there some other way to check where the conversion failed? thanks

**Comment by jkitchin** [comment]
you should probably try to build the latex by hand.

you might also try running (ox-manuscript-toggle-interactive-build), which may be more informative.

It would be nice if there was better failure information.

**Comment by jkitchin** [comment]
would it be possible for you to post a small org example you are having trouble with?

**Comment by Arjay-El** [comment]
Turned out to be a missed underscore in an image name.  You can close this issue, I was just confused by the buffer being empty of any error information. A test in Texstudio helped find the problem. Thanks.

**Comment by jkitchin** [comment]
I am going to leave it open, because this same issue bugs me too. It is just infrequent it comes up, and low on the list of things to do! This will remind me one day to make it easier to debug.
