### ISSUE TITLE
Using toggle latex-images vs C-c C-x C-L

### ISSUE THREAD

**Issue by Arjay-El** [jkitchin/scimax#187]
I can toggle latex formulas with C-c C-x C-L but using the menu item in Scimax Toggle latex-images to activate the overlay gives this message: command-execute: Wrong type argument: commandp, org-toggle-latex-overlays. Is there a difference between these two methods?

**Comment by jkitchin** [comment]
I pushed a fix for this. I am not sure if the command name changed at some point, or I put the wrong command in at some point. Either way, thanks for reporting it!
