### ISSUE TITLE
scimax-dashboard loading error

### ISSUE THREAD

**Issue by Arjay-El** [jkitchin/scimax#188]
I did a new install for scimax as I wanted to try the dashboard feature. 'scimax-dashboard' did not show up in the command list for scimax-. So placed scimax-dashboard.el in a directory where I load other misc. .el files. I added a path to it  and a (require...) for it in user.el.  It then appeared in the minibuffer menu but I obtain this error message when I select it:

Loading c:/scimax/scimax-dashboard.el (source)...
if: Symbol’s value as variable is void: dashboard-item-generators

**Comment by jkitchin** [comment]
There was a missing require that I just pushed. This was an experiment. I like the idea, but I don't use it myself too often. If you have ideas for improving it, please file issues. Thanks.
