### ISSUE TITLE
Menu entries not loading

### ISSUE THREAD

**Issue by rbirkelbach** [jkitchin/scimax#189]
Hello,

I use an unmodified scimax version and GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.28) on Arch Gnu/Linux with Gnome. The menu entries for Lisp-Interaction, Outline, and Scimax often do not show up when clicking on the menu entry. It is rather unpredictable when they show up/not show up, but they do not show up most of the time.
Do you  have an idea what could be going on?

Edit: the same holds true for the menu items text, org and tbl. 

Thanks,
Robert

**Comment by jkitchin** [comment]
I don't have an idea. I occasionally see a lag on opening the menu. I think somewhere I set up something that might be checking a status on github. That is the only think that I think could be related.

**Comment by rbirkelbach** [comment]
I think this was caused from not having installed Jupyter. I just installed it and didn't observe this behavior so far. However, I think it would be good not to be forced to have Jupyter installed, because this starter kit is really nice even without using python notebooks.

**Comment by jkitchin** [comment]
I don't think jupyter is required (I could be wrong about that, it could be
possible somewhere it is looking up something specific about jupyter, but I
don't know where that would be).

John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu


On Mon, Mar 26, 2018 at 4:26 PM, Robert Birkelbach <notifications@github.com

**Comment by rbirkelbach** [comment]
Yes, the issue reappeared, so it's not caused by Jupyter. That's the reason I deleted my former response. In the future, I'll just edit my comments or write another comment.

**Comment by jkitchin** [comment]
I don't know what could be causing this. I had a look through the menu code (scimax-mode.el) and there si nothing that stands out as problematic. It doesnt' appear there is anything checking github now (there was and I have it commented out).

There is a hook in menu-bar-update-hook that updates a projects menu from scimax. If that was slow (because you have a lot of projects, for example) maybe that is a problem?

**Comment by rbirkelbach** [comment]
I think that did the trick. I just restarted emacs and everything's available immediately. I'll close this issue for now, but if the problem resurfaces, I'll reopen it. Thank you very much!

**Comment by jkitchin** [comment]
what was the trick?

**Comment by rbirkelbach** [comment]
I pulled the newest Version. I was behind a couple of commits apparently, though I do not remember by heart how many.
