### ISSUE TITLE
org-plus-contrib and org

### ISSUE THREAD

**Issue by AKielhorn** [jkitchin/scimax#190]
I just did a clean install from git.

`scimax` installs both `org-plus-contrib` and `org` into `elpa`.

The later is probably loaded due to a dependency.

This is really an `org` problem, but it can lead to a mixed installation when only one package is updated.

Since I use `org` from git I will remove both.

**Comment by jkitchin** [comment]
Thanks for reporting this. I am not sure what I can do about it. Any suggestions?
