### ISSUE TITLE
How to use modular components of scimax (like new ipython)?

### ISSUE THREAD

**Issue by apnewberry** [jkitchin/scimax#191]
I just discovered scimax and I'm pretty excited about it. I'm looking to get started with some of the features, like the fancy new `ob-ipython`.

Since I already have a fair amount of emacs/org configuration of my own, I'd like to incorporate scimax a bit at a time, rather than enabling the whole thing all at once, so I have a better sense of what changes I'm making and so I have finer-grained control of which packages are controlling what.

I see [the docs say](https://github.com/jkitchin/scimax/blob/master/scimax-ipython.org#updates-to-ipython-in-scimax) 

> The new update is in two files: ./scimax-ob.el, which contains pretty general functions for all org babel src blocks I think, and ./scimax-org-babel-ipython-upstream.el which contains monkey-patches on ob-ipython, and additional features.

Is there a recommended way to use only the new `ob-ipython`, while keeping the other components disabled? 

I already have the MELPA version of ob-ipython installed. Should I then clone this repo and `(require 'scimax-ob)` and `(require scimax-org-babel-ipython-upstream)` to get the added scimax ipython features? What of `scimax-ob`, `scimax-notebook` and `scimax-org-babel-ipython`?

Thanks for your help!

**Comment by jkitchin** [comment]
You can do any of the following:
1. use load-file to load specific files in scimax
2. add scimax to your load-path and require what you want.

You will have to read the source files to see what is required, and then debug what is missing. You probably need scimax-ob and scimax-org-babel-ipython-upstream. You do not need scimax-notebook or scimax-org-babel-ipython (which is the old branch).

**Comment by singletS** [comment]
These seem to be the minimum needed to get things working for me on a (very) simplified spacemacs install:
```
(require 'ox-ipynb)
(require 'ob-ipython)
(require 'scimax-org-babel-ipython-upstream)
```
My .spacemacs loads a file that adds a few things like Easy Template definitions, keymap tweaks, etc., and the nuke-ipython function (found in scimax-org-babel-ipython.el).

**Comment by apnewberry** [comment]
This works, thanks. I'll leave it open in case you want to reference it for the docs or anything.

**Comment by jkitchin** [comment]
Thanks.
