### ISSUE TITLE
pdf links are not converted correctly upon latex export when in an outside directory

### ISSUE THREAD

**Issue by Hagopian** [jkitchin/scimax#192]
I've experienced an issue, where links to pdfs (but not .org ) files do not work in an exported pdf if the linked pdf is not in the same subtree. If one looks in the .tex file one can see that links to "outside" *.org files and *.pdf files look the same, but after the pdf conversion this is not true anymore. I'm therefore not sure where this problem comes from scimax/org-mode or the pdf conversion.
However the issue can be resolved by forcing relative links also for outside directories by setting (setq org-link-file-path-type 'relative).
See attached files for details (the jpg summarises the behaviour) The ZIP file contains all relevant files.
My tree structure is:
D:\outside-dir\\*files
D:\test\subdirectory\\*files
D:\test\\*files

![pdf-links-in-latex-export](https://user-images.githubusercontent.com/16701489/38412237-3161b556-3989-11e8-9a54-acea3a4395b2.jpg)
[subdirectory.zip](https://github.com/jkitchin/scimax/files/1883319/subdirectory.zip)
[outside-dir.zip](https://github.com/jkitchin/scimax/files/1883341/outside-dir.zip)

**Comment by jkitchin** [comment]
This seems like a question for the org-mode mailing list. I don't think scimax does anything special in this regard.

**Comment by Hagopian** [comment]
ok I'll see that I get some input from them ..

Thx

**Comment by jkitchin** [comment]
I am trying to understand the issue here. It seems like a latex issue and href with absolute paths. See https://tex.stackexchange.com/questions/12787/macos-x-insert-hyperlink-to-local-file-complete-path-in-latex-only-working. I am going to close this.

**Comment by Hagopian** [comment]
Just checked back on it, yeah it seems it is an issue of the latex conversion. 
Nevertheless my workaround is to set (setq org-link-file-path-type 'relative) and it works fine for me so far.
