### ISSUE TITLE
Does someone use evil-mode with scimax?

### ISSUE THREAD

**Issue by rbirkelbach** [jkitchin/scimax#193]
Hello,

I have been using spacemacs for quite a while but have trouble going back to standard emacs keybindings, because I am prone to RSI. So I was wondering whether there's someone out there using evil mode with scimax and maybe even managed to adopt spacemacs keybindings for scimax? If not, I will probably go back to spacemacs and use a minimal configuration and just adopt the parts of scimax I like and occasionally check whether there are some nice new features. 

Thank you,
Robert

**Comment by jkitchin** [comment]
What is there about scimax that is incompatible with spacemacs?

**Comment by rbirkelbach** [comment]
I found an easy solution without needing anything from spacemacs. I was a bit scared by the complexity of the spacemacs code and at first didn't know how to setup the leader key properly (e.g. I was unable to type space and scimax/body didn't load). The following code chunk is a start to make scimax become more similar to spacemacs.
I inserted this in my user.el file:

```elisp
(use-package evil) 
(use-package evil-leader)
(evil-mode t)
(require 'evil-leader)
(global-evil-leader-mode)
(evil-leader/set-leader "<SPC>")
(define-key evil-normal-state-map (kbd "SPC") 'scimax/body)
```

If anyone has suggestions for improvement, I am more than happy to hear them, but this is something that makes work less painful :)

**Comment by singletS** [comment]
For anyone following this thread...

I've been down a similar RSI path. I'm using a stripped-down spacemacs (#191) with ob-ipython and it works best if the spacemacs python layer is disabled (they use anaconda-mode and it doesn't play nice for completion and fixing org source block errors with default settings). 

I haven't spent enough time on it (except to get h,j,k,l working) but another approach might be re-mapping the navy- hydra keys to vi equivalents (see the *Navigation section in scimax.el). If this works, perhaps the navy hydra keys could be refactored into a customize-group with common default maps (emacs, vi)?

**Comment by rbirkelbach** [comment]
I reopened it, because setting scimax/body to the space key only works as long as I manually evaluated the buffer of user.el. If I restart emacs, I'm still in evil mode, but I need to use f12 again to use hydra. Does anybody know how I could make my change permanent?

**Comment by rbirkelbach** [comment]
Replacing my previous code chunk with the following solves the "not loading issue".
```elisp
(use-package evil)
(evil-mode t)
(define-key evil-normal-state-map (kbd "SPC") 'scimax/body)
```
