### ISSUE TITLE
Unnecessary call to ‘package-initialize’ in init file

### ISSUE THREAD

**Issue by rbirkelbach** [jkitchin/scimax#194]
Hello,

does anybody have an idea how to get rid of this warning message when loading scimax?

> Warning (package): Unnecessary call to ‘package-initialize’ in init file [2 times]

Best,
Robert

**Comment by rbirkelbach** [comment]
It did something, as it now just says 

> Warning (package): Unnecessary call to ‘package-initialize’ in init file
without the [2 times] in the end. I forgot to mention that I'm on emacs 27.0.50, so maybe this version of emacs is behaving differently than older versions.

**Comment by jkitchin** [comment]
I read something on the org-list that emacs 27 might automatically initialize for you, so the ones in the init file are not necessary. I guess I should add some conditional statement to avoid it.

**Comment by jkitchin** [comment]
I guess so. I don't have a way to test it. I would just try it and see what happens.

**Comment by rbirkelbach** [comment]
It works for now. When time permits (maybe this weekend) and if I do not forget to do so, I'll try to see how it works on a fresh install of scimax using the most current emacs version.

**Comment by jkitchin** [comment]
Thanks. I will give that a try.
