### ISSUE TITLE
Notebook format

### ISSUE THREAD

**Issue by pathologicalhandwaving** [jkitchin/scimax#197]
[scimax-notebook.el](https://github.com/jkitchin/scimax/blob/master/scimax-notebook.el), line 89 you have written:
` (format-time-string "%Y-%m-%d-%H:%m%p")))))))`

Ignore this if I am mistaken, but perhaps you meant this line to be:
` (format-time-string "%Y-%m-%d-%H:%M%p")))))))`

As `%m` twice would give: Year-month-day-hour-month-am/pm
and not: Year-month-day-hour-minute-am/pm

Just wondering if this is intentional.

**Comment by jkitchin** [comment]
I think you are correct. Thanks for reporting it.
