### ISSUE TITLE
Have ob-ipython respect :dir

### ISSUE THREAD

**Issue by dangom** [jkitchin/scimax#199]
It seems to me that ob-ipython will respect the :dir header argument when the kernel is started, but won't afterwards. Example:

```org

* Header One
:PROPERTIES:
:header-args: :dir /home/header_one
:END:

#+BEGIN_SRC ipython
import os
os.getcwd()
#+END_SRC

#+RESULTS:
:RESULTS:
# Out[356]:
# text/plain
: '/home/header_one'
:END:

 * Header Two
:PROPERTIES:
:header-args: :dir /home/header_two
:END:

#+BEGIN_SRC ipython
os.getcwd()
#+END_SRC

#+RESULTS:
:RESULTS:
# Out[357]:
# text/plain
: '/home/header_one'
:END:


```
 
I was wondering if there are any simple workarounds to overcome this issue? 
Could one prepend a os.chdir() command if `:dir` is local and specified upon sending code to the kernel?

**Comment by jkitchin** [comment]
I guess that this should be reported upstream in ob-ipython, unless you know it works with that, and doesn't work with the scimax mods. As a far as I know, scimax isn't intentionally making this not work.

**Comment by dangom** [comment]
I'll close this since it's been reported upstream. In any case, I've "fixed" it by changing the end of `org-babel-execute:ipython` to:

```elisp
(let* ((exec-dir (cdr (assoc :dir params)))
         (exec-body (concat
                     (when exec-dir
                       (concat "from os import chdir as __ob_ipy_chdir; "
                               " __ob_ipy_chdir(\""
                               exec-dir
                               "\")\n"))
                     body)))
    (if (assoc :async params)
       (ob-ipython--execute-async exec-body params)
     (ob-ipython--execute-sync exec-body params)))
```

Ugly and hackish, though, I admit.

**Comment by jkitchin** [comment]
I don't really see another way to do it. Is it expected that the :dir is active for all subsequent code blocks, or should it be local to the block?

**Comment by dangom** [comment]
I haven't thought too much about it to be honest. I usually set :dir as a header property and consider it to be "heading" local. If a heading doesn't have the :dir parameter it's because it doesn't make a difference.

My use case is that I have multiple participants for an experiment, and I set `:dir` to explore each subject's directory. So when I call something like `np.loadtxt('mixing_matrix')`, I don't have to be specific about paths. Very handy when combined with scimax's clone and execute to point functionalities. Also convenient for tangling code without losing generality.

**Comment by jkitchin** [comment]
Thanks for your approach to the solution. I have implemented a variation of your solution. I think you should only temporarily change the directory in each block, and change back to the original directory afterwards. This allows you to set a :dir on a subtree, but not on a subsequent subtree at the same level. Let me know if this works for you.

**Comment by dangom** [comment]
Going back to the original directory afterwards is indeed a less invasive idea and closer to the behaviour of `:dir` in SRC blocks with other languages.

Thank you again!!
