### ISSUE TITLE
Cannot change indent level in python mode

### ISSUE THREAD

**Issue by zhongnanxu** [jkitchin/scimax#2]
While editing python code, I realized I could not change indent level with tab. I found it very difficult to close loops, since pressing *backspace* put the contents on the previous line, and shift+tab did not do anything.

**Comment by zhongnanxu** [comment]
Nevermind. Restarting emacs allowed me to use *backspace* to unindent, though shift+tab still doesn't work. I can't remember whether this worked in the old jmax version though...

**Comment by jboes** [comment]
shift+tab doesn't seem to do anything in jmax. What's it's function supposed to be?

**Comment by zhongnanxu** [comment]
Alright, I was probably mistaken. I thought it was supposed to unindent the level.
