### ISSUE TITLE
html-clip-w32.py created on Linux

### ISSUE THREAD

**Issue by malb** [jkitchin/scimax#20]
My understanding is that `html-clip-w32.py` is for Windows systems. However, it is also created on my Linux system. As far as I can tell, the logic at

https://github.com/jkitchin/scimax/blob/fcae1c3e9f2c63a991d78ed03dfd24e891bdad83/ox-clip.el#L349

is to blame (?)

**Comment by jkitchin** [comment]
yes, it looks like I am missing a not in there. I just pushed that. It should fix it, let me know if it doesn't. Thanks for reporting it.

**Comment by malb** [comment]
Hi, shouldn't the fix read: 

```
(when (and (eq system-type 'windows-nt)
	     (not (file-exists-p ox-clip-w32-cmd)))
  (with-temp-file "html-clip-w32.py"
    (insert ox-clip-w32-py)))
```

**Comment by jkitchin** [comment]
yes indeed! thanks, I just pushed that.

**Comment by malb** [comment]
Thanks, all good now. And thanks for your awesome packages in general!

**Comment by jkitchin** [comment]
No problem. Thanks for notifying me of the issue, and glad they are helpful!
