### ISSUE TITLE
Scimax not initializing since update

### ISSUE THREAD

**Issue by Cumol** [jkitchin/scimax#200]
I updated scimax through `scimax-update`. When I restarted scimax I got the following error:

```
Eager macro-expansion failure: (file-error "Cannot open load file" "No such file or directory" "use-package") [2 times]
progn: Cannot open load file: No such file or directory, use-package
```
so I thought that broke something and decided to have a fresh install of scimax. Deleted the folder and re-ran the mac installation script.

running `./scimax.sh`worked fine. When I restarted scimax I got the same error.

Any idea what is happening?

**Comment by jkitchin** [comment]
I just pushed a fix that should address this. A recent commit was making packages not get activated. try pulling again and see if that fixes it. sorry about that.

**Comment by Cumol** [comment]
Works perfectly now. Thank you for the quick fix :)
