### ISSUE TITLE
How to disable a package loaded by scimax?

### ISSUE THREAD

**Issue by Cumol** [jkitchin/scimax#201]
I was trying out Company-mode and noticed that both company and autocomplete are active leading to weird behavior such as multiple popups etc.

How do I "unload" a package that scimax automatically loads in the packages.el file without directly editing packages.el? (by adding something to my user.el for example)

**Comment by jkitchin** [comment]
You could try (unload-feature 'some-package).

**Comment by Cumol** [comment]
There seem to be some dependencies

```
unload-feature: Loaded libraries ("/Users/muadabdelhay/cloud/scimax/elpa/auto-complete-20170124.1845/auto-complete-config.elc" "/Users/muadabdelhay/cloud/scimax/elpa/jedi-20160425.2156/jedi.elc") depend on /Users/muadabdelhay/cloud/scimax/elpa/auto-complete-20170124.1845/auto-complete.elc
```

Then I did the following:

```
(unload-feature 'jedi-direx)
(unload-feature 'jedi)
(unload-feature 'auto-complete)
```

And was confronted with this message:

```
unload-feature: Loaded libraries ("/Users/muadabdelhay/cloud/scimax/elpa/auto-complete-20170124.1845/auto-complete-config.elc") depend on /Users/muadabdelhay/cloud/scimax/elpa/auto-complete-20170124.1845/auto-complete.elc
```

Am I missing something?

**Comment by jkitchin** [comment]
What are you really trying to do? Is this related to an elpy configuration for completion? There is an optional force argument to the unload-feature. Try (unload-feature 'some-package t).

**Comment by Cumol** [comment]
I want to replace auto-complete with company mode (because they are both activated when I am in an R buffer for example). 
As scimax loads auto-complete in its packages.el and I did not want to meddle with the scimax files, I was looking for a way to do so in the user.el instead.

**Comment by jkitchin** [comment]
Can you just add an R-mode-hook that runs (auto-complete-mode -1)?
