### ISSUE TITLE
I had an old version of jmax that used ibuffer. Way to get that functionality back.

### ISSUE THREAD

**Issue by excetara2** [jkitchin/scimax#202]
I had turned off updating jmax awhile ago and just switched over to the newest version of scimax and updated to emacs-plus. I used to really like the smart ibuffers that would come up. It seems now it's a modifed version of ibuffers or something? Did this change is there a way to get the old ibuffer back?

**Comment by jkitchin** [comment]
what are you typing to get that?

**Comment by excetara2** [comment]
Yeah, I realized I think it is still ibuffer but just the theme or formatting looks much different. 

Sorry, I'll close the issue.
