### ISSUE TITLE
Overriding keybindings

### ISSUE THREAD

**Issue by excetara2** [jkitchin/scimax#205]
I am trying to override the binding `M+backspace` to `'backward-kill-word` instead of `'backward-kill-sentence`. 

If I set it in preload.el in the user file it doesn't seem to have any effect. I have successfully created new bindings in there that weren't set to anything but overriding bindings already set in this case didn't work. Is there any way to do this?

**Comment by jkitchin** [comment]
I guess those get set by some package after preload is loaded. Try putting it at the end of your user.el file instead.

**Comment by excetara2** [comment]
I also tried to set it un my `user.el` file. Any file in the user folder with a `.el` prefix technically gets loaded right or it has to be named user.el?

**Comment by excetara2** [comment]
Nevermind I renamed it to user.el and fixed the problem. Thanks
