### ISSUE TITLE
Yasnippet message after new installation

### ISSUE THREAD

**Issue by Arjay-El** [jkitchin/scimax#209]
I needed to reinstall Scimax on a win10 system so I used the git bash method. Once installed, I noticed Yasnippet on the main menu to the left of Scimax. I also received a warning message stating:

Error (use-package): Failed to install ivy-yasnippet: Package ‘emacs-25.3’ is unavailable

Has yasnippet been added to the distribution and needs emacs 25.3?  I believe you have a 25.2 installation included.

**Comment by jkitchin** [comment]
I have started using yasnippet to replace org-templates. you should probably comment out the use-package line for ivy-yasnippet in packages.el. It isn't critical. I won't get a chance to update the emacs distribution until August, and at that time hope to jump to emacs 26.

**Comment by jkitchin** [comment]
I added some conditional code that should fix this issue.

**Comment by Arjay-El** [comment]
Yes issue fixed. I used the update menu item in the scimax menu and that fixed it. As Murphy is never far away, scimax now recompile’s itself every time I start up so it’s about a 5 minute wait for that to conclude. I did not add new packages or make changes other than what I have described using the update menu item. Can you suggest where I should look for the trigger for this behaviour? I do have the compile and message logs.Thanks.

**Comment by jkitchin** [comment]
I am pretty sure if I launch scimax with : 

emacs -q -l /path/to/scimax/init.el

Then I do not see this recompile. Otherwise on my mac I am pretty sure that what you describe happens. I have not figured out what causes that. Interestingly, I do not see this happen on linux yet (AFAIK).

**Comment by Arjay-El** [comment]
You are correct, I was using an old shortcut. Please close this issue.
