### ISSUE TITLE
Please maintain ox-clip in a separate repository

### ISSUE THREAD

**Issue by tarsius** [jkitchin/scimax#21]
Now that `ox-clip` is available from Melpa, please consider maintaining it in a separate repository. If you want to maintain its history but have difficulties using `git filter-branch` to do so, then I can help you with that.

**Comment by jkitchin** [comment]
why does it matter?

**Comment by tarsius** [comment]
It would allow installing the package as a git submodule. I explain why installing packages as submodules enables users to more easily contribute to the packages that they use in [Assimilate Emacs packages using Git submodules](https://emacsair.me/2016/05/17/assimilate-emacs-packages-as-git-submodules).

I mentioned the Melpa package because I maintain the Emacsmirror, a mirror of Emacs package *repositories*, and have been trying to mirror all packages that are available from Melpa. Something that I have accomplished yesterday (sans one package for testing purposes)!

I used to not mirror any packages whose repositories bundle third-party packages, in this case `org-mime` which is part of `org` itself. I mirror them anyway now because I want to mirror everything that is available from Melpa, but that requires a lot of work to fixup the extracted metadata. And that is all I can do, fixup the metadata, if a user actually adds a "broken" repository to the `load-path`, then issues like the below will arise.

When a repository bundles third-party libraries, then it is undefined which version will get loaded, the bundled version or the authoritative version. That's an issue because bundled versions in experience tend to not get updated for years. The user, being unaware that s/he is using an outdated version, might then report bugs against the upstream repository, and for obvious reasons upstream won't be able to reproduce them.

**Comment by jkitchin** [comment]
This sounds reasonable. My hands are full at the moment, so I will try to do this in December.

**Comment by tarsius** [comment]
Take our time.

**Comment by tarsius** [comment]
Friendly ping!

**Comment by jkitchin** [comment]
It is on its way hopefully: https://github.com/melpa/melpa/pull/4916
