### ISSUE TITLE
tlmgr not found on startup

### ISSUE THREAD

**Issue by roblem** [jkitchin/scimax#210]
Getting this error message (about texlive manager) when starting scimax:
```
error in process sentinel: async-handle-result: Searching for program: No such file or directory, tlmgr
error in process sentinel: Searching for program: No such file or directory, tlmgr
error in process sentinel: async-handle-result: Searching for program: No such file or directory, tlmgr
error in process sentinel: Searching for program: No such file or directory, tlmgr
```
I found `tlmr` being called in .yas_setup.el and perhaps from scimax-latex.el from [here](https://github.com/jkitchin/scimax/search?q=tlmgr&unscoped_q=tlmgr).

A lot of linux distros don't package tlmgr with texlive since the user is expected to use package managers (e.g. `apt` or `dnf`) to install texlive components to avoid conflicts.  

So far, this hasn't impacted any functionality that I can see.

**Comment by jkitchin** [comment]
Thanks for reporting this. I have also seen that occassionally, but haven't tracked it down yet, so thanks for doing that!

It is a little odd, since the code should only be run when tlmgr is found, but I guess that in the async environment the path is not the same. I pushed some code that should fix this. Let me know if it goes away for you.

**Comment by roblem** [comment]
Getting this now:
```
error in process sentinel: async-handle-result: Wrong type argument: stringp, nil
error in process sentinel: Wrong type argument: stringp, nil
error in process sentinel: async-handle-result: Wrong type argument: stringp, nil
error in process sentinel: Wrong type argument: stringp, nil
```
Again, no apparent impact on functionality.

**Comment by jkitchin** [comment]
hm. I added another thing to see if it would stop the errors. I wouldn't expect any functionality issues, this just gathers installed packages. It is slow, so I was trying to run it in a separate process so it wouldn't interfere with startup.

**Comment by roblem** [comment]
I'll close as this is only cluttering messages with everything else working.
