### ISSUE TITLE
virtual environments and jupyter not found

### ISSUE THREAD

**Issue by roblem** [jkitchin/scimax#211]
When starting scimax, I get this among the first 20 or so messages: 
```
jupyter was not found on your path. ob-ipython was not loaded.
Loading /home/myusername/emacs_setup/.emacs.d/scimax/user/custom.el...done
Created assignment link.
Created solution link.
Created exercise link.
Created mc link.
Created ans link.
[yas] Prepared just-in-time loading of snippets successfully.
Loading /home/myusername/emacs_setup/.emacs.d/scimax/user/user.el (source)...
```
My custom.el contains this near the top:
```
;; pyvenv setup
(require 'pyvenv)
(setenv "WORKON_HOME" "~/anaconda/envs/")
(setq pyvenv-workon "python36")
(pyvenv-mode 1)
```
I am on linux and the distro I use relies heavily on python for scripting, so I leave it as the default python setup (jupyter isn't installed by default).  Instead, I use anaconda and load it in my `user.el`.  It seems from the timing of the messages, that scimax is looking for jupyter before it is accessible in user.el.

Also, I am wondering if this is related to #189 since I am still seeing empty menu items for scimax and yasnippet pretty much all the time (and this sorts itself after about 5 minutes).

Is this the recommended way to use virtual environments, or perhaps do I need another configuration file for python virtual environments that fires off very early in the emacs startup process?

**Comment by jkitchin** [comment]
It sounds like you should either:
1. Add

```
(use-package ob-ipython
      :ensure nil
      :load-path (lambda () (expand-file-name "ob-ipython-upstream" scimax-dir))
      :init (add-to-list 'load-path (expand-file-name "ob-ipython-upstream" scimax-dir))
      (require 'ob-ipython))
```

in your user.el file after you load your pyenv. You will still get the message, but at least ob-ipython will eventually load.

or see if you can move the pyenv code to "user/preload.el". This is loaded pretty early in init.el before packages.el is loaded.

I don't know if it is related to issue #189. I still see an occasional lag when accessing the scimax menu, but I still haven't had time to track it down.

**Comment by roblem** [comment]
Currently using method 1.  Thanks.

Tried method 2 and was able to successfully add the virtual environment code into `preload.el` after adding the elpa pyvenv folder to `load_path`, but strangely the jupyter not found error is still present.  Also, the scimax menu items still lagged after doing this, so it is doubtful that this is related to #189.
