### ISSUE TITLE
Removing projects from Scimax-Notebook

### ISSUE THREAD

**Issue by Arjay-El** [jkitchin/scimax#212]
Is there a way to delete or remove old projects from the scimax-notebook. I love the interface and am trying to see if I can combine it with scimax-dashboard to bring up my projects in work at startup. Occasionally I mess up creating a project (mispelled name,etc) but I cannot seem to remove the remnants from the list of projects. Any suggestions? 

Also I modified scimax-notebook.el to use the directory/project name as the main file of the project as well.  I use the main file for links to all the files in the directory and I can search for all my main files this way  to create a separate master directory and they are all uniquely identified. I also use "_" to ensure the master file is the first file in the working directory and not lost in the crowd.

here is what I modified in defun nb-new(name):
;;;###autoload
(defun nb-new (name) "Create a new project of NAME in `nb-notebook-directory'."
  (interactive "sNew project name: ")

  ;; name = project name. Create a master file name from it by adding "_" and ".org"
  (defvar nb-master-file (concat "_" name ".org") "Name of the master file in each project.")

  (let ((dir (file-name-as-directory (expand-file-name name nb-notebook-directory))))
    (unless (file-directory-p dir)
      (make-directory dir t)
      (let ((default-directory dir))
	(shell-command "git init")))
    (projectile-add-known-project dir)
    (projectile-save-known-projects)
    (find-file (expand-file-name nb-master-file dir))))

Seems to work but do you see any problems with it?

**Comment by jkitchin** [comment]
scimax-notebook is a pretty thin wrapper around projectile. You should be able to use projectile commands to remove projects I think.  Try M-x projectile-remove-known-project.

I usually use @ to get files listed at the top of a directory. - works also, and doesn't require a shift press.

In your code, it is probably wrong to use a defvar inside the function. I am pretty sure this will not work after one function call because defvar does nothing if a variable is already defined.  You probably neither want setq, as that will change the variable globally. Instead, you should move this into the let statement.  You probably want this, but I doubt this will work with nb-open.

```
;;;###autoload
(defun nb-new (name)
  "Create a new project of NAME in `nb-notebook-directory'."
  (interactive "sNew project name: ")

  (let ((nb-master-file (concat "" name ".org"))
	(dir (file-name-as-directory (expand-file-name name nb-notebook-directory))))
    (unless (file-directory-p dir)
      (make-directory dir t)
      (let ((default-directory dir))
	(shell-command "git init")))
    (projectile-add-known-project dir)
    (projectile-save-known-projects)
    (find-file (expand-file-name nb-master-file dir))))

```

An easy solution here is to change the definition of nb-master-file from a string constant to a customizable function that returns the name you want. What do you think? It would be a little tricky to get that to work with nb-open, but it is probably doable.

**Comment by jkitchin** [comment]
See the new push I just made, it probably eliminates the need for you to redefine nb-new. There  is an example function (nb-example-master) that should do what you want.

`(setq nb-master-file nb-example-master)` should make it work for you.

**Comment by Arjay-El** [comment]
Thanks John, I will check it out.

**Comment by Arjay-El** [comment]
I am using Win10. When I access open notebook, I receive a directory pane that shows the current projects in the project directory  but it does not allow me to enter a project name. The input frame has the word directory in very light grey but no selecting will allow an entry there. Does it do so on your system?

**Comment by jkitchin** [comment]
That is not what I see. I don't have a windows machine to test it on. no panes show up, everything should be happening in the minibuffer. I am not sure what you are seeing.

**Comment by Arjay-El** [comment]
Okay, the input pane allows you to input directory name (does not work) or file name (works). It does let you create a project directory by entering the name as if its a file. Odd but works.

**Comment by jkitchin** [comment]
Incidentally, the scimax hydra (bound to f12) has a projectile hydra that conveniently makes it easy to remove projects:

f12 px will prompt you for a project to delete.

If you have already deleted the project directory, then

f12 pX should clean up the project list and remove non-existing onese.

**Comment by shrysr** [comment]
The hydra bound to f12 worked perfectly as expected.
