### ISSUE TITLE
Customizing formatted-citations in org-ref

### ISSUE THREAD

**Issue by colormotor** [jkitchin/scimax#213]
Hi, 
I am relatively new to emacs/scimax, and I have been trying to customize the formatted citation format in org-ref. I was previously using spacemacs with org-ref and was able to set custom formats by adding a `org-mode-hook` with a function containing the following:
```
(reftex-set-cite-format
          '((?c . "cite:%l")
            (?t . "%t")
            (?h . "*** %a, %y, %t cite:%l\n")
            (?a . "%a")
            (?y . "%y")
            (?m . "| %a | %y |  %t |  cite:%l |")))
```
Which allowed me to easily insert titles for my biblio notes together with a link to the corresponding bibtex key.
But the same code in my user.el file does not seem to have any effect.
Would you have suggestions on how to proceed?

**Comment by jkitchin** [comment]
I don't follow what you are trying to do. How were you using these keys to insert citations from org-ref?  Do you have reftex setup as the backend somehow?

**Comment by colormotor** [comment]
Sorry for the confusion, indeed I realize now that the code I posted (and I was using with no effect) was from a reftex setup that was left around in my previous initialization file. 
What I am trying to do is to customize the format used when selecting "insert formatted citation(s)" from the org-ref menu. 
I have this working again by modifying a snippet you have previously suggested here:
[https://www.mail-archive.com/emacs-orgmode@gnu.org/msg110385.html](https://www.mail-archive.com/emacs-orgmode@gnu.org/msg110385.html)
```
(defun set-format (key)
  (setf (cdr (assoc key (cdr (assoc "org"
                                    org-ref-formatted-citation-formats))))
        "${author} ${year}. /${title}/. [[cite:${=key=}]]")
  )
(setq org-ref-formatted-citation-backend "org")
(set-format "article")
(set-format "inproceedings")
;; etc...
```

**Comment by jkitchin** [comment]
Ok. I am going to close this then.
