### ISSUE TITLE
WIN10- New Install recompiles every time scimax is run

### ISSUE THREAD

**Issue by Arjay-El** [jkitchin/scimax#214]
Using WIN10, and scimax.bat to run scimax.  This is the second new installation I have done with the same behaviour.  Everytime I run scimax with scimax.bat, it runs through a complete compile cycle before starting. Any suggestions where I can start to troubleshoot this? Perhaps exclude yasnippets which seems to be the only real change over previous versions (?) I am not familiar enough with debug to understand if it would reference what triggers the recompile. Is there a way to do some full log to track and capture such an event?

thanks for your help.

**Comment by jkitchin** [comment]
I also do not know what causes this, it happens on Mac also. Can you try running it from the scimax dir like this:

emacs-win\bin\runemacs.exe -q -l .\init.el

I find the -q option avoids the recompile on a Mac.

**Comment by jkitchin** [comment]
any chance you have something in your ~/.emacs.d/init.el file?

**Comment by Arjay-El** [comment]
I will check. I have WIn7 and Win10 VMs so I will experiment in there to see if I can find this. One question: The update menu items, does that update all scimax*.el packages or all packages?

**Comment by jkitchin** [comment]
That just runs a git pull, updates the submodules, and then runs the init.el file again. I would not expect it to update the packages in elpa.

**Comment by AKielhorn** [comment]
> Am 11.06.2018 um 15:51 schrieb John Kitchin <notifications@github.com>:
> 
> That just runs a git pull, updates the submodules, and then runs the init.el file again. I would not expect it to update the packages in elope.

I’ve seen this as well.

It is a conflict between the elpa directory in .emcas.d and scimax-dir.

The emacs starts up it reads the files in .emacs.d/elpa.
These are out of date.

When it updates the elpa files, the elpa-user-dir is already set to scimax-dir/elpa,
thus the new files are written there.

When you start emacs the next time, it sees the out of date files first.

What I have done:
start emacs without scimax.
M-x package-refresh-contents
M-x package-install-selected-packages

Now I have the updated packages in .emacs.d/elpa.

My guess about what happened:

Someone (definitely not me) put the line
(package-initialize)
in my init.el

Someone (probably the same person) put the line
‚(package-selected-packages
(quote
(long list of package)))
into my custom.el

Maybe putting a ; in front of the (package-initialize) would have been an easier solution.

I’ve changed my password.

Just for the record:
this is MacOS X with emacs 25.3

Axel

**Comment by jkitchin** [comment]
indeed, that is also what I saw in my .emacs.d/init.el file. I assume some automatic process made that and put it there. For me, just deleting .emacs.d/init.el was enough to solve it I think. It also explains why -q solved the problem for me, as that bypasses this init directory.

**Comment by Arjay-El** [comment]
John, your suggestion works on my current install on windows 10. Does this mean the init.el file needs to be modified/deleted?

**Comment by Arjay-El** [comment]
When I try the refresh method per  AKielhorn, it fails with a message ' Failed to download 'gnu' archive'.

**Comment by jkitchin** [comment]
I think it means you just have to start with -q on your emacs executable to avoid using anything in the .emacs.d directory.  scimax should be totally self-contained that way.

**Comment by Arjay-El** [comment]
Solved
