### ISSUE TITLE
nb-open with preloaded nb-master-file broken since update

### ISSUE THREAD

**Issue by Cumol** [jkitchin/scimax#215]
I decided to update scimax and some packages (maybe projectile too) lately and after restarting, running `nb-open` and choosing a porjects leads to the following error:

```
Invalid function: "index.org"

```

I guess it has something to do with me preloading (in preload.el) the following:

```
(defvar nb-master-file "index.org"
  "Name of the master file in each project.")
```

Any idea what is happening?

**Comment by johnrkitchin** [comment]
I think I changed that from a string to a function. It should be a simple fix for you to define that variable as a lambda function with one optional argument that returns index.org. See scimax-notebook.el. The new default for that variable is an example.

**Comment by Cumol** [comment]
Maybe I am misunderstanding something, but when I try this:

```
(defcustom nb-master-file (lambda (&optional name)
			    "Return the master file name for the project."
			    "index.org")
```

In my preload.el the scimax initialization stops at the file preload.el

**Comment by Cumol** [comment]
Problem solved. Had a missing bracket and replaced it with setq
