### ISSUE TITLE
Tail space removes item automatically in list environment in org mode

### ISSUE THREAD

**Issue by QinBa** [jkitchin/scimax#217]
System: MacOS High Sierra + Emacs 26.1 + org mode 9.1.13. Scimax is updated. 

Problem Description: 
In the list environment in org mode (invoked with "- ", "1. ", ect.), the entire line of the item would be removed automatically after I hit "SPC "+ "Enter". The problem would not occur if I did not leave any space in the end. 

I use "C-h k SPC" and found that "SPC runs the command org-self-insert-command". The description for "org-self-insert-command" is as follows: 
"
Like ‘self-insert-command’, use overwrite-mode for whitespace in tables. If the cursor is in a table looking at whitespace, the whitespace is overwritten, and the table is not marked as requiring realignment.
"

This problem is getting really annoying, as I am used to putting a space in the end of each list item. Hope someone could help me. Thanks.

**Comment by jkitchin** [comment]
I just pushed a fix for this. It has been bugging me too.

**Comment by QinBa** [comment]
Problem solved. I am gonna close the issue. Thanks very much. @jkitchin
