### ISSUE TITLE
Optionally enable wakib-keys for non-Emacs users?

### ISSUE THREAD

**Issue by dangirsh** [jkitchin/scimax#219]
[wakib-keys](https://github.com/darkstego/wakib-keys) enables CUA bindings to reduce the barrier-to-entry for non-Emacs users. It has significantly more bindings than cua-mode, and even handles remapping C-x / C-c to C-d / C-e. 

I use code from scimax (thank you!), but have never used or studied it's default bindings. So, I have no idea if this is feasible or intelligent. At first glance, it seems possible. 

An option like this wakib-keys could significantly increase the number of people that try things like the excellent Jupyter interface in scimax. It might be especially useful if that's the _only_ thing they use Emacs for. This also seems aligned with the work to replicate the Jupyter notebook bindings in the Org interface (thanks for that!).

When enabling wakib-keys in my own config, the only gotcha was handling the customizations I've made to default bindings (e.g. C-s is swiper-helm instead of isearch). This wasn't too hard.

Of course, there are downsides to supporting multiple sets of bindings. I wanted to start a discussion here to see if this seems worth the effort / drawbacks.

**Comment by jkitchin** [comment]
This seems like something that might go in a scimax wiki (https://github.com/jkitchin/scimax/wiki). There isn't currently anything there, and I don't know how easy it is for anyone to add to it. If you want to try we could try it.

I don't think I want to support multiple sets of bindings; scimax probably already breaks some Emacs conventions and adding more would probably make things more difficult than less.

**Comment by dangirsh** [comment]
I think this would only be a good idea if the alternate bindings were fully supported. I understand that having multiple supported bindings would be a burden, but wanted to guage whether you thought it would be worth the effort.
