### ISSUE TITLE
wow..this is amazing :)  user defined colors/bold etc possible?

### ISSUE THREAD

**Issue by zeltak** [jkitchin/scimax#22]
wow..just wow..this is amazing :)

im now spoiled with both the new color links you created (which i use *alot* now for my org-reveal presentations!..posted on that in the org list and many colleagues here at uni ;-)) and now this which seems even easier to add highlights.

I have the same question i asked with color links before regarding user defined colors/bold etc, that is to add highlight types such as colorX that has a FG:blue and BG: white and BOLD and then a colorY with a FG:yellow and BG: red etc..

thx so much again, your hard work is really appreciated here in my lab :D

PS will this come to melpa eventually and or get integrated into org?

best

Z

**Comment by jkitchin** [comment]
This is a good idea! I pushed a pretty major change today that I think enables this.

With the latest code you can put this in an init file:

(ov-make-highlight "eww" '(:foreground "red" :background "yellow" :height 200 :weight bold))

and it will create a command: ov-highlight-eww that will add that face to the highlighted or word at point. you can now change all the properties of the text, including the font! and they are persistently saved in the file (baring bugs of course).

Once this stabilizes, it will probably get onto melpa.

**Comment by zeltak** [comment]
cool thx alot!

is that pusged yet to git? 
the link
https://github.com/jkitchin/scimax/blob/master/ov-highlighter.el

says it was edited 17h ago

i can try and report performance, happy to help in any areas (apart coding which i suck at :)) you think are needed (testing,docu etc)

best

Z

**Comment by jkitchin** [comment]
It is on the org-9 branch: https://github.com/jkitchin/scimax/blob/org-9/ov-highlighter.el

**Comment by zeltak** [comment]
Hi

Just reporting that i have been using ov-highlighter for about a week including the most useful `ov-make-highlight` and its been working great for me :)
actually one thing to note is that if i use it in my org based init file it throws errors at startup 

```
File local-variables error: (void-function ov-highlight-load)
```

but its not issue for me as i can not use it in init org file

thx again, really great addition :)

Z

**Comment by jkitchin** [comment]
It is necessary to have loaded the library before that function is called, which I guess could be a problem with an init file. I don't seem much way around that  other than more file local variables ;)
