### ISSUE TITLE
New OSX Install gives plain Emacs interface not Scimax

### ISSUE THREAD

**Issue by Arjay-El** [jkitchin/scimax#220]
I have just loaded the Mac version on my new Airbook following your instructions (copying the bash command as you have written it and running that in the terminal). When I run ./scimax.sh, I am given a plain emacs interface, not the scimax menu  I have on my PC version. I copied the contents of scimax.sh to the terminal window and ran it with the same result. Did I make some error installing or is there some other method of making scimax run with its custom menus? It also looks like its the non-graphical interface. Any suggestion on what I can troubleshoot?

thanks

**Comment by jkitchin** [comment]
What  do you get from:

which emacs

emacs -q --version

and finally:

emacs -q -l /path/to/scimax/init.el

**Comment by Arjay-El** [comment]
1.Which emacs?
/usr/local/bin/emacs

2. emacs -q --version
GNU Emacs 26.1
Copyright (C) 2018 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.

3. emacs -q -l /path/
For information about GNU Emacs and the GNU system, type C-h C-a.
(Shell command succeeded with no output)
if: Symbol’s value as variable is void: Info-directory-list

#3 looks like the previous Win10 error so I will delete and reinstall per your instructions (I am loading scimax on a dual boot Mac Air). 

Thanks John.

**Comment by Arjay-El** [comment]
Reinstalled after your package.el fix and it installs properly with the full scimax menus.

Thanks
