### ISSUE TITLE
ipynb export giving unwanted markdown cells

### ISSUE THREAD

**Issue by singletS** [jkitchin/scimax#221]
It seems the ipynb export is combining/jumbling code and markdown content after code blocks are evaluated.  Example org file:

```
Test this.
#+BEGIN_SRC ipython :session
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline
#+END_SRC

#+RESULTS:
:RESULTS:
# Out[1]:
:END:

A blank source cell.
#+BEGIN_SRC ipython :session

#+END_SRC

#+RESULTS:
:RESULTS:
# Out[1]:
:END:

An image.
#+BEGIN_SRC ipython :session :display image/png
x = np.linspace(-5,5)
plt.plot(x, np.sin(x))
#+END_SRC

```

Export to an ipynb.  After code cells, a markdown cell is generated with the content
```
:RESULTS:
nil:END:
```

Opening the exported ipynb in a browser:
If an image (say, from a plot) is output from the code cell, I'm getting an extra markdown cell with the image link.  Sometimes there are spurious ":RESULTS: nil:END:" statements in the markdown cell.  Code or output from later cells appear before they actually evaluated (I re-ran all cell from the top of the notebook, yet image is showing up before the plotting statement):

![image](https://user-images.githubusercontent.com/8687756/43530399-13457fe4-9573-11e8-9671-695754d12acb.png)

After evaluating cell with plot statement:
![image](https://user-images.githubusercontent.com/8687756/43530511-5e5b99fa-9573-11e8-9f21-d869d2d5661a.png)

Emacs 25.3.5, scimax latest commit.

Thanks,
Steve

**Comment by jkitchin** [comment]
This has been an ongoing hassle! I have pushed a small fix that seems to address it. Let me know if it works for you.

**Comment by singletS** [comment]
I think it does fix the problem.  Thanks!
