### ISSUE TITLE
ob-ipython enhancements: "raw" results not handled for value result types

### ISSUE THREAD

**Issue by dangirsh** [jkitchin/scimax#222]
A source block header of `#+BEGIN_SRC ipython :results raw output` correctly handles the "raw" argument via the `*ob-ipython-output-results-prefix*` global variable. However, the same code block with header `#+BEGIN_SRC ipython :results raw value` incorrectly prepends the results with ": ". This breaks the use-case where the results are used in a `:var` assignment in another block, since the colon and space are captured in the result string.

**Comment by jkitchin** [comment]
can you post an example that shows the problem, including the second block with the :var in the header?

**Comment by dangirsh** [comment]
Sure. Here's the output I see with `ob-ipython-show-mime-types` set to `nil`.

```
#+BEGIN_SRC ipython :results raw output
print(1)
#+END_SRC

#+RESULTS:
1


#+BEGIN_SRC ipython :results raw value
1
#+END_SRC

#+RESULTS:
: 1
```

The issue is the prepended colon and space in the second output.

It seems like `ob-ipython-format-text/plain` gets called regardless of `raw` being used, and that function always prepends " : ". 

I'm happy to try to fix this. The simplest option I see is adding another global like `*ob-ipython-output-results-prefix*`, but for the value formatters. Sound sane?

**Comment by jkitchin** [comment]
I see the problem. I think it is easier to check if the block has raw in the headers, and then not prefix it if it is. I pushed a commit that does that. What do you think?

**Comment by dangirsh** [comment]
Works for me. Thanks!
