### ISSUE TITLE
Win10: Install halts with error on accessing info-directory-list

### ISSUE THREAD

**Issue by Arjay-El** [jkitchin/scimax#223]
New installation Win10. Used the git call method. When emacs first begins to configure itself, the following error occurs and script exits:

... install snippet..
Wrote c:/scimax/elpa/use-package-20180715.1801/use-package-lint.elc
Checking c:/scimax/elpa/use-package-20180715.1801... [2 times]
Compiling c:/scimax/elpa/use-package-20180715.1801/use-package.el...done
Wrote c:/scimax/elpa/use-package-20180715.1801/use-package.elc
Checking c:/scimax/elpa/use-package-20180715.1801...
Done (Total of 8 files compiled, 2 skipped)

if: Symbol’s value as variable is void: Info-directory-list   <==script exits with this error.
..... 
Has something changed in the installation script or is this a problem in the use-package code?

Thanks for your help!

**Comment by jkitchin** [comment]
I saw this in the CI testing. I guess it is a problem with MELPA that may clear itself up in a few hours. I am not aware of anything I have done to cause this error.

**Comment by jkitchin** [comment]
I am not sure what changed, but it does appear that a line in scimax/packages.el was causing this issue. I fixed it in commit 3bfb8fe, and it seems to build on CI again.
