### ISSUE TITLE
Question: desktop shorcut to start scimax

### ISSUE THREAD

**Issue by Arjay-El** [jkitchin/scimax#225]
John,

Do you use a desktop shortcut to initiate scimax or always open a terminal window and give the "emacs..." command? I have researched many ways of creating an .app shorcut on the desktop but have always been stopped with an error stating  "emacs: standard input is not a tty". Do you have some tricky way for a one click startup?

Thanks

**Comment by AKielhorn** [comment]
> Am 19.08.2018 um 03:19 schrieb Arjay-El <notifications@github.com>:
> 
> John,
> 
> Do you use a desktop shortcut to initiate scimax or always open a terminal window and give the "emacs..." command? I have researched many ways of creating an .app shorcut on the desktop but have always been stopped with an error stating "emacs: standard input is not a tty". Do you have some tricky way for a one click startup?

I have an automator workflow:

<key>ActionParameters</key>
<dict>
	<key>COMMAND_STRING</key>
	<string>

Setting the PATH
export  PATH=/Users/axel/Library/Haskell/bin: for pandoc
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:
/usr/local/MacGPG2/bin: GPG
/Library/TeX/texbin: TeX
/opt/local/bin: MacPorts after texbin to prevent tex from Macports being used

calling Emacs from emacsfromac.com (you can get 26.1 as well)
(You can use the Railwaycat emacs as an alternative, the macOS Emacs will *not* work.)
/Applications/Emacs\ 25.3.app/Contents/MacOS/Emacs  -l ~/src/Emacs/scimax/init.el "$*" &amp;

„$*“ is the file dropped on the Automator Icon. (Drag further files to the emacs icon in the dock)

This gives an error message when you just click on the Icon but i usually drop an org file.

</string>
	<key>CheckedForUserDefaultShell</key>
	<true/>
	<key>inputMethod</key>
	<integer>1</integer>
	<key>shell</key>
	<string>/bin/bash</string>
	<key>source</key>
	<string></string>
</dict>

**Comment by jkitchin** [comment]
I always use the Terminal to start scimacs, and I leave it open for days/weeks at a time, basically until I have some reason to restart it. It is basically open if I am logged in since I use it for email, RSS, and almost every writing task. For a while I was using emacsclient, but I feel like it stopped working some months ago, and things have been stable enough I rarely need to restart emacs.
