### ISSUE TITLE
Using scimax with prelude

### ISSUE THREAD

**Issue by domingoUnican** [jkitchin/scimax#227]
Dear all,

I am a newbie in emacs so I decided to start with https://github.com/bbatsov/prelude, 
I was wondering if it possible to combine prelude with scimax, which looks really nice.
Using the script provided in the web starts another instance of emacs, which does not take into account my 
configuration. 
Including the directory where scimax.sh is installed inside init.el does not work either.

Do you have any suggestions?

**Comment by jkitchin** [comment]
I don't know what you mean by "doesn't work". How do you start emacs? You should be able to add scimax on top of what ever you normally do with something like this at the command line:

`emacs -l /path/to/scimax/init.el`

**Comment by domingoUnican** [comment]
Sorry for the late response. I wasn't expecting such a fast answer.
That was the problem. But, can I install scimax in .emacs.d/
like the default init.el?

**Comment by jkitchin** [comment]
you can put the whole scimax directory inside ~/.emacs.d if you want. Then, start emacs with:

`emacs -l ~/.emacs.d/scimax/init.el`

Alternatively, in your ~/emacs.d/init.el file, add a line like:

`(load-file "~/.emacs.d/scimax/init.el")`

**Comment by domingoUnican** [comment]
Thanks! that was exactly that I was looking for.
