### ISSUE TITLE
How do I remove flyspell from automatically being launched in org-mode or change the binding for correcting previous word?

### ISSUE THREAD

**Issue by excetara2** [jkitchin/scimax#228]
I prefer to manually launch flyspell mode when I want to but not sure how to disable it by default. Another option is to change the binding from `C-;` for correcting the previous word to something else. I had `C-;` set to `daabrev-expand` but it is overidden when flyspell is loaded.

Also, the autocomplete (that displays what will be expanded and allows expansion via tab) that happens in the scratch buffer or other modes is possible with org-mode? Sorry this is a side question but semi-related.

**Comment by excetara2** [comment]
I did try the below in my user.el file to try to add a hook to disable flyspell in org-mode but didn't seem to work.

```
(dolist (hook '(org-mode-hook))
      (add-hook hook (lambda () (flyspell-mode 0))))
```

**Comment by jkitchin** [comment]
Try this instead:

```
(dolist (hook '(org-mode-hook))
  (add-hook hook (lambda () (flyspell-mode 0)) t))
```

the subtle difference is to append this to the end of the hook, so it gets run last.

**Comment by jkitchin** [comment]
If you put this in your user.el file it will probably set it back to what you wanted. If not, there is a flyspell-mode-hook you could use to set it. 

`(define-key flyspell-mode-map (kbd "C-;") 'dabbrev-expand)`

**Comment by excetara2** [comment]
Sorry for late response but those both work so thanks! Also, just curious how you prefer to move around a buffer. I was used to using Ace-jump mode which has been replaced by avy-goto-char in your scimax. Didn't know if there was something you preferred using more.

**Comment by jkitchin** [comment]
I don't have a great way to move around the buffer. I have a jump hydra coded in scimax that I sometimes use, and it has some avy bindings. I bound caps-lock to f12, so a typical jump to a line might be: capslock j l l and then what ever avy chars are on the line I want to jump to.

To jump to a character:
capslock j c c then the char, and then the avy chars to jump there.

I doubt it is ideal, but I have a few committed to memory, and the hydra to remind me of others.
