### ISSUE TITLE
Crashes sinse update to 26.1

### ISSUE THREAD

**Issue by Cumol** [jkitchin/scimax#231]
Since the update to 26.1 I have been getting crashes when using scimax but not when using vanilla emacs.

I cannot always reproduce the crash but it has something to do with source blocks and plots generated from them.

Sometimes creating a source block and writing the language name "R" or python leads to a crash. Other times executing a source block that generates a plot (again, with R for example) crashes emacs. In other cases expanding a heading with source blocks and plots leads to a crash.

How do I debug crashes like these?

**Comment by jkitchin** [comment]
That sounds irritating! I haven't had that issue with Emacs 25 so far. It sounds like something buggy to me. Off the top of my head I guess it is related to something in font-lock. scimax does do some extra font-lock stuff on src blocks that vanilla emacs doesn't, e.g. with org-src-font-lock-fontify-block. You could eliminate this function (comment it out in scimax-org.el) and see if your crashes go away.

Also in that file, it looks like I modified org-display-inline-images to have a more flexible set of options for image sizes.

I haven't tried debugging crashes before, but this might give you some ideas for how to start trying:

https://emacs.stackexchange.com/questions/14354/how-do-i-debug-an-emacs-crash

**Comment by Cumol** [comment]
Update...

I tried commenting the function out. It did not change the behavior.

The crashes do not seem to even be associated with an emacs version. I tried every option from 25.2 to the bleeding edge 27. Crashes keep happening, and it definitely has something to do with source blocks. Until now only R source blocks, I don't use python or emacs code blocks so I don't know what causes those. It also might have something to do with images the are displayed. Sometimes a crash is triggered by pressing tab on a collapsed headline that contains images and code blocks.

I tried to use GNU GDB on my mac to do the debugging, I keep getting error trying to open emacs through GDB as described. After multiple trials I gave up as the errors do not seem meaningful and googling did not help.

On a vanilla emacs without using scimax I did not observe the crashes so something in scimax is causing them. I will start from a vanilla emacs and build up the init slowly and see how that behaves. Maybe I can avoid the crashes.

Any other suggestions to what I could try?

**Comment by jkitchin** [comment]
Sorry to hear this, that sounds strange. The usual strategy for this is bisection of the init files. It is a little tedious, but the gist is you comment out half of a file, and see if the problem goes away.  I guess that you could start in the packages.el file with this. You can open an el file, go to a point, press C-spc, go to another point and type M-; to comment the region out. Later if you select the region again, M-; should then uncomment it.

alternatively, start by commenting out the scimax packages, scimax-org seems like a probable suspect. If that stops the crashes, then bisect scimax-org.el.

**Comment by malcook** [comment]
Coming in late to the conversation… have you already been advised that you must be careful when swapping versions of emacs to “do the right thing” with you .el files.  By “do the right thing”  I mean recompile the ones that need recompiling.   I tend to be conservative and always recompile all of them when I change emacs version – this has been the safest though I know not always necessary.  An “easy” way to do this is to start using “use-package” along with (setq use-package-always-ensure t).

**Comment by jkitchin** [comment]
Thanks for the tip. I usually don't use byte-compiled files myself. You might try deleting all the .elc files. That may be necessary for the bisecting I mentioned anyway, since they may get loaded even if you have commented out lines in the el files.

**Comment by Cumol** [comment]
An update

I am using scimax on a 26.1 version of emacs and had no crashes yet. I did not add all my user.el file back and working on minimum settings. So it is either my own settings or something that I did wrong installing emacs before.

Will update once I am brave enough to try to solve this. I am happy I have something stable now :)

**Comment by Cumol** [comment]
Another update. The crashes came back.

It seems to be involved with inline images. I am guessing that some of them are too large (when producing high-res images for posters and talks). toggling off the display of inline images does the trick for me, for now.

`(setq org-startup-with-inline-images "nil")
`
I have no idea how to fix it or what is happening with it though.

**Comment by jkitchin** [comment]
you probably want `(setq org-startup-with-inline-images nil)` instead (no quotes on nil). That sounds like an imagemagick bug. Does this only happen with scimax, or do you have the same problem with a mostly vanilla emacs?

In scimax-org.el there are some modifications to images and rescaling them. It is possible they are the source of the problem. You could search for ;; * Rescaling inline-images

and comment out the whole section. You will have to restart emacs then.

**Comment by Cumol** [comment]
So, the amount of crashes was reduced after setting the inline images to nil, and also using smaller output image size.

But they still happen. Now mainly triggered when creating a new source block and writing something into the header options. emacs freezes and then crashes.

This *does not* happen with vanilla emacs (which only has some babel packages and ess installed)

So maybe it has something to do with source blocks, somehow

**Comment by jkitchin** [comment]
That could be an issue. I hacked some parts of how src blocks are fontified to get different colored src blocks by language.

Look in scimax-org.el for a section called ;; * Colored src blocks. It should be safe to comment out `org-src-font-lock-fontify-block`, `org-fontify-meta-lines-and-blocks-1`.  After a restart then the original org functions should be active.

Those seem like the most likely candidates, but it seems like they would be triggering an bug in font-lock if it is causing a crash.
