### ISSUE TITLE
Show source code of Python function a la Jupyter `function??`

### ISSUE THREAD

**Issue by timehaven** [jkitchin/scimax#232]
Currently, you have the following keybinding in org mode, ipython source:

     H-/      get help about thing at point (ob-ipython-inspect)

In Jupyter, that is equivalent to a single question mark after a function.  For instance, if I have a function previously defined as

```python
def foo(x):
    print(x)
```

then in a notebook (or Jupyter console), typing `foo?` in a cell would display

```
Signature: foo(x)
Docstring: <no docstring>
File:      ~/my/project/<ipython-input-217-26bef3f8a412>
Type:      function
```
in a partial window at the bottom of the notebook.  This is the same output as `H-/` in scimax.

Further, in Jupyter, typing `foo??`  will produce the actual source code of the function.  The following is a pure Python way to get the same:

```python
import inspect
print(inspect.getsource(foo))
```

but there is no syntax highlighting--it is just plain text output.

Can you see a way to add to the inspection capabilities and emulate the `??` functionality of Jupyter?

P.S.--You haven't heard from me in a while--that means everything works great.  I use scimax with org+jupyter daily (with multiple remote kernels on multiple remote machines in the same .org file on my local laptop).  Great work!  Thank you.

**Comment by jkitchin** [comment]
I pushed a hacky solution to this. I think it should be possible to use the ?/?? syntax more directly, but the output in the responses from the kernel are currently getting ignored. For now, H-/ will pop up the docstring buffer, and C-u H-/ should pop up a source buffer.

**Comment by timehaven** [comment]
Thanks, John.  I tried it.  It is not respecting the session, tries to run introspection using a local kernel.  I use a remote session:

    :PROPERTIES:
    :header-args:ipython: :display text/plain :session jupyter-kernel-bare-ssh.json
    :END:

Execution works fine, as per normal, on the remote kernel.  But your new introspection spins up a new local kernel and then fails (since my function is defined in the remote kernel).

This is not a big deal, so no worries about digging too deep.

**Comment by jkitchin** [comment]
That is would happen here. The results get sent from the kernel. I will see if I can dig them out. I am traveling the next few days, so it may be a week or so. alternatively, maybe you can figure out how to get the right session passed to the params.

**Comment by timehaven** [comment]
OK, I'll look into that.  Thanks.  Safe travels.

**Comment by jkitchin** [comment]
I pushed a new approach that should let the ipython syntax work. so, foo? should pop up a buffer with the docstring, and foo?? should pop up a buffer with the source. Let me know if it works for you.

**Comment by timehaven** [comment]
Works great for me.  Thank you.  

Mission creep (new issue?):  after issuing either `foo?` or `foo??`, the cursor is placed in a new buffer called `ob-ipython-data`, which is in `Fundamental` major mode.  Any chance it could land in a buffer that is in something like `Help` mode that has a convenient keybinding like `q` for `quit-window`?  That way, the workflow is: `foo??` lands you in a new window, you can scroll around (for larger functions) to see what the code of the function is, then hit `q` to land back where you were originally in the .org file.

Regardless, I'll close this because you solved the original issue.  Thanks again.

**Comment by jkitchin** [comment]
I think special-mode does this. Try da4dfef and see if it does enough of what you want.

**Comment by timehaven** [comment]
Perfect!  Thank you, John.
