### ISSUE TITLE
Justify Latex fragment preview

### ISSUE THREAD

**Issue by YujiShen** [jkitchin/scimax#233]
I encounter error "Symbol's function definition is void: image-display-size" after I used snippet below in my init.el. I am using Emacs 26.1.

https://github.com/jkitchin/scimax/blob/50e06f88299249a556825549818a8f79cba867e8/scimax-org.el#L585-L616

I can use the snippet from your blog without issue. But I think you made some improvements here, so I want to use this one.

UPDATE: I change `image-display-size` to `image-size`, it is working now.

I have a question: can I prevent image fragment to be centered if there are texts behind it?

**Comment by jkitchin** [comment]
I think b840d83 will prevent equations with text after them from being centered.

**Comment by YujiShen** [comment]
@jkitchin Thanks! It works great for inline fragment, but it will cause numbered equation not centered. Maybe have to distinguish different kinds of equation?

Also what does this function do? I added it into my init file but did not see any effect. https://github.com/jkitchin/scimax/blob/b840d83b992426c2399175efaa380ba71f7f3b59/scimax-org.el#L624

P.S. I have a question about Latex preview and post it on Stack Exchange, I know you are experienced in this topic, would you like to take a look at it? [Adjust font weight for Latex fragment preview in Org-mode - Emacs Stack Exchange](https://emacs.stackexchange.com/questions/45299/adjust-font-weight-for-latex-fragment-preview-in-org-mode)

**Comment by jkitchin** [comment]
7809908 probably addresses the numbered equations issue. 

org-renumber-environment alone won't do anything without the corresponding advice:

`(advice-add 'org-create-formula-image :around #'org-renumber-environment)`

which I believe makes the numbers in the previews correct (i.e. not all equal to 1).

Also, I posted an answer on your stack exchange question. It isn't straightforward to get it, but it is possible.

**Comment by YujiShen** [comment]
@jkitchin So many thanks! I tested the fix and it works.

For `org-renumber-environment`, the reason I did not see correct numbers is that I wrote two same functions. But even I did not add this function and advice, I could still get correct numbers, at lease under same subtree... Is this a default now?

P.S. I add a comment under your answer for my questions about how to write `org-latex-default-packages-alist`.

**Comment by jkitchin** [comment]
I don't think it is default. If I comment this out and the advice, then I get (1) for subsequent equations instead of sequentially numbered equations.

I added an additional solution to the stackexchange question, and made that approach the one used in scimax.

**Comment by YujiShen** [comment]
@jkitchin You are right about the numbered equations. I got correct numbers because the images are generated before.

Thanks for the additional solution for my question, I will use that one along with fourier font setting in `org-format-latex-header`.

Really appreciate your quick and detailed help!
Issue closed.

**Comment by YujiShen** [comment]
Just want to make sure the position for numbered equations: the image is centered, but not the formula, because there is space between formula and number. So the formula is on the left side and number on the right side. Is this intended effect for centered numbered equation under current setting? Is it possible to make formula centered and number on the right side? (How is length of the space between number and function determined? Can we control it?)

**Comment by jkitchin** [comment]
It is only the image that gets centered. If you want the number on the right, I would use :justify 'right.  I don't know how to ontrol the space between the number and equation, that is done in LaTex somehow.

**Comment by YujiShen** [comment]
@jkitchin Got it. Thanks!
