### ISSUE TITLE
ipython and inline code

### ISSUE THREAD

**Issue by mankoff** [jkitchin/scimax#234]
I'm using the Scimax version of ob-ipython and running into an issues with inline code blocks. I post here because this project is actively developed while the last commit to ob-ipython in February. Please let me know if you think this is an upstream bug.

This works fine:

```
#+BEGIN_SRC ipython :session
vel.shape[0]
#+END_SRC

#+RESULTS:
:RESULTS:
# Out[30]:
# text/plain
: 7225
:END:
```

This produces an error:

```
src_ipython[:session]{vel.shape[0]}
```

`user-error: Inline error: multiline result cannot be used`

I can get inline code to work if I set

```
(setq ob-ipython-suppress-execution-count t)
(setq ob-ipython-show-mime-types nil)
```

But I'd like those (and line numbering) in general in my IPython babel blocks. Is there a way to turn these features off for inline code only?

**Comment by mankoff** [comment]
Follow-on issue:

Even when working, the `:` is included in the results:

src_ipython[:session]{vel.shape[0]} {{{results(: 7225)}}}

and both code and results are exported (even though by default, neither code nor results are exported). Is it possible to do further customization to inline code so that only results are exported and the colon is not included?

**Comment by roblem** [comment]
You don't need to specify `:session` if using the default session (ob-ipython always uses a session by default), and you want raw output I believe.  This works for me:
```
src_ipython[:results raw]{x = np.array([0,1]); print(x.shape[0])} 
```
and results in just `2` being printed without a colon and no `results` wrapper.

**Comment by mankoff** [comment]
Yes - `:results raw` fixes the colon issue (but causes other problems if run >1x). Thanks for the `:session` hint. I still find in my system that `ob-ipython-show-mime-types` must be `nil`. When this is `nil`, we lose the ability to have Pandas tables reformatted as Org tables :(.

**Comment by jkitchin** [comment]
Thanks for reporting this. I haven't used inline src blocks alot, so I hadn't noticed this issue. I pushed 72ed22c, which at least partially fixes the issue, without requiring you to change ob-ipython-show-mime-types or the execution count. With this commit, I get something like this:

`see src_ipython[:exports results]{4 + 4} {{{results(8)}}}, for example.`

I think scimax has some defaults on exports for both code and results, so if you want to suppress code, you either have to change the defaults, or specify results in the inline src_block.

**Comment by mankoff** [comment]
Seems to work well. Thanks for the quick fix!
