### ISSUE TITLE
hunspell exited with code 123

### ISSUE THREAD

**Issue by tuxiano** [jkitchin/scimax#237]
Hi Mr. Kitchin,

thank you for providing scimax (and org-ref).

I'm using scimax version 2.0 on windows 10 Version 1803 Build 17134.345 and installed scimax using the follwing command:

`bash -c "$(curl -fsSL https://raw.githubusercontent.com/jkitchin/scimax/master/install-scimax-win.sh)"`

When I try to enable flyspell I get the follwing error message:

`hunspell exited with code 123`

Any ideas how to fix this issue?

Kind regards,

Marko

**Comment by jkitchin** [comment]
This is the same issue reported in https://github.com/jkitchin/scimax/issues/159. I am not sure what the solution is. Unless flyspell is important for you, this could be ignored.

**Comment by tuxiano** [comment]
Hi, unfortunately I need flyspell, since I want to write technical reports with scimax/emacs.

**Comment by tuxiano** [comment]
Ups, wrong button.

**Comment by jkitchin** [comment]
you can try the following:
1. Close emacs
2. cd scimax/emacs-win
3. git checkout master
4. reopen emacs.

It appears that hunspell was crashing some emacs for a while, so I had checked out an earlier version that was not doing that.

**Comment by jkitchin** [comment]
I guess that when you load scimax, the changes are getting reverted back to the old commit. Can you try the following. change into the scimax/emacs-win directory. Then run this command:

`> bin/hunspell -h`

I guess it will have no output. If that is the case, next run this command:

`> git checkout master`

and then try `> bin/hunspell -h` again. If you get a regular output of the help arguments, this is an indication of the problem, namely which version of hunspell is installed. If that worked, also try:

`> bin/hunspell -d`

If this all looks promising, then the thing to do is change up to the scimax directory and run `git status` where it should look like there are new commits in emacs-win. You can commit these with:

`git commit emacs-win -m "some message"`

and then when you start up scimax you should probably have a working version of hunspell.

Alternatively, you an install hunspell yourself and configure the relevant variables to use it.

**Comment by tuxiano** [comment]
Thank you, that did the trick.

I still cannot use german spell checking, buts that another isse.

**Comment by jkitchin** [comment]
That could have to do with what LANG windows is set to.

What is the output of this:

`(message "LANG: %s" (getenv "LANG") )`

**Comment by tuxiano** [comment]
Hi, it the command returns:

`LANG: DEU`

**Comment by jkitchin** [comment]
And if you run 

`hunspell -D`

is a german dictionary listed?

**Comment by tuxiano** [comment]
Hi, it returns:

``C:\Users\user\scimax\emacs-win\bin>hunspell.exe -D
SEARCH PATH:
.;;C:\Hunspell\;C:\Users\user\.openoffice.org\3\user\wordbook;C:\Users\user\scimax\emacs-win\bin\..\share\hunspell;C:\Program files\OpenOffice.org 2.4\share\dict\ooo\;C:\Program files\OpenOffice.org 2.3\share\dict\ooo\;C:\Program files\OpenOffice.org 2.2\share\dict\ooo\;C:\Program files\OpenOffice.org 2.1\share\dict\ooo\;C:\Program files\OpenOffice.org 2.0\share\dict\ooo\
AVAILABLE DICTIONARIES (path is not mandatory for -d option):
C:\Users\user\scimax\emacs-win\bin\..\share\hunspell\default
**C:\Users\user\scimax\emacs-win\bin\..\share\hunspell\de_DE_frami**
C:\Users\user\scimax\emacs-win\bin\..\share\hunspell\en_GB
C:\Users\user\scimax\emacs-win\bin\..\share\hunspell\en_US
LOADED DICTIONARY:
C:\Users\user\scimax\emacs-win\bin\..\share\hunspell\default.aff
C:\Users\user\scimax\emacs-win\bin\..\share\hunspell\default.dic
Hunspell 1.3.2``

So yes, it find the german dictionary.

**Comment by jkitchin** [comment]
I guess it is not finding the right name that it is looking for. Maybe this could help: https://unix.stackexchange.com/questions/86554/make-hunspell-work-with-emacs-and-german-language
