### ISSUE TITLE
Errors when starting scimax

### ISSUE THREAD

**Issue by sbacelar** [jkitchin/scimax#239]
Suddenly when I do in my Mac (10.14.1) as always in iTerm `emacs -q -l scimax/init.el` I get the following message: 
```
/Applications/Emacs.app/Contents/MacOS/bin/emacsclient: unrecognized option '-l'
Try '/Applications/Emacs.app/Contents/MacOS/bin/emacsclient --help' for more information
```
I also normally use an alias  alias `es=" open /Applications/emacss.command"` that runs the following script:
```
#! /bin/bash
cd ~
emacs -q -l scimax/init.el
```
But when I run this script it opens emacs (scimax) only on my Terminal (iTerm).

**Comment by jkitchin** [comment]
I haven't come across this error. Did you update Emacs or anything?

**Comment by sbacelar** [comment]
I changed my emacss.command from `emacs -q -l scimax/init.el` to `/Applications/Emacs.app/Contents/MacOS/Emacs -q -l scimax/init.el` and now scimax works. I don't understand what happened.
