### ISSUE TITLE
Inserting citation issue

### ISSUE THREAD

**Issue by tygao** [jkitchin/scimax#24]
Hi professor,

I met a problem of citation insertion. 
There's  only a message of "No PDF(s) Found" and no citation inserted. Would you please check this?
Thanks,

Tianyu

**Comment by jkitchin** [comment]
I can not reproduce this. Can you update helm-bibtex and let me know if
it persists?

Tianyu Gao writes:

> Hi professor,
>
> I met a problem of citation insertion.
> There's only a message of "No PDF(s) Found" and no citation inserted. Would you please check this?
> Thanks,
>
> Tianyu
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.


-- 
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by tygao** [comment]
Wow, it worked!
Thanks
