### ISSUE TITLE
sci-max installing packages every time starting emacs

### ISSUE THREAD

**Issue by domingoUnican** [jkitchin/scimax#244]
Dear all,

Is it normal that, although I have been using scimax since three months, it keeps installing packages when I open it?

**Comment by jkitchin** [comment]
Can you provide a little more information about which OS you use? This issue is related to when/if package-initialize is called in bootstrap.el. I think it should do the right thing, but it doesn't always seem to for some reason.

**Comment by domingoUnican** [comment]
Sorry, my fault. I am using Debian GNU/Linux testing (buster).
The emacs package is installed through aptitude and the version is 25.2.2

**Comment by jkitchin** [comment]
There is another reason I recall that causes this, and that is sometimes there is an ~/.emacs.d directory that has packages installed in it which somehow conflict in version which seems to trigger reloading all the packages.  Can you check if there is a .emacs.d/elpa?

**Comment by jkitchin** [comment]
If you delete, or rename ~/.emacs.d and then start scimax does it still reload all the packages?

**Comment by domingoUnican** [comment]
It has improved. Now, it is only two packages. 
pdf-tools and auctex. Could it be that there are warnings during the installation?

**Comment by jkitchin** [comment]
neither of those are mission critical for me, I even disable loading auctex on some systems where it segfaults. You could also do that. I guess pdf-tools is loaded in org-ref. you could comment that out there maybe too.

**Comment by domingoUnican** [comment]
That was the problem. Thanks!
