### ISSUE TITLE
M-x not working on new install fails with symbol’s value as variable is void ivy-height-alist

### ISSUE THREAD

**Issue by NahsiN** [jkitchin/scimax#246]
On PopOS 18.04 (same as Ubuntu 18.04), I'm trying to install scimax using the instructions in the README and end up with the following errors after install,
```
Error (use-package): Failed to install org-edna: Failed to verify signature: "seq-2.20.tar.sig"
Error (use-package): org-edna/:init: Symbol’s function definition is void: org-edna-load
Error (use-package): Cannot load org-edna
Error (use-package): scimax-ivy/:catch: Symbol’s value as variable is void: ivy-height-alist
```
When I run scimax, M-x does not work, the message `autoload-do-load: Symbol’s value as variable is void: ivy-height-alist` is displayed in the minibuffer.

Emacs version: GNU Emacs 25.2.2 (x86_64-pc-linux-gnu, GTK+ Version 3.22.21) of 2017-09-22, modified by Debian

**Comment by jkitchin** [comment]
This usually means there is some issue on MELPA, and the packages were not installed/loaded properly. It usually also goes away on its own after a few hours to a day. Do you still see the problem now?

**Comment by NahsiN** [comment]
Unfortunately yes, I'm still seeing this problem. There is definitely some issue with downloading v2.20 of the seq package.

**Comment by NahsiN** [comment]
I got past the error `Failed to install org-edna: Failed to verify signature: "seq-2.20.tar.sig"` by setting `(setq package-check-signature nil)` explicitly in init.el below the `(let* ....)` clause. So now all the packages get installed but I run into the following errors

```
Error (use-package): Failed to install org-edna: Assertion failed: (or (= (buffer-size tar-data-buffer) (buffer-size)) (eq tar-data-swapped (> (buffer-size tar-data-buffer) (buffer-size))))
Error (use-package): org-edna/:init: Symbol’s function definition is void: org-edna-load
Error (use-package): Cannot load org-edna
Error (use-package): scimax-ivy/:catch: Symbol’s value as variable is void: ivy-height-alist
```

**Comment by jkitchin** [comment]
That sounds like progress, but those are still related to incomplete or out of date installs. You can safely comment out the line for loading org-edna. It is not a critical package. 

The ivy-height-alist issue means you have an out of date ivy/swiper/counsel installation. Maybe look in your elpa directory and either delete all of those folders, or move them to another place and try opening scimax again, which I think will reinstall all those. Alternatively, you might try installing the newest packages from emacs and then restarting..

**Comment by NahsiN** [comment]
Thanks for the hint! I've had emacs for while and didn't realize I had elpa packages installed using apt. `sudo apt remove elpa-*` did the trick! Turns out I had the Debian package `elpa-ivy` installed on my system. Finally, time to starting using Scimax. Thanks for your great work.
