### ISSUE TITLE
Want to spell THe but cannot

### ISSUE THREAD

**Issue by mankoff** [jkitchin/scimax#247]
I'd like to spell a word like `THe`, but on a clean sci-max install it keeps correcting it to `The`. I have tried disabling `scimax-autoformat-transposed-caps` and `scimax-autoformat-sentence-capitalization` but it still occurs. How can I disable this "feature"?

**Comment by jkitchin** [comment]
That is from dubcaps-mode. You can turn it off with M-x dubcaps-mode I think.

It is added to text-modes in scimax.el here.

(add-hook 'text-mode-hook #'dubcaps-mode)

you could either comment that line out, or add a line to your init to remove that hook if you want it permanently off.

**Comment by mankoff** [comment]
Thank you! That was a hard one to debug for a emacs beginner. I couldn't diagnose it with `C-h k` or similar functions.

**Comment by jkitchin** [comment]
no worries, it took me a few minutes to track it down too!
