### ISSUE TITLE
colons in code output from ipython block

### ISSUE THREAD

**Issue by colormotor** [jkitchin/scimax#248]
Hello,
Since a few days I have the following problem with python code blocks in org mode. I want to generate a python code block from another as follows:
```
#+BEGIN_SRC ipython :exports code
print('generate_python_func()')
#+END_SRC
```
but the each line of the output is prepended by colons as follows:
```
#+RESULTS:
:RESULTS:
# Out[8]:
# output
: generate_python_func()
: 
:END:
```
After some search I found that one solution it to set the value of `org-babel-min-lines-for-block-output`. But while this works fine with ELISP code blocks, e.g.:
```
#+BEGIN_SRC emacs-lisp :results code
(setq  org-babel-min-lines-for-block-output 0)
(print '(generate-elisp-func))
#+END_SRC

#+RESULTS:
#+BEGIN_SRC emacs-lisp
(generate-elisp-func)
#+END_SRC
```
the flag seem to be ignored by ob-ipython even when set to 0. I also tried different combinations of options for the :results but the problem persists.
 
I'm not sure wether this is a problem specific to scimax, ob-ipython or to my installation of emacs.
I am running on a Mac, and I have had some problems since I switched to OSX Mojave with which there seem to be still some compatibility issues, so the last option is very likely. 

But if this is a known issue any suggestions are more than welcome!

**Comment by jkitchin** [comment]
This is for sure just an issue in scimax/ob-ipython. I have never used code with python, and so this isn't a corner tested in the scimax ob-ipython mods. I have pushed a commit that at least partially  fixes this for your example. There may be other corners though, I don't think my fix catches everything. 
Let me know if that helps.

**Comment by colormotor** [comment]
Yes it works. Thanks for the quick fix! And for maintaining such a wonderful tool:) Works perfectly now.
