### ISSUE TITLE
Code block image output issues

### ISSUE THREAD

**Issue by Cumol** [jkitchin/scimax#25]
Hey! thanks for putting together scimax, I stumbled upon an issue while exporting to PDF that I am trying to understand. Here is an example:

I have three R code blocks in which I generate a sample plot from ggplot2. The first one outputs the image correctly, in the second one I use an underscore in the #+name: attribute (for easier complex file naming) and the block does not generate the plot. In the third one I add a line of code which calls to output the plot (bp) which leads to a truncated/weird image in org-mode.

```
#+name: test
#+BEGIN_SRC R :results output graphics :exports both :file-ext png :res 180 :width 16000 :height 900
library(ggplot2)


bp <- ggplot(data=PlantGrowth, aes(x=group, y=weight, fill=group)) + geom_boxplot()
#+END_SRC

#+RESULTS: test
[[file:test.png]]
```

```
#+name: test_1
#+BEGIN_SRC R :results output graphics  :exports both :file-ext png :res 180 :width 16000 :height 900
library(ggplot2)

bp <- ggplot(data=PlantGrowth, aes(x=group, y=weight, fill=group)) + geom_boxplot()
#+END_SRC

#+RESULTS: test_1
[[file:test_1.png]]
```

```
#+name: test_2
#+BEGIN_SRC R :results output graphics :exports both :file-ext png :res 180 :width 16000 :height 900
library(ggplot2)

bp <- ggplot(data=PlantGrowth, aes(x=group, y=weight, fill=group)) + geom_boxplot()
bp
#+END_SRC

#+RESULTS: test_2
[[file:test_2.png]]
```

Now, when I try to export this file to either pdf or html, I get different results as you can see [here wit HTML](https://cloud.cumol.org/index.php/s/6G3gMek0krjojmB) or [here for PDF](https://cloud.cumol.org/index.php/s/elSczsGa76xeaLe).

Any idea what is causing this?

**Comment by jkitchin** [comment]
using _ in latex is tricky, as it often means underscore, and needs to be escaped or a package needs to be used to change how underscore is used. Try using - instead.

**Comment by Cumol** [comment]
Ah, thanks for the help 👍
