### ISSUE TITLE
How to automatically load a .el file from start

### ISSUE THREAD

**Issue by maikol-solis** [jkitchin/scimax#250]
Hello!

I see that scimax have very neat features like `scimax-dashboard.el`, `scimax-statistics.el`, `scimax-evil.el`, etc. 

How do I load them automatically from start? Do I have to create a custom file in the `user` folder and load them from there or there is a better solution?

Thanks

**Comment by jkitchin** [comment]
The best thing to do is definitely create user/user.el and put any commands you want to run in there. That file is automatically loaded at the end of scimax/packages.el.
