### ISSUE TITLE
tlmgr exits with status 2 on startup

### ISSUE THREAD

**Issue by tarihatari** [jkitchin/scimax#252]
After installing scimax on Ubuntu 18.04 I have a similar issue as  [tlmgr not found on startup](https://github.com/jkitchin/scimax/issues/210): as soon as I open a file which is not empty, on startup I get this message in the buffer

> [yas] Prepared just-in-time loading of snippets successfully.
Starting new Ispell process /usr/bin/hunspell with en_US dictionary...
error in process sentinel: async-handle-result: /usr/bin/tlmgr exited with status 2
error in process sentinel: /usr/bin/tlmgr exited with status 2

and this one in the bash 
> (emacs:10831): Gtk-CRITICAL **: 21:55:30.753: gtk_distribute_natural_allocation: assertion 'extra_space >= 0' failed`

and the configuration file does not load correctly

**Comment by jkitchin** [comment]
The bash Gtk thing does not seem critical. Do you have a /usr/bin/tlmgr? if so, what happens if you run:

tlmgr info --only-installed

?

One temporary solution is to comment out the function that does this in scimax/snippets/org-mode/.yas-setup.el 

It is not a critical feature, it just sets up some yasnippets.

**Comment by tarihatari** [comment]
tlmgr info --only-installed returns

running on Debian, switching to user mode!)
Cannot determine type of tlpdb from /home/USER/texmf!
cannot setup TLPDB in /home/USER/texmf at /usr/bin/tlmgr line 6424.

Commenting out the function in .yas-setup.el worked, thanks.

**Comment by jkitchin** [comment]
That suggests something is not setup correctly with your latex installation. This isn't a critical functionality, it just provides completion on the installed packages you have on your system. I am going to close this issue. If you figure out what is wrong with your setup that breaks tlmgr, please put it here later. Best wishes,

**Comment by badkey** [comment]
tlmgr init-usertree
solves the problem.

**Comment by jkitchin** [comment]
Thanks for the update! That is helpful information.
