### ISSUE TITLE
ob-ipython not running

### ISSUE THREAD

**Issue by domingoUnican** [jkitchin/scimax#253]
Dear all,

Sorry, I was trying using the ob-ipython feature inside Scimax.

However, when putting the following code:
#+BEGIN_SRC ipython :session salida :results output

print("Hello")
#+END_SRC

It appears the following message in *ob-ipython-debug*:
OSError: Could not find 'emacs-salida' in ['.', '/Users/gomezd/Library/Jupyter/runtime']

**Comment by jkitchin** [comment]
I can't reproduce this, your block worked  fine for me on a Mac and Windows machine. I am not sure what to suggest for debugging, if you try several times does it always fail?

**Comment by domingoUnican** [comment]
Yes, it always fails with the same error.
I am in a Mac, by the way.
Does it makes any difference if I am editing a org file after using nb-create or nb-open?

**Comment by jkitchin** [comment]
It should not matter. I guess what is happening is the notebook server/kernel is not getting started in time. Does it work if you don't use a session? e.g. like this:

#+BEGIN_SRC ipython  :results output

**Comment by domingoUnican** [comment]
Still the same error. Here is the *ob-ipython-debug*

Traceback (most recent call last):
  File "/Users/gomezd/Git_Repositories/scimax/ob-ipython-upstream/client.py", line 60, in <module>
    c = create_client(args.conn_file)
  File "/Users/gomezd/Git_Repositories/scimax/ob-ipython-upstream/client.py", line 43, in create_client
    cf = find_connection_file('emacs-' + name)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/connect.py", line 218, in find_connection_file
    raise IOError("Could not find %r in %r" % (filename, path))
OSError: Could not find 'emacs-ipython-46e35967b4a91e751ee675f78a73f17a' in ['.', '/Users/gomezd/Library/Jupyter/runtime']

**Comment by jkitchin** [comment]
Is this a new problem, i.e. did it work before but not now? Or is it the first time you have tried this?

**Comment by domingoUnican** [comment]
Yes, this is the first time that I try it.

**Comment by domingoUnican** [comment]
I discover what was the problem! 
When I checkout out the buffer *ob-ipython-out*, it says that Jupiter-console was not installed.

I close the issue and thank you very much!
