### ISSUE TITLE
Latex export: supress drawers from export into pdf

### ISSUE THREAD

**Issue by Arjay-El** [jkitchin/scimax#254]
I place notes in a drawer labelled ":NOTES: I have been trying to suppress their output into latex with
#+OPTIONS: :d(no "NOTES") in my org file headers.
but this does not seem to work. I have looked through the documentation but cannot find a solution as it seems  :d should toggle drawers off. Can you suggest a solution I can use?

**Comment by jkitchin** [comment]
I guess you should use:

#+OPTIONS: d:(not "NOTES")

**Comment by Arjay-El** [comment]
It must be peculier to my setup that I cannot get that to work but #+OPTIONS: d:nil does, regardless what I call the drawers. Closing this one as I have a solution, thanks.
