### ISSUE TITLE
ox-ipynb exports invalid ipynb if blocks have header arg ":exports none"

### ISSUE THREAD

**Issue by singletS** [jkitchin/scimax#255]
As of commit e10f09eb632  is seems ox-ipynb is ignoring the header arg ":exports none" in some cases. Sample org file:
```
Mixing python and elisp
#+BEGIN_SRC elisp :exports none
(message "Good day")
#+END_SRC

Some python
#+BEGIN_SRC ipython
print("good day")
#+END_SRC
```
Although an ipynb file is created, it is invalid with the jupyter server complaining,
 
Unreadable Notebook: test.ipynb TypeError('pop() takes at most 1 argument (2 given)',)

**Comment by jkitchin** [comment]
The problem is that the first block is used to determine the language type, and elisp is not a supported language. I just pushed a commit to address this for blocks that shouldn't be exported. One easy solution though is to add:

#+OX-IPYNB-LANGUAGE: ipython

to set the language you want.

**Comment by singletS** [comment]
This seems to be fixed...thanks. Turns out I didn't need to add #+OX-IPYNB-LANGUAGE, but will keep this in mind if problems arise; thanks for the pointer.

There seems to a different (but related?) problem limiting scope to a subtree (C-c C-e C-s) in that other subtrees get exported.

Trying to work around this using :noexport: in headlines, the exported ipynb doesn't include the headline, but content of the subtree is included. E.g., using C-c C-e C-s on "Another tree", there  no headline for "Python" subtree, but its content is exported:
```
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 26.1 (Org mode 9.1.13)

Mixing python and elisp

* Lisp                                                             :noexport:
#+BEGIN_SRC elisp :exports none
(message "Good day")
#+END_SRC

* Python                                                           :noexport:
Some python
#+BEGIN_SRC ipython
print("good day")
#+END_SRC

* Another tree
Try to export only this subtree.
```
Exported ipynb:
![image](https://user-images.githubusercontent.com/8687756/50649090-8b400e80-0f42-11e9-8be4-c9fdfe577bbb.png)

I can open a new issue if appropriate.
Thanks,
Steve

**Comment by jkitchin** [comment]
ox-ipynb isn't a regular exporter, so a lot of these kinds of things won't, and can't really work. Basically, what happens is the buffer gets parsed into cells, which then get converted  to markdown or code cells. It isn't meant for general export like you are trying to do here. I don't know a real way around this that doesn't lose alot of other features (e.g. the metadata on cells) which get lost if you do an org-export-as org for example.

**Comment by singletS** [comment]
I understand.  Thanks for the quick fix to the original export issue...that helps greatly.

**Comment by singletS** [comment]
Sorry to re-open, but I think I may have confused things describing the work-around.  The real issue is that after commit e10f09e, sections under headlines tagged with :noexport: are being exported to the ipynb. Should ox-ipynb still respect :noexport:, and not include these sections?

If this isn't possible, is there another way to get the same behavior? This is a super useful tool I've used for exporting different versions of notebooks from a single org file (e.g., a homework notebook and its solutions from the same org file).

**Comment by singletS** [comment]
Thanks for the follow up.

Trying the example above, I'm getting a lisp error on export: (wrong-number-of-arguments (0 . 0) 1)
The first few lines of traceback (it's over 30K lines long) if it's helpful?? 
```
Debugger entered--Lisp error: (wrong-number-of-arguments (0 . 0) 1)
  org-get-tags(144)
  (-intersection (org-get-tags (org-element-property :begin hl)) exclude-tags)
  (if (-intersection (org-get-tags (org-element-property :begin hl)) exclude-tags) (progn hl))
 ```

**Comment by jkitchin** [comment]
What does C-h f org-get-tags tell you? I wonder if this is a change in org 9.2.

**Comment by jkitchin** [comment]
I added a new commit that looks closer to the regular export behavior. Now, all blocks marked with :exports none are removed from the copy of the buffer before exporting.

I don't understand the :ignore: tag, but you should be able to try this:

C-c C-e OO to export the buffer to a temp org buffer that does use all the export machinery, and then C-c C-e n o to export that buffer to an ipynb.  I am pretty sure this approach won't work with cell metadata, it gets stripped out, but if you aren't using that, it won't be an issue. Also at the moment this will lead to Untitled.ipynb.

If it is just a matter of deleting headlines with :ignore tags, that is also an easy fix to implement.

**Comment by singletS** [comment]
I've tried a couple different org files and it looks like exports are working as expected. Thanks! This is very helpful for my use case.

Re: the ignore tag. As implemented in ox-extra, headlines with :ignore: tag are removed, but the text under the headline is promoted to the parent. I'm ignorant about how the tree structure would be affected, but maybe it doesn't matter if the :ignore: headlines are simply deleted at the right time (just before creating/writing the ipynb buffer?). If so, I think doing this should work fine.

If it makes sense to use the existing function, it's org-export-ignore-headlines from org/contrib/lisp/ox-extra.el; behavior is explained just above the defun.

**Comment by jkitchin** [comment]
I think we can now do something like ox-extra does. It seems like all the headings are one level too low, but they seem relatively correct now. there is also a new preprocessing hook to make it easier to add additional things like this.

**Comment by singletS** [comment]
This looks good. I'll test with some more org files in the next few days and close the issue unless anything pops up.  Thanks again!
