### ISSUE TITLE
Excessive memory utilisation on Antergos / Arch Linux

### ISSUE THREAD

**Issue by shrysr** [jkitchin/scimax#257]
As I continue to use Scimax, the RAM utilisation by Emacs steadily rises to a ridiculous level ~4GB over a few hours! I am performing data analysis in memory, but the data files themselves are hardly big enough to warrant such a steep rise.  I have tried killing all the processes, but the utilisation does not reduce at all. I have also tried using the profiler, but cannot find the reason. 

I am using Scimax (daemon+ client) on Antergos (Arch based Linux distro) running as a VM within a Windows host.  Predominantly, I have eshell, w3m, org mode, R and python based processes running. At the moment, I'm predominantly processing data using R (ESS). 

My home machine is an old Macbook, which I almost never shut down and Emacs has never behaved in this manner on it despite performing even more activities on the machine. In fact, I've happily used the same Linux distro and setup with Emacs in the past. 

Could this have anything to do with the `gc-cons-threshold` setting? Would appreciate advice to troubleshoot the problem.

**Comment by shrysr** [comment]
I will investigate the response on a Jupyter notebook and gc-cons-threshold. I am also inclined to think that the reason may be related to a specific version of a package or program. It is now clear that performing exactly the same processes / steps on my macbook certainly does not cause such a steep and continuously rising utilisation of memory. I did try reinstalling Emacs on the Linux OS, but that did not help.

Would compiling Emacs from source on the Linux OS help? 

John Kitchin <notifications@github.com> writes:

> From: John Kitchin <notifications@github.com>
> To: jkitchin/scimax <scimax@noreply.github.com>
> Cc: Shreyas Ragavan <shreyasr@gmail.com>, Author
>  <author@noreply.github.com>
> Subject: Re: [jkitchin/scimax] Excessive memory utilisation on
>  Antergos / Arch Linux (#257)
> Flags: seen, list
> Date: 2019-01-09T17:23:28-0700
> Maildir: /INBOX
> List: scimax.jkitchin.github.com
>
> I wouldn't think it has anything to do with gc-cons-threshold, but you could certainly try lowering it. It is set high to speed up the startup I think. I would just comment the line out in init.el if you want to try it out.
>
> It sounds more like an emacs bug, maybe in the specific version that is problematic, or in a program that does the analysis (like R or python). If you try the analysis in a jupyter notebook do you still get the memory leakage?


-- 
==================
Shreyas Ragavan
M: +1 647 671-1851
E: shreyas@fastmail.com
https://shrysr.github.io

**Comment by jkitchin** [comment]
Unless you think Emacs is the problem, i doubt compiling from source would help.

**Comment by shrysr** [comment]
I'd like to report that I have not experienced this problem subsequently on Debian or other distros. If I remember right, changing gc-cons-threshold did not solve the problem. I will close the issue, and revert if I experience this again.
