### ISSUE TITLE
using Scimax in a script 

### ISSUE THREAD

**Issue by theottm** [jkitchin/scimax#258]
Hello John,

first of all thank you for this amazing piece of software!  I also have my own version but for some particular tasks I like to use yours, especially when working with ipython and babel. 

I'm trying to automatize the generation of html pages from my org-babel notebooks. I would like to avoid having to open emacs so I thought of running the simple org-html-export-to-html command from the command line.

Which gives us a command like this 
` emacs --batch -Q -l scimax-init.el --file="./grub.org" --eval="(org-html-export-to-html)"
`
But there emacs gets stuck with this message

> Starting new Ispell process /usr/bin/hunspell with en_US dictionary

I also tryed without batch and scimax open and also gets stuck. When I open scimax regularly and open my file and then run the command with M-x it works perfectly.

What I also find strange is that sometimes it worked when ran from the command line... Surely some mechanism launching Ispell that I don't understand !

I also thought of writing a elisp script and loading it but the problem is the same. It's at the opening of the file apparently that the problem occurs.

**Comment by jkitchin** [comment]
One way is like this I think. It is a little hacky, and removes an org-mode hook that starts flyspell, then opens the file and exports it. you could put something like this in a script and should do the same thing. 

emacs --batch -Q -l ~/vc/jkitchin-github/scimax/init.el  --eval="(progn (remove-hook 'org-mode-hook (lambda () (flyspell-mode +1) (flycheck-mode +1))) (find-file \"grub.org\") (org-html-export-to-html))"
