### ISSUE TITLE
User modifications via submodule

### ISSUE THREAD

**Issue by shrysr** [jkitchin/scimax#259]
I am using Scimax on 2 computers (Work -> Linux and home -> Mac). I have my config setup in the user folder as a submodule tracking a particular branch of a private repo. 

Is it necessary to track and sync the following files /folders? 
abbrev_def
projectile-bookmarks.eld
ac-comphist.dat
eshell/ 
recentf/ 

I see the value of syncing projectile-bookmarks.eld, however the remaining do not seem necessary to me. I have all my projects (mostly as git repos) in a single directory and can alternately also use `projectile-discover-projects-in-directory` when needed. However, I am unclear about abbrev_def.  Would appreciate advice.

**Comment by jkitchin** [comment]
I wouldn't think any of those are necessary to track.

**Comment by shrysr** [comment]
Thank you.
