### ISSUE TITLE
Customising scimax-journal.el

### ISSUE THREAD

**Issue by shrysr** [jkitchin/scimax#260]
I'm trying to adapt/improve scimax-journal for my daily journal.  Basically, I had some trouble customising org-journal and want to start with mimicking some of it's featuresd.   Being new to writing lisp, I would be glad for advice on the overall approach.

Am I correct in thinking that I will need to directly modify scimax-journal.el, and adding hooks/modifications in my 'user' folder will be insufficient? 

The following are modifications made so far to `scimax-journal-new-entry`. Essentially : each month has it's own folder, rather than each day, and some text inserts are being done. 

```
(defun scimax-journal-new-entry ()
  "Add new entry to journal.
Add new day if necessary, otherwise, add to current day."
  (interactive)
  (let* ((date (calendar-current-date))
	 (year (elt date 2))
	 (month (format-time-string "%b"))
	 (day (elt date 1))
         (org-file (f-join scimax-journal-root-dir
			   (number-to-string year)
                           (format "%s" month)
			   ;; (format "%02d" day)
			   (format "%s-%s-%02d.org" year month day))))
    (mkdir (f-join scimax-journal-root-dir
		   (number-to-string year)
		   (format "%s" month)
		   ;; (format "%02d" day)
                   )
	   t)
    (find-file org-file)
    (cond
     ((file-exists-p org-file)
      (end-of-buffer)
      ;; (insert (org-insert-heading))
      (insert (format-time-string "\n* %H:%M "))
      (save-buffer))
     (t
      (progn
        (insert (format-time-string "#+TITLE: Entry - %b %d, %Y\n"))
        (insert (format-time-string "\n* %H:%M "))        
        (save-buffer))))))
```

**Comment by jkitchin** [comment]
You do not need to modify scimax-journal.el directly unless you want to. If you just define scimax-journal-new-entry like that in user.el file it will override the definition in scimax-journal.el and become the current one that Emacs knows about. Or you could give it your own name, e.g. sr/scimax-journal-new-entry so it has a distinct different name, and then use that instead.

**Comment by shrysr** [comment]
Thank you for the clarification. I have overwritten the scimax-journal-new entry function, and would prefer this method in order to keep merges with your branch conflict free to the extent possible. 

In any case, it appears that that the problems I faced with org-journal were related to the order of loading the scripts at startup. I have reverted to org-journal for the time being. I was also curious to know whether you use scimax-journal / org-journal / just prefer capturing into an org file?

**Comment by jkitchin** [comment]
I use scimax-journal almost every day. Any time I want to write something, I basically type M-x scimax-journal-new-entry, which always opens the org-file for the current day.

**Comment by shrysr** [comment]
Thank you for sharing your workflow. I agree that a regular writing process makes a great difference to the thought process.  I used a single org file and the date tree capture for ~2 years, and moved over to org-journal about a year ago as it seemed more suitable / efficient for the long run and helped de-clutter the org-agenda. 

As such - there is a PR open for the org-journal package to store files in a folder based division format like in scimax-journal. On further review - it does appear that org-journal has a bunch of features that enhance the results achieved by scimax-journal, thus making my original endeavour of adapting scimax-journal rather unnecessary, especially since I got org-journal working again. 

I will close this issue.

**Comment by jkitchin** [comment]
It does look like there are a lot of cool things in there. If it has some compatible functions I should learn how to use them in scimax-journal.

**Comment by shrysr** [comment]
I think it would certainly add value to integrate org-journal's features into Scimax / scimax-journal. Though my lisp knowledge and skills are (very) nascent at best, I'd be happy to give it a shot and contribute. Please let me know your thoughts.
