### ISSUE TITLE
(add-to-list 'org-modules 'org-habit) not working in user.el after update

### ISSUE THREAD

**Issue by NahsiN** [jkitchin/scimax#261]
Hello, I updated my scimax today and now org-habit is not added automatically upon startup to org-modules. The command `(add-to-list 'org-modules 'org-habit)` is present in my user.el. After startup, I have to call customize-variable, uncheck/check the box by habit and click an Apply for the module to be loaded properly. The same issue persists in both Ubuntu and mac machines.

**Comment by jkitchin** [comment]
I can't think of any reason why scimax would affect this at all. Are there any other messages that would indicate a problem that might prevent user.el from getting loaded?

**Comment by NahsiN** [comment]
Other than
```
error in process sentinel: async-handle-result: /usr/bin/tlmgr exited with status 2
error in process sentinel: /usr/bin/tlmgr exited with status 2
```
there are no other messages. I did manage to fix the problem by replacing `(add-to-list 'org-modules 'org-habit)` with 
```
(require 'org-install)
(require 'org-habit)
```
Now the consistency graph is generated in the agenda.
