### ISSUE TITLE
How do I fix warning kitchingroup-github-id is nil

### ISSUE THREAD

**Issue by Arjay-El** [jkitchin/scimax#263]
" (emacs): ‘kitchingroup-github-id’ is nil. Please set it in c:/scimax//user/preload.el"

I occasionally receive this message and it asks to set it in preload.el which I do not seem to have. Can you suggest a solution to fix the? Thanks for your help. (Do I need preload.el?)

**Comment by jkitchin** [comment]
I have commented out the line causing that. It is something specific for students in my group at the moment.

**Comment by Arjay-El** [comment]
Great, thanks.
