### ISSUE TITLE
Org-ref C-u not providing cite options

### ISSUE THREAD

**Issue by Arjay-El** [jkitchin/scimax#265]
C-u does not call up any options for the type of cite. Another user tries C-c C-u but that did not work for me. Is there another key combo? I am on Win10. Thanks.

**Comment by Arjay-El** [comment]
I was looking at your dft files for an example but I do not see where you call your bibliography type (natbib, bibtex or latexbib). Perhaps I am not calling it correctly. Do you explicitly call out your bibliography formatting type?

**Comment by jkitchin** [comment]
There are a few different ways to do this. I have the default package alist setup to include natbib, and the default pdf process (org-latex-pdf-process )calls bibtex. 

You can also set it in a latex header like:

#+latex_header: \usepackage[numbers,super,sort&compress]{natbib}


There is also a bibtex-dialect variable that can be important (it defaults to bibtex) if you use any biblatex entry types in your bibtex file.

You do have to specify a bibliographystyle if you use bibtex, e.g.

bibliographystyle:unsrt

if you use biblatex, this is another latex header setting

**Comment by jkitchin** [comment]
The output of org-ref-debug is weird. Did this problem go away when you reinstalled scimax?

**Comment by Arjay-El** [comment]
Okay, found it. On my WIN PC, I need to use C-u-enter (I was pushing enter, just trying to call up C-u). The error message remained the same after installation. One last question before I close this: I need to cite "[Author,year]" but none of the options seem to give that. Do I need to switch to bibtex or latexbib for that?

**Comment by jkitchin** [comment]
That is a latex bibliography style you have to set in the org document. Something like:

bibliographystyle:apalike

seems to look that way.
