### ISSUE TITLE
Scimax does not load-states an error with use-package

### ISSUE THREAD

**Issue by Arjay-El** [jkitchin/scimax#266]
I have just started to get this message since I closed scimax a few hours ago. Scimax menus do not load (yahsnippet and Porjectile are there).

Msg:
Error (use-package): scimax-mode/:init: Symbol’s value as variable is void: <<<<<<<

If I check the message buffer, I see this following the loading of custom.el:

Loading c:/scimax/user/custom.el (source)...done
ingesting c:/scimax/scimax-lob/noweb.org
1 source block added to Library of Babel
ingesting c:/scimax/scimax-lob/lob.org
21 source blocks added to Library of Babel
ingesting c:/scimax/scimax-lob/kitchingroup.org
8 source blocks added to Library of Babel
[yas] Prepared just-in-time loading of snippets successfully.
load-with-code-conversion: Symbol’s value as variable is void: <<<<<<<
<noname> is undefined
Mark set [2 times]
<noname> is undefined [3 times]

My PC continues beeping and the bracketed count is now up to [12 times]  (I exit scimax to stop it). Would this have anything to do with the kitchin-group.org change. On a normal load, the message buffer stops after custom.el is loaded, I have not seen these messages before. Any ideas? thanks.

**Comment by jkitchin** [comment]
That looks like there is a merge conflict marker. if you go to a terminal, what does git status output?

You can probably find the file that is a problem with something like this in the scimax dir:

grep --recursive <<<<<<  *

you probably need to resolve those conflicts and the issue will go away.

**Comment by Arjay-El** [comment]
I searched the files but did not find that marker except in packages.el

<<<<<<< HEAD
=======
(use-package kitchingroup
  :ensure nil
  :load-path scimax-dir)

As removing this did not fix the issue and being in the middle of writing something, I just recloned a new installation. I assume something messed up in the updates I did today (24 through melpa and 1 from you (kitchengroup.org).

**Comment by jkitchin** [comment]
That is indeed a merge conflict. There are usually a few sections like:
<<<<<<<HEAD
some stuff
=========
other stuff
>>>>>>> some commit

This would happen if you modified packages.el, and then pulled where the pulled file has changes in the same place. git can't tell which one is the right one and marks the file with the merge conflict.
