### ISSUE TITLE
Error with `xah-dired-rename-space-to-underscore` function also renaming directories not just filename

### ISSUE THREAD

**Issue by JSpenced** [jkitchin/scimax#267]
If the directory name has spaces, this will try to replace them as well and then the directory can't be found so it results in an error.

This should probably just replace the current filename not including directory or extensions.

I was assuming it would work along these lines:
`^\\(.+\\)*(.+)\.(.+)$`
where just in group `\2` above would replace spaces with hyphens.

I am just not sure how to do this in emacs-lisp regex syntax though.

**Comment by JSpenced** [comment]
I figured out that I can correct it using the below code for unix-based filesystems but this would not work for Windows so not sure I should submit a PR.

Also there might be a better way than creating the variable `dired-rename-file-split` but I wasn't sure.
```
(defun xah-dired-rename-space-to-hyphen ()
  "In dired, rename current or marked files by replacing space to hyphen -.
If not in `dired', do nothing.
URL `http://ergoemacs.org/emacs/elisp_dired_rename_space_to_underscore.html'
Version 2016-12-22"
  (interactive)
  (require 'dired-aux)
  (if (equal major-mode 'dired-mode)
      (progn
        (mapc (lambda (x)
		(setq dired-rename-file-split (split-string x "/"))
                (when (string-match " " (car (last dired-rename-file-split)))
		  (setcar (last jj/dired-rename-file-split) (replace-regexp-in-string " " "-" (car (last jj/dired-rename-file-split))))
                  (dired-rename-file x (mapconcat 'identity jj/dired-rename-file-split "/")  nil))
		)
              (dired-get-marked-files))
        (revert-buffer))
    (user-error "Not in dired")))
```

**Comment by jkitchin** [comment]
What do you think of commit a770b6d? It combines everything into one function for this that cycles through spaces, - and _.

**Comment by JSpenced** [comment]
Yes, I think that works great but I also added these lines in after `(revert-buffer)` that go to the next line if only one file is selected and a change did not occur (if a change occurred, it automatically moved to the next line already so `dired-next-line` wasn't needed):

	  (when  (and (eq t jj/dired-rename-file-string-not-matched) (eql 1  (length (dired-get-marked-files))))
	    (dired-next-line 1)
	    )

Since the function above cycles, I think that probably isn't desired but I did notice it clears the marks as soon as you run the function. So if you have multiple files selected, it is hard to cycle through. Does it clear the marks due to the call to revert-buffer?

**Comment by JSpenced** [comment]
I tried to figure out how to keep the marks if multiple files are selected but couldn't find a good solution. I could only think of storing the paths and then using dired-mark-files-regexp, but I wasn't even sure if this would work. Any ideas?

**Comment by jkitchin** [comment]
It does look like you need to store the paths, and then remark them. See commit 35e9b43 for an implementation.

**Comment by JSpenced** [comment]
Okay, I modified it like below to only mark files when more than one is selected (now if you run the command it marks the current file even if it isn't marked in the buffer). But if just one file is marked, it will unmark it so maybe you know a way to check if only one file is operated on whether it is marked by `*` or was just the file at point.

(defun scimax-dired-cycle-space-hyphen-underscore ()
  "In dired, rename current or marked files by cycling spaces->hyphens->underscores.
We only change the filename, not the rest of the path.
Adapted from http://ergoemacs.org/emacs/elisp_dired_rename_space_to_underscore.html."
  (interactive)
  (require 'f)
  (require 'dired-aux)
  (if (equal major-mode 'dired-mode)
      (let ((p (point))
	    (new-names '())
	    (number-marked-files (length (dired-get-marked-files))))
	(progn
	  (mapc (lambda (x)
		  (let* ((path-parts (f-split x))
			 (path-file-name (car (last path-parts))))
		    (cond
		     ;; There is a space, so we switch them all to -
		     ((string-match " " path-file-name)
		      (setcar (last path-parts)
			      (replace-regexp-in-string " " "-" path-file-name)))
		     ;; no spaces, but - gets converted to _
		     ((string-match "-" path-file-name)
		      (setcar (last path-parts)
			      (replace-regexp-in-string "-" "_" path-file-name)))
		     ;; no -, convert _ to spaces
		     ((string-match "_" path-file-name)
		      (setcar (last path-parts)
			      (replace-regexp-in-string "_" " " path-file-name))))

		    ;; now rename the file
		    (dired-rename-file x (apply 'f-join path-parts) nil)
		    ;; and save it so we can remark it at the end
		    (push (apply 'f-join path-parts) new-names)))
		(dired-get-marked-files))
	  (revert-buffer)
	  (when (not (eq 1 number-marked-files))
	    (loop for f in new-names do
		  (dired-goto-file f)
		  (dired-mark nil))))
	(goto-char p))
    (user-error "Not in dired")))

**Comment by JSpenced** [comment]
Okay fixed below:
```
(defun scimax-dired-cycle-space-hyphen-underscore ()
  "In dired, rename current or marked files by cycling spaces->hyphens->underscores.
We only change the filename, not the rest of the path.
Adapted from http://ergoemacs.org/emacs/elisp_dired_rename_space_to_underscore.html."
  (interactive)
  (require 'f)
  (require 'dired-aux)
  (if (equal major-mode 'dired-mode)
      (let ((p (point))
	    (new-names '())
	    (number-marked-files (length (dired-get-marked-files nil nil nil t))))
	(progn
	  (mapc (lambda (x)
		  (let* ((path-parts (f-split x))
			 (path-file-name (car (last path-parts))))
		    (cond
		     ;; There is a space, so we switch them all to -
		     ((string-match " " path-file-name)
		      (setcar (last path-parts)
			      (replace-regexp-in-string " " "-" path-file-name)))
		     ;; no spaces, but - gets converted to _
		     ((string-match "-" path-file-name)
		      (setcar (last path-parts)
			      (replace-regexp-in-string "-" "_" path-file-name)))
		     ;; no -, convert _ to spaces
		     ((string-match "_" path-file-name)
		      (setcar (last path-parts)
			      (replace-regexp-in-string "_" " " path-file-name))))

		    ;; now rename the file
		    (dired-rename-file x (apply 'f-join path-parts) nil)
		    ;; and save it so we can remark it at the end
		    (push (apply 'f-join path-parts) new-names)))
		(dired-get-marked-files))
	  (revert-buffer)
	  (when (not (eq 1 number-marked-files))
	    (loop for f in new-names do
		  (dired-goto-file f)
		  (dired-mark nil))))
	(goto-char p))
    (user-error "Not in dired")))
```

**Comment by JSpenced** [comment]
`(dired-get-marked-files nil nil nil t)` returns `(t file-name)` when just one mark is selected so this works properly. Maybe I should have added a comment.

**Comment by jkitchin** [comment]
Nice! Thanks for the help!
