### ISSUE TITLE
Error (use-package): pydoc/:catch: Required feature ‘pydoc’ was not provided

### ISSUE THREAD

**Issue by brioglade** [jkitchin/scimax#268]

**Comment by jkitchin** [comment]
This probably means there was problem in the melpa installation resulting in pydoc.el being empty in your elpa directory. The solution is probably to delete the pydoc directory in elpa and just reinstall it from melpa.

**Comment by brioglade** [comment]
I delete the file and start scimax,but it does not work.
I download and cover pydoc.el in the directory and it does not work as the
same error.

John Kitchin <notifications@github.com> 于2019年1月24日周四 下午9:14写道：

**Comment by jkitchin** [comment]
This still means that the files in elpa/pydoc* are not correct, and probably one or more of them is either empty or incomplete. It could be what you did was not effective because of a corrupted package in another elpa directory, e.g. in ~/.emacs.d or something.
