### ISSUE TITLE
Cannot insert square bracket characters in elisp mode

### ISSUE THREAD

**Issue by NahsiN** [jkitchin/scimax#269]
Hello, in my user.el I want to assign a hotkey to scimax-ob-ipython-complete-ivy using `(define-key org-mode-map (kbd "M-[") 'scimax-ob-ipython-complete-ivy)` however when using scimax, I cannot insert the [ character. I have to use another editor. This is probably caused by using lispy-mode but is there a way around this while retaining lispy-mode?

**Comment by NahsiN** [comment]
Thanks, I just discovered the gitter channel for such type of questions.

**Comment by jkitchin** [comment]
I would be happy to see the gitter channel used for this!
