### ISSUE TITLE
Turn an org-link into a PDF link?

### ISSUE THREAD

**Issue by Cumol** [jkitchin/scimax#27]
If I have a link to another org file and then I produce a PDF, the PDF will still link to the org file.

Is there a way to turn the org-link into a PDF link given that the linked PDF is in the same folder as the org file linked and has the same name?

**Comment by jkitchin** [comment]
There is almost always a way. you would have to use a filter on links to change what they point to. see http://orgmode.org/worg/exporters/filter-markup.html 

Alternatively, you could make your own custom link with custom export. Here is a really bare bones approach. You would want to put some logic in to check for the existence of a pdf file, for example, and only modify it if it exists.

```
#+BEGIN_SRC emacs-lisp
(org-link-set-parameters "file" :export (lambda (path desc backend)
					  (concat
					   (file-name-sans-extension path)
					   ".pdf")))
#+END_SRC
```
