### ISSUE TITLE
Using (garbage-collect) seems to make Scimax a LOT more snappy

### ISSUE THREAD

**Issue by shrysr** [jkitchin/scimax#273]
I'm experiencing Scimax to be significantly more snappy :- faster cursor movement, buffer loading and even agenda generation, as well as much lower memory utilisation --> after including `(garbage-collect)` at the very end of my configuration. 

Probably worth mentioning that I've also just switched over to an org-mode based configuration with Scimax. However, most of my existing configuration was ported over to an org file, with relatively minor changes (mostly the addition of employing the use-package method). I don't think these changes would result in the above. 

Would be nice to know if you experience the same, and if there is some explanation to it.  This is my user.el file for reference: 

```
;; Adding some external packages like reveal for presentations
(add-to-list 'load-path "~/scimax/user/external_packages/")

;; Load main config
(org-babel-load-file (expand-file-name "sr-config.org" user-emacs-directory))

;; Loading personal config 
(org-babel-load-file (expand-file-name "sr-secrets.org.gpg" user-emacs-directory))

(garbage-collect)
```

**Comment by jkitchin** [comment]
There could be a good reason for that.  In the first line of init.el, I set the `gc-cons-threshold` to be very high, and there is a note that it speeds up the startup by a two seconds. I added a line at the end of init.el to reset it to the default.

**Comment by shrysr** [comment]
Finally found where I came across this: https://github.com/angrybacon/dotemacs/blob/master/dotemacs.org
It is just before the heading  "load .custom.el"

**Comment by jkitchin** [comment]
This seems like a reasonable thing to do. I added it in commit 4314ea1.
