### ISSUE TITLE
Possible to change the lighter of dubcaps-mode in user.el

### ISSUE THREAD

**Issue by JSpenced** [jkitchin/scimax#278]
I want to change dubcaps-mode to not have a lighter so to display an empty string instead of " DC" but I am not sure how to do this since it isn't declared as a variable. Just declared as `:lighter (" DC")` from the init of dubcaps-mode.

**Comment by jkitchin** [comment]
I think you can just add `(diminish 'dubcaps-mode)` to your user.el file.

**Comment by JSpenced** [comment]
Yeah, that worked.
