### ISSUE TITLE
compatibility with emacs 25?

### ISSUE THREAD

**Issue by QikeLi** [jkitchin/scimax#28]
Awesome starter kit!  
I wonder if scimax works well with emacs 25. I just installed everything, but encountered a lot of errors--3362 lines.  Attached are the error messages. 
[errors.txt](https://github.com/jkitchin/scimax/files/691409/errors.txt)

PS: my emacs version is 25.1.1

**Comment by jkitchin** [comment]
yes it should work fine, I use it all the time with emacs.  Those mostly look like warnings that you can ignore. Does anything actually not work?

**Comment by QikeLi** [comment]
Thank you, Prof. Kitchin! Nothing so far.

**Comment by jkitchin** [comment]
I am going to close this then. If you get something that doesn't work, please make a new issue. Thanks,
