### ISSUE TITLE
LibreOffice ODT support

### ISSUE THREAD

**Issue by Arjay-El** [jkitchin/scimax#280]
When I publish to ODT, it does not complete and I see a statement  "LaTeX to MathML converter not available" in the Messages buffer.It  I have the file  LaTexMathML.js on my Win path, I have also used "add-to-list..." to path it yet it still does not seem to find it. Is this the correct conversion tool?
I have a number of equations in latex code blocks. This is what I see in Messages:

org-babel-exp process latex at position 37819...
executing Latex code block...
Code block evaluation complete.
org-babel-exp process latex at position 37971...
executing Latex code block...
Code block evaluation complete.
LaTeX to MathML converter not available.
Formatting LaTeX using verbatim
...
Any suggestions? Thanks.

**Comment by jkitchin** [comment]
what about using dvipng? That will make every equation into an image. See https://orgmode.org/worg/org-tutorials/org-latex-preview.html
