### ISSUE TITLE
Using org-db

### ISSUE THREAD

**Issue by shrysr** [jkitchin/scimax#281]
I've been checking out org-db over the past few days and it looks very interesting. Curious to know how you actually use it beyond jumping to headlines / files?

For example, could this be hooked up to refiling org headlines? Despite active archiving, and using special identifiers like "@" or the like for regularly used headings, it still takes time to generate headlines for refiling.

**Comment by jkitchin** [comment]
I mostly use it to jump to headlines in any org-file that has been indexed. that is bound for me to "f12 jh", and I probably use it a dozen times a day to jump around or find old things. I have a few thousand org files from various projects, and org-db is mostly a performant cache. 

I don't use it to jump to links much, mostly because it is slow. I wrote that to find all org files that had a particular cite link, for example.  I use the other contacts database in scimax more than the one in org-db. For a while I tested the locations idea, but i don't need it very frequently.

**Comment by shrysr** [comment]
Yes, org-db is nice to search through org headlines and it will definitely come in handy as the number of org files grow. Wow, I don't have 1000's of org files yet!  Sometimes, I have to manually exit the index though.

On a parallel note - I was surprised to see that org-rifle also seems to work pretty fast, paired with helm-org-rifle. I hooked it up to the refile command, but this is still not fast enough to be pleasing. The only way I can refile quickly is by using a hydra, and that is to set locations.

**Comment by jkitchin** [comment]
I don't do much refiling, but I guess you could make org-db do refiling too. You would want to add some code to make sure the file hasn't been moved, or the headline deleted somehow.

**Comment by shrysr** [comment]
I will try to explore this. As such my focus has now changed drastically towards reducing my refiling by using org-journal as a daily driver, and using org-brain to consolidate notes of 'better' quality.  This is significantly faster (for now) and seems a lot more useful.

One thing I've found inconvenient so far about org-db is the long delay when Emacs is started fresh and the agenda is called. This is when all the org files are added to the queue.

**Comment by jkitchin** [comment]
Do you call the agenda when emacs starts? I don't think org-db does that. You might add another condition to the org-db-hook-function like (buffer-modified-p) to only add it when the buffer has been changed.

**Comment by shrysr** [comment]
Yes I call the agenda after Emacs starts. I believe as each org file is opened, it is added to the queue. And that takes a second or so. When the agenda is called, all the files are added, which takes a few seconds, after which it does not noticeably occur again. I've generally observed there's always a second or so of delay when the file is added to the queue.  I wonder if it could be run as a separate daemon process in the background?

**Comment by shrysr** [comment]
On a related topic, (I can open a new thread for this question if you advise) --  how do you usually perform a complete text search through your org files / journal files / project files? Especially if they are in different locations and repositories and so on. Do you do this often? 

As mentioned[ in this discussion](https://github.com/bastibe/org-journal/issues/151#issuecomment-477179693) on org-journal - I found grep / ag/ rgrep to be quite fast, but was wondering if there is a streamlined method already defined in Scimax that I am missing

**Comment by jkitchin** [comment]
I don't have anything that searches through all org files. There is a whole hierarchy of things related to swiper/projectile that I sometimes use.

`swiper-all` for all open buffers, `projectile-grep`, `counsel-git-grep`. You might also look in scimax-journal.el for some search things I have tried there .
