### ISSUE TITLE
html-clip-w32.py (ox-clip) causes 'OpenClipboard', 'Access is denied'

### ISSUE THREAD

**Issue by VladimirAlexiev** [jkitchin/scimax#282]
I installed package `ox-clip` but when I try `ox-clip-formatted-copy` I get this error: 
```
Traceback (most recent call last):
  File "c:/my/.emacs.d/elpa/ox-clip-20180306.340/html-clip-w32.py", line 226, in PutToClipboard
    win32clipboard.OpenClipboard(0)
pywintypes.error: (5, 'OpenClipboard', 'Access is denied.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/my/.emacs.d/elpa/ox-clip-20180306.340/html-clip-w32.py", line 267, in <module>
    PutHtml(data)
  File "c:/my/.emacs.d/elpa/ox-clip-20180306.340/html-clip-w32.py", line 41, in PutHtml
    cb.PutFragment(fragment)
  File "c:/my/.emacs.d/elpa/ox-clip-20180306.340/html-clip-w32.py", line 217, in PutFragment
    self.PutToClipboard(html, fragmentStart, fragmentEnd, selectionStart, selectionEnd, source)
  File "c:/my/.emacs.d/elpa/ox-clip-20180306.340/html-clip-w32.py", line 231, in PutToClipboard
    win32clipboard.CloseClipboard()
pywintypes.error: (1418, 'CloseClipboard', 'Thread does not have a clipboard open.')
```

https://stackoverflow.com/questions/53594046/getting-error-pywintypes-error-5-openclipboard-access-is-denied says the reason is that another program is using the clipboard.

I am running [ditto](https://ditto-cp.sourceforge.io/), which is a multi-clipboard manager. If I disconnect it from the clipboard, `ox-clip` works ok. But I have no problem with `ditto` when I use a plain-text copy.

Maybe html-clip-w32.py can be fixed so it doesn't cause such conflict with `ditto`? the above link points to https://stackoverflow.com/questions/101128/how-do-i-read-text-from-the-windows-clipboard-from-python/23285159#23285159, which list other python methods for working with the clipboard.

**Comment by VladimirAlexiev** [comment]
@jkitchin, thanks a lot for `ox-clip`! It's the only package that pastes highlighting ok in both Word and Google Docs, and works both in `org-mode` and any programming language mode.

**Comment by jkitchin** [comment]
You can already customize `ox-clip-w32-cmd` to do this. Just write a new python script that does what you want, and then setq that variable to run your script. Getting text to the clipboard isn't hard though, it is getting html onto the clipboard in the right way so you can paste it later.

It is worth a try, but I am suspicious this is a Windows problem that may not have a fix if ditto is using the clipboard.

**Comment by VladimirAlexiev** [comment]
- posted question https://stackoverflow.com/questions/76175244/how-to-put-formatted-text-on-clipboard-with-python-and-avoid-conflict-with-ditto
- posted bug https://github.com/mhammond/pywin32/issues/2060
- I could use this (https://github.com/sabrogden/Ditto/wiki/Command-Line-Options).
However, html-clip-w32.py already takes 3-4 sec, and the extra `ditto` commands may slow it more
```
Ditto.exe /Disconnect
python html-clip-w32.py
Ditto.exe /Connect
```
- Another alternative as per https://stackoverflow.com/a/71168816/20282178 ([Set-Clipboard documentation](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/set-clipboard?view=powershell-5.1&WT.mc_id=ps-gethelp)):
```
powershell -Command Set-Clipboard -AsHtml # if it reads from stdin
powershell -Command Set-Clipboard -AsHtml -Value "<h1>Heading1</h1>This is <b>bold</b>"
```
I tried the latter and it works: pastes formatted text in Google Docs. But
- the text isn't seen in Ditto (only `HTML format`, then need to use F3 View Full Description)
- pastes empty in a text editor

I tried using `-Append` to set both text and HTML formats. But instead, it concatenates the two `-Value`.

**Comment by VladimirAlexiev** [comment]
Here's my `use-package` setup that avoids the problem. I use two advices:
```elisp
;;;; ox-clip. Copies formatted text from org-mode, or any mode through "htmlize"
;; pip install pywin32 # for module win32clipboard
(use-package ox-clip
  :config
  (defadvice ox-clip-formatted-copy (after beep-and-message activate)
    "It takes a couple seconds, so print a confirmation message and beep"
    (let ((visible-bell nil))
      (beep)
      (message "Copied formatted region to clipboard")))
  (defadvice ox-clip-formatted-copy (around ditto-disconnect-reconnect activate)
    "Fix conflict with `ditto': https://github.com/jkitchin/scimax/issues/282"
    (shell-command "\"C:\\Program Files\\Ditto\\Ditto.exe\" /Disconnect")
    ad-do-it
    (shell-command "\"C:\\Program Files\\Ditto\\Ditto.exe\" /Connect"))
  :bind
  ("C-M-S-w" . ox-clip-formatted-copy))
```
