### ISSUE TITLE
Switching windows makes a cursor that runs animation that highlights the line for a second.

### ISSUE THREAD

**Issue by JSpenced** [jkitchin/scimax#284]
This is less an issue but maybe I disabled the package that does this by accident. I know before I heavily modified scimax theme to use a darker theme that I used to get the line highlighted when switching between windows in a frame. This would highlight the line from black to gray with an animation. I don't know what package did this and maybe I accidentally disabled it because when I go back to your theme. I still don't get this feature. Do you know what I'm talking about and if so what package it was that did this? I tried searching but couldn't figure it out.

**Comment by jkitchin** [comment]
I think that is the beacon package.

**Comment by JSpenced** [comment]
Yup, you are correct. Thanks!
