### ISSUE TITLE
Changing the background color of source code blocks

### ISSUE THREAD

**Issue by shrysr** [jkitchin/scimax#287]
How can I change the background color of the source code blocks?  This is after having disabled the leuven theme and switching to the zenburn theme. I tried a helm-ag search of 'pink' and 'green' in the scimax folder, but did not see anything useful. 

I've tried 👎 

``` emacs-lisp
(defface org-block-begin-line
  '((t (:underline "#A7A6AA" :foreground "#008ED1" :background "#EAEAFF")))
  "Face used for the line delimiting the begin of source blocks.")

(defface org-block-background
  '((t (:background "#FFFFEA")))
  "Face used for the source block background.")

(defface org-block-end-line
  '((t (:overline "#A7A6AA" :foreground "#008ED1" :background "#EAEAFF")))
  "Face used for the line delimiting the end of source blocks.")
```
 This was found at https://orgmode.org/worg/org-contrib/babel/examples/fontify-src-code-blocks.html

**Comment by yantar92** [comment]
Note that `defface` does not override previous font definitions (same with all other `def*` special forms).  The link you provided clearly states that `defface` must be used before requiring org.

Alternatively, you can use `(set-face-background 'org-block "Gainsboro")` to change the existing face, for example. See `info:elisp#Attribute Functions` for more ways to change the defined faces.

**Comment by jkitchin** [comment]
Try something like (set-face-background 'org-block-ipython "green yellow")

**Comment by shrysr** [comment]
>
> Try something like (set-face-background 'org-block-ipython "green yellow")
>

Thank you this is useful to know.

**Comment by shrysr** [comment]
> Note that `defface` does not override previous font definitions (same with all other `def*` special forms).  The link you provided clearly states that `defface` must be used before requiring org.
>
> Alternatively, you can use `(set-face-background 'org-block "Gainsboro")` to change the existing face, for example. See `info:elisp#Attribute Functions` for more ways to change the defined faces.

Thank you for this insight. The suggested command worked and is a good
starting point for me
