### ISSUE TITLE
ox-word should support code snippets (and be released standalone...)

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [jkitchin/scimax#288]
I tend to use `ox-word` a lot when producing documents whose final destination is administration : those people insist on editable documents (therefore no PDF) but can barely use Microsoft Word and nothing else (computer literacy is *extremely* low in those spheres : suggesting them learning `emacs` would amount to *lèse-majesté*...).

In this documents, I need to report tables and figures, well handled by `ox-word`, as well a bibliographic references (which are the *forte* of `ox_word`). However, I also need to be able to  quote code used in the analyses I report (usually in appendices). In the current version of `ox-word`, code snippets are numbered as figures and listed as such.

Could they be handled by `ox-word` as a distinct category ?

I would also suggest to release `ox-word` as a standalone `melpa` package : `scimax` is a bit of a daunting proposition, and my current kludge (have the `scimax` git tree somewhere in my directory, with `ox-word.el` symlinked somewhere in my `.emacs.d/elpa/` directory) is not something I could recommend...

**Comment by dangom** [comment]
The *problem* of installing pieces of Elisp code from different sources in the current `Date.getYear()` can be considered solved with tools such as [Borg](https://github.com/emacscollective/borg), [straight.el](https://github.com/raxod502/straight.el), [Quelpa](https://github.com/quelpa/quelpa), [el-get](https://github.com/dimitri/el-get), etc.

Here's an install directive for `ox-word` using a combo of use-package & straight, for example:

```elisp
(use-package ox-word
  :after (:all org-ref ox)
  :demand t
  :straight (ox-word :type git
                     :host github
                     :repo "jkitchin/scimax"
                     :files ("ox-word.el")))
```

Considering your issue with the docx export, could you perhaps provide a minimal document that would produce a correct LaTeX PDF (correctly numbered code snippets) but fails to do so for Word?

**Comment by jkitchin** [comment]
ox-word is just using pandoc behind the scenes from a latex export. The key is probably as @dangom suggested, first to figure out what latex is required to get what you want, and then to see what is required from org-mode to get it. My src-blocks are not numbered in this export, so I don't know what you are doing to get that. some examples might be helpful. pull-requests on these features are of course welcome.
