### ISSUE TITLE
Using scimax with virtual environments

### ISSUE THREAD

**Issue by peteWT** [jkitchin/scimax#289]
Hi,

Thanks immensely for scimax! I am wondering if you could give some best practice guidelines for working with virtual environments?

I as because I have started to use pipenv. After having installed jupyter using pipenv,  if I activate the environment before opening my `.org` file jupyter is found and all is well. If I don't activate the virtual environment, jupyter is not found (as I don't have it installed on system python).

This seems a little clunky to me. Any suggestions would be most welcome.

Thank you!

**Comment by jkitchin** [comment]
I don't use virtualenvs myself, so I don't have a lot of experience with them. Some ideas are to look into directory or file local variables, which could be used to load the virtual environments when you open the file. You could also look into something like elpy or one of the emacs packages for using virtual environments.

**Comment by roblem** [comment]
Not sure if this is best practice, but it works for me:

This is at the very top of my `scimax/user/user.el` file
```
;; pyvenv setup
(require 'pyvenv)
(setenv "WORKON_HOME" "~/anaconda/envs/")
;; python36 is the virtual environment I want to activate
(setq pyvenv-workon "python36")
(pyvenv-mode 1)
```

**Comment by roblem** [comment]
The way of starting the virtual environment I outline above in https://github.com/jkitchin/scimax/issues/289#issuecomment-481794211 lately fails to work properly.  Additionally, I get error #211.  

While `pyvenv` seems to start the `python36' virtual environment that is recognized in the menu bar of emacs it fails to apply to the current buffer.  So to get around this I now set the virtual environment before starting scimax using this script:
```bash
#!/bin/bash
source $HOME/anaconda/bin/activate python36
emacs -q -l /path/to/scimax/directory/scimax/init.el $@
```
also, if I continue to include the pyenv setup code in `user.el` you can switch virtual environments on the fly and things work.

Note this also addresses #211.
