### ISSUE TITLE
ox-clip package install doesn't install html-clip-w32.py

### ISSUE THREAD

**Issue by notuntoward** [jkitchin/scimax#29]
I installed the melpa ox-clip package but when I select a region of an org mode file and run

    M-x ox-clip-formatted-copy

I get the error message

    python: can't open file 'c:/Users/scott/OneDrive/scotto/.emacs.d/elpa/ox-clip-20161106.823/html-clip w32.py': 
    [Errno 2] No such file or directory
    Quit

The documentation says that html-clip-w32.py will be installed on Windows but it isn't in my case. I'm using windows 10 and emacs 25.1.1

**Comment by jkitchin** [comment]
That could be the case. I just pushed a commit that should fix that. Let me know if it works. Thanks for reporting.

**Comment by notuntoward** [comment]
Thanks.  After the python script is installed, but there's still a module problem.  This is what I see when I select an org file region and run ox-clip-formatted-copy:

    Traceback (most recent call last):
      File "c:/Users/scott/OneDrive/scotto/.emacs.d/elpa/ox-clip-20170108.1348/html-clip-w32.py", line 11, in <module>
        import win32clipboard
    ModuleNotFoundError: No module named 'win32clipboard'

**Comment by jkitchin** [comment]
try:

pip install pywin32
