### ISSUE TITLE
Running scimax as daemon?

### ISSUE THREAD

**Issue by Cumol** [jkitchin/scimax#290]
I am trying to use scimax as daemon and I have been getting some errors when running it.

Here are some:
`Error: (error "Package ‘help-fns+-’ is unavailable")`
```
Error enabling Flyspell mode:
(/usr/local/bin/hunspell exited with signal Trace/BPT trap: 5)
Starting new Ispell process /usr/local/bin/hunspell with en_US dictionary...
Error enabling Flyspell mode:
(/usr/local/bin/hunspell exited with signal Trace/BPT trap: 5)
1 src block added to Library of Babel
ingesting /Users/muadabdelhay/cloud/scimax/scimax-lob/lob.org
Starting new Ispell process /usr/local/bin/hunspell with en_US dictionary...
Error enabling Flyspell mode:
(/usr/local/bin/hunspell exited with signal Trace/BPT trap: 5)
Starting new Ispell process /usr/local/bin/hunspell with en_US dictionary...
Error enabling Flyspell mode:
(/usr/local/bin/hunspell exited with signal Trace/BPT trap: 5)
21 src blocks added to Library of Babel
ingesting /Users/muadabdelhay/cloud/scimax/scimax-lob/kitchingroup.org
Starting new Ispell process /usr/local/bin/hunspell with en_US dictionary...
Error enabling Flyspell mode:
(/usr/local/bin/hunspell exited with signal Trace/BPT trap: 5)
Starting new Ispell process /usr/local/bin/hunspell with en_US dictionary...
Error enabling Flyspell mode:
(/usr/local/bin/hunspell exited with signal Trace/BPT trap: 5)
```

When I try opening a project or file inside a frame, I get the following error:
```
Error enabling Flyspell mode:
(/usr/local/bin/hunspell exited with signal Trace/BPT trap: 5)
Starting new Ispell process /usr/local/bin/hunspell with en_US dictionary...
Error enabling Flyspell mode:
(/usr/local/bin/hunspell exited with signal Trace/BPT trap: 5)

```
Flyspell doing troubles again...

When editing code (for example R using ESS) my minibufer is constantly cluttered with these messages:
`
Error running timer ‘ac-show-menu’: (wrong-type-argument popup [cl-struct-popup 1113 26 1 0 10 nil 1 [#<overlay from 1119 to 1119 in *R:warm-sensitive*> #<overlay from 1120 to 1120 in *R:warm-sensitive*> #<overlay from 1121 to 1121 in *R:warm-sensitive*> #<overlay from 1122 to 1122 in *R:warm-sensitive*> #<overlay from 1123 to 1123 in *R:warm-sensitive*> #<overlay from 1124 to 1124 in *R:warm-sensitive*> #<overlay from 1125 to 1125 in *R:warm-sensitive*> #<overlay from 1126 to 1126 in *R:warm-sensitive*> #<overlay from 1127 to 1127 in *R:warm-sensitive*> #<overlay from 1128 to 1128 in *R:warm-sensitive*>] (keymap (mouse-5 . ac-mouse-5) (mouse-4 . ac-mouse-4) (down-mouse-1 . ac-ignore) (mouse-1 . ac-mouse-1) (19 . ac-isearch) (16 . ac-previous) (14 . ac-next) (13 . ac-complete) keymap (C-up . ac-quick-help-scroll-up) (C-down . ac-quick-help-scroll-down) (67108927 . ac-help) (M-f1 . ac-persist-help) (f1 . ac-help) (up . ac-previous) (down . ac-next) (27 keymap (57 . ac-complete-select-9) (56 . ac-complete-select-8) (55 . ac-complete-select-7) (54 . ac-complete-select-6) (53 . ac-complete-select-5) (52 . ac-complete-select-4) (51 . ac-complete-select-3) (50 . ac-complete-select-2) (49 . ac-complete-select-1) (16 . ac-quick-help-scroll-up) (14 . ac-quick-help-scroll-down) (67108927 . ac-persist-help) (112 . ac-previous) (110 . ac-next) (9 . auto-complete)) (13 . ac-complete) (tab . ac-expand) (9 . ac-expand)) nil 0 ac-candidate-face ac-candidate-mouse-face ac-selection-face popup-summary-face 1 0 nil t t 0 0 0 0 nil 10 nil nil nil])`

Any idea how to fix it?

**Comment by jkitchin** [comment]
The first error  about`help-fns+-` is unusual, there is a help-fns+.el in scimax that it should be able to load, unless that file has been damaged somehow.

The the second one, I guess you have a problem with the hunspell installation. what happens when you run hunspell at the command line?

**Comment by Cumol** [comment]
Running hunspell in the command line give this output:

```
dyld: Library not loaded: /usr/local/opt/readline/lib/libreadline.7.dylib
  Referenced from: /usr/local/bin/hunspell
  Reason: image not found
Trace/BPT trap: 5
```

**Comment by jkitchin** [comment]
that seems pretty clear; you are missing a library. I guess this is related to a homebrew update that maybe changed libreadline? maybe you can try upgrading hunspell.

**Comment by Cumol** [comment]
Upgrading bash and hunspell solved that issue.

The other issues are still present.

**Comment by jkitchin** [comment]
if you don't use autocomplete, maybe you can disable that. I can't think of a scimax reason for that error, it looks related to autocomplete.

**Comment by Cumol** [comment]
I tested it as described here: https://github.com/jkitchin/scimax/issues/201#issuecomment-387403386 and disabled auto-complete for ess-mode-hook and didn't get that weird behavior. But it seems like I need to add (auto-complete-mode -1) to every hook that ESS offers.

How do I achieve disabling auto-complete everywhere with scimax?

Should I file an issue for auto-complete about this?

**Comment by jkitchin** [comment]
Maybe try `(setq ess-use-auto-complete nil)`.

ess-use-auto-complete is a variable defined in `ess-custom.el'.
Its value is t
