### ISSUE TITLE
Scimax hotspot: error with helm-source-recentf

### ISSUE THREAD

**Issue by shrysr** [jkitchin/scimax#291]
When I start up Scimax - I am unable to use hotspots as the first command.  The error message is "mapcar: Symbol’s value as variable is void: helm-source-recentf". 

However, if I first do a switch buffer (mapped to helm-mini) and then call hotspots - it works as expected. When I try the switch buffer command first, I notice an extra message saying clearing up recent files. 

I would appreciate advice in debugging this. I've tried toggle debug on error and can provide the output if required.

Relevant configuration: 
Sources for helm :
```
(setq helm-mini-default-sources '(helm-source-buffers-list
                                  helm-source-recentf
                                  helm-source-bookmarks
                                  helm-source-bookmark-set
                                  helm-source-buffer-not-found))

(setq helm-buffers-list-default-sources '(helm-source-buffers-list
                                          helm-source-recentf
                                          helm-source-bookmarks
                                          helm-source-bookmark-set
                                          helm-source-buffer-not-found))
```
Scimax hotspot config: 

```
(setq scimax-user-hotspot-commands
      '(("Agenda All" . (lambda () (org-agenda "" "a")))
        ("Agenda Office" . (lambda () (org-agenda "" "o")))
	("Mail" . (lambda ()
                    (if (get-buffer "*mu4e-headers*")
                        (progn
                          (switch-to-buffer "*mu4e-headers*")
                          (delete-other-windows))
                      (mu4e))))
        ("Bookmarks" . (lambda () (helm-source-bookmarks)))
        ("Reload Scimax babel" . (lambda () (org-babel-load-file (expand-file-name "sr-config.org" user-emacs-directory))))
        )
      )

(setq scimax-user-hotspot-locations
      '(
        ("CV Org" . "~/org_cv/CV_Shreyas_Ragavan.org")
        ("scd - scimax dir" . "~/scimax/" )
        ("scu - scimax user dir" . "~/scimax/user/")
        ( "sco - scimax org conf" . "~/scimax/user/sr-config.org")
        ("blog" . "~/my_org/blog-book.org")
	("github" . "~/my_gits/")
        ("project" . "~/my_projects/")
        ("cheatsheet" . "~/my_projects/ds_cheatsheets/")
        ("passwords" . "~/my_org/secrets.org.gpg")
        ("references" . "~/Dropbox/bibliography/references.bib")
        )
      )
```

**Comment by jkitchin** [comment]
This sounds like something is not getting autoloaded. That variable is defined in helm-for-files.

Maybe you can solve this by adding this to your init?

`(require 'helm-for-files)`

**Comment by shrysr** [comment]
Thank you! That worked. 
I'd love to know the approach with which you found that the variable was defined in helm-for-files?

**Comment by jkitchin** [comment]
Once the command works, I just did C-h v helm-source-recentf and the help page that comes up shows you where it is defined. Otherwise I would have done something as mundane as grep the helm directories. The key observation is that it worked after running some other helm command, which probably did the required autoload.

**Comment by shrysr** [comment]
Thanks John. That was helpful. I will close the issue.
