### ISSUE TITLE
Customizing scimax

### ISSUE THREAD

**Issue by anthrolisp** [jkitchin/scimax#292]
I'm trying to decide it is easier 1) to add a custom layer to scimax, or 2) to add it my load path and just require what is wanted.

### add a custom layer to scimax
if i choose to do this, and want to change the theme and tell emacs where my agenda files are, etc. do i do that by creating a user.el file in the user directory?

### add it my load path and just require what is wanted
if i choose this method, if there any easy to select desired packages in one file (by commenting or uncommenting)?

Thanks in advance!

**Comment by jkitchin** [comment]
you can change the theme in user.el probably something like (load-theme 'your-theme) will do it. That is also where you could define your agenda variables, etc. Alternatively just put a line in user.el that loads the file where you already have this defined.

Most packages are loaded from scimax/packages.el that is the place you could comment/uncomment.

**Comment by anthrolisp** [comment]
Thank you!!

One more quick question: which file in the "task" capture template stored? I'd like to change which file (~/.notes) that it save it in. Thank you again!!

**Comment by jkitchin** [comment]
I don't think that is stored anywhere in scimax. I think you just customize the variable `org-default-notes-file`
