### ISSUE TITLE
Indentation in ipython org-mode

### ISSUE THREAD

**Issue by alaskamike** [jkitchin/scimax#293]
I am trying to write python code in org-mode.  Is there a way to get the code to indent for function blocks?  Right now I have to hit the space key 4 times to indent each line.  Thanks.

**Comment by jkitchin** [comment]
if you use ipython blocks, they should indent automatically. In a python block tab works for me.

**Comment by alaskamike** [comment]
John -
My mistake. It's working for me now.  Thanks for a great emacs
implementation!

Mike

**Comment by alaskamike** [comment]
So, I spoke too soon.  The issue I'm seeing is with evil.  Indentation works fine with the base scimax, but when I enable scimax-evil (require 'scimax-evil) it no longer indents in ipython, nor allows me to tab in python source blocks.  Any idea what I need to tweak to run evil and still have indentation?

**Comment by jkitchin** [comment]
I am not sure. If you type C-h k return what do you get? Mine is bound to (newline-and-indent). maybe evil has changed that. scimax-evil is pretty short, maybe you can see which package in particular is doing it, there are only three packages loaded in it.

**Comment by alaskamike** [comment]
Here's what I get:
<return> runs the command newline-and-indent (found in org-mode-map),
which is an interactive compiled Lisp function in `simple.el'.

(newline-and-indent)

For more information check the manuals.

Insert a newline, then indent according to major mode.
Indentation is done using the value of ‘indent-line-function’.
In programming language modes, this is the same as TAB.
In some text modes, where TAB inserts a tab, this command indents to the
column specified by the function ‘current-left-margin’.



I also checked for tab, and got this:

<return> runs the command newline-and-indent (found in org-mode-map),
which is an interactive compiled Lisp function in `simple.el'.

(newline-and-indent)

For more information check the manuals.

Insert a newline, then indent according to major mode.
Indentation is done using the value of ‘indent-line-function’.
In programming language modes, this is the same as TAB.
In some text modes, where TAB inserts a tab, this command indents to the
column specified by the function ‘current-left-margin’.


I haven't had a chance to dig through the code to find the problem,
but I think it is more of an evil problem than a scimax problem.  I've
also learned that C-c ' opens the source block into a separate code
buffer, and indenting works fine there, so that may be my way ahead.
Thanks.
