### ISSUE TITLE
How to use Python 3 by default?

### ISSUE THREAD

**Issue by DiogoFerrari** [jkitchin/scimax#294]

**Comment by domingoUnican** [comment]
Maybe what you can do is to create a pyenv for python 3. You can do it using the command
pyvenv-create inside emacs.

**Comment by DiogoFerrari** [comment]
That does not work. I use a venv with python 3.6 and the only jupyter kernel for that ve is python3. But the ipython code blocks use python 2.7. (I am using Ubuntu and emacs 26)

**Comment by jkitchin** [comment]
This would by my approaches, in order of preference.

1. Install python3 so it is the system default.
2. Customize `ob-ipython-command` to launch a python3 version of ipython
3. Customize `org-babel-python-command` to launch the python3 of your choice
4. this doesnt' make it default, but you can use :python /path/to/python3 on a per python block basis I think, and probably set it as a generic header in the file..

**Comment by DiogoFerrari** [comment]
The only missing piece was the `ob-ipython-command`. Now it is working fine. Thank you!

An unrelated topic: I noticed a JSON error in the upstream version of ob-ipython [see here](https://github.com/gregsexton/ob-ipython/issues/210) caused by an unexpected error message in the shell. Maybe it will come up here, so it may be good to be aware of.

**Comment by DiogoFerrari** [comment]
... and as I predicted, the JSON error occurred. The problem is that any warning that happens in the shell command produces a JSON readtable error in the .org file. It happens when using `#+INCLUDE:`, for instance. 

Setting `ob-ipython-command` to `ipython3` does not help because it causes some warnings in the shell (with python 3.6.1), which results in JSON readtable error. 

The solution I found was to let `ob-ipython-comman` to `jupyter` to use the jupyter console, but modify this function below to include the argument `"--kernel=python3"`. It is a provisory solution, but make it possible to use ob-ipython (upstream version) in combination with your enhancements.

```
(defun ob-ipython--kernel-repl-cmd (name)
  (list ob-ipython-command "console" "--simple-prompt" "--existing" "--kernel=python3"
        (ob-ipython--kernel-file name)))
```

**Comment by jkitchin** [comment]
Can you give me mwe org file that causes the json warning? I never see this issue my self.

**Comment by DiogoFerrari** [comment]
Here is a mwe:

```
#+TITLE:  title

#+INCLUDE: tmp2.org

* A section
#+BEGIN_SRC ipython :session tmp :exports both :results output
print("ok")
#+END_SRC
```

I am using
- Org mode version 9.0.9
- Ubuntu 18.04.2
- GNU Emacs 26.2 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.30)
- Python 3.6.8
- IPython 7.5.0 
- Jupyter console 5.2.0

**Comment by roblem** [comment]
I have good experiences on scimax using anaconda python (rather than the system's python) and `pyvenv` on both Ubuntu and Fedora.  I put this code in my `user.el` near the top:
```emacs
;; pyvenv setup
(require 'pyvenv)
(setenv "WORKON_HOME" "~/anaconda/envs/")
(setq pyvenv-workon "python36")
```
