### ISSUE TITLE
Cannot start jupyter ipython kernel after latest update

### ISSUE THREAD

**Issue by singletS** [jkitchin/scimax#295]
Hello,
After a recent Anaconda update, ob-ipython cannot successfully start a kernel.  ob-ipython-debug shows
```
Traceback (most recent call last):
  File "/home/ssinglet/src/scimax/ob-ipython-upstream/client.py", line 60, in <module>
    c = create_client(args.conn_file)
  File "/home/ssinglet/src/scimax/ob-ipython-upstream/client.py", line 43, in create_client
    cf = find_connection_file('emacs-' + name)
  File "/home/ssinglet/anaconda3/lib/python3.7/site-packages/jupyter_client/connect.py", line 218, in find_connection_file
    raise IOError("Could not find %r in %r" % (filename, path))
OSError: Could not find 'emacs-ipython-8402d47be67fc791e89eed060c048ae4' in ['.', '/home/ssinglet/.local/share/jupyter/runtime']
```
Current jupyter/ipython environment:
```
$ jupyter --version
jupyter core     : 4.5.0
jupyter-notebook : 6.0.0
qtconsole        : not installed
ipython          : 7.6.1
ipykernel        : 5.1.1
jupyter client   : 5.3.1
jupyter lab      : 1.0.2
nbconvert        : 5.5.0
ipywidgets       : 7.5.0
nbformat         : 4.4.0
traitlets        : 4.3.2

$ python --version
Python 3.7.3
```
Reverting to  jupyter 4.4.x, everything works fine. The location of the kernel runtime file has changed in the new version, but I don't think this is the problem.  

Can someone verify and/or offer a suggestion to fix?  Thanks.

**Comment by singletS** [comment]
It turns out the conda package dependencies for jupyter (specifically jupyter_console) had a glitch if using the conda-forge jupyter channel in a base python3.7 environment.  Updating jupyter_console solved the problem.

**Comment by jkitchin** [comment]
Thanks for the report, and the solution!
