### ISSUE TITLE
Something can not be completed

### ISSUE THREAD

**Issue by brioglade** [jkitchin/scimax#296]
Warning (emacs): No wkhtmltoimage found. Either set ‘ob-ipython-html-to-image-program’ to the location, or go to https://wkhtmltopdf.org/downloads.html to get and install it.
Error (use-package): pydoc/:catch: Required feature ‘pydoc’ was not provided
Error (use-package): Failed to install ivy-xref: https://melpa.org/packages/ivy-xref-20180821.1211.el: Not found
Error (use-package): Cannot load ivy-xref

**Comment by jkitchin** [comment]
The first one is a warning about an optional feature.

Probably you somehow got a faulty pydoc package from melpa and it is empty. You will have to delete the elpa/pydoc files and reinstall it.

The rest mean you need to run M-x package-refresh-contents or something like that; your package archives are out of date.

**Comment by brioglade** [comment]
@jkitchin  Thank you very much.

**Comment by jkitchin** [comment]
This should be something like `(setq ob-ipython-html-to-image-program "C:\Program Files\wkhtmltopdf")`

that path looks suspiciously like a directory, and not an actual executable though.

**Comment by brioglade** [comment]
When I run M-x package-refresh-contents  2-3 times,reopen emacs an error occur:
package-read-archive-contents: Wrong type argument: listp, <html>
 Before that saying that can not refresh elap archive.

**Comment by jkitchin** [comment]
> package-read-archive-contents: Wrong type argument: listp, html 
probably means a package archive is contaminated. Check the contents of scimax/elpa/archives/*/archive-contents. If any of them don't look like regular lisp code you can just delete them.

You can ignore this:
> scimax-journal.el: Obsolete name arg "scimax-journal" to constructor pcache-repository

You can also ignore this
> command-line-normalize-file-name: Args out of range: "", 1
it is from a small bug in scimax.sh or the script you are calling scimax from I think. I thought it was fixed, but I guess not.
