### ISSUE TITLE
Bad request

### ISSUE THREAD

**Issue by domingoUnican** [jkitchin/scimax#297]
Dear all,
Maybe it is a simple issue, but auctex is not installed anymore.
Everytime that I try to open emacs, it appears:

Error (use-package): Failed to install tex: https://elpa.gnu.org/packages/auctex-12.1.2.tar: Bad Request
Error (use-package): Cannot load tex

I am working on a Mac os X 10.14.5 with Emacs 26.2.

**Comment by alaskamike** [comment]
Domingo -
Have you tried M-x package-install auctex?

Mike

**Comment by domingoUnican** [comment]
Yes, but the same message appears.

**Comment by alaskamike** [comment]
What TeX program are you using?

**Comment by domingoUnican** [comment]
Well, first of all, thanks for helping.
I am using mactex.

**Comment by alaskamike** [comment]
Is the package installed? You can check with list-packages. list-packages may also have an alternative version. The next thing to try is to manually download the package and install it with package-install-file.

**Comment by domingoUnican** [comment]
I didn't know about package-install-file. It worked! Thanks!
