### ISSUE TITLE
Executing python in org-mode code blocks always outputs None

### ISSUE THREAD

**Issue by zhongnanxu** [jkitchin/scimax#3]
Not sure if this behavior is correct, but it is definitely different than old jmax. Any successfully run python code always outputs "None".

**Comment by jkitchin** [comment]
hm. How recent is your scimax? I added a default header of output pretty
recently (maybe the last day) that should take care of that.  I just pushed
another commit to the template to make output be there too.

In the meantime, add :results output to the header

John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by zhongnanxu** [comment]
Thanks. I've been using jmax so long that I forgot this was needed to bet set...
