### ISSUE TITLE
Error using org-capture

### ISSUE THREAD

**Issue by domingoUnican** [jkitchin/scimax#301]
Dear scimax users,

Have you experienced the following error using org-capture?
`Debugger entered--Lisp error: (void-function org-mks)
  org-mks((("t" "Task" entry (file+headline "" "Tasks") "* TODO %?\n  %u\n  %a")) "Select a capture template\n=========================" "Template key: " (("C" "Customize org-capture-templates") ("q" "Abort")))
  org-capture-select-template(nil)
  org-capture(nil)
  funcall-interactively(org-capture nil)
  call-interactively(org-capture nil nil)
  command-execute(org-capture)
`
Best regards.

**Comment by jkitchin** [comment]
That seems weird, org-mks is defined in org-macs.el. Maybe you have a mixed org-installation?

**Comment by domingoUnican** [comment]
Thanks, that was it.
I added `(add-to-list 'load-path "~/Git_Repositories/scimax/elpa/org-9.2.5")`
