### ISSUE TITLE
Error using org-agenda

### ISSUE THREAD

**Issue by domingoUnican** [jkitchin/scimax#302]
Dear scimax users,

Have you tried to use the org-agenda and add an element?
It appears the following error:
`org-agenda-get-timestamps: Wrong number of arguments: (0 . 0), 2`

**Comment by jkitchin** [comment]
This also suggests some mixed org-installation where the wrong version of this function is getting called. In newer org versions, 0 arguments is fine. What do you get from `M-x org-version`?

**Comment by domingoUnican** [comment]
You are right, the version is

Org mode version 9.1.9 (release_9.1.9-65-g5e4542 @ /Users/gomezd/Git_Repositories/scimax/elpa/org-plus-contrib-20190819/)

Could you help me to solve this issue?

**Comment by domingoUnican** [comment]
Googling for this error,  I added
`(add-to-list 'load-path "~/Git_Repositories/scimax/elpa/org-9.2.5")` and it is solved. Thank you very much!
