### ISSUE TITLE
how to require only ox-manuscript?

### ISSUE THREAD

**Issue by cryoguy** [jkitchin/scimax#306]
How do I require only, say ox-manuscript? 
Emacs kept complaining about scimax-dir etc.  

 `(add-to-list 'load-path "/home/tan/config/emacs/extend/scimax/ox-manuscript")`

**Comment by jkitchin** [comment]
I think you have to define ox-manuscript-user-template-dir as a variable. It can point to any place you have permission to write and make directories.

(setq ox-manuscript-user-template-dir "/tmp/ox-manuscripts")

before you require ox-manuscript. This isn't super optimal, and I will try to make it more independent in the future.

**Comment by cryoguy** [comment]
got it thanks!
