### ISSUE TITLE
SQL source block output in export

### ISSUE THREAD

**Issue by peteWT** [jkitchin/scimax#307]
Hi,

I'd like to  be able to export the nicely org-formatted table returned from a sql source block to a table in html. The following  with and without `:results output drawer` exports the sql but not the resulting table. Outside of scimax the desired behavior is the default. I'm happy to work on a snippet for an sql source block if that would help. Thanks!

```
#+name: Summary
#+BEGIN_SRC sql :engine postgresql :cmdline "-h <host> -U <username> -p 5432 -d <dbname>"
select * from foo;
#+END_SRC


#+CAPTION: Summary for site class across tracts.
#+RESULTS: Summary
| baz        | bing     | bop | beep  |
|---------+-------+------------+-------|
| nickle    | wooden| yep             | 21546 |
| dime      | plastic  | nope          | 14078 |
| quarter  | rock      | nope         | 13760 |
```

**Comment by jkitchin** [comment]
I don't understand the problem you are reporting. I get a table with these settings. 

```
#+begin_src sqlite :db outgoing.db :results value
select course, title from s18 limit 3;
#+end_src

#+RESULTS:
| 10601 | Introduction to Machine Learning (Masters) |
|  1999 | Dissertation Complete                      |
| 10701 | Introduction to Machine Learning (PhD)     |
```
If you aren't getting what you want, what are you getting?

**Comment by peteWT** [comment]
Hi,

I have the same result as you, however when exporting to html, the
representation of the table is suppressed, just the code book shows up.

Thanks!

**Comment by jkitchin** [comment]
You probably need to add ` :exports both` to the src block header then.

**Comment by peteWT** [comment]
Thanks! That was the solution, it was curious to me that the output from ipython blocks was included in the export by default.

**Comment by jkitchin** [comment]
That is probably enabled by default in scimax here https://github.com/jkitchin/scimax/blob/master/scimax-org-babel-ipython-upstream.el#L248
