### ISSUE TITLE
Error loading scimax with no user config: cc-mode? 

### ISSUE THREAD

**Issue by shrysr** [jkitchin/scimax#308]
I have just updated to the latest commit of Scimax, and in the process also revamped my setup to not use a sub-module for my user config (and instead reference a separate repo). I had some trouble installing packages (https://www.reddit.com/r/emacs/comments/cdf48c/failed_to_download_gnu_archive/) and so had to update to Emacs 26.3 as well. 

This error is found with vanilla Scimax though (no user config), and does not occur with vanilla Emacs (scimax config not loaded). 

The backtrace (toggle debug on error) is attached for reference, and appears to be connected to cc-mode. I'm trying to investigate the source, and would appreciate advice.

[backtrace-cc-mode.txt](https://github.com/jkitchin/scimax/files/3652501/backtrace-cc-mode.txt)

**Comment by shrysr** [comment]
Update: I'm having the same problem on a Linux (debian) machine as well as Mac. Have tried disabling the org-babel loading of 'C', but that does not seem to help.

**Comment by jkitchin** [comment]
The only thing that comes to mind is this recent add: https://github.com/jkitchin/scimax/blob/master/scimax-org.el#L1656

If you comment this section out does the problem go away?

**Comment by shrysr** [comment]
Okay, I don't know what exactly happened, but after commenting out this block - scimax did actually load without error and a few more packages were installed in the process. After this, I re-started scimax without commenting out the section above, and it still loaded fine. fwiw: I am also suspecting whether in the process of troubleshooting - perhaps I un-commented a comment statement by mistake.

In any case, the problem appears resolved now on my Linux machine. I will check on my Mac when I get home and close the issue if all is well. 

Thank you very much! It is quite a relief to be able to get back to using the Emacs daemon + client.

**Comment by shrysr** [comment]
Closing the issue as it is resolved on the Mac as well. Thanks again!

**Comment by kadir-gunel** [comment]
Hello, I am having the same error with emacs version 26.3 on mac. I read the whole thread but could not find out which section to comment that @jkitchin mentioned. 
Could you help please ? 
B.R.
