### ISSUE TITLE
Not an Issue: Which module defines the fonts for the org mode headers?

### ISSUE THREAD

**Issue by Arjay-El** [jkitchin/scimax#309]
I am trying to learn how to program fonts in the manner in which you did the headers in org mode (ex. 1st level, large font black, 2nd level, smaller font green etc). I have searched the scimax*.* files but I am probably not recognizing where this is done. Could you point me to the module that sets the headline fonts? Thanks!

**Comment by shrysr** [comment]
I believe this is set via the Leuven theme, and not via Scimax. 
You could also use something like the following to set the font size
```
(custom-set-faces
 '(org-level-1 ((t (:inherit outline-1 :height 1.2))))
 '(org-level-2 ((t (:inherit outline-2 :height 1.1))))
 '(org-level-3 ((t (:inherit outline-3 :height 1.05))))
 '(org-level-4 ((t (:inherit outline-4 :height 1.00))))
 '(org-level-5 ((t (:inherit outline-5 :height .95))))
 )
```

**Comment by jkitchin** [comment]
@shrysr is correct, these are set by the Emacs theme you use.
