### ISSUE TITLE
keybinding conflicts

### ISSUE THREAD

**Issue by QikeLi** [jkitchin/scimax#31]
I use ergoemacs-mode (https://ergoemacs.github.io/). But with scimax, a lot of my ergoemacs keybindings conflict with the ones defined by the packages preinstalled in scimax. Would you please suggest a solution? Thank you!

**Comment by jkitchin** [comment]
Can you just load ergoemacs-mode last, so it redefines the keybindings?

**Comment by QikeLi** [comment]
Thank you, problem solved with your suggestion and redefining some of the conflicted keybindings under *:bind*.
