### ISSUE TITLE
Scimax journal : unable to view previous or next entry 

### ISSUE THREAD

**Issue by shrysr** [jkitchin/scimax#310]
I have recently switched back to using scimax journal as I think the workflow with new functions is more useful to me than org-journal, and the latter has been used for over 2 years. I have set `(setq scimax-journal-root-dir "~/my_org/journal")` : the journal sub-folder contains all my journal files. This is the only customisation so far.

The projectile root would be the parent folder `~/my_org`, and this contains all my org files within which all the journal files are contained in the journal sub-folder. This is so that I have a single repo of all my org files, and easier version control, and also allowing me to `ag` through all my org files.

The problem is that the above setup does not allow me to use `scimax-previous-entry` which throws the error "Wrong type argument: number-or-marker-p, nil". I see that the entries are also not being registered on the calendar, which means that the available journal grep functions would not find the required files. Note: `scimax-open-heading` does work as expected and lists all the headings.

**Comment by jkitchin** [comment]
Did your files move? If so, maybe the cache is just not correct anymore.

You can see what is in the cache with 

`(pcache-get scimax-journal-entries  'entries)`

**Comment by shrysr** [comment]
When I started up scimax-journal initially - the default location was used (and a test entry was created there), after which I changed the path, but the files themselves were not moved after this. It may be worth adding that I use 2 different systems (Mac and Linux) and so `~/` would expand differently.

Running `(pcache-get scimax-journal-entries 'entries)` shows the test entry, but it does not show all the subsequent actual entries (files) either. Also, for example in the output below, you see an entry for 2019-09-28.org, but the previous entry hydra goes from 29th (today) directly to 26th. There are in fact entries for each day from 26th to 29th, but 27th does not show up the cache list at all. As noted earlier, all the headlines in *all* the entries are still available via the headline jump. I thought the cache list feeds that list as well ?

Also: I've just merged to your latest commits - but it does not seem the cache list is getting updated, because the very first test entry in the default location still shows up and the remaining behavior is as described above. Plus as noted, the entry for 27th is missing from the cache.

```
(pcache-get scimax-journal-entries 'entries)
```

```
#+RESULTS:
: #s(avl-tree- [[[nil nil "/Users/shrysr/vc/journal/2019/09/25/2019-09-25.org" 0] [nil [nil nil "/Users/shrysr/my_org/journal/2019/09/29/2019-09-29.org" 0] "/Users/shrysr/my_org/journal/2019/09/28/2019-09-28.org" 1] "/Users/shrysr/my_org/journal/2019/09/26/2019-09-26.org" 1] nil nil 0] (lambda (fname1 fname2) (time-less-p (org-read-date nil t (file-name-base fname1)) (org-read-date nil t (file-name-base fname2)))))
```

**Comment by jkitchin** [comment]
The first thing to check next is if the output of `(scimax-journal-entries)` lists all the files you want to search. If it does then you can manually update the cache with `(pcache-put scimax-journal-entries 'entries (scimax-journal-entries))`.

I just pushed another commit that will allow you do that with `M-x scimax-journal-update-cache`.

I think that adding new files should add entries to the cache automatically if they are getting made from `scimax-journal-open-entry`. If that isn't happening then there is either a bug, or you are making new entries in a way I did not anticipate.

**Comment by shrysr** [comment]
AH! So I've been creating entries using the hydra F12 >> a > j > j  (open today) to create entries, and have not been using the entry option (e) which I saw just now. 

After reloading scimax `(scimax-journal-entries)` seemed to list all the correct files in the path. Next i tried the new M-x function for the cache update and I think the only difference was in the order of the files listed. Now - all the entries i.e files are shown in orange when.

Okay - now the issue is that it seems the order of entries is not correct. I'm not sure how that is so - because each entry was created as described above. For eg: while using previous and next entry : today is the 30th. `scimax-journal-previous-entry` goes to 28th and then to 26th, *but then* does go to 25th. When I move forward `scimax-journal-next-entry` from 25th - I go to 27th instead of 26th. 


```
(scimax-journal-entries)
```

    #s(avl-tree- [[[[nil nil "/home/shrysr/my_org/journal/2019/09/25/2019-09-25.org" 0] [nil nil "/home/shrysr/my_org/journal/2019/09/27/2019-09-27.org" 0] "/home/shrysr/my_org/journal/2019/09/26/2019-09-26.org" 0] [nil [nil nil "/home/shrysr/my_org/journal/2019/09/30/2019-09-30.org" 0] "/home/shrysr/my_org/journal/2019/09/29/2019-09-29.org" 1] "/home/shrysr/my_org/journal/2019/09/28/2019-09-28.org" 0] nil nil 0] (lambda (fname1 fname2) (time-less-p (org-read-date nil t (file-name-base fname1)) (org-read-date nil t (file-name-base fname2)))))

**Comment by shrysr** [comment]
Quick Update: I just tried looking into the `scimax-journal-entries` function - I'm not entirely sure what avl-tree does yet - but I guess this is controlling the order. I was also curious how you found this package. It looks quite interesting.

**Comment by jkitchin** [comment]
It sounds like the cache is some how not correct. The avl-tree is supposed to keep all the entries in a sorted form, and it should get saved by pcache so that is persistent. That way, we just have to find the position of the entry you are in, and then can go forward/backward in order. It is also used to help  find ranges of files for searching etc.  I found it looking for a way to keep a sorted list.

f12 ajj should open a new entry for today, or reopen it if you already created it, and it should be adding it to the avl-tree automatically.

your interest has inspired me to clean this up a little, and improve the documentation in it. hopefully these won't break anything for you though. Let me know if it does.

**Comment by shrysr** [comment]
I have added the latest commits and given it another spin. Indeed, I am quite eager to get this right, as I'm actively using the journal, and am trying to study and use more of existing scimax features. 

I think the TODO listed of an individual journal for each project is a cool idea. As an idea - I've been using [org-projectile](https://github.com/IvanMalison/org-projectile) to capture project tasks + notes into a specified org file, and include only this file in the agenda. It can be made to use a file per Repo and should be possible to customise it to capture a date-tree I guess, and is also very useful to quickly capture an entry from *anywhere* - but direct it into a specified projectile project heading. This may be easier to adapt into scimax.

Coming back to the order of cache entries - I'm afraid it is still not correct for me. However, `scimax-get-list-of-entries` seems to return the correct order, though this still uses `scimax-get-entries` - it appeared to me that the difference is perhaps because of avl-create-tree, versus using the created cache? 

```
(scimax-journal-entries)
```

    #s(avl-tree- [[[[nil nil "/home/shrysr/my_org/journal/2019/09/25/2019-09-25.org" 0] [nil nil "/home/shrysr/my_org/journal/2019/09/27/2019-09-27.org" 0] "/home/shrysr/my_org/journal/2019/09/26/2019-09-26.org" 0] [[nil nil "/home/shrysr/my_org/journal/2019/09/29/2019-09-29.org" 0] [nil nil "/home/shrysr/my_org/journal/2019/10/01/2019-10-01.org" 0] "/home/shrysr/my_org/journal/2019/09/30/2019-09-30.org" 0] "/home/shrysr/my_org/journal/2019/09/28/2019-09-28.org" 0] nil nil 0] (lambda (fname1 fname2) (time-less-p (org-read-date nil t (file-name-base fname1)) (org-read-date nil t (file-name-base fname2)))))

```
(scimax-journal-get-list-of-entries)
```

    ("/home/shrysr/my_org/journal/2019/09/25/2019-09-25.org" "/home/shrysr/my_org/journal/2019/09/26/2019-09-26.org" "/home/shrysr/my_org/journal/2019/09/27/2019-09-27.org" "/home/shrysr/my_org/journal/2019/09/28/2019-09-28.org" "/home/shrysr/my_org/journal/2019/09/29/2019-09-29.org" "/home/shrysr/my_org/journal/2019/09/30/2019-09-30.org" "/home/shrysr/my_org/journal/2019/10/01/2019-10-01.org")


Other things I've tried: 
1. setting scimax-root-journal-dir in preload.el and changing it directly in scimax-journal.el - but I realised that scimax-journal is triggered only when a function is called, so this understandably did not help.

2. Tried modifying scimax-get-previous-entry to use the list from `scimax-journal-get-list-of-entries`, but could not get the lisp right.

**Comment by jkitchin** [comment]
> I have added the latest commits and given it another spin. Indeed, I am quite eager to get this right, as I'm actively using the journal, and am trying to study and use more of existing scimax features.
> 
> I think the TODO listed of an individual journal for each project is a cool idea. As an idea - I've been using [org-projectile](https://github.com/IvanMalison/org-projectile) to capture project tasks + notes into a specified org file, and include only this file in the agenda. It can be made to use a file per Repo and should be possible to customise it to capture a date-tree I guess, and is also very useful to quickly capture an entry from _anywhere_ - but direct it into a specified projectile project heading. This may be easier to adapt into scimax.
> 
> Coming back to the order of cache entries - I'm afraid it is still not correct for me. However, `scimax-journal-get-list-of-entries` seems to return the correct order, though this still uses `scimax-journal-entries` - it appeared to me that the difference is perhaps because of avl-create-tree, versus using the created cache?

It could be that the order it is printed in the tree is not relevant. only the order that the entries are accessed matters. if the list is correct, that suggests it is fine. also if the next/previous navigation is working right that suggests it is right. If that is not right, then I would try updating the cache, that may fix it.

> 
> ```
> (scimax-journal-entries)
> ```
> 
> ```
> #s(avl-tree- [[[[nil nil "/home/shrysr/my_org/journal/2019/09/25/2019-09-25.org" 0] [nil nil "/home/shrysr/my_org/journal/2019/09/27/2019-09-27.org" 0] "/home/shrysr/my_org/journal/2019/09/26/2019-09-26.org" 0] [[nil nil "/home/shrysr/my_org/journal/2019/09/29/2019-09-29.org" 0] [nil nil "/home/shrysr/my_org/journal/2019/10/01/2019-10-01.org" 0] "/home/shrysr/my_org/journal/2019/09/30/2019-09-30.org" 0] "/home/shrysr/my_org/journal/2019/09/28/2019-09-28.org" 0] nil nil 0] (lambda (fname1 fname2) (time-less-p (org-read-date nil t (file-name-base fname1)) (org-read-date nil t (file-name-base fname2)))))
> ```
> 
> ```
> (scimax-journal-get-list-of-entries)
> ```
> 
> ```
> ("/home/shrysr/my_org/journal/2019/09/25/2019-09-25.org" "/home/shrysr/my_org/journal/2019/09/26/2019-09-26.org" "/home/shrysr/my_org/journal/2019/09/27/2019-09-27.org" "/home/shrysr/my_org/journal/2019/09/28/2019-09-28.org" "/home/shrysr/my_org/journal/2019/09/29/2019-09-29.org" "/home/shrysr/my_org/journal/2019/09/30/2019-09-30.org" "/home/shrysr/my_org/journal/2019/10/01/2019-10-01.org")
> ```
> 
> Other things I've tried:
> 
> 1. setting scimax-root-journal-dir in preload.el and changing it directly in scimax-journal.el - but I realised that scimax-journal is triggered only when a function is called, so this understandably did not help.

As long as the `scimax-root-journal-dir` is set before loading scimax-journal it should be fine, so preload should be the place to set that. I would not change it in the el file, it will just make it trickier to merge future changes I think.

> 2. Tried modifying scimax-get-previous-entry to use the list from `scimax-journal-get-list-of-entries`, but could not get the lisp right.

I would not modify this. 1) it should not be needed, and 2) the avl-tree should work for it.

**Comment by shrysr** [comment]
Yes, I guess I also got a sense that the order may not be important. i.e the tree is used to identify the previous and next based on the current entry. Initially it seemed that next entry jump was due to the order of the list.

Okay. I checked out the default scimax fork, and have set the root dir in user/preload.el. 

1. F12 a j j brings me to the entry of today 1st October. 
2. Exit hydra for good measure. 
3. F12 a j p : takes me to 29th, and then 27th , 25th. 
4. exit hydra. And tried next entry (F12 a j n) - goes from 25th, 27th, 29th, 1st.

Updated cache - and tried above steps and got the same behavior.  

F12 a j e : shows me all the entries highlighted in orange (25th to 1st).

Next tried : F12 a j e >> opened 26th and then tried next and previous entries. It still seems to skip an entry. i.e 26th > 28th > 30th. 

For good measure : loaded scimax, with only preload.el (containing only root dir specification) and no other user files. The above behavior was the same. 

Perhaps worth mentioning - org-journal has a function to jump to previous entries. I believe this is done via entries registered on the calendar. i.e if the calendar does not have an entry registered for some reason - it would not jump. I remembered because I had some trouble with a long time ago.

**Comment by shrysr** [comment]
Update: removing root-dir customisation. So I copied the journal folders to the default location ~/vc/journal/  and updated the cache which enabled all the entries. After this - previous/next entry have the same behavior as described above. i.e 1 entry is skipped when moving forward or backward.

**Comment by jkitchin** [comment]
You are right! incf/decf modify variables in place and were getting called twice in those functions so it was skipping things. I think I have just pushed a fix for that. Thanks for reporting that!

**Comment by shrysr** [comment]
Thank you! The previous and next entry commands now appear work as expected now which is quite pleasing. I'm planning to try out further customisation and will keep you posted. fwiw: I was actually trying decipher the increment portion, but then got distracted trying to study avl-tree.. :) It would have been great to help you more constructively, but I have forgotten what little I had learned of lisp during the last foray into scimax-journal several months ago.

**Comment by shrysr** [comment]
I guess I also use the journal as a scratch pad, but additionally as a conventional journal of daily notes/thoughts/reviews etc. I've been using org-projectile as the project-journal /task collector for scimax notebook into a single org file that is included in my agenda. Initially, I was using active date links and the agenda. However, I've realised a cluttered agenda is quite stressful even with constructed filters. Additionally, it seems a required practice to 'archive' done tasks if you don't want to wait forever for agenda generation. So then I tried using inactive date links, creating specific filters in the agenda and so on. At the end of the day - I guess I thought that even if there were a few major themes - it still felt so much more streamlined to capture without constraint into a daily journal file and then refile or transfer elsewhere or even better - leave it there. Clocking tasks seems to be the best solution for time tracking, but then my current issue is how can I clock stuff in my journal files or non-agenda files? Org-projectile has helped here, but I'm still relying a lot on projectile + org id based links.

I was hoping to implement some of these ideas and revert, but I figured sharing them now would be more useful to know your thoughts as well:

1. Ability to transfer/refile a heading from an old entry to today.
   1. Perhaps add some indication in the property of the date created. For example, sometimes I have drafts, half written reports, thoughts, articles etc etc hanging around, and have been plugging these into the journal, and transferring to a better location when they are satisfactorily finished. For eg: most of this response was written on 2nd October, in scimax journal.
2. Refile a heading from any other org file to today's entry or even better - a specified journal entry.
3. org-capture function into today's entry. This should be relatively trivial to setup I guess.
4. Future entries. Eg: I may have a meeting or potential topic I want to look at, but perhaps it is clear that I want to look at this later.
   1. Yes, I understand this can be done via any org file included in the agenda and scheduled, but somehow, it is still difficult many times to select a 'place' for this heading. Using a journal and a single file per day, and optimising on search method/patterns seems more useful for most tasks.
5. Go to previous/next/specific entry and then browse through the headings using the speed keys, with headings getting expanded.
6. More useful leverage of org capabilities from journal files, without including them in the agenda list, eg: clocking, tags, leveraging the properties drawer.
   1. i.e Using the org-agenda to gather TODO's or even search is probably not very efficient for daily journal files because I believe each org file is opened to generate the agenda. There are some workarounds in org-journal for this. i.e agenda integration can be switched on explicitly, and will only include entries with active date stamps. Any heading marked a TODO, is transferred to the current entry, every day (when a new entry is created). i.e I can continue working on mini projects from the journal itself, until I find a place for such projects. The problem with this TODO transfer is particularly when you switch machines. Sometimes, the transferred TODO's disappear or do not translate correctly and are lost. The approach is also not truly conducive in terms of time tracking, and my workaround has been to use a 'created' property with an inactive date.
   2. I was wondering whether one way to use a daily journal, but have individual headings cater to different projects or topics, is to leverage properties?

**Comment by shrysr** [comment]
I guess I also use the journal as a scratch pad, but additionally as a conventional journal of daily notes/thoughts/reviews etc. I've been using org-projectile as the project-journal /task collector for scimax notebook into a single org file that is included in my agenda. Initially, I was using active date links and the agenda. However, I've realised a cluttered agenda is quite stressful even with constructed filters. Additionally, it seems a required practice to 'archive' done tasks if you don't want to wait forever for agenda generation. So then I tried using inactive date links, creating specific filters in the agenda and so on. At the end of the day - I guess I thought that even if there were a few major themes - it still felt so much more streamlined to capture without constraint into a daily journal file and then refile or transfer elsewhere or even better - leave it there. Clocking tasks seems to be the best solution for time tracking, but then my current issue is how can I clock stuff in my journal files or non-agenda files? Org-projectile has helped here, but I'm still relying a lot on projectile + org id based links.

I was hoping to implement some of these ideas and revert, but I figured sharing them now would be more useful to know your thoughts as well:

1.  Ability to transfer/refile a heading from an old entry to today.
    1.  Perhaps add some indication in the property of the date created. For example, sometimes I have drafts, half written reports, thoughts, articles etc etc hanging around, and have been plugging these into the journal, and transferring to a better location when they are satisfactorily finished. For eg: most of this response was written on 2nd October, in scimax journal.
2.  Refile a heading from any other org file to today's entry or even better - a specified journal entry.
3.  org-capture function into today's entry. This should be relatively trivial to setup I guess.
4.  Future entries. Eg: I may have a meeting or potential topic I want to look at, but perhaps it is clear that I want to look at this later.
    1.  Yes, I understand this can be done via any org file included in the agenda and scheduled, but somehow, it is still difficult many times to select a 'place' for this heading. Using a journal and a single file per day, and optimising on search method/patterns seems more useful for most tasks.
5.  Go to previous/next/specific entry and then browse through the headings using the speed keys, with headings getting expanded.
6.  More useful leverage of org capabilities from journal files, without including them in the agenda list, eg: clocking, tags, leveraging the properties drawer.
    1.  i.e Using the org-agenda to gather TODO's or even search is probably not very efficient for daily journal files because I believe each org file is opened to generate the agenda. There are some workarounds in org-journal for this. i.e agenda integration can be switched on explicitly, and will only include entries with active date stamps. Any heading marked a TODO, is transferred to the current entry, every day (when a new entry is created). i.e I can continue working on mini projects from the journal itself, until I find a place for such projects. The problem with this TODO transfer is particularly when you switch machines. Sometimes, the transferred TODO's disappear or do not translate correctly and are lost. The approach is also not truly conducive in terms of time tracking, and my workaround has been to use a 'created' property with an inactive date.
    2.  I was wondering whether one way to use a daily journal, but have individual headings cater to different projects or topics, is to leverage properties?

**Comment by jkitchin** [comment]
> I guess I also use the journal as a scratch pad, but additionally as a conventional journal of daily notes/thoughts/reviews etc. I've been using org-projectile as the project-journal /task collector for scimax notebook into a single org file that is included in my agenda. Initially, I was using active date links and the agenda. However, I've realised a cluttered agenda is quite stressful even with constructed filters. Additionally, it seems a required practice to 'archive' done tasks if you don't want to wait forever for agenda generation. So then I tried using inactive date links, creating specific filters in the agenda and so on. At the end of the day - I guess I thought that even if there were a few major themes - it still felt so much more streamlined to capture without constraint into a daily journal file and then refile or transfer elsewhere or even better - leave it there. Clocking tasks seems to be the best solution for time tracking, but then my current issue is how can I clock stuff in my journal files or non-agenda files? Org-projectile has helped here, but I'm still relying a lot on projectile + org id based links.
> 
> I was hoping to implement some of these ideas and revert, but I figured sharing them now would be more useful to know your thoughts as well:
> 
> 1. Ability to transfer/refile a heading from an old entry to today.
>    
>    1. Perhaps add some indication in the property of the date created. For example, sometimes I have drafts, half written reports, thoughts, articles etc etc hanging around, and have been plugging these into the journal, and transferring to a better location when they are satisfactorily finished. For eg: most of this response was written on 2nd October, in scimax journal.

This is the point of the filename and path: year/month/day/year-month-day.org 

That should be the day it is created. Of course, you can go back and modify any time. at the moment there is no easy way to do last modified time. in emacs you would have to do a save-buffer hook.


> 2. Refile a heading from any other org file to today's entry or even better - a specified journal entry.

I think you do this with `org-refile-targets' if you want to use the org-refile feature. It is slow though with a lot of entries. there could be a journal command to do this more efficiently maybe with the calendar interface. I have 500+ entries, and don't want them open every time!

> 3. org-capture function into today's entry. This should be relatively trivial to setup I guess.

Probably so. I have a few capture templates that I use once in a while. I guess it could have a function to compute today's date and journal file.

What would you capture there? I usually do f12 ajj and start typing. 

> 4. Future entries. Eg: I may have a meeting or potential topic I want to look at, but perhaps it is clear that I want to look at this later.

I think if you use f12 aje you can navigate to a future date to create an entry.

>    
>    1. Yes, I understand this can be done via any org file included in the agenda and scheduled, but somehow, it is still difficult many times to select a 'place' for this heading. Using a journal and a single file per day, and optimising on search method/patterns seems more useful for most tasks.
> 5. Go to previous/next/specific entry and then browse through the headings using the speed keys, with headings getting expanded.

If you always start entries with a headline, this might already be doable I think. If not, it isn't real obvious if you always want to jump to the first headline. Also, for entries that are already open, it isn't obvious you want to move automatically move the point. 

> 6. More useful leverage of org capabilities from journal files, without including them in the agenda list, eg: clocking, tags, leveraging the properties drawer.

I am not sure what you mean here. You can temporarily make a journal agenda that is separate from your regular agenda. 

>    
>    1. i.e Using the org-agenda to gather TODO's or even search is probably not very efficient for daily journal files because I believe each org file is opened to generate the agenda. There are some workarounds in org-journal for this. i.e agenda integration can be switched on explicitly, and will only include entries with active date stamps. Any heading marked a TODO, is transferred to the current entry, every day (when a new entry is created). i.e I can continue working on mini projects from the journal itself, until I find a place for such projects. The problem with this TODO transfer is particularly when you switch machines. Sometimes, the transferred TODO's disappear or do not translate correctly and are lost. The approach is also not truly conducive in terms of time tracking, and my workaround has been to use a 'created' property with an inactive date.

You are correct that making an agenda requires opening and parsing each file. It can be easier/faster to grep for TODO

>    2. I was wondering whether one way to use a daily journal, but have individual headings cater to different projects or topics, is to leverage properties?

Or tags.  You could interweave it all together like this. My

**Comment by shrysr** [comment]
I will revert on the other points. I had a question regarding the agenda generation based on journal files. This does not seem to work for me. Only 2 headlines on 2 different entries are shown and I do not see why those are shown and the others are not. There is no active date on these headlines either.

scimax-journal-agenda-range seems to indicate that scimax journal entries are passed as a list to org-agenda-files. However, the final (org-agenda) command makes the usual agenda selection (C-c a) pop up which makes me need to choose again from the options set in my agenda. My understanding from the script was for eg: f12 a j aw should show me an agenda with last week's journal headlines? I do have sticky agenda enabled, but this persists even with a fresh agenda.

**Comment by jkitchin** [comment]
Hm. this is not working like I thought it would. The right files get passed, but then the agenda is not showing what I thought, and if you refresh that it does seem to show your global agenda. I guess I have some work to do to figure out how to make an agenda based on the past week, and not the current week, for example. That may be a while. It might be worth a new issue to track it.
