### ISSUE TITLE
Fail to download melpa/gnu on windows build

### ISSUE THREAD

**Issue by oren-weiss** [jkitchin/scimax#311]
Downloaded Emacs 26.3 for Windows separately and tried running 
`emacs -q -l path/to/scimax/init.el --debug-init` (although with actual path)

And got the following output:

For information about GNU Emacs and the GNU system, type C-h C-a.
(Shell command succeeded with no output)
Contacting host: orgmode.org:443
gnutls.el: (err=[-50] The request is invalid.) boot: (:priority NORMAL:-VERS-TLS1.3 :hostname orgmode.org :loglevel 0 :min-prime-bits 256 :trustfiles nil :crlfiles nil :keylist nil :verify-flags nil :verify-error nil :callbacks nil)
Failed to download ‘org’ archive.
Contacting host: elpa.gnu.org:443
gnutls.el: (err=[-50] The request is invalid.) boot: (:priority NORMAL:-VERS-TLS1.3 :hostname elpa.gnu.org :loglevel 0 :min-prime-bits 256 :trustfiles nil :crlfiles nil :keylist nil :verify-flags nil :verify-error nil :callbacks nil)
Failed to download ‘gnu’ archive.
gnutls.el: (err=[-50] The request is invalid.) boot: (:priority NORMAL:-VERS-TLS1.3 :hostname melpa.org :loglevel 0 :min-prime-bits 256 :trustfiles nil :crlfiles nil :keylist nil :verify-flags nil :verify-error nil :callbacks nil)
Package refresh done
Failed to download ‘melpa’ archive.
gnutls.el: (err=[-50] The request is invalid.) boot: (:priority NORMAL:-VERS-TLS1.3 :hostname orgmode.org :loglevel 0 :min-prime-bits 256 :trustfiles nil :crlfiles nil :keylist nil :verify-flags nil :verify-error nil :callbacks nil)
Failed to download ‘org’ archive.
gnutls.el: (err=[-50] The request is invalid.) boot: (:priority NORMAL:-VERS-TLS1.3 :hostname elpa.gnu.org :loglevel 0 :min-prime-bits 256 :trustfiles nil :crlfiles nil :keylist nil :verify-flags nil :verify-error nil :callbacks nil)
Failed to download ‘gnu’ archive.
gnutls.el: (err=[-50] The request is invalid.) boot: (:priority NORMAL:-VERS-TLS1.3 :hostname melpa.org :loglevel 0 :min-prime-bits 256 :trustfiles nil :crlfiles nil :keylist nil :verify-flags nil :verify-error nil :callbacks nil)
Package refresh done
Failed to download ‘melpa’ archive.
Setting ‘package-selected-packages’ temporarily since "emacs -q" would overwrite customizations [2 times]
package-compute-transaction: Package ‘diminish-’ is unavailable

**Comment by shrysr** [comment]
I thought it may be helpful to add: 

1. just last night - I deleted the elpa folder on my mac and re-setup scimax from scratch o my Mac and am using Emacs 26.3, if I remember correctly. The packages downloaded and started up without this issue. However, a few days ago - none of the packages would download over several repeated attempts.

2. Just now - I tried deleting the elpa folder on my Debian Linux machine as a test. It took 4 attempts ( 4 times of emacs -q -l ~/scimax/init.el) before which it finally connected. This is running Emacs 26.3 - I did not face the problem of the diminish package being unavailable.

**Comment by oweiss57** [comment]
So as an update, I was able to fix it roughly by downloading gnutls into my emacs\bin folder and it worked decently. The only error message I'm getting now is:
Error (use-package): Failed to install org-plus-contrib: Package ‘org-plus-contrib-’ is unavailable

Which I fixed by downloading directly from the orgmode.org/elpa/
