### ISSUE TITLE
Turn off bindings in scimax-org-babel-ipython.el

### ISSUE THREAD

**Issue by JSpenced** [jkitchin/scimax#312]
There is a defcustom with all the ob-ipython-key-bindings. Is the best way to modify this to define it in the preload.el but I think this will throw an error when it is defined again.

What is the best way to remove some bindings that are conflicting and rebind them to another binding?

Like removing this binding:
```    
("M-s-<return>" . #'scimax-restart-ipython-and-execute-to-point)
```

**Comment by jkitchin** [comment]
Hm. this is tricky. The safest way to do this is in preload.el use something like this and modify/delete as you want.

```
(setq (defcustom ob-ipython-key-bindings
  '(("<return>" . #'newline-and-indent)
    ("C-<return>" . #'org-ctrl-c-ctrl-c)
    ("M-<return>" . (lambda () (interactive) (scimax-execute-and-next-block t)))
    ("S-<return>" . #'scimax-execute-and-next-block)
    ("M-S-<return>" . #'scimax-execute-to-point)
    ("s-<return>" . #'scimax-ob-ipython-restart-kernel-execute-block)
    ("M-s-<return>" . #'scimax-restart-ipython-and-execute-to-point)
    ("H-<return>" . #'scimax-ob-ipython-restart-kernel-execute-buffer)
    ("H-k" . #'scimax-ob-ipython-kill-kernel)
    ("H-r" . #'org-babel-switch-to-session)

    ;; navigation commands
    ("s-i" . #'org-babel-previous-src-block)
    ("s-k" . #'org-babel-next-src-block)
    ("H-q" . #'scimax-jump-to-visible-block)
    ("H-s-q" . #'scimax-jump-to-block)

    ;; editing commands
    ("H-=" . #'scimax-insert-src-block)
    ("H--" . #'scimax-split-src-block)
    ("H-n" . #'scimax-ob-copy-block-and-results)
    ("H-w" . #'scimax-ob-kill-block-and-results)
    ("H-o" . #'scimax-ob-clone-block)
    ("s-w" . #'scimax-ob-move-src-block-up)
    ("s-s" . #'scimax-ob-move-src-block-down)
    ("H-l" . #'org-babel-remove-result)
    ("H-s-l" . #'scimax-ob-clear-all-results)
    ("H-m" . #'scimax-merge-ipython-blocks)
    ("H-h" . #'scimax-ob-edit-header)
    ("H-M-l" . #'scimax-ob-toggle-line-numbers)
    ("s-." . #'scimax-ob-ipython-complete-ivy)
    ("s-/" . #'ob-ipython-inspect)

    ;; the jupyter hydras
    ("H-e" . #'scimax-jupyter-edit-mode/body)
    ("H-c" . #'scimax-jupyter-command-mode/body)

    ;; The hydra/popup menu
    ("H-s" . #'scimax-obi/body)
    ("<mouse-3>" . #'scimax-ob-ipython-popup-command)))
```
(check that for balanced ()).

If you just want to redefine a binding I think you can do it like this:

```
(scimax-define-src-key ipython "M-S-<return>" #'some-new-func)
```

Looking at the way that works you might also be able to just do this in your init file:

```
(define-key org-mode-map "M-S-<return>" #'some-new-func)
```

After scimax has loaded, you can delete an element in ob-ipython-key-bindings with
```
(setq ob-ipython-key-bindings 
      (delq (assoc "M-s-<return>" ob-ipython-key-bindings) ob-ipython-key-bindings))
```

but, this won't delete the keybinding, just the element in the list.

**Comment by JSpenced** [comment]
It seems this works to just set the bindings that I don't want to:
```
(scimax-define-src-key ipython "s-<return>" #'nil)
```
Then if I want I can redefine them however I please. Note that this setting the value to `nil` doesn't if using `define key org-mode-map`.

I like that better than using the preload file I think. I didn't try that solution yet. Any negative to the above?

**Comment by jkitchin** [comment]
I can't think of any downsides to that.

**Comment by JSpenced** [comment]
I realized this only works if you do it after the org file is opened. I tried in a `emacs-startup-hook` and then a `org-mode-hook`. Both it doesn't work, so for now I just wrote a function to reset them. 

It has to be done on every new buffer that I open. Any hook you can think that if I put the function in that it will reset everytime that I'm using org-babel?

If not, I will maybe add it to the preload as suggested above or just use the function.

**Comment by jkitchin** [comment]
It should work in an org-mode-hook. Maybe you have to append it to that variable so it runs last?

**Comment by JSpenced** [comment]
That did the trick!
