### ISSUE TITLE
New install looks for 25.3

### ISSUE THREAD

**Issue by Arjay-El** [jkitchin/scimax#313]
I just did a new install (win10) as I managed to muck up my current config and I see this msg.

Error (use-package): Failed to install dashboard: Package ‘emacs-25.3’ is unavailable
Error (use-package): Cannot load dashboard
Error (use-package): undo-tree/:catch: Required feature ‘undo-tree’ was not provided

Is there a way to upgrade to 25.3 to use Dashboard without breaking anything? Not critical but just asking for a suggestion before I break my new installation.
Thanks

**Comment by jkitchin** [comment]
You could try out https://github.com/m-parashar/emax64/releases/download/emax64-26.2-20190417/emax64-bin-26.2.7z

That is the distribution I am currently working with in windows.

**Comment by Arjay-El** [comment]
thanks
