### ISSUE TITLE
Chaining optional commands with projectile switch to project

### ISSUE THREAD

**Issue by shrysr** [jkitchin/scimax#314]
The current workflow is to switch to a project f12 p p , select a file and then use say ag, or git status. However, quite frequently, I want to search through that project's code or readme, or quickly check the magit status i.e rather than open a file.

How can I chain commands together (perhaps need a hydra?) for optional flow paths like f12 p p v/a/ and other commands?

Observation: f12 p p and say I select a project, but mini-buffer is still open to select a file. Now if I hit f5, which is bound to magit-status - this works and the status pops up, but the mini-buffer to select a file from the project stays open. If I exit the mini-buffer, then the magit status buffer becomes hidden. I recall something somewhat similar seemed possible using helm, like selecting some files using C-spc to perform actions.

**Comment by jkitchin** [comment]
If you look in scimax-ivy, you will see where I have added actions to some things, so I can for example type: f12 p p M-o f 
to select a project to open in finder. In theory I could open a shell there too, but I just found a bug playing with this, and hopefully fixed that.

Here is what that code looks like right now.

(ivy-add-actions
```
 'projectile-completing-read
 '(("b" (lambda (x)
	  (bash x))  "Open bash here.")
   ("f" (lambda (x)
	  (finder x))  "Open Finder here.")
   ("g" (lambda (x)
	  (let ((default-directory x))
	    (magit-status)))  "Magit status")))
```

With this, f12 pp M-o g should open magit status for that project.

**Comment by shrysr** [comment]
Ah! I am yet to touch scimax-ivy. The git function works as desired! Thank you. I will find the definitions to set bash/finder to be per the OS's I use. 

This is very interesting. I have actually been using helm since the start. I'm curious to know why you prefer counsel/ido over helm in general? I've seen discussions about helm being 'heavy' - but personally I have not found any deterioration in performance.

**Comment by jkitchin** [comment]
you can find bash and finder in scimax-apps.el, they should cover the main OSs already.

I used to use helm a lot, and there is a fair bit of helm code in org-ref. Eventually, I found writing ivy code easier than writing helm code, but maybe only by a smidge. I doubt it has much to do with performance, and there are still things helm does that ivy doesn't, like heterogenous collections aren't as easy in ivy as with helm, helm has easier (and built in support) for multiple selections... I probably like pressing tab (helm) more than M-o (ivy), but these are all minor choices in the end, and maybe even configurable.

**Comment by shrysr** [comment]
Thank you for the explanation. I will look deeper into customising helm/ivy. I'm guessing having both around for specific options should not hurt. 

Re: scimax-apps - I use iterm on the mac and xfce-terminal on my i3wm debian as a few examples. I presume I should just redefine these scimax functions with the chosen app in my user config?

**Comment by jkitchin** [comment]
You could define your own similar function in your user config, if you want. 

I am slowly doing things like this:

```
(defun my-new-func (args) ...)
(advice-add 'some-func-to-replace :override #'my-new-func)
```

instead of just monkey-patching functions like I have in the past. This functionally replaces an old function with a new one that does something different, but you can undo it, and if you look at help on the old function, it notes there is advice on it, which makes it easier to see if you changed something.

We could try a defcustom here, maybe as an alist to look up an os specific program.

**Comment by shrysr** [comment]
This approach makes a lot of sense. I've heard the term 'monkey-patching' before, but now I know what it  means :). Just tried advice-add and saw the advice added on help, and was able to remove it as well. I think a defcustom for this would be nice to have for scimax. I've started building a defcustom alist and will revert when I make better sense of how options can be defined.

**Comment by jkitchin** [comment]
I think the best way to do this is to have a way to look up an OS specific command for an app. Then the app functions just have to lookup and run the command.

Which of these do you like better:

```
(defcustom scimax-apps
  '(shell . (("gnu/linux" . "gnome-terminal")
	     ("darwin" . "com.apple.terminal")
	     ("windows-nt" . "%SYSTEMDRIVE%\\Program Files\\Git\\bin\\bash.exe")))
  "List of shell-commands to run to open preferred apps to use on different OSs.")
```
here you have do something like:
`(cdr (assoc system-type (cdr (assoc 'shell scimax-apps)))`

to look up a command.

or

if you just want to set one, something like:

`(setq scimax.bash.gnu/linux "gnome-terminal")`

Then we look up a command like:

`(symbol-value (intern-soft (format "scimax.bash.%s" system-type)))`

either way, some of these app commands take an optional path, and could probably take an optional filename, suggesting a template system might be nice that could be expanded.

**Comment by shrysr** [comment]
The 2nd option appears easier to get done I guess. Personally, I do not think I would end up using defcustom too much and would prefer write a new function in my user config.

However, from my exploration yesterday - the defcustom route looks useful to have and appears to have the potential to list other apps as well. It also makes sense from the point of view of 'scimax as an app' with settings, and is actually convenient for quick modifications.

I was trying to construct something like a list with options actually, but obviously have not gotten far - the syntax for the 2nd list for 'finder' does not seem correct, and I don't know if this would work?

```
(defcustom scimax-user-apps '()
  "List of shell commands to run to open preferred apps to use on different OSs."
  :group 'scimax
  :type '(alist
          :key-type (choice :tag "shell"
			    (choice :tag "gnu/linux"
				    (const gnome-terminal)
				    (const xfce4-terminal)
				    (const lxterm))
			    
			    (choice :tag "darwin"
				    (const "com.apple.terminal")
				    (const "com.apple.iterm2")))
	  (choice :tag "finder"
		  (choice :tag "gnu/linux"
			  (const nautilus)
			  (const thunar ))
		  
		  (choice :tag "darwin"
			  (const "com.apple.finder")
			  (const "com.apple.pathfinder")))))
```
