### ISSUE TITLE
tramp using vanilla scimax : modules not supported 

### ISSUE THREAD

**Issue by shrysr** [jkitchin/scimax#315]
I'm unable to use tramp or sudo edit with vanilla Scimax. The issue is not faced with vanilla Emacs, or even Prelude. 

The error is simply : 'modules not supported', and the command does not complete. I receive no feedback from toggle-debug-on-error

How I use sudo is either using the crux-sudo-edit command or simply C-x C-f /sudo:root@localhost: after which I hit 'tab' which is the point where I get the message about modules. The same error is faced when I try to /ssh:user@host:

**Comment by jkitchin** [comment]
That sounds odd. Is it the same emacs executable that is used with scimax and vanilla Emacs/Prelude?

That error suggests an Emacs executable that is not compiled with module support?

If it is the same executable, then what I would do is launch it with:

`emacs -q /path/to/scimax/init.el`

and then execute that file line by line and see when tramp stops working. that will tell you if it is a scimax configuration or not, and indicate where the configuration is happening.

**Comment by shrysr** [comment]
I think it should be the same executable, because prelude as of now is stored at ~/.emacs.d and so calling 'emacs' would just load prelude. I bind scimax to an alias and call it with emacs -q -l ~/scimax/init.el. I'm doing a apt-get upgrade now and will revert.

**Comment by shrysr** [comment]
Okay! The update is that tramp stops working at (require 'bootstrap) in the init file, with the same message as stated before. I have repeated this procedure now several times.

**Comment by jkitchin** [comment]
You could skip that line then, and instead open scimax/bootstrap.el. I guess it is related to a setting of gnutls maybe? although this should only affect an emacs 26. otherwise that file mostly loads use-package, and a few  libraries at the bottom.

**Comment by shrysr** [comment]
Wow. I have lost count of the hours spent on this! The suggestion regarding gnutls also did not work. Calling tramp-unload-tramp seemed to work after calling bootstrap.el, and then the problem recurred on (require 'packages) and would not get resolved.

What finally seems to have worked is - I re-cloned scimax, installing all the packages from scratch !! Perhaps it was some some issue with the packages. I guess I'll never know. In this painful process I revamped my own Emacs config as well for what it is worth to enable much easier troubleshooting in the future which is probably the only plus point. I will close the issue - but please feel free to add your comments.

**Comment by jkitchin** [comment]
I am glad to hear it worked finally. The solution sure sounds like some issue in the packages, but it seems like an issue of package incompatibility maybe. 

In some cases like this, I have done something like rename elpa to elpa.off and then reload scimax, which will trigger reinstalling and recompiling packages.

That sounds like it could be related to old .elc files that are mixed between versions of emacs perhaps? Sometimes I will just delete all the .elc files to see if that is an issue.

**Comment by shrysr** [comment]
> I have done something like rename elpa to elpa.off and then reload scimax, which will trigger reinstalling and recompiling packages.

Indeed - this is exactly what I did, just in case I faced problems in connecting to melpa, but thankfully it went fine. I used to store my packages in git as well and recently was reading that subtree is a better option than submodule for such a purpose. I have to check this out. 

> That sounds like it could be related to old .elc files that are mixed between versions of emacs perhaps? Sometimes I will just delete all the .elc files to see if that is an issue.

This is possible. As such I updated to 26.3 somewhat recently, and perhaps I did not notice the tramp issue, after facing which I tried to downgrade and even compile from source, but had some trouble with that as well. I will keep this in mind though.

**Comment by seblemaguer** [comment]
For information, it seems to be linked to ZMQ. I am not using scimax but I face the same problem and pinpoint it to this.

**Comment by jkitchin** [comment]
I guess what is happening is a library is getting loaded that wants to use an emacs module, which is a compiled library (https://www.gnu.org/software/emacs/manual/html_node/elisp/Dynamic-Modules.html). But you have to use an emacs compiled to support modules. I don't think it is a scimax problem, it doesn't intentionally use any modules I think, or do anything with tramp.

**Comment by shrysr** [comment]
Thought it may be worth adding here:

Incidentally, along with the other ob-ipython issue - I ran into the dbus + tramp problem as well (again) and just emerged apparently victorious!

However this time - vanilla scimax worked fine. I had been facing this off and on, but I also think the issue was not related to Scimax. After hours of debugging only this - I am not still not exactly sure of the reasons, but I believe in my case it was a combination of something related to to my config of the helm package, and also the way I had defined my auth sources (I'd modified 'defaults' instead of adding 'sources').

Even with the correctly defined auth sources, while using helm - Emacs would sometimes simply freeze just around entering the SSH password or fetching the directories. Neither C-g nor Esc worked, and I had to restart Emacs. counsel-find-file on the other hand has worked well, and even if there is some lag in the connection - I am able to cancel the operation. Perhaps to be fair this laggy behavior of helm is relatively new, and probably worth noting - I recently upgraded all my packages. So I've set helm to be used only for 1-2 functions like bookmarks (for now).

We've discussed helm v/s counsel in #314 I remembered, and I've been using helm till date. As of right now, my observation is that counsel is a wee bit more responsive, and perhaps adding too many sources or config to helm functions like enabling fuzzy matching etc slows helm down and this adversely impacts tramp as well.

> But you have to use an emacs compiled to support modules ...

I'm not sure if Emacs can be compiled with dbus support on a Mac? My impression was that Macs do not support dbus modules.

**Comment by jkitchin** [comment]
Interesting. I haven't seen any issues you describe, and haven't tried anything with dbus.

The original question you asked in #314 has a better answer now; in scimax-ivy I figured out how to use projectile-find-file to find a file, but only insert a link to it without opening the file.
