### ISSUE TITLE
Results drawer not collapse-able

### ISSUE THREAD

**Issue by Cumol** [jkitchin/scimax#319]
Using Emacs26 on OSX catalina.
Plain emacs allows the collapse of results drawers (from executing a source block), scimax does not.

**Comment by jkitchin** [comment]
I don't understand what you mean here.  If I press tab on a results drawer it collapses for me.

**Comment by Cumol** [comment]
when I press tab, it doesn't.
Any idea what I could check to troubleshoot it?

**Comment by jkitchin** [comment]
What does C-h -k tab tell you that tab is assigned to at that position? For me it is bound to org-cycle.

You might try M-x org-cycle there to make sure it is cycling from the command.

**Comment by Cumol** [comment]
It is assigned to org-cycle, but doing M-x org-cycle on it does not hide the collapse the result (usually an image).

I wonder if it has something to do with images.

**Comment by Cumol** [comment]
This seems to be something that is connected to my version of emacs used (?). It is still "scimax-specific" but I noticed that it vanished when I switched to another version of emacs on my linux machine (using this PPA https://github.com/kelleyk/ppa-emacs).

Now the behavior is as expected.

**Comment by Cumol** [comment]
Weird behavior of the `tab` key (still).

I found out that sometimes, and I am not sure exactly what causes it, pressing `tab` on a headline will make it do something weird. Either start a table or do some kind of expansion that I don't understand.

Here is one example:

```
** Example of a
blabla
```
If I hit `tab` on the `f` in the headline, I get this:

```
** Example #+options: 
   f a
blabla
```

If I do `C-h k tab` on the `f` I get :

```
<tab> runs the command yas-expand (found in yas-minor-mode-map), which
is an alias for `yas-expand-from-trigger-key'.

It is bound to TAB, <tab>, <menu-bar> <YASnippet> <Expand trigger>.

(yas-expand &optional FIELD)
```

Running it on any other key in the headline show `org-cycle`

**Comment by Cumol** [comment]
This is caused by yasnippet recognizing `o` and `oo` when I hit tab.

I wonder if there is a way to tell yasnippet to not work inside headlines

**Comment by jkitchin** [comment]
this has bugged me before too. I added some conditional expansion to the snippets that seems to do the right thing. now they should only expand at the beginning of a line.

**Comment by Cumol** [comment]
Just tried it, works well. Thank you :)
