### ISSUE TITLE
org-toggle-latex-fragment is obsolete in Org 9.3

### ISSUE THREAD

**Issue by AKielhorn** [jkitchin/scimax#320]
I'm using Org mode from git and recently I get the following warning:

src/Emacs/scimax/scimax-org-latex.el:Warning: ‘org-toggle-latex-fragment’ is
    an obsolete function (as of Org 9.3); use ‘org-latex-preview’ instead.
src/Emacs/scimax/scimax-org-latex.el:Warning: ‘org-toggle-latex-fragment’ is
    an obsolete function (as of Org 9.3); use ‘org-latex-preview’ instead.

The new function was added on 2019-02-13 with 6d9022df,
which means it is available starting with Org mode 9.2.2.

Greetings
Axel

**Comment by jkitchin** [comment]
I am running org 9.2.3, and `org-latex-preview` does not seem to be available yet.

**Comment by AKielhorn** [comment]
Sorry, it is only in master, not in maint.
