### ISSUE TITLE
Eager macro-expansion failure: (end-of-file "/home/x/scimax/scimax-utils.el")

### ISSUE THREAD

**Issue by GTM269** [jkitchin/scimax#322]
Hello! everyone,

I got an error as described in the title when starting Emacs by scimax.sh.
I use ubuntu 18.04 and emacs 26.3.
All messages in the startup are attached as below.
Thanks in advance!

--
For information about GNU Emacs and the GNU system, type C-h C-a.
(Shell command succeeded with no output)
[yas] Prepared just-in-time loading of snippets successfully.
Loading /home/x/scimax/elpa/mustache-20190905.2214/mustache-render.el (source)...
Loading /home/x/scimax/elpa/mustache-20190905.2214/mustache-lex.el (source)...done
Loading /home/x/scimax/elpa/mustache-20190905.2214/mustache-parse.el (source)...done
Loading /home/x/scimax/elpa/mustache-20190905.2214/mustache-render.el (source)...done
jupyter was not found on your path. ob-ipython was not loaded.
Eager macro-expansion failure: (end-of-file "/home/x/scimax/scimax-utils.el")
LaTeX fragment tooltips are enabled.
Latex fragment justification enabled
Latex numbering enabled
Inject latex enabled
Colored src-blocks enabled.
Loading /home/x/scimax/scimax-notebook.el (source)...done
Loaded /home/x/scimax/scimax-notebook.el
ingesting /home/x/scimax/scimax-lob/noweb.org
Starting new Ispell process aspell with default dictionary...
initializing spell-checkers!
Ispell process killed
Starting new Ispell process aspell with default dictionary...
1 source block added to Library of Babel
ingesting /home/x/scimax/scimax-lob/lob.org
initializing spell-checkers!
21 source blocks added to Library of Babel
ingesting /home/x/scimax/scimax-lob/kitchingroup.org
initializing spell-checkers!
8 source blocks added to Library of Babel
[yas] Prepared just-in-time loading of snippets successfully.
Loading /home/x/scimax/scimax-editmarks.el (source)...done
Loaded /home/x/scimax/scimax-editmarks.el

**Comment by jkitchin** [comment]
Assuming you mean `Eager macro-expansion failure: (end-of-file "/home/x/scimax/scimax-utils.el")`, this is an unimportant message.

**Comment by GTM269** [comment]
> Assuming you mean `Eager macro-expansion failure: (end-of-file "/home/x/scimax/scimax-utils.el")`, this is an unimportant message.

John, Thanks!
I will just ignore it. :)
