### ISSUE TITLE
linux keyboard mapping

### ISSUE THREAD

**Issue by uliw** [jkitchin/scimax#324]
Hi John,

the following took me forever to figure out since much of the info on Linux keyboard mapping out there is either incomplete or out of date. Furthermore, my window manager (KDE)  is hardcoded to intercept the win-key (regardless of mapping). Hope this can be of use to someone else

Cheers

Uli

! -*- coding: utf-8 -*-
! Example how to change keyboard assignments with xmodmap
! Tools: xev, setxkbmap, xmodmap

! General strategy: 
! 1) always reset to baseline before changing maps since changes are
!    cummulative: setxkbmap
! 2) print current mapping:  xmodmap -pm
! 3) Build new map save in ~/.Xmodmap
! 4) install new map xmodmap .Xmodmap
! 4) test with xev: xev | grep KeyPress -A4
! 5) test with emacs
! 6) if all is well, add this to your ~/.xinitrc
!    if [ -s ~/.Xmodmap ]; then
!       xmodmap ~/.Xmodmap
!    fi

! Below 2 examples how to change the mapping of the super and hyper keys
! First remove key from one of the modifier groups
! then change the key code
! and in a last step add them back onto a modifier group (keys in the
! modifier group do not generate a symbol, rather they modify another key)

! Swap alt-right with Super_r:

! 1) free up right-Alt for remapping
remove mod1 = Alt_R
! 2) map Super_R code to Alt_R
keysym Alt_R = Super_R
! 3) add Super-r to modifier group
add mod4 = Super_R

! Win keys are hard coded into KDE plasma, so here I map Hyper to Crtl_R
! For this to work, I need to know the keycode for Ctrl_R (use xev)
! Swap ctrl-right to hyper:

remove control = Control_R
remove mod4 = Hyper_L
keycode 105 = Hyper_R
add mod3 = Hyper_R

! in order to get emacs to use the new keys, you need to add these 2 lines to
! your emacs init file.
! Lower caps (e.g., super) means either right or left, whereas the capitalized
! form (e.g., Hyper_R) will only apply to the actual key.
! (setq x-super-keysym 'super)
! (setq x-hyper-keysym 'Hyper_R)

**Comment by shrysr** [comment]
Thank you for this note! This is certainly useful as a guide.

**Comment by uliw** [comment]
Re-opening this since the above is only working for the X11 window manager. Since many distributions are/have moving/moved to wayland, there is currently no easy way to remap keyboard keys.

Many of the key combinations that require the hyper key are related to scimax hydras, and `'scimax-dispatch-mode-hydra` provides a context-sensitive way to activate hydras.

So something like this `(global-set-key (kbd "<M-f12>") 'scimax-dispatch-mode-hydra)` solves the majority of the cases that need the hyper key. Maybe this can be a default setting?

**Comment by jkitchin** [comment]
That seems reasonable enough. I made a defcustom for the actual binding so maybe it is easier to set.
