### ISSUE TITLE
Org mode fontification error

### ISSUE THREAD

**Issue by artpelling** [jkitchin/scimax#325]
Hello,

I'm running Emacs 26.3 on Ubuntu 18.04 LTS.
After installing scimax and creating a test.org file with a simple emacs-lisp source block I get:

`Org mode fontification error in #<buffer test.org> at 3`

I get this error with a vanilla scimax, where I only changed the TLS protocol in bootstrap.el to 1.2 in order to get it to work on Ubuntu. Other languages give the same.

Everything worked fine in the past, i decided to do clean up my configs and started from scratch.

Compile Log contains:
`.scimax/scimax-org-latex.el:Warning: ‘org-toggle-latex-fragment’ is an
    obsolete function (as of Org 9.3); use ‘org-latex-preview’ instead.
.scimax/scimax-org-latex.el:Warning: ‘org-toggle-latex-fragment’ is an
    obsolete function (as of Org 9.3); use ‘org-latex-preview’ instead.`

Could it have something to do with the Org-mode version?

Any help is greatly appreciated!

**Comment by artpelling** [comment]
I have just tested it with Emacs 25.3.2 and it is the same

**Comment by jkitchin** [comment]
I think this may be due to a change in org 9.3. I have pushed a possible fix for it.

**Comment by artpelling** [comment]
Thank you very much! I am closing the issue, because this commit has fixed fontification for me.

However, the Warning on startup in the Compile Log persists, which is a bit annoying.

> .scimax/scimax-org-latex.el:Warning: ‘org-toggle-latex-fragment’ is an obsolete function (as of Org 9.3); use ‘org-latex-preview’ instead. .scimax/scimax-org-latex.el:Warning: ‘org-toggle-latex-fragment’ is an obsolete function (as of Org 9.3); use ‘org-latex-preview’ instead.

**Comment by jkitchin** [comment]
This warning might be fixed in 85c4e30.

**Comment by artpelling** [comment]
fixed indeed. Many thanks, keep up the great work!
