### ISSUE TITLE
Initialisation problems in windows  

### ISSUE THREAD

**Issue by chanGimeno** [jkitchin/scimax#326]
Hi John,

Thank you very much for this great development!

During the last years, I got used to do most of my daily tasks using Emacs and org-mode and one of my favourite setups is Scimax.

I am a Linux user that now has to use work also under Windows. So, I cloned Scimax and I am using it in Windows. Since some time ago, I am getting problems triggered by a jupyter/ipython error during the initialisation which prevents all scimax packages and settings to be loaded completely.

The *Messages* and *Warnings* buffers contain the following information:

***Messages***

> jupyter was not found on your path. ob-ipython was not loaded.
> edebug--read: Non-hex digit used for Unicode escape

***Warnings***
> Error (use-package): Failed to install dashboard: Package ‘emacs-25.3’ is unavailable
> Error (use-package): Cannot load dashboard
> Warning (emacs): No wkhtmltoimage found. Either set ‘ob-ipython-html-to-image-program’ to the location, or go to https://wkhtmltopdf.org/downloads.html to get and install it.

Have you encountered similar problems? Do you have any tips to solve the issue?

Thank you very much in advance!

**Comment by jkitchin** [comment]
> Hi John,
> 
> Thank you very much for this great development!
> 
> During the last years, I got used to do most of my daily tasks using Emacs and org-mode and one of my favourite setups is Scimax.
> 
> I am a Linux user that now has to use work also under Windows. So, I cloned Scimax and I am using it in Windows. Since some time ago, I am getting problems triggered by a jupyter/ipython error during the initialisation which prevents all scimax packages and settings to be loaded completely.
> 
> The _Messages_ and _Warnings_ buffers contain the following information:
> 
> _**Messages**_
> 
> > jupyter was not found on your path. ob-ipython was not loaded.

This means jupyter is not on your path somehow.  How are you starting emacs? I always start it from a git bash shell so that it inherits the path. If you start from double clicking an icon then the paths may not be right.

> > edebug--read: Non-hex digit used for Unicode escape

This is a strange one. It looks like maybe there is some \path somewhere, but I am not sure where. Maybe related to a windows path perhaps. See https://lists.gnu.org/archive/html/emacs-devel/2010-11/msg00326.html and see if anything there points to the problem. You probably have to use \\ in those paths.

> 
> _**Warnings**_
> 
> > Error (use-package): Failed to install dashboard: Package ‘emacs-25.3’ is unavailable
> > Error (use-package): Cannot load dashboard

This is not an essential package. It is probably a MELPA failure I guess. You can just comment this out in packages.el if you don't need it.

> > Warning (emacs): No wkhtmltoimage found. Either set ‘ob-ipython-html-to-image-program’ to the location, or go to https://wkhtmltopdf.org/downloads.html to get and install it.

You can solve this by going to that url and installing this package. There should be a windows version.

> 
> Have you encountered similar problems? Do you have any tips to solve the issue?
> 
> Thank you very much in advance!

**Comment by chanGimeno** [comment]
Thank you very much for the rapid response!

I start scimacs using an application shortcut (see attached figure):
<img width="286" alt="scimax_shortcut" src="https://user-images.githubusercontent.com/6866605/71134692-7d40d780-21ff-11ea-8e46-ac54f2d0fc58.PNG">

As you pointed out, I modified some configuration files with things like that

+(use-package ediff
+  :init
+  (setq ediff-diff-program "c:\Program Files\Git\usr\bin\diff.exe")
+  (setq ediff-diff3-program "C:\Program Files\Git\usr\bin\diff3.exe"))
+

containing "\"'s. I have to investigate my installation first (or clone scimax again) before posting again.

BTW, now I have installed anaconda and, if starting scimax from the anacanda promt, I am not getting the error not finding jupyter anymore.

Thanks!

**Comment by jkitchin** [comment]
I think if you change things like "c:\Program Files\Git\usr\bin\diff.exe" to "c:\\Program Files\\Git\\usr\\bin\\diff.exe" the hex code error will probably go away.

**Comment by chanGimeno** [comment]
sorry for the delay in replying to this issue! 
I got now a working scimax installation in windows 10 using emacs 26.3, no initialization problems anymore. I had to make a couple of adjustments to have full functionality under Windows (e.g. bash commands --find, grep, ssh, ...-- from Git Bash, hunspell, plantuml, ...), but now everything is working ... Or almost, a couple of features are still not working (fontifying org mode source blocks and interactive python/matplotlib plots), but I will report them in dedicated issues.
Thanks again for the support!

**Comment by chanGimeno** [comment]
I forgot to mentioned that I had to change the TLS protocol version in bootstrap.el:

diff --git a/bootstrap.el b/bootstrap.el
-  (setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3"))
+  (setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.2"))
