### ISSUE TITLE
Undo-Tree-Save error on loading scimax

### ISSUE THREAD

**Issue by JSpenced** [jkitchin/scimax#330]
I get this error when trying to start emacs. Is there a way to start emacs without undo-tree-save-history or do you know what is causing this problem:

```
Loading /Users/bigtyme/Programs/scimax/scimax-notebook.el (source)...
Error during file deserialization: (void-function undo-tree-save-history-from-hook) [2 times]
kill-buffer: Symbol’s function definition is void: undo-tree-save-history-from-hook
Package cl is deprecated
kill-buffer: Symbol’s function definition is void: undo-tree-save-history-from-hook
```

I can't use scimax now. I feel maybe upgrading packages caused this problem. I tried updating scimax to current master, but that didn't help.

**Comment by jkitchin** [comment]
I guess this means there is some other error above this that is preventing undo-tree from loading. If you don't find one, maybe undo-tree itself is corrupted. in the elpa directory, this might look like the files are there, but one or more has 0 bytes for size. you can probably delete the undo-tree directory, and reinstall it. 

However, I am looking at my installation and I don't have a `undo-tree-save-history-from-hook` in mine either. I am using undo-tree-0.6.5.

Maybe go into your elpa folder, and run `grep --recursive "undo-tree-save-history-from-hook" *` to see where that is coming from.

**Comment by JSpenced** [comment]
Actually, I realized right after I wrote the last message that I should try deleting undo-tree and then restarting emacs. I found that I actually had two versions installed in the elpa folder, so deleted both. After restarting twice, it seemed everything was back to normal.  Thanks.
