### ISSUE TITLE
Generate a TOC of a notebook?

### ISSUE THREAD

**Issue by Cumol** [jkitchin/scimax#332]
My notebooks contain many org file where each represents an experiment. Each experiment has a title, a subtitle, and a date.

I was wondering if it is possible to somehow generate a table of contents (or a helm popup) for each of the files. Similar to a table of contents with title, subtitle, and date.

Probably something similar to the tag function in the scimax notebook file.

This would make navigating a notebook much easier. Right now, I need to remember what short name I gave each .org file and then look for it when opening a notebook. I usually end up picking the wrong find.

Recently I started to use git-counsel-grep to look for things that I remember typing in the file to find the file. But that is also a mess...

Any idea where to start here?

**Comment by jkitchin** [comment]
Is something like `ivy-org-jump-to-heading-in-directory` what you want, but with the directory being the notebook directory? I sometimes use projectile functions for this, e.g `projectile-find-file`. There is a more comprehensive discussion of searching at https://github.com/jkitchin/scimax/blob/master/scimax-notebook.org#searching-the-notebook. `nb-search` tries to consolidate some things for searching, but it probably isn't the same as a table of contents.

We could make something that has headlines, filename, and if there is a date as a candidate for some completion backend I think.

**Comment by Cumol** [comment]
Thank you for pointing me towards `ivy-org-jump-to-heading-in-directory` that is neat but not quite what I envisioned.

instead of headline, it would be nice to get the title as in `#+title: <title>` of the org file. This would end up with a rather "short" list in comparison to an output with headlines which, as is seen with the above ivy function, a huge list.

Invoking the function would create a helm/ivy buffer with the following:

Title | Date | Link

And choosing one would open that file.

**Comment by jkitchin** [comment]
How about something like:

```
(defun nb-search-title ()
  "Select a notebook file by title, date or filename."
  (interactive)
  (let ((org-files (-filter (lambda (f) (f-ext? f "org"))
			    (projectile-project-files (projectile-project-root))))
	candidates
	candidate
	title
	date)

    (setq candidates (mapcar (lambda (f)
			       (with-temp-buffer
				 (insert-file-contents f)
				 (setq title (if 					 (re-search-forward "#\\+TITLE: \\(.*\\)" nil t)
						 (match-string 1)
					       "No title"))
				 
				 
				 (goto-char (point-min))
				 (setq date (if 					 (re-search-forward "#\\+DATE: \\(.*\\)" nil t)
						(match-string 1)
					      "No date"))
				 
				 (cons (format "%40s | %20s | %s" title date f) f)))
			     org-files))
    
    (setq candidate (completing-read "Open: " candidates))
    (find-file (cdr (assoc candidate candidates)))))

```

It should be possible to sort on the date, but I don't have time to work on that right now.

**Comment by Cumol** [comment]
This is exactly what I was looking for. 

It chokes on empty .org files (gave me a reason to clean up) but apart from that does it correctly.
The columns produced are not well aligned and sorting by date would also be nice. But for not, this is great, thank you!

It could be something that other people might be interested in. Specially if they use scimax and the notebook functionality to write their lab notebooks.

**Comment by jkitchin** [comment]
I pushed a slightly modified version that probably fixes your alignment, and sorts on the date so more recent things come first.

**Comment by Cumol** [comment]
Works great!

Which date is it using? I see multiple dates with the "mod" prefix (which I guess means modified).

**Comment by jkitchin** [comment]
It looks for a #+DATE: in the org file, and if it doesn't find one it uses the last modified date on the file. unfortunately, it doesn't seem possible to use a created date, most OS seem to only have the last modified time available.
