### ISSUE TITLE
strange behavior for org-*-region-or-point on item end in a list

### ISSUE THREAD

**Issue by yiufung** [jkitchin/scimax#333]
Many thanks for `org-*-region-or-point`, they are very useful commands, especially that they work for subscript and superscript. I wish they are bundled with Org. 

I found some strange behavior when it works on a list of items. Given:

```
- Item hello
- Item world
```

If region is marked with mark and point as specified below to highlight `hello`:

```
- Item [mark]hello[point]
- Item world
```

then running `org-italic-region-or-point` would result in:

```
- Item /hello/
/- Item/ world
```

instead of 

```
- Item /hello/
- Item world
```

Is this intended behavior?

**Comment by jkitchin** [comment]
That was not intended. I have pushed a fix that should resolve this.

**Comment by yiufung** [comment]
It's solved now. Many thanks!

**Comment by yiufung** [comment]
According to documentation of new patch:

```
Mark the region, word or character at point as code.
This function tries to do what you mean:
1. If you select a region, markup the region.
2. If in a word, markup the word.
3. Otherwise wrap the character at point in the markup.
```

Given:

```
[mark]t[point]esting
```

I'd expect output to be `*t*esting`, but instead I was shown `*testing*`. Is this intended?

**Comment by jkitchin** [comment]
That is expected behavior to me. *t*esting is not legal org syntax, i.e. it is not possible to partially bold a word like this, so it bolds the whole word. There might be some tips at https://stackoverflow.com/questions/1218238/how-to-make-part-of-a-word-bold-in-org-mode to do this, but I didn't want to do this in scimax for now.

**Comment by yiufung** [comment]
Ah, I didn't know that's the case. I was only wondering how it's different from docs description. 

It's working mostly fine with me. Only in one case, that is, Chinese input, that I preferred native `org-emphasize`. In Org there must be extra space ` ` between two Chinese character for them to be properly stylized. For example, `中文高亮` needs to be bolded as `中 *文高* 亮`. 

I still keep your command as it provides additional subscript/superscript integration. Is there any plan to integrate this in Org? That should benefit a lot of users. 

Again, much thanks for the command!
