### ISSUE TITLE
Using scimax with EXWM?

### ISSUE THREAD

**Issue by Cumol** [jkitchin/scimax#335]
Does anyone have experience with using EXWM with the custom init of scimax?

I don't seem to find any information about how to start EXWM when logging into ubuntu with the scimax settings.

**Comment by shrysr** [comment]
Always wanted to try. I've only used i3wm. Perhaps this may help as a guide though it is for Arch : https://wiki.archlinux.org/index.php/EXWM

**Comment by Cumol** [comment]
`exec emacs` in `xinitrc` is probably where we need to let it know where to find our custom init file.

Need to try that. I remember it being not as straight forward though

**Comment by shrysr** [comment]
Yes, the exec command is not straightforward from what I remember either. I believe it can execute a single command easily, but has trouble with arguments or something like that. IIRC : it may be better to exec a sh file which contains what you need.

**Comment by Cumol** [comment]
I wonder if it works with setting an alias to scimax instead?

**Comment by shrysr** [comment]
I think for aliases to work, the .bashrc or equivalent has to be processed first. `.xinitrc` is basically a shell script. There are some caveats with respect to one shell script calling another. I think one possible way is to save the scimax load command in a shell script, and use .xinitrc to call the shell script. Perhaps you could also try something like `(emacs "-q" "- l" "$HOME/scimax/init.el" &)` without the exec.

**Comment by Cumol** [comment]
eventually I ended up moving my whole scimax directory into `~/.emacs.d ` and now I am using `startx ~/.xinitrc -- /usr/bin/Xephyr :4 -screen 1920x1080` to test it. So far so good

**Comment by zenny** [comment]
> eventually I ended up moving my whole scimax directory into `~/.emacs.d ` and now I am using `startx ~/.xinitrc -- /usr/bin/Xephyr :4 -screen 1920x1080` to test it. So far so good

@Cumol 

Can't this be achieved by creating a shell script in your `.local/bin` directory and pointing the `scimax/init.el`? So that you do not need move the `scimax` inside `.emacs.d`. This way one can run regular window manager in tty7 whereas EXWM in preferred tty.

1. Create a script `$HOME/.local/bin/startexwm` with the following contents:
```
#!/bin/bash
echo ''
echo 'Starting EXWM in Xephyr in tty :4'
Xephyr -ac -screen 1920x1080 -br 2> /dev/null :4&

echo ''
echo 'Switching to display number :4'
export DISPLAY=:4

emacs -q -l /path/to/scimax/init.el&
exit 0
```

Do not forget to `chmod +x $HOME/.local/bin/startexwm`.

Just my two cents. Hope this is helpful

Cheers and stay safe,
/z
