### ISSUE TITLE
ox-word and docx+smart extension bug?

### ISSUE THREAD

**Issue by ckelty** [jkitchin/scimax#338]
Hey, I am trying to get ox-word to work (Emacs 26.3, org 9.2.2. pandoc 2.9.1 with pandoc-crossref and pandoc-citeproc).

(ox-export-call-pandoc-tex-to-docx) incudes the option --to=docx+smart, but this throws the error "The extension smart is not supported for docx"

Turns out this is also true if I do it with pandoc manually....  and the pandoc man page says +smart is only supported for "markdown, latex, context, rst"

Am I missing something... ?

ck

**Comment by jkitchin** [comment]
It does seem it is not supported now. I assume it was at some point, but either that is not true, or something changed on the pandoc side! I removed that option, and was able to build a word doc. see c805d02.

**Comment by ckelty** [comment]
Cool...  it works fine without the option.  In fact it works great, thank you for making it :)
