### ISSUE TITLE
Ipython source blocks freeze Emacsclient 

### ISSUE THREAD

**Issue by shrysr** [jkitchin/scimax#341]
I actually had this issue (#277 ) quite some time back, which has actually persisted but left unaddressed. Since I'm back focusing on python now for foreseeable future - I'm trying to understand scimax's enhancements to ob-ipython and leverage a nice workflow.

Behavior:

1. If emacs is run in daemon mode - in a client when the cursor reaches (or is in) an ipython block - emacs freezes, right after the message 'kernel started ...' . I have to hit C-g repeatedly to un-freeze.  The end status seems that Source edit (C-c ') mode is entered, but without the actual edit buffer being opened. Then I have to manually 'revert' (or not), by hitting C-c' again. If the cursor is still in a ipython block - the above repeats and is terribly painful to get out of. Essentially, with an emacsclient  - I am unable to use ipython blocks without emacs constantly freezing as long as the cursor is in a ipython source block. It becomes better if I immediately execute a simple source block on a new org file and launch a session. However, the issue returns with a vengeance as I work through code in the same buffer unexpectedly. NOte: Python source blocks work fine, so it seems an issue with ob-ipython. 

2. When emacs is run standalone (not a deamon) - the above does not occur. Ipython works pretty much as expected from several repeated tests. If a kernel is not running - then as the cursor, there is a very very brief pause (almost negligible) during each cursor movement. The difference there is the additional message 'Hy command not found', since I do not use it. 

 I'm not sure how to debug this to pinpoint the exact issue. I believe toggle-debug-on-error does not work here, and will have to try toggle-debug-on-exit. I would really prefer using the daemon + client method as it helps with startup time.

**Comment by jkitchin** [comment]
There are a few places where org-edit-special is called in scimax-org-babel-ipython-upstream.el, but none that should obviously get called when a cursor enters a block.  That sounds like something triggered by font-lock or a cursor-sensor function. I can't think of anything causing that from scimax though.

if you are seeing this on every cursor move, it could be some function in a post-command-hook.  You could see what functions are in there, and do `(setq post-command-hook nil)` to see if that eliminates the issue. That would narrow it down at least to one of those functions.

I do not know why you would see 'Hy command not found'. There is only a small part of scimax-org.el that has anything to do with the hy lang, and I would be surprised to find out it has any effect like this.

**Comment by shrysr** [comment]
I am glad to report this finally seems to be resolved for good. I have ipython blocks working as expected both in the daemon and GUI. I did try the post-command-hook, but that did not help.

I think there were multiple possible issues, but suspect the root cause was that I had not specifically installed jupyter-console. I guess I assumed it would be installed along with jupyter, (and I did not have trouble with jupyter notebooks in the past). Looks like a case of RTFM as well, as I may have spotted this it if I went through the docs.

I've removed miniconda to eliminate the path causing additional issues, and in any case it may be healthier to use vanilla python in general without adding an additional layer to troubleshoot.

Subsequently, I've set the following for good measure:

```
(setq python-shell-interpreter "python3")
(setq org-babel-python-command "python3")
(setq flycheck-python-pycompile-executable "python3")

```

sys.version gives me the expected version 3.x from python/ipython blocks, as well as M-x run-python. The one exception is eshell, where it appears I will have to call python3 specifically to invoke python3. I've set an alias for .zshrc for convenience in the terminal. I guess I should be using vanilla bash by extension of avoiding troubleshooting layers, but things appear to be okay at the moment.

Maybe worth noting in the process that I found the old error of #272 using org. However, it was fixed once jupyter was installed as noted earlier. I will dig into that portion another day.

I'm studying the scimax docs to get more intimate with the customisations of ob-ipython. Happy to hear your feedback for any further optimisation I should look at.

I think this issue can be closed.

**Comment by jkitchin** [comment]
I mostly use what is in scimax. Lately I looked into emacs-jupyter again, which is a better way to do ipython than ob-ipython, but it seems to still be hard to build on windows, and there are some other minor things I don't like like the same kernel in every buffer. It has better support for remote kernels though, which is increasingly a need for me.

**Comment by shrysr** [comment]
Thank you. I would very much prefer a separate kernel per buffer as well.

As a side note - I am now using tramp to create org files with ipython blocks on a remote computer. It works surprisingly well, albeit with some lag - though the code I'm executing is still trivial. The function described in http://kychoi.org/blog/2014/11/02/Org-Display-Inline-Remote-Images has to be implemented to display the images inline.
