### ISSUE TITLE
Ox-word problems when converting to docx

### ISSUE THREAD

**Issue by nettoyoussef** [jkitchin/scimax#342]
Hi all,

Thanks for all your effort putting such awesome packages as org-ref and scimax.

I am running in a problem when using the ox-word.el script.

Basically, it has problems converting links that are inside a latex expression (such as `\textcolor`). 

Here is the backlog:

```elisp
Saving file ...
Wrote /home/...
done with tables.
Running "pandoc -F pandoc-crossref -s  --bibliography=/tmp/ox-word-alEDLN.bib  \"path" --to=docx -o \"path""

Error at "source" (line 382, column 693):
unexpected _
\footnote{\textcolor{red}{=This JEL code= is L11: Production, Pricing, and Market Structure; Size Distribution of Firms. This information is taken from the February 2009 update to the JEL classification system: [[http://www.aeaweb.org/journal/jel_class_system.php]] =(last accessed 25 November 2011).=}} 
```
The above generates an error when converting from latex to docx using pandoc.
The expected output should be something like:

```elisp
\footnote{\textcolor{red}{This JEL code is L11: Production, Pricing, and Market Structure; Size Distribution of Firms. This information is taken from the February 2009 update to the JEL classification system: \url{http://www.aeaweb.org/journal/jel_class_system.php} (last accessed 25 November 2011).} 
 ```
The raw input is:

```elisp
\textcolor{red}{=This JEL code= is L11: Production, Pricing, and Market Structure; Size Distribution of Firms. This information is taken from the February 2009 update to the JEL classification system: [[http://www.aeaweb.org/journal/jel_class_system.php]] =(last accessed 25 November 2011).=}
```

**Comment by nettoyoussef** [comment]
Also, do you have some suggestions when converting tables?

I have some defined on my org file using `\input{table.tex}` that don't get converted, either using ox-word or pandoc directly. 

Thanks in advance!

**Comment by jkitchin** [comment]
I am not sure how to deal with this, it sounds like a pandoc issue.

Can you provide a small working example that illustrates this?
