### ISSUE TITLE
Suggestion: add which-key to scimax

### ISSUE THREAD

**Issue by shrysr** [jkitchin/scimax#344]
Considering the number of shortcuts, and that some could change in the future, I'd like to suggest adding which-key to default scimax. For example, H-c within ipython blocks is quite handy. But outside the source blocks - typing H-c + which-key enabled achieves the same effect (in a way) and helps keep track of assigned keys as well.

I thought this could aid in discovering and actually using more of scimax, because it is doing so for me. Perhaps it a case of personal preference as well. Maybe something like this ? :   

```
(defcustom scimax-which-key 'nil
  "Scimax option to enable or disable which-key. Defaults to `nil'.
Set to 1 to install and enable which-key."
  :group 'scimax)


(when scimax-which-key
  (use-package which-key
  :ensure nil
  :defer nil
  :config
  (which-key-mode)))  

```

**Comment by jkitchin** [comment]
I like this idea, but I am not sure where the best place to do it is. Most of the use-package code is in packages.el, and most defcustoms are defined after that. There are few conditional loads in packages.el, and none that depend on a variable I think.

Maybe an alternative way to do this is to make a contrib folder that could have suggestions like this. Maybe this folder could have org-files for short snippets? WDYT?

**Comment by shrysr** [comment]
I think a user contrib folder could be a good idea to enrich 
Scimax, or atleast be a good experiment.

I guess depending on preference, the user could add that contrib 
folder to the load-path, which could also contain single or 
multiple Org files, while also catering to longer .el files and 
those that prefer contributing in that manner. I'm not sure if 
adding to the load path alone would affect Scimax's config or init 
time, unless the script has a ~require~ instead of ~provide~ in 
it?

OTOH - no tangling nor adding to load-path whatsoever could mean 
that anybody is free to add their ideas and participate without 
much restriction, and also cause less concern in terms of 
integration of any sort. User contributions would remain purely 
optional, serve as examples of additional customisation and also 
come with no guarantee of either working, or against redundancy 
(stuff already in scimax). Org files would mean anybody can 
execute the snippet to test drive quickly. The old Emacs wiki 
approach comes to mind as a possible alternative + showcase, but 
that is probably a different style / purpose altogether.

I'm also thinking, it may be easier to have a single Org file 
rather than many to make it easy to browse and to keep it neat. 
Contributors could make their own heading, and individual headings 
could be tangled into different file names as desired to mix and 
match snippets or even entire configs for that matter?

I guess the above contributions could be filtered by you as 
'official' additions that cause no conflict, and those alone would 
be actually loaded.

**Comment by jkitchin** [comment]
I added this to scimax/contrib.org for now.
