### ISSUE TITLE
Correct way to map scimax/body to Ctrl + revert if desired ? 

### ISSUE THREAD

**Issue by shrysr** [jkitchin/scimax#345]
If I recall correctly - there was an earlier discussion where you mentioned that you have the scimax/body hydra (default F12) mapped to Control (?).  

I've actually been wanting to give a shot to migrating to using Control (currently using `C-\` ), and rely entirely on the hydra, particularly for navigation as well - and reduce having Control (capslock in my case) depressed 24/7. It seems potentially workable and a very good idea. (Particularly because I also seem to be having a recurring case of 'emacs-pinky' of late)  

However, `(global-set-key (kbd "C") 'scimax/body)` uses the capital letter C, and then unset removes 'C' altogether, which was fun! I'm not able to figure out using only 'Ctrl'.

However, I also think it may be necessary to migrate 'slowly' due to muscle memory, and thus should have a way to 'reset to default' when I am pressed for time. I would be glad for advice on implementing this.

**Comment by jkitchin** [comment]
I have it bound to caps-lock. On my keyboard it is right next to my left pinkie, and I never use it for anything. It is a software remap outside of Emacs. I am not sure you can use control that way, as it is a modifier, not a key, e.g. C-h k ctrl doesn't do anything. Maybe you could use a software remap on your keyboard though so it mapped ctrl to f12. On mac I use Karabiner-Elements, but there are other tools for this on windows and linux. Spacemacs uses the space bar for this.

**Comment by shrysr** [comment]
Ah. I see now. No wonder I found almost nothing other than using apps like Karabiner. Thank you. I had switched left control and capslock a long time ago on all my keyboards and am trying to overcome the muscle memory as it seems to have stopped working very well over the past few weeks. I have been going through Xah Lee's articles which suggest using the palm press for control instead, with raised wedges over the keycaps to make the pressing easier. My keyboard looks funny with the makeshift wedges on top of the control keys, but I'm trying this out as a precursor to switching to some ergonomic keyboard in the future. I've also remapped F12 to Capslock, as I think it is not of much use either. I also realised that I cannot completely avoid using ctrl for navigation within menu items. One solution seems to be switching to evil mode which I may end up trying at a later time as modal editing does not seem to suit my style the last time I tried it. So far having implemented the above - it does seem that my finger movements have reduced with this method and are closer to the home row though there is a bit of a hindrance in reaching RET due to the wedge. I guess this issue can be closed, but I'm happy to hear suggestions.

**Comment by jkitchin** [comment]
I don't have any other suggestions. I have tried a lot of ergonomic keyboards, but I have always come back to a regular mac keyboard. If you only ever type on one keyboard and have 4-6 weeks to get into it you might find one that works, but I could never get over the barrier, and typing on multiple different keyboards was part of the problem. 

I have tried foot pedals but found my feet are never as fast as my fingers, and eventually have not used them. If you are a maker type you could build a palm key plate pretty easily I think that you could map to control.

The way I use f12 is sort of like modal editing. It is a leader key, and then there are hydra keys that are effectively C-keys. For example instead of C-x, I can type Caps-lock then x (no chording). I find the chording is what is stressful on my pinky, because you have to hold it down while doing something else, which is harder than just pressing in sequence. Instead of C-n , I would type Capslock then n and then use home row keys for navigation. I don't know if it is better than using Ctrl all the time.

**Comment by shrysr** [comment]
Quite interesting to read about your experience, thank you for sharing. I have never really tried any ergonomic keyboard, though I have used a mechanical keyboard in the past (and that was wonderful). I dislike the new macbook pro keyboards as the travel is not enough and the old ones were way better. My external keyboards have usually been non-mac types. I have had my eye on the [Atreus](https://atreus.technomancy.us/2) for a while and think it could be small enough to carry around and conceptually work on different platforms. The caveat of lower number of keys would be offset by minimum finger travel and customisation I think. 

Yes, i realised that f12 was sort of like modal editing and think it is a sensible idea, and that was the intention behind trying this. Even so - though the palm-press-control seems to work so far with my glued-on-rolled-up-index-card wedges, my pinky does not yet want to let go of muscle memory easily and inches toward capslock on its own and is still stressed! I will have to figure out better designed wedges as well.

With respect to f12 >  n, one thing that bothers me is the size of the minibuffer providing the hydra information. Is there a way to reduce that? 

Another question was how do I access the x1, x7 ... options with projectile i.e f12 p ?  If I hit f12 p x - this maps to M-x. I see a comment that you did not want to override this in scimax-hydra.el.

**Comment by jkitchin** [comment]
Regarding the Atreus, see https://www.kickstarter.com/projects/keyboardio/the-model-01-an-heirloom-grade-keyboard-for-seriou/posts/2646925.

I built one of the original Atreus kits. It was fun to build it, but I found it very hard to adapt to. There are three layers of keys you have to keep track of in your head. YMMV.

Check out https://sugru.com/ for making the wedges.

Regarding the size of the minibuffer, I don't think you can reduce it. You can probably suppress when it shows up though, e.g. if you type fast enough you won't see it, but if you don't it will show to help you remember what to type. I think this is done with an :idle setting. It is currently 0.5 seconds in the base hydra. Maybe longer would work better for you.

Regarding the x1/7 commands, it looks like they are currently not accessible. I am not sure how to get them that way either. probably we have to change the keys, make this not inherit from scimax-base, or do something fancier. The only downside of not inheriting I think is you lose the ability to navigate the hydra stack.

**Comment by shrysr** [comment]
Quick note : thank you for the suggestion regarding Sugru. I intend to look into that for sure. Atreus is on my list to evaluate down the line. I'm yet to test the inheritance removal, since I'm using a forked version of Scimax. I will have to find a way to keep up to date, though it does not seem this will be painless.
