### ISSUE TITLE
ox-word failed.

### ISSUE THREAD

**Issue by cryoguy** [jkitchin/scimax#346]
ox-word convert produces following error:

`Error at "source" (line 130, column 1):
unexpected \end
\end{figure}
^`
It worked fine before and PDF is exported fine.  

I am using: Arch Linux 5.5.7
Emacs 26.3
Org-mode 9.3

**Comment by cryoguy** [comment]
here is a MWE.  It exports as pdf ok, not Word.

`#+LATEX_CLASS: elsarticle
#+LATEX_CLASS_OPTIONS: [number,url=false, sort&compress, review, 12pt]
#+OPTIONS: author:nil
#+latex_header: \usepackage[utf8]{inputenc}
#+latex_header: \usepackage{graphicx}

\begin{frontmatter}
\title{Title}
\begin{abstract}
abstract goes here...
\end{abstract}
\end{frontmatter}

* Background and Introduction
  background here...
* Method and Materials
  M&M section....
* Results
  #+ATTR_LATEX: :placement [H]
  #+ATTR_LATEX: :width 12cm
  #+ATTR_ORG: :width 300
  #+caption: caption. \label{fig-temp}
  [[./bsevit/BSE-temp.jpg]]

  ref to fig [[ref:fig-temp]] 

* Discussions

  and more ...

* References
bibliographystyle:elsarticle-harv
bibliography:~/Documents/bibliography/references.bib
`

**Comment by jkitchin** [comment]
It still isn't great, but for some reason if you change \label{fig-temp} to label:fig-temp in the caption it at least exports.
