### ISSUE TITLE
 No url found for submodule path 'emacs-win252' in .gitmodules

### ISSUE THREAD

**Issue by Arjay-El** [jkitchin/scimax#350]
I have upgraded the emacs-win directory to 26.2 but now obtain this message. It does not seem to effect the operation of scimax but I would like to update something in the git config to have it recognize a new version. Does anyone have an idea of what I should do to solve this message? (Win10 platform). I tried deleting/changing the references in the various config files but that throws more error messages.
Thanks!

**Comment by jkitchin** [comment]
maybe look in scimax/.gitmodules to see if there is a remnant path there? I don't currently have a windows machine available for testing, so I am not sure what else I can do right now.

**Comment by Arjay-El** [comment]
Found a remnant path.
