### ISSUE TITLE
:init-fn not one of error

### ISSUE THREAD

**Issue by Cumol** [jkitchin/scimax#351]
Updated some packages and restarted scimax and suddenly got this error.

```
Error (use-package): lispy/:catch: Keyword argument :init-fn not one of (:initial-input :height :occur :update-fn :unwind-fn :index-fn :sort-fn :format-fn :display-transformer-fn :more-chars :grep-p :exit-codes)
Error (use-package): scimax-org-babel-ipython-upstream/:catch: Symbol’s value as variable is void: lispy-mode-map
Error (use-package): scimax-org/:init: Symbol’s value as variable is void: lispy-mode-map
Error (use-package): scimax-ivy/:catch: Keyword argument :init-fn not one of (:initial-input :height :occur :update-fn :unwind-fn :index-fn :sort-fn :format-fn :display-transformer-fn :more-chars :grep-p :exit-codes)
Error (use-package): scimax-journal/:catch: Symbol’s value as variable is void: lispy-mode-map
Error (use-package): scimax-ob/:catch: Symbol’s value as variable is void: lispy-mode-map
Warning (initialization): An error occurred while loading ‘/Users/muadabdelhay/.emacs.d/init.el’:

error: Keyword argument :init-fn not one of (:initial-input :height :occur :update-fn :unwind-fn :index-fn :sort-fn :format-fn :display-transformer-fn :more-chars :grep-p :exit-codes)
```

It all seems to be connected to lispy mode as the rest of the errors (apart from scimax-ivy) have to do with lispy-mode-map.

I just cant figure out what changed suddenly. From what I understand, the keyword argument :`inif-fn` is not one of the listed options. So I went to look for `init-fn` but couldn't find any mention of it in lispy, scimax, or use-package.

Any idea what is happening?

**Comment by Cumol** [comment]
Removing the elpa directory and reinstalling all the packages solved the issue...

**Comment by jkitchin** [comment]
Probably you got a corrupted package from melpa. I bet the lispy package was empty or had an empty file. usually just deleting that package and reinstalling it can fix this.
