### ISSUE TITLE
Spell checker not to run the whole file when loading org files

### ISSUE THREAD

**Issue by JSpenced** [jkitchin/scimax#352]
I am not sure why, but it seems to ispell the whole file everytime I open `gcal.org` from the org-gcal package which can take a long time. 

It seems to not do this if I remove (ispell-init-process) from the function below. From reading the description of the function, it seems it just boots up ispell. I am not sure why that should be in a hook or does it do something else?? 

I could just put to not turn on flyspell mode for a specific org file, but I wasn't exactly sure how to do that. I might just remove your hook and write my own.

```
  (add-hook 'org-mode-hook
	    (lambda ()
	      ;; do we need to start this? It seems like the first time your run
	      ;; flyspell-mode you get a nil error, and the second time it
	      ;; works.
	      (ispell-init-process)
	      (message "initializing spell-checkers!")
	      (flyspell-mode +1)
	      (flycheck-mode +1))
	    t)
```

**Comment by JSpenced** [comment]
I just ended up adding a when clause, but I think the `(ispell-init-process)` might not be necessary. Let you know if I have any problems disabling it.:

```
(add-hook 'org-mode-hook
		  (lambda ()
			;; do we need to start this? It seems like the first time your run
			;; flyspell-mode you get a nil error, and the second time it
			;; works.
			(when (not (string-equal (buffer-name) "gcal.org"))
			  (flyspell-mode +1)
			  (flycheck-mode +1)))
		  88)
```

**Comment by jkitchin** [comment]
I don't know the answer to this. That comment makes it look like this solved one problem of a nil error. The docstring for `ispell-init-process` suggests it starts the ispell process only if needed. I don't know if that also means it initiates spell checking.

I would probably use some file-local variable to check instead. It looks like the hook runs after local variables, so unfortunately I guess you can't turn it off there.
