### ISSUE TITLE
latexpreview not available in org

### ISSUE THREAD

**Issue by domingoUnican** [jkitchin/scimax#353]
Dear scimax users,

I am trying to use scimax with Debian Bulleye and emacs 26.1 to open an org file where there are several latex-fragments.
However, I can not see them and in the Messages buffer appears this:

eldoc error: (void-function org-src-get-lang-mode) [4 times]
command-execute: Wrong type argument: commandp, (lambda (interactive) (funcall scimax-toggle-latex-fragment-func))

**Comment by jkitchin** [comment]
maybe you have a mixed org installation? `org-src-get-lang-mode` is defined in org-src.el in org 9.3

**Comment by domingoUnican** [comment]
org-version says:
Org mode version 9.3.6 (9.3.6-25-g685b2c-elpa @ /home/gomezd/Git_Repositories/scimax/elpa/org-plus-contrib-20200323/)

One thing, in the directory ltximg there are a lot of png, but when I opened, it seems that there isn't any image, only black background.

**Comment by domingoUnican** [comment]
Okay, the problem was gone after I deleted the directory ltximg.

**Comment by johnrkitchin** [comment]
hm. That sounds weird and unrelated to the first things you mentioned. Glad to hear it is working for you now though!
