### ISSUE TITLE
does this package precede ipython?

### ISSUE THREAD

**Issue by CDitzel** [jkitchin/scimax#355]
Hi John and first of all thank you for what you have given the Emacs community. Appreciate it.

- does this package precede [ipython](https://github.com/jkitchin/ob-ipython)?

- Whats the relation to https://github.com/gregsexton/ob-ipython?

- As a vanilla Emacs/Org-mode user, I was wondering, is it possible, to use your s[cimax-org-babel-python.el](https://github.com/jkitchin/scimax/blob/org-9/scimax-org-babel-python.el) funtionality as well?

thanks in advance

**Comment by jkitchin** [comment]
There are two versions of ipython in scimax. The current active version uses  https://github.com/gregsexton/ob-ipython as the base, and then adds or modifies functionality in scimax-org-babel-ipython-upstream.el. The older version isn't used by me anymore. 

I don't know if scimax-org-babel-python.el works in a standalone form. I think it does. It mostly provides async support, although that may be enabled by newer approaches in org-mode. I don't use python blocks that much, mostly ipython.
