### ISSUE TITLE
Cannot display inline images

### ISSUE THREAD

**Issue by Arjay-El** [jkitchin/scimax#356]
Have you ever seen this one? I am no longer able to place inline images. To explain it simply, I place one image link in a buffer with some descriptive text. When I toggle show inline images, I receive a message  'No images to display inline'. However if i click the link, the image opens properly in a separate buffer.
This not the behaviour I have had in the past. I have linked and turned on/off images with no issues.
I also notice that if i open an org file from several months back, I can toggle the images. But if i delete the link and retype it, the image does not open inline, only when clicked in a separate buffer and now acts as noted above.
I am using Win10-64, Emacs 26.2, Org 9.x. Completely baffled by this, any ideas or suggestions would be much appreciated. Thanks

**Comment by jkitchin** [comment]
Is this totally out of the blue? i.e. you haven't made any changes to anything? No updates to anything, including scimax?

Is there anything in the messages, maybe related to mogrify or convert or imagemagick?

**Comment by Arjay-El** [comment]
I cannot say when it started but its on all my Win10 machines, same behaviour. What bothers me is that if i have an old document with an image, it works fine. If I delete the link and re-enter it, toggle stops working and reports it cant find an image even though clicking the link opens the image in a buffer. I dont have my mac working so I cant try it there. I will try a VM of Win7 II use to see if if its there as well. I pray its not some Win10 update issue, I was hoping other Win10 uses could confirm/deny what I see.

**Comment by jkitchin** [comment]
Does it happen with vanilla emacs? scimax does a few things with images. you might look in scimax-org-images.el to see if anything jumps out at you.

**Comment by Arjay-El** [comment]
It came down to this: If I used [[./img/picture.jpg]], it would not toggle open in the document. I needed to put [[file:./img/picture.jpg]]. It needed file: in from pf the reference path, no space.  What still throws me is that I have one image that toggles properly without the "file:"  But it does seem to be working so I will not investigate further until it breaks again.

**Comment by jkitchin** [comment]
huh. That suggests something has changed where  [[./img/picture.jpg]] is not recognized as an image link. For me these are both file links. I think this happens in `org-display-inline-images` which you might instrument and trace through to see what it thinks those links are.
