### ISSUE TITLE
ipython block does not work

### ISSUE THREAD

**Issue by domingoUnican** [jkitchin/scimax#358]
Dear all,
I am running scimax in a Debian 10 buster with emacs 26.1, the problem is
when I run the following code:
    #+BEGIN_SRC ipython
    print("HELLO")
    #+END_SRC
I get the following error

    org-babel-execute:ipython: Symbol’s function definition is void: ob-ipython--clear-output-buffer

I don't know if it has to do with the fact that I recently updated the packages inside emacs package manager.

**Comment by jkitchin** [comment]
This sounds like some package wasn't loaded. check the Messages, maybe it didn't find jupyter, and didn't load the scimax ipython modules. or it is some mixed loading of packages.

**Comment by domingoUnican** [comment]
Thanks, you are right. 
I have installed jupyter with conda and the problem is that when I start my window manager session, I put a line:

emacs --fg-daemon &

Then, emacs does not see the environment installed by conda.
However, if I start emacs in the terminal, it works. Were should I setup in scimax the variables where the conda environment is?

**Comment by jkitchin** [comment]
The only way I know to make this work is to start it in the terminal.  The issue seems to be whether/how/which env variables emacs gets when started different ways (http://ergoemacs.org/emacs/emacs_env_var_paths.html)

**Comment by domingoUnican** [comment]
Thanks! that was it.
