### ISSUE TITLE
cc-mode error 

### ISSUE THREAD

**Issue by kadir-gunel** [jkitchin/scimax#359]
Hello, I am having the same error with emacs version 26.3 on mac. I read the whole thread but could not find out which section to comment that @jkitchin mentioned. 
Could you help please ? 
B.R.

_Originally posted by @kadir-gunel in https://github.com/jkitchin/scimax/issues/308#issuecomment-615417718_

**Comment by jkitchin** [comment]
I think the section I referred to in that old issue was a red herring. The previous isue seems to be in loading ob-fortran, which loads cc-mode. Maybe you have an older version of cc-mode somewhere that is byte-compiled. Maybe try removing all .elc files? See what location cc-mode is in and make sure it is the right one.

M-x locate-library cc-mode

**Comment by kadir-gunel** [comment]
Thank you very much. Removing all .elc files resolved the cc-mode error. But now I have no reference section problem when exporting from org to pdf. This does not happen when I export to html strangely.
