### ISSUE TITLE
No citation when exporting to pdf

### ISSUE THREAD

**Issue by kadir-gunel** [jkitchin/scimax#360]
When I export from org to html I can see the references section. But if I want to export to pdf no citation section occurs.

**Comment by jkitchin** [comment]
If you run `M-x org-ref` it will tell you if there are issues that might prevent the pdf from having a bibliography. Common ones are you do not have a bibliographystyle or bibliography link specified. These are required for latex, but not required for html.

**Comment by kadir-gunel** [comment]
After your post I used M-x org-ref and I didn't see anything required. Just to try everything, I used C-c C-e j m (as submission manuscript pdf and open) then it worked. But the usual command C-c C-e j o does not work if I want to see references. 

I am using emacs 26-3 with org-9.3.2. Is it possible the problem that I am facing is related with those ? 

Kindly Regards

**Comment by jkitchin** [comment]
You should check that with C-c C-e lo works first. C-e j o uses the usual org to pdf machinery, so if you don't have that setup to call bibtex, then you won't see the references.

C-c C-e j m does not use that machinery, and is a manual sequence of build commands that includes bibtex.

**Comment by kadir-gunel** [comment]
I understand now why it does not work (bibtex). 
Thank you for useful information.
