### ISSUE TITLE
can't get output from ipython src-blocks with babel-call syntax

### ISSUE THREAD

**Issue by federkamm** [jkitchin/scimax#361]
When using org-babel call-syntax to execute a ipython src-block, ob-ipython-format-output and ob-ipython-format-text/plain fail because org-babel-get-src-block-info returns nil where s-split expects a string.

    #+name: example
    #+begin_src ipython
    print("hello")
    #+end_src

    #+call: example()

ctrl-c-ctrl-c on the last line fails.  I use the following quick-fix in user.el but a solution that queries the correct org-babel-src-block-info from the babel-call entity would be probably preferable.

    ;; quickfix scimax-ob-ipython to allow babel-calls
    
    (defun safe/s-split (s-split separator s &optional omit-nulls)
      (when (stringp s) (funcall s-split separator s omit-nulls)))
    
    (defun advice/ob-ipython-format (formatter file-or-nil value)
      (advice-add 's-split :around #'safe/s-split)
      (let ((result (funcall formatter file-or-nil value)))
        (advice-remove 's-split #'safe/s-split)
        result))
    
    (dolist (formatter '(ob-ipython-format-output
                         ob-ipython-format-text/plain))
      (advice-add formatter :around #'advice/ob-ipython-format))

**Comment by federkamm** [comment]
Additionally, the callback in ob-ipython--execute-async only formats as :wrap_example as it fails to get the :results parameter.  A solution would be probably to replace most of the `org-babel-get-src-block-info` calls in scimax-org-babel-ipython-upstream.el by `org-babel-lob-get-info` which also works on babel-calls.

**Comment by jkitchin** [comment]
I tried implementing this. I think I found all of them. Let me know if it works for you.

**Comment by federkamm** [comment]
It works definitely better and I can use `#+call:` to call async src-blocks.  But I still get the result in an `example` block instead of a `drawer`.  I don't currently understand why this is the case but I'll try to find out, when I have time for it.

**Comment by federkamm** [comment]
I close this issue, but probably reopen a new one for the problem with the example block.

**Comment by jkitchin** [comment]
I just pushed a small change that improves this a bit I think. At least, I get this output now:

```
#+name: test
#+BEGIN_SRC ipython :async
import time
print('hello', time.asctime())
#+END_SRC

#+RESULTS: test
:results:
# Out [53]:
# output
hello Thu May  7 13:59:55 2020

:end:

#+call: test()

#+RESULTS:
:results:
# Out [54]:
# output
hello Thu May  7 13:59:58 2020

:end:
```
