### ISSUE TITLE
Super and Hyper on Windows (part 2)

### ISSUE THREAD

**Issue by AKielhorn** [jkitchin/scimax#362]
Hello,

there is an article about modifying the Windows keyboard in the german computer magazine c't (10/2020, p 146 ff).

This article has no relevance to this issue, it was just the reason for me to look into the Super/Hyper issue #179 again.

On many keyboards there are keys like "scroll lock" and "pause" that are rarely used.

There are some emacs commands that could be bound to these keys:

```
 (define-key function-key-map (kbd "<pause>") 'event-apply-super-modifier)
 (define-key function-key-map (kbd "<scroll>") 'event-apply-hyper-modifier)
```

These work as prefix keys, not as modifier keys, which I think is more convenient.

I found this information here:

[Stackoverflow](https://stackoverflow.com/questions/27418756/is-it-possible-to-make-emacs-interpet-an-fn-key-as-a-modifier-key)

It works fine on Windows 10 - 1909.

You may want to add the information to scimax.org.

To be honest, s-e is the only command I regularly use and I could have bound it to a different key combination.

Greeting
Axel

**Comment by jkitchin** [comment]
Thanks. I added this note to scimax.org.
