### ISSUE TITLE
How to run scimax as an independent installation

### ISSUE THREAD

**Issue by sbacelar** [jkitchin/scimax#363]
I always run `scimax` using `emacs -q -l scimax/init.el` in a `bat` file (in Windows) or using an `alias` (Mac and Linux), I am using `Emacs 26.3`.
I want to run `scimax` as an independent installation (I don't know exactly the word), but I don't know how to do it. 
I am using a profile switcher (`chemacs`) where I can define each installation profile. 
For `scimax` I am using these profiles in Windows:
```
(("default" . ((user-emacs-directory . "C:\Users\sbac\.emacs.d")))
 ("scimax" . ((user-emacs-directory . "C:\Users\sbac\scimax"))))
```
but when I run `emacs --with-profiles scimax` it doesn't run `init.el` from` scimax`.

**Comment by jkitchin** [comment]
I am not familiar with chemacs or --with-profiles. scimax should be independent, i.e. you don't have to run anything in it. what is wrong with the alias approach?

**Comment by sbacelar** [comment]
There is nothing wrong with the alias option. I was simply thinking how to run Scimax without using -q and -l options.

**Comment by sbacelar** [comment]
Thank you. It is solved. I had no problem switching between `Scimax` and other `emacs` distributions using `chemacs` in Linux (but not yet on Windows).

**Comment by zenny** [comment]
> I am not familiar with chemacs or --with-profiles. scimax should be independent, i.e. you don't have to run anything in it. what is wrong with the alias approach?

I like this vanilla way of launching stuffs without infringing other configs. Simply great work by Prof. @jkitchin ! :clap: :clap:
