### ISSUE TITLE
:results prameter not respected on #+call:

### ISSUE THREAD

**Issue by federkamm** [jkitchin/scimax#364]
Using

    #+call: my-babel-function()

does not respect `:results` parameter and puts the output always in a #+begin_/end_example block.

The callback in `ob-ipython--execute-async` does not forward the results parameter to `org-babel-insert-result` as they are differently formated for babel-calls and for src-blocks (unfortunatelly).

`(org-babel-get-src-block-info)` contains something that looks like `(:results-params "replace" "drawer")` whereas `(org-babel-lob-get-info)` would return something containing `(:results . "replace drawer")`.

It probably works to replace

    (cdr (assoc :result-params (nth 2 (or (org-babel-get-src-block-info)
                                      (org-babel-lob-get-info)))))

by

    (or (cdr (assoc :result-params (nth 2 (org-babel-get-src-block-info))))
        (s-split " " (or (cdr (assoc :results (nth 2 (org-babel-lob-get-info)))) "")))

**Comment by jkitchin** [comment]
see https://github.com/jkitchin/scimax/commit/a4533be8e503e3cb56f727674fdcb2d48273857e. It might help a little.

**Comment by federkamm** [comment]
That works for me!

It also merges all results parameter in the babel-call correctly:

    #+call: function[:results pre-parameter]() :results post-parameter

And it means, the parameters are applied that were active when the cell was executed, instead of the parameters, when the result gets inserted.  I think that is the more reliable behaviour.

Thank you!
