### ISSUE TITLE
Capture throws a json-readtable-error 84

### ISSUE THREAD

**Issue by sbacelar** [jkitchin/scimax#365]
Suddenly my `scimax` installation, when I try to use `capture` to edit for example on my journal, gives me an `json-readtable-error 84`. It opens the `journal.org` buffer but it doesn't show it in the main window. I have reinstalled `scimax` and `emacs` even the v. 27 without success.
These are the error messages (after `emacs -q -l scimax\init.el -debug-init`) 
```
Use M-x make-directory RET RET to create the directory and its parents
File mode specification error: (file-error Setting current directory Permission denied c:/Users/sbac/AppData/Roaming/Dropbox/org/notes/journal/)
apply: Setting current directory: Permission denied, c:/Users/sbac/AppData/Roaming/Dropbox/org/notes/journal/
Error in post-command-hook (yas-global-mode-check-buffers): (file-error "Setting current directory" "Permission denied" "c:/Users/sbac/AppData/Roaming/Dropbox/org/notes/journal/")
```
These are the error messages that appear when I open `scimax`:
```
ingesting c:/Users/sbac/scimax/scimax-lob/noweb.org
File mode specification error: (json-readtable-error 84)
1 source block added to Library of Babel
ingesting c:/Users/sbac/scimax/scimax-lob/lob.org
File mode specification error: (json-readtable-error 84)
21 source blocks added to Library of Babel
ingesting c:/Users/sbac/scimax/scimax-lob/kitchingroup.org
File mode specification error: (json-readtable-error 84)
```
My `scimax` installation on my Mac runs fine.

**Comment by sbacelar** [comment]
Sorry, this was making me insane. Most of the above problems were solved after updating `conda`.

**Comment by jkitchin** [comment]
weird. I guess it was related to a jupyter error then.
