### ISSUE TITLE
Eager expansion message for scimax-utils

### ISSUE THREAD

**Issue by Arjay-El** [jkitchin/scimax#366]
I have been getting this message just recently.
Eager macro-expansion failure: (end-of-file "c:/scimax/scimax-utils.el")

I ave been through scimax-utils but don't see what in scimax-utils would trigger an EOF error, it really hasn't changed.  Any suggestions?  Can this error be ignored? Thanks.

**Comment by jkitchin** [comment]
I don't think that is a new message. I have seen it for a while. It doesn't seem to do anything but be annoying. I think it comes from the f-string macro in that file. 

I converted this back to a function, which should get rid of that warning.
