### ISSUE TITLE
ipython src code not returning

### ISSUE THREAD

**Issue by jmpetit** [jkitchin/scimax#367]
Hello there,

thanks for this seemingly very nice piece of code. Unfortunately I cannot benefit from it as it fails to execute any ipython code.

I'm running LinuxMint 19.3, a derivative of Ubuntu 18.04. I have python (python2) installed for the system, and python3 (ipython, jupyter) for my work. Since I had problems installing scimax with the distribution's emacs25, I switched to the latest emacs-snapshot (28.0.50) as of today 2020-05-18. I also downloaded scimax today, and all seems good. After some digging, I had to customize
- elpy-rpc-python-command
- org-babel-python-command
- python-shell-interpreter
to "python3" since that's how my python is called.

Now, I open file scimax-ipython.org and try to execute the first code block:
```
#+BEGIN_SRC ipython
def f(x):
    print(x)
    return x**2

f(1.41)
#+END_SRC
```
In a fraction of a second, I get a message telling me that the kernel was created (0.04 or 0.05 secons), and then nothing. Emacs is frozen, the "waiting..." cursor keeps turning. I waited more than 10 mn each time, to no avail. I had to kill the emacs process from a shell.

Any idea what's going on ?

I've been using Emacs25 + orgmode + python for a year now, and really enjoy it. But I'd like/need to get ipython working, with interactive graphics, jupyter notebooks, ... That's why I grabbed scimax, which is claimed to provide all this.

Thnaks, Jean-Marc

**Comment by jkitchin** [comment]
scimax should provide all that. I guess this is related to a jupyter problem, e.g. some component is not updated, or is raising some kind of error that isn't communicated through. There are sometimes some buffers with details in them,  like *ob-ipython-out* or something like that with debug in them. Can you see if there is anything in those buffers that might be a hint?

I am only on emacs26 myself. I would be surprised if 28 was the origin of the problem though.

**Comment by jmpetit** [comment]
The problem is that emacs is frozen. Actaully, I was able to regain control by hitting "C-g". I looked at *ob-ipython-out*, it's empty. 
*ob-ipython-kernel-ipython-507ef191e55dc2e6003dc1c60a78057d* contains:
```
Jupyter console 6.1.0

Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: 
```
*Messages* contains:
```
...
Hy cmd not found. Install or activate a env with Hy.
executing Ipython code block...
Kernel started in 0.06 seconds
Waiting for process to die...done
Quit
...
```
I guess the last bit is due to "C-g".

Regards, Jean-Marc

**Comment by jmpetit** [comment]
Hello,
I finally got it running. The problem was due to 2 different initializations of Jupyter which I mangled at some point. I deleted all directories for Jupyter and restarted emacs, which regenerated some initialisation of Jupyter. Now it behaves almost as expected. I mean, the output is almost what was shown in the recorded output of scimax-ipython.org:

In the original file, there is:
```

#+BEGIN_SRC ipython
print(1 / 0)
#+END_SRC

#+RESULTS:
:RESULTS:
# Out[7]:
# output

ZeroDivisionErrorTraceback (most recent call last)
<ipython-input-7-3ec96714f820> in <module>()
----> 1 print(1 / 0)

ZeroDivisionError: division by zero
:END:
```
while when I re-run it, I get:
```
#+RESULTS:
:results:

ZeroDivisionErrorTraceback (most recent call last)
<ipython-input-7-3ec96714f820> in <module>
----> 1 print(1 / 0)

ZeroDivisionError: division by zero
:end:
```
As you can see, I've lost the
```
# Out[7]:
# output
```
part.

Regards, Jean-Marc

**Comment by jkitchin** [comment]
Those are controlled by some variables, e.g. `ob-ipython-execution-count` and `ob-ipython-show-mime-types`. Maybe these are set to something that suppresses those outputs, or the defaults changed since the example you are looking at was written. Otherwise, it looks like it is working to me.

**Comment by jmpetit** [comment]
Hi John,

indded, that what I just figured out. I was going in sequence in file scimax-ipython.org, and I executed the block
```
#+BEGIN_SRC emacs-lisp
(setq ob-ipython-execution-count 'ob-ipython-execution-count-suppress)
#+END_SRC
```
which turned off that part of the output. Mystery solved.
