### ISSUE TITLE
ipython src code not returning - The return

### ISSUE THREAD

**Issue by jmpetit** [jkitchin/scimax#368]
Hello John,

sorry for starting this new thread, but the previous one is closed.

I just found out that the issue is recurrent. I mean, every time I close emacs and re-start it, I have this behaviour of ipython src code not returning after execution. The kernel is started, but the execution doesn't return. To solve the problem I have to clear some jupyter directory (in my case, `\rm -rf ~/.local/share/jupyter`). This is annoying, and potentially unaffordable if I have a jupyter notebook running elsewhere, in a browser say.

Any idea ?

Regards, Jean-Marc

**Comment by jkitchin** [comment]
Is it the same issue regarding Hy? 

That was a strange error before, it is (i believe) related to the Hy lang, but scimax should not be doing anything to cause that error.

In scimax-org.el there is one small section that does configure jupyter-hy (search for jupyter-hy blocks).

what is in the directory ~/.local/share/jupyter? I guess just deleting the right files would help figure out what the issue is.

**Comment by jmpetit** [comment]
The message regarding Hy is present each time I start the kernel, when I execute the first ipython src block. It's there whether the code returns (I've deleted ~/.local/share/jupyter) or not (I haven't). So this is not the reason for the bug. Somehow starting the kernel tries to also configure jupyter-hy.

~/.local/share/jupyter is a directory that holds some files to communicate with the kernel. There is a directory `runtime` inside which contains the json file. Maybe just killing the json file will be enough. However, it's trange as this file is re-created each time I launch the kernel.

Weird. Regards, Jean-Marc

**Comment by jkitchin** [comment]
That stuff with Hy should not be happening though. 

Those kernel files should get re-created each time you start the kernel, as it contains information about the kernel. I would expect that a new file is created each time, unless you have some default session name specified.
