### ISSUE TITLE
Python highlighting broken from added code to highlight f-strings

### ISSUE THREAD

**Issue by JSpenced** [jkitchin/scimax#369]
This might only be an Emacs 27 issue, but highlighting for python-mode stopped working when I upgraded scimax. I looked through the log of changes and found your f-string code might have been the culprit. 

If I remove that, then I get my highlighting back. I customize the colors heavily and figured maybe it was code I added that messed with your font-lock-code. I checked on a vanilla install of scimax and highlighting still doesn't work. I have pasted an image below from a vanilla install. 

I am running emacs-27 latest head on a mac, so any suggestions would be great. I can try to help debug.

![image](https://user-images.githubusercontent.com/43424787/85936588-4b08e480-b8ca-11ea-929e-dda1bbe2ef27.png)

**Comment by jkitchin** [comment]
I guess you should just comment that code out. I don't know why there would be a version issue with it, the font-lock code looks pretty simple. Are there any messages about font lock errors in *Messages*?

**Comment by JSpenced** [comment]
Nope, I didn't see any errors. I was just surprised it happened on a vanilla install of scimax. I was curious if others with osx have any issues but I guess not.

**Comment by jkitchin** [comment]
Why do you suspect osx? I run scimax on a Mac also, but I am still on 26.3 for Emacs.

**Comment by JSpenced** [comment]
Okay, I wasn't sure if it was emacs 27 or maybe osx-based. I will comment
out the code for now. Maybe when emacs-27 is fully released we can see if
it works from your end.

Thanks

**Comment by JSpenced** [comment]
I was installing this on linux with emacs 26, and these issues don't arise. Should I leave it open for now because maybe it is emacs 27 related, but I think that is supposed to be released soon?

**Comment by jkitchin** [comment]
I guess it is fine to leave open. I am not sure when I will be updating to emacs 27.

**Comment by dangom** [comment]
As an alternative to font-lock, you can use Emacs Tree Sitter to get f-string highlighting. 
See more info at https://github.com/ubolonton/emacs-tree-sitter
It's yet another dependency, but works quite nicely provided you compile Emacs with support for modules.

**Comment by jkitchin** [comment]
it looks like this has been commented out for a while. closing.
