### ISSUE TITLE
[SOLVED] Citations were exported to `?` symbols

### ISSUE THREAD

**Issue by zenny** [jkitchin/scimax#370]
@jkitchin Thanks for this package, and new to org-mode. Inspired by your 2016 workflow ( https://www.youtube.com/watch?v=2t925KRBbFc), I tried to reproduce. However, when exported to pdf (`C-c C-e l p`), the output has got citations shown as `?` (question marks)! :(

BTW, I found similar old issue #264, but I could not figure out the `natbib` package in with `M-x package-list`. Did I miss anything? I am in linux, fyi.

Has the workflow changed with recent release of scimax? If so, I (maybe the research community) appreciate if you can post your current workflow of note-taking and academic writing in relation to scimax. 

Just my two cents.

Cheers, and stay safe,
/z

**Comment by jkitchin** [comment]
Nothing has changed. The main reason you would get a ? is if you didn't define a bibliographystyle and bibliography link.  Another possibility is you don't have your `org-latex-pdf-process` setup to run bibtex. One way to check is to try manually building the pdf at the command line.

**Comment by zenny** [comment]
> Nothing has changed. The main reason you would get a ? is if you didn't define a bibliographystyle and bibliography link. Another possibility is you don't have your `org-latex-pdf-process` setup to run bibtex. One way to check is to try manually building the pdf at the command line.

Thanks for your prompt response. 

I have inserted bibliographystyle (unsorted) and bibiliography link (covid-19.bib which contains the bibtex entries):

```
bibliographystyle:unsrt
bibliography:covid-19.bib
```
How can one list available `bibliographystyle`s withing scimax?

Fyi, I am using the same configuration as with your upstream. So what do I need to config to make `org-latex-pdf-process` without breaking your default configs?

Cheers,

**Comment by zenny** [comment]
@jkitchin An internet search point to a relevant link (https://www.reddit.com/r/emacs/comments/gqmvlr/latex_pdf_export_error/) to setup `org-latex-pdf-process` to run bibtex, but the problem persisted.

However, I managed to troubleshoot using the inputs from @bpalmer and @wrycode in the #emacs IRC by running `rubber` (https://www.systutorials.com/docs/linux/man/1-rubber/) and `pdflatex file.tex && pdflatex file.tex && bibtex file.aux && pdflatex file.tex` to figure out the exact error.

Actually the culprit was the reference entry which was imported by `doi-add-bibtex-entry`:

@INPROCEEDINGS{Cutrell01notification,disruption,,
    author = {Edward Cutrell and Mary Czerwinski and Eric Horvitz},
    title = {Notification, Disruption, and Memory: Effects of Messaging Interruptions on Memory and Performance},
    booktitle = {},
    year = {2001},
    pages = {263--269},
    publisher = {IOS Press}
}
```

Changing the entry to:

```
@INPROCEEDINGS{Cutrell01notification,
    author = {Edward Cutrell and Mary Czerwinski and Eric Horvitz},
    title = {Notification, Disruption, and Memory: Effects of Messaging Interruptions on Memory and Performance},
    booktitle = {Proceedings of Interact 2001},
    year = {2001},
    pages = {263--269},
    publisher = {IOS Press}
}
```

solved the issue.

Cheers,
/z

**Comment by jkitchin** [comment]
> > Nothing has changed. The main reason you would get a ? is if you didn't define a bibliographystyle and bibliography link. Another possibility is you don't have your `org-latex-pdf-process` setup to run bibtex. One way to check is to try manually building the pdf at the command line.
> 
> Thanks for your prompt response.
> 
> I have inserted bibliographystyle (unsorted) and bibiliography link (covid-19.bib which contains the bibtex entries):
> 
> ```
> bibliographystyle:unsrt
> bibliography:covid-19.bib
> ```
> 
> How can one list available `bibliographystyle`s withing scimax?
> 
> Fyi, I am using the same configuration as with your upstream. So what do I need to config to make `org-latex-pdf-process` without breaking your default configs?
> 
> Cheers,

I think yasnippet at https://github.com/jkitchin/scimax/blob/master/snippets/org-mode/org-ref/bibliographystyle will give you a list of styles you can choose from. They are defined in a variable at https://github.com/jkitchin/scimax/blob/master/snippets/org-mode/.yas-setup.el#L74.

**Comment by jkitchin** [comment]
Also, in your org-file if you run M-x org-ref, it might tell you that there is an invalid bibtex file.

**Comment by zenny** [comment]
> Also, in your org-file if you run M-x org-ref, it might tell you that there is an invalid bibtex file.

It didn't in my case as seen in the screenshot posted here: https://paste.pics/9FXNL, fyi.

**Comment by jkitchin** [comment]
I can see from your screenshot that your `org-latex-pdf-process` does not include running bibtex. See https://github.com/jkitchin/org-ref/blob/master/org-ref.org#latex-export for some help in correcting that.

**Comment by zenny** [comment]
> I can see from your screenshot that your `org-latex-pdf-process` does not include running bibtex. See https://github.com/jkitchin/org-ref/blob/master/org-ref.org#latex-export for some help in correcting that.

As I have posted earlier, I have already have the following lines to use luatex as stated above in https://github.com/jkitchin/scimax/issues/370#issuecomment-651610140:

```
org-latex-pdf-process
	'("%latex -8bit -interaction nonstopmode -shell-escape -output-directory %o %f"
	  "%latex -8bit -interaction nonstopmode -shell-escape -output-directory %o %f"
	  "%latex -8bit -interaction nonstopmode -shell-escape -output-directory %o %f"))
```

Is there any reason to use pdflatex again? Just confused.

**Comment by jkitchin** [comment]
latex always takes a few passes to get everything right. e.g. First pass to find out where citations go. then bibtex to get the citation info. then 1-2 more passes may be required to resolve all cross-references. It isn't always like that, and depends on your document. tools like latexmk try to monitor the messages and only run latex as many times as needed.
