### ISSUE TITLE
Citation in content/body in the format of [AUTHOR et al., YEAR] instead of superscript numerals?

### ISSUE THREAD

**Issue by zenny** [jkitchin/scimax#371]
Hi,

How can one export citations inside the body/content of an org output to appear in the format of [AUTHOR et al.,YEAR] instead of the superscript reference numerals?

Cheers, and stay safe,
/z

**Comment by jkitchin** [comment]
If you are exporting to latex, this is done by choosing a different bibliographystyle, or by using a different cite command, e.g. citep. see https://gking.harvard.edu/files/natnotes2.pdf for some tips.

**Comment by zenny** [comment]
> If you are exporting to latex, this is done by choosing a different bibliographystyle, or by using a different cite command, e.g. citep. see https://gking.harvard.edu/files/natnotes2.pdf for some tips.

Thanks for extremely useful pointer, @jkitchin.

**Comment by zenny** [comment]
Hi again, @jkitchin 

I tried with ` citep:vivantiTransplacentalTransmissionSARSCoV2202` within the org document which produced correct syntax in the TEX file produced as `\citep{vivantiTransplacentalTransmissionSARSCoV22020}`, but when exported to PDF file, it did not produce the in-body citation which reportedly should look like `(Vivanti et al., 2020)` as described in the link you referred to (https://gking.harvard.edu/files/natnotes2.pdf.

I am using `bibliographystyle:unsrt`. (

BTW, how do I get a list of `bibiliographystyle`?

Cheers, and stay safe,
/z

**Comment by zenny** [comment]
Meanwhile, I have chosen Elsevier as `bibliographystyle` from a scimax-manuscript template (`M-x ox-manuscript-new-ivy`):

```
bibliographystyle:elsarticle-num
bibliography:references.bib
```

Elsevier style is supposed to cite in `AUTHOR, YYYY` format in final pdf, but still citing in numbers (_See next to the text_ `QUOTE` _in the screenshot_).

![pic-selected-200722-0829-20](https://user-images.githubusercontent.com/1653166/88142344-a2fae880-cbf5-11ea-9205-a78689c33848.png)

Any inputs to get the `AUTHOR, YYYY` citation format would be highly appreciated. Thanks and stay safe,

**Comment by zenny** [comment]
Thanks to Prof. @jkitchin's clear explanation in #378 which solved this issue.
