### ISSUE TITLE
Inkscape link to preview inline

### ISSUE THREAD

**Issue by OmarAshkar** [jkitchin/scimax#372]
I am using the inkscape link script and it works great except for one enhancement that I want to request. If I changes the link to be 
[[file:draw.svg]] instead of [[inkscape:draw.svg]], I can preview the drawing inline. It would be great if I can toggle to inline previewing without changing the url type.

**Comment by jkitchin** [comment]
That doesn't sound right, you should see a preview, e.g. what I see is something like this:

![image](https://user-images.githubusercontent.com/1610070/86953927-2959f980-c123-11ea-8bb2-a3b3d229580e.png)

and it gets toggled with C-c C-x C-v.

**Comment by omarelashkar** [comment]
> That doesn't sound right, you should see a preview, e.g. what I see is something like this:
It says there is no inline image found there!
