### ISSUE TITLE
ob-ipython, non-standard kernels, and missing mime-types

### ISSUE THREAD

**Issue by roblem** [jkitchin/scimax#373]
I am using a "non-standard" kernel  (stata_kernel) with jupyter notebook and everything works fine.  I am able to execute valid stata code and results (both text and graphical output) display fine.

I can use the stata_kernel via ob-ipython (the scimax version) using a header containing `ipython :kernel stata :session`.  I can execute code fine and results display as expected as long as there is text output only.  When I try to run code that generates a figure (e.g. a histogram) that runs fine in jupyter notebook, I get this error:
```
cdr: Wrong type argument: listp, "JVBERi0xLjMKJbe <lots more gibberish here>"
```
So I went back to my jupyter notebook `ipynb` file containing the same code and inspected the cell mime-types and see this:
```"outputs": [
    {
     "data": {
      "application/pdf": "JVBERi0xLjMKJbe <lots more gibberish here indentical to above>"
      "image/svg": "....."
```
It is worth noting that `image/png` isn't being returned.  So it appears that `stata_kernel` is returning a mime-type that ob-ipython doesn't know about which causes the error.  I tried adding a custom mime-type for `application/pdf` as mentioned [in your documentation of ipython](https://github.com/jkitchin/scimax/blob/master/scimax-ipython.org), but was never successfully able to avoid the error message mentioned above.

I was able to avoid the error message and display the svg data by using this header: `ipython :session :kernel stata :results output drawer :display image/svg+xml`.  This works pretty well but isn't exportable into pdf- rather than displaying the image a file link is displayed pointing to an svg in the obipy-resources folder. 

At `stata_kernel` they say they add the `application/pdf` output explicitly for exporting the notebook to pdf using nbconvert.  I am wondering if registering a proper formatter for pdf would allow me to do something similar, and if so how do I do that?   

As always, thanks in advance.

**Comment by roblem** [comment]
I should add that I am able to save the figures to disk and then reference them in the orgmode document, so there is a viable workaround for the exporting issues.  Just wondering if adding the pdf mimetype might overcome some of these steps.

**Comment by roblem** [comment]
I am going to withdraw this question.  Using `emacs-jupyter` rather than `ob-ipython` alleviates most of the problems outlined above, and so far I haven't noticed any glitches when running on top of `scimax`.

**Comment by jkitchin** [comment]
> I am going to withdraw this question. Using `emacs-jupyter` rather than `ob-ipython` alleviates most of the problems outlined above, and so far I haven't noticed any glitches when running on top of `scimax`.

I think emacs-jupyter is the right solution to this. I haven't had time to make sure that would work easily across windows/mac/linux for scimax yet. When I do, I think scimax will also switch.
