### ISSUE TITLE
Installation via straight.el?

### ISSUE THREAD

**Issue by jsigman** [jkitchin/scimax#374]
I've tried to approximate this myself, but it gets pretty complicated.

```lisp
(straight-use-package 'gitter)
(straight-use-package 'emacsql-sqlite)
(straight-use-package '(scimax :type git
                                        :host github
                                        :repo "jkitchin/scimax"))
(set-variable 'scimax-dir (concat (file-name-as-directory user-emacs-directory) "straight/build/scimax"))
(add-to-list 'load-path scimax-dir)
```
Beyond this, I don't see an easy way to import the submodules for ob-ipython and the like. All I really want is `ob-ipython`, so maybe I should go to the upstream version again.

**Comment by shrysr** [comment]
> Beyond this, I don't see an easy way to import the submodules for ob-ipython and the like. All I really want is `ob-ipython`, so maybe I should go to the upstream version again.

I am using quite a bit of Scimax goodies in my config, and it is done through straight. Here are the ob-ipython bits, and I've been using this for several months now as my daily driver. Note: I'm not entirely sure this is the best or 'right' approach.

```
    (use-package ob-ipython
      :straight (ob-ipython 
		 :host github 
		 :repo "gregsexton/ob-ipython" 
		 :files ("client.py" "ob-ipython.el"))
      :config
      (require 'ob-ipython))

  ;;; * Applying John's customisations and monkeypatches
  ;;; These are related to ipython kernel management
  ;;; * These  are related mostly to org-babel customisations

    (use-package scimax-ob
      :straight (scimax-ob 
		 :repo "git@git.sr.ht:~shrysr/scimax-subset" 
		 :files ("scimax-ob.el")))

    (use-package scimax-org-babel-ipython-upstream
          :straight (scimax-org-babel-ipython-upstream 
		     :repo "git@git.sr.ht:~shrysr/scimax-subset" 
		     :files ("scimax-org-babel-ipython-upstream.el")))


```

So the above uses scimax-ob that is sourced from a fork of Scimax from 3-4 months back, i.e. my fork does not contain 'all of scimax', is not updated with the latest commits, and I use a few more, including most of the Org mode customisations from Scimax. A diff of scimax-ob.el may help.

Iirc - the packages used in the fork do not have any major modifications other than commenting out some parts, and converting =use-package= to =straight-use-package= or adding =:straight t= and removing =:ensure t= as straight apparently does not require this.

I believe that the above method can be used with the official scimax repo instead if you wish. The 'files' argument helps in installing a particular package from a 'single' repo.

If it helps, my current Emacs configuration using parts of scimax : https://github.com/shrysr/.emacs.d

**Comment by jkitchin** [comment]
I am not familiar with straight.el. It seems like the easier path is to just clone scimax, and add the directories you want to your load-path, then load what you want.

**Comment by shrysr** [comment]
> It seems like the easier path is to just clone scimax, and add the directories you want to your load-path, then load what you want.

This was the first thing I tried. I think I ended up needing to load Scimax the way it is loaded (entirely) to get to some scimax-packages, due to inter-dependencies. In trying to resolve the tramp issue #349 - I wanted to whittle down Scimax to find the culprit (which I have not). 

> just clone scimax, and add the directories you want to your load-path, then load what you want.

In essence, straight.el does this for you. There are other options as their readme mentions. It clones the specified package as a git repo and then byte-compiles the package. Being a git repo, it is easy to switch to a custom branch or freeze packages as desired. If say the package is commented out, then it is not loaded afaik.

I have found straight.el to be more reliable to quickly jumpstart my configuration in a fresh computing instance. I've mostly had trouble using Scimax's install scripts on new Linux instances due the well discussed issues of connecting to MELPA and gnutls versions. Using straight would only require an initial bootstrap to be done once.

@jkitchin, I was thinking it may be very cool if Scimax is designed using something like straight.el - i.e it would mean scimax maintains its integrity as now, but also allows users to access internal scimax-packages separately. It would be easy to update specific packages, while still keeping the main scimax-repo up-to-date and also experiment in a controlled manner using Scimax as a whole, or with parts of Scimax.

**Comment by zenny** [comment]
> It seems like the easier path is to just clone scimax, and add the directories you want to your load-path, then load what you want.
> This was the first thing I tried. I think I ended up needing to load Scimax the way it is loaded (entirely) to get to some scimax-packages, due to inter-dependencies. In trying to resolve the tramp issue #349 - I wanted to whittle down Scimax to find the culprit (which I have not).
> just clone scimax, and add the directories you want to your load-path, then load what you want.
> In essence, straight.el does this for you. There are other options as their readme mentions. It clones the specified package as a git repo and then byte-compiles the package. Being a git repo, it is easy to switch to a custom branch or freeze packages as desired. If say the package is commented out, then it is not loaded afaik. I have found straight.el to be more reliable to quickly jumpstart my configuration in a fresh computing instance. I've mostly had trouble using Scimax's install scripts on new Linux instances due the well discussed issues of connecting to MELPA and gnutls versions. Using straight would only require an initial bootstrap to be done once. @jkitchin, I was thinking it may be very cool if Scimax is designed using something like straight.el - i.e it would mean scimax maintains its integrity as now, but also allows users to access internal scimax-packages separately. It would be easy to update specific packages, while still keeping the main scimax-repo up-to-date and also experiment in a controlled manner using Scimax as a whole, or with parts of Scimax.

@jkitchin, @jsigman and @shrysr: Yep, the approach @shrysr suggested shall give a flair of Doom-emacs where the main distribution is separated from the user-specific configuration of init, config and packages. Right now, I am using doom, just because of the evil-mode (RSI issues) and nifty issues with the theme-rendering with scimax (same monochrome theme gets rendered differently in scimax and doom, the latter looks better at par with someone suffering from tetrachromat and palinopsia.

Cheers, and stay safe,
/z

**Comment by shrysr** [comment]
> with the theme-rendering with scimax (same monochrome theme gets rendered differently in scimax and doom

On that and a separate note, I would like to heartily recommend Scimax and Leuven theme lovers to check out the Modus themes (https://gitlab.com/protesilaos/modus-themes) with the recently added supported for colored source code blocks and Org headings. It is very Leuven like now, but then with significantly more customisation options, better design and excellent documentation. It also works well on the terminal, which Leuven probably does not(?). I have found it to be very pleasant, even before the colored source blocks. 

> Right now, I am using doom, just because of the evil-mode (RSI issues)

@zenny, Sorry to hear about the RSI issues. I worry about this, and there was an earlier discussion on it too. I have fully and shamelessly copied Scimax's hydra functions for my config. In addition, I've been slowly building my own combination of nested hydras for different packages like perspective-el, eyebrowse, jumping around org-journal files, and the semi-modal approach has certainly been reducing the time and effort spent in M-x'ing and typing or holding Ctrl. Check out : https://github.com/shrysr/.emacs.d/blob/master/emacs-config.org#hera

**Comment by zenny** [comment]
> with the theme-rendering with scimax (same monochrome theme gets rendered differently in scimax and doom
> On that and a separate note, I would like to heartily recommend Scimax and Leuven theme lovers to check out the Modus themes (https://gitlab.com/protesilaos/modus-themes) with the recently added supported for colored source code blocks and Org headings. It is very Leuven like now, but then with significantly more customisation options, better design and excellent documentation. It also works well on the terminal, which Leuven probably does not(?). I have found it to be very pleasant, even before the colored source blocks.

Thanks for the input, but for someone who has tetrachromat (who has an extra layer of filter in the eye and makes different color appear in layers as if in 3D with red on the back and white on the top), the modus-theme appears to be extremely colorful! ;-)

> Right now, I am using doom, just because of the evil-mode (RSI issues)
> @zenny, Sorry to hear about the RSI issues. I worry about this, and there was an earlier discussion on it too. I have fully and shamelessly copied Scimax's hydra functions for my config. 

Thanks, but I could not figure out whether your customization goes to the @jkitchin's `scimax`s `/user` folder or just run directly `emacs -q -l /path/to/your/.emacs.d`?

>In addition, I've been slowly building my own combination of nested hydras for different packages like perspective-el, eyebrowse, jumping around org-journal files, and the semi-modal approach has certainly been reducing the time and effort spent in M-x'ing and typing or holding Ctrl. Check out : https://github.com/shrysr/.emacs.d/blob/master/emacs-config.org#hera

@shrysr Would you mind elaborating a bit more about your customization? Thanks.

**Comment by jsigman** [comment]
@jkitchin On a side note, straight.el is a really great tool, I've found. It manages all installation, so I can download emacs on a new machine and from just the configs end up with everything installed and running.
