### ISSUE TITLE
Any pointers to some specific tasks?

### ISSUE THREAD

**Issue by zenny** [jkitchin/scimax#377]
Hi,

I have gone through scimax.org (info scimax) several times. Some of the issues that I could not achieve as stated in the manuals are:

1. The second part (maths, chemistry formula) of the autoformat, despite appending the lines to the user.el
```
;;; autoformat
(add-hook 'org-mode-hook 'scimax-autoformat-mode)
(scimax-toggle-abbrevs 'scimax-month-abbreviations +1)
(scimax-toggle-abbrevs 'scimax-weekday-abbreviations +1)
(scimax-toggle-abbrevs 'scimax-contraction-abbreviations +1)
(scimax-toggle-abbrevs 'scimax-transposition-abbreviations +1)
(scimax-toggle-abbrevs 'scimax-chemical-formula-abbreviations +1)
(scimax-toggle-abbrevs 'scimax-misc-abbreviations +1)
```

2. Under org-ref, I could not figure out how to cite a paper in `AUTHOR et.al (if more than 3), YYYY` format. Manually appending `cite` to `citep` did not appear to change. Details are posted here: https://github.com/jkitchin/scimax/issues/371 (SOLVED in #378, kudos to @jkitchin).
3. Could not figure out how to cite a URL in a specific `bibliographystyle` from within scimax.
4. Autoformat the long lines in the table despite appending `ltablex` code as well as `tabularx` and tabulary :

```
;;https://emacs.stackexchange.com/questions/32347/how-to-have-wrapped-text-when-exporting-from-org-to-latex?rq=1
;;(add-to-list 'org-latex-packages-alist '("" "tabularx"))
;; https://gitlab.com/OlMon/emacs_config/commit/56086b52c69f1a5b3e5134eee1195f21ca697bc1
;; Latex export additional packges
;;(add-to-list 'org-latex-packages-alist '("" "tabularx"))
;;(add-to-list 'org-latex-packages-alist '("" "tabulary"))
;; https://github.com/w4nderlust/ltablex-fixed/raw/master/ltablex.sty
(require 'ox-latex)
(add-to-list 'org-latex-packages-alist'("" "ltablex"))
```
5. Break pages for specifc headers like `Contents` if needed.

6. Modal editing (tried with xah-fly-keys, meow and kakoune.el) but never smooth as in doom-emacs.

7. Same theme (gruvbox, monochrome. I prefer latter due to some eye issues with colors) appears differently in doom (actually using sunnyhacija's repo with modifications) and scimax.

Appreciate if anyone can throw light on any of the above aspects categorically? I asked here because most of the users here are experienced in academic documents. Thanks in advance.

Cheers, and stay safe
/z

**Comment by zenny** [comment]
I appreciate if anyone could give a hint on 
A. 2 above (regarding citation) 
B. 4 above (regarding justifying lines in tables)
C. 5 above (break pages for specific headers.

Thanks in advance. 

Cheers,

**Comment by jkitchin** [comment]
A. See https://orgmode.org/manual/Tables-in-LaTeX-export.html. There are a bunch of ways to control how tables are exported.

B. The usual ways I add page breaks is to use \newpage. This only works for latex export.

**Comment by zenny** [comment]
> A. See https://orgmode.org/manual/Tables-in-LaTeX-export.html. There are a bunch of ways to control how tables are exported.

Prof. @jkitchin, Thanks for the pointer, I did visit the link you provided several times. I tried many ways including the one described in https://emacs.stackexchange.com/a/32353. 

I tried with the following code:

```
#+latex_class: elsarticle
#+latex_class_options: [12pt,authoryear]


Test sentence with regular cite cite:vivantiTransplacentalTransmissionSARSCoV22020.

Citation with multiple authors without brackets cite*:pique-regiDoesHumanPlacenta2020

Test sentence with citep citep:pique-regiDoesHumanPlacenta2020.

Citation with multiple authors in brackets citep*:vivantiTransplacentalTransmissionSARSCoV22020

Table with long lines:

#+CAPTION: /How to wrap table with long lines in pdf output?/
#+ATTR_LATEX: :environment ltablex :width \textwidth :align lXl
| Keybinding  | Function                                                                                                                                                                                                                                                                                           | Execution                                                                                                                                                                        |
|-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| C-x C-c     | Exit                                                                                                                                                                                                                                                                                                | Press `Control` Key and letter `x` first and release. Thereafter press `Control` Key and letter `c`.                                                                             |
| C-c C-e l o | This exports the org-document first to `tex` and then to searchable `pdf` and opens within emacs browser if `pdf-tools` and `org-pdf-tools` are installed and configured. To get desired output, you may need to append some `#+LATEX` header, class and options fields inline of the org-document. | Press `Control` Key and letter `c` first and release. Thereafter press `Control` Key and letter `e` and release. Lastly press letter `l`, followed by `o` (not at the same time) |
| C-c ]       | This inserts a an org-ref citation                                                                                                                                                                                                                                                                  | Press `Control` Key and letter `x` first and release. Thereafter press `Control` Key and letter `c`.                                                                                                                                                                           |
bibliographystyle:elsarticle-num-names
bibliography:Medical.bib
```
The code above produced a pdf as garbled wrap as seen below:

![pic-selected-200725-0804-19](https://user-images.githubusercontent.com/1653166/88450374-c7053680-ce4e-11ea-8bd3-aa4251165c77.png)

The code without table attribution (`#+ATTR_LATEX: :environment ltablex :width \textwidth :align lXl`) produced a pdf with the long lines bled out of the page on the right side as seen below:

![pic-selected-200725-0808-05](https://user-images.githubusercontent.com/1653166/88450409-ff0c7980-ce4e-11ea-859e-8f6c7a6b2403.png)
 

> 
> B. The usual ways I add page breaks is to use \newpage. This only works for latex export.

Thanks for extremely valuable input. :+1:

**Comment by jkitchin** [comment]
> > A. See https://orgmode.org/manual/Tables-in-LaTeX-export.html. There are a bunch of ways to control how tables are exported.
> 
> Prof. @jkitchin, Thanks for the pointer, I did visit the link you provided several times. I tried many ways including the one described in https://emacs.stackexchange.com/a/32353.
> 
> I tried with the following code:
> 
> ```
> #+latex_class: elsarticle
> #+latex_class_options: [12pt,authoryear]
> 
> 
> Test sentence with regular cite cite:vivantiTransplacentalTransmissionSARSCoV22020.
> 
> Citation with multiple authors without brackets cite*:pique-regiDoesHumanPlacenta2020
> 
> Test sentence with citep citep:pique-regiDoesHumanPlacenta2020.
> 
> Citation with multiple authors in brackets citep*:vivantiTransplacentalTransmissionSARSCoV22020
> 
> Table with long lines:
> 
> #+CAPTION: /How to wrap table with long lines in pdf output?/
> #+ATTR_LATEX: :environment ltablex :width \textwidth :align lXl
> | Keybinding  | Function                                                                                                                                                                                                                                                                                           | Execution                                                                                                                                                                        |
> |-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
> | C-x C-c     | Exit                                                                                                                                                                                                                                                                                                | Press `Control` Key and letter `x` first and release. Thereafter press `Control` Key and letter `c`.                                                                             |
> | C-c C-e l o | This exports the org-document first to `tex` and then to searchable `pdf` and opens within emacs browser if `pdf-tools` and `org-pdf-tools` are installed and configured. To get desired output, you may need to append some `#+LATEX` header, class and options fields inline of the org-document. | Press `Control` Key and letter `c` first and release. Thereafter press `Control` Key and letter `e` and release. Lastly press letter `l`, followed by `o` (not at the same time) |
> | C-c ]       | This inserts a an org-ref citation                                                                                                                                                                                                                                                                  | Press `Control` Key and letter `x` first and release. Thereafter press `Control` Key and letter `c`.                                                                                                                                                                           |
> bibliographystyle:elsarticle-num-names
> bibliography:Medical.bib
> ```
> 
> The code above produced a pdf as garbled wrap as seen below:
> 
> ![pic-selected-200725-0804-19](https://user-images.githubusercontent.com/1653166/88450374-c7053680-ce4e-11ea-8bd3-aa4251165c77.png)
> 
> The code without table attribution (`#+ATTR_LATEX: :environment ltablex :width \textwidth :align lXl`) produced a pdf with the long lines and the third column bled out of the page (even sight) in the right side of the screenshot as of below:
> 
> ![pic-selected-200725-0808-05](https://user-images.githubusercontent.com/1653166/88450409-ff0c7980-ce4e-11ea-859e-8f6c7a6b2403.png)
> 
> However, I do realize that this is not a scimax issue, but LATEX export issues. Just trying to get some inputs from seasoned scimaxer. ;-)
> 
> > B. The usual ways I add page breaks is to use \newpage. This only works for latex export.
> 
> Thanks for extremely valuable input. 👍

You need to change a few things here. One is make sure to include the right packages at the top for LaTeX:

I used this:

#+latex_header: \usepackage{tabularx}
#+latex_header: \usepackage{float}

I think the elsarticle org definition does not use any default packages, so you have to include everything.

Then I changed the table to:
#+CAPTION: /How to wrap table with long lines in pdf output?/
#+ATTR_LATEX: :environment tabularx :width \textwidth :align llX :placement [H]
| Keybinding  | Function        | Execution                                                                                                                                                                        |
|-------------+-----------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|             |                 |                                                                                                                                                                                  |
| C-x C-c     | Exit            | Press `Control` Key and letter `x` first and release. Thereafter press `Control` Key and letter `c`.                                                                             |
| C-c C-e l o | Export          | Press `Control` Key and letter `c` first and release. Thereafter press `Control` Key and letter `e` and release. Lastly press letter `l`, followed by `o` (not at the same time) |
| C-c ]       | Insert citation | Press `Control` Key and letter `x` first and release. Thereafter press `Control` Key and letter `c`.                                                                             |

It is asking a lot for LaTeX to figure out how to make this table with overflowing text in the middle and last columns. I shortened one cell in the middle column, and moved the X to the last column.

**Comment by zenny** [comment]
> | Keybinding | Function | Execution |
> |-------------+-----------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
> | | | |
> | C-x C-c | Exit | Press `Control` Key and letter `x` first and release. Thereafter press `Control` Key and letter `c`. |
> | C-c C-e l o | Export | Press `Control` Key and letter `c` first and release. Thereafter press `Control` Key and letter `e` and release. Lastly press letter `l`, followed by `o` (not at the same time) |
> | C-c ] | Insert citation | Press `Control` Key and letter `x` first and release. Thereafter press `Control` Key and letter `c`. |

This is extremely helpful. :+1: @jkitchin. However, just consulting with https://texblog.org/2019/06/03/control-the-width-of-table-columns-tabular-in-latex/

Thanks anyway for confirming it is not possible to format random length of contents in org tables.

**Comment by jkitchin** [comment]
The problem is not in org-tables, it is in LaTeX.  It is usually possible to do anything (reasonable) in org that can reasonably done in LaTeX.
