### ISSUE TITLE
[REQUEST] Include optional styles in elarticle-template

### ISSUE THREAD

**Issue by zenny** [jkitchin/scimax#378]
Hi @jkitchin 

As discussed in https://github.com/jkitchin/scimax/issues/371#issuecomment-662270938, there are two resources which I found it essential to include in the elarticle-template to make it easier in citation for researchers:

1. https://tex.stackexchange.com/questions/199294/elsarticle-not-working-with-citep (AUTHOR et. al., YYYY issue)
2. https://tex.stackexchange.com/questions/246791/author-number-citation-with-elsarticle (Other inline citation styles)

If you can incorporate the two styles above into scimax, it would save hundreds of hours of scimax-/emacs-/org-mode-/org-ref-uninitiated users like me wandering around, struggling with the tool. I appreciate if you can include at least 1 above or possibly 2 which may save uncountable hours of researchers, kudos to you.

3. Meanwhile, I came across https://www.draketo.de/english/emacs/writing%2Dpapers%2Din%2Dorg%2Dmode%2Dacpd where there is a snippet of code which may be relevant to the 1 and 2 above:

```
(require 'reftex-cite)
(defun org-mode-reftex-setup ()
  (interactive)
  (and (buffer-file-name) (file-exists-p (buffer-file-name))
       (progn
        ; Reftex should use the org file as master file. See C-h v TeX-master for infos.
        (setq TeX-master t)
        (turn-on-reftex)
        ; enable auto-revert-mode to update reftex when bibtex file changes on disk
        (global-auto-revert-mode t) ; careful: this can kill the undo
                                    ; history when you change the file
                                    ; on-disk.
        (reftex-parse-all)
        ; add a custom reftex cite format to insert links
        ; This also changes any call to org-citation!
        (reftex-set-cite-format
         '((?c . "\\citet{%l}") ; natbib inline text
           (?i . "\\citep{%l}") ; natbib with parens
           ))))
  (define-key org-mode-map (kbd "C-c )") 'reftex-citation)
  (define-key org-mode-map (kbd "C-c (") 'org-mode-reftex-search))

(add-hook 'org-mode-hook 'org-mode-reftex-setup)
```
But could not figure out how to implement the above `reftex` snippet in compliance with `scimax` configuration without breaking other features of `org-ref`?!

UPDATE: I did see an existing code block in `scimax/org-ref/org-ref-reftex.el` the following:

```
(eval-after-load 'reftex-vars
  '(progn
     (add-to-list 'reftex-cite-format-builtin
                  '(org "Org-mode citation"
                        ((?\C-m . "cite:%l")     ; default
                         (?d . ",%l")            ; for appending
                         (?a . "autocite:%l")
                         (?t . "citet:%l")
                         (?T . "citet*:%l")
                         (?p . "citep:%l")
                         (?P . "citep*:%l")
                         (?h . "citeauthor:%l")
                         (?H . "citeauthor*:%l")
                         (?y . "citeyear:%l")
                         (?x . "citetext:%l")
                         (?n . "nocite:%l"))))))
```

I replaced the block with the following code without success, instead it disabled `C-c ]` keybinding:

```
(eval-after-load 'reftex-vars
  '(progn
     (add-to-list 'reftex-cite-format-builtin
                  '(org "Org-mode citation"
                        ;;((?\C-m . "cite:%l")     ; previous default
                        ((?\C-P . "citep*:%l")     ; default
                         (?d . ",%l")            ; for appending
                         (?m . "cite:%l"	; added to replace with line 85
                         (?a . "autocite:%l")
                         (?t . "citet:%l")
                         (?T . "citet*:%l")
                         (?p . "citep:%l")
                         ;;(?P . "citep*:%l")	;disabled to replace with line 78
                         (?h . "citeauthor:%l")
                         (?H . "citeauthor*:%l")
                         (?y . "citeyear:%l")
                         (?x . "citetext:%l")
                         (?n . "nocite:%l"))))))
```

What is the keybindings for `p` and `P` above?  

Thanking you in anticipation,

Cheers,
/z

**Comment by zenny** [comment]
@jkitchin I just read your reply about the harvard-style citation in https://emacs.stackexchange.com/a/52498, can one use the same code in scimax without breaking stuffs? Thanks in advance.

**Comment by zenny** [comment]
Whining around the interenet, I came across @jkitchin's a year and a half year old post at https://emacs.stackexchange.com/a/46003 where he suggested to specify the default citation type.

As suggested, I appended the following line in `user.el`:

```
(setq org-ref-default-citation-link "citep")
```

Yet, no go. :(

**Comment by jkitchin** [comment]
I don't think any of these are scimax issues. The styling has to do with the LaTeX setup. this case is more complex than usual. Normally the style is set by the bibliographystyle link. In this case though, you have to pass some options to the LaTeX class.

With scimax, this works for me with no further customization:

```
#+latex_class: elsarticle
#+latex_class_options: [12pt,authoryear]


Test sentence with regular cite cite:schuett-2018-schnet.


Test sentence with citep citep:schuett-2018-schnet.


bibliographystyle:elsarticle-num-names
bibliography:~/Box/kitchingroup/jkitchin/bibliography/references.bib
```
and it yields this result:

![image](https://user-images.githubusercontent.com/1610070/88340766-610f9680-cd0a-11ea-850a-709a686845d1.png)

**Comment by jkitchin** [comment]
> Whining around the interenet, I came across @jkitchin's a year and a half old post at https://emacs.stackexchange.com/a/46003 where he suggested to specify the default citation type.
> 
> As suggested, I appended the following line in `user.el`:
> 
> ```
> (setq org-ref-default-citation-link "citep")
> ```
> 
> Yet, no go. :(

This works as advertised for me. It changes the default inserted cite type from `cite:key` to `citep:key`. Without telling the bibliography style to use author year though, these render the same with the default elsarticle style (which used bracketed numbers).

**Comment by jkitchin** [comment]
> @jkitchin I just read your reply about the harvard-style citation in https://emacs.stackexchange.com/a/52498, can one use the same code in scimax without breaking stuffs? Thanks in advance.

yes you can use this code without breaking anything in scimax.

**Comment by zenny** [comment]
> #+latex_class: elsarticle
> #+latex_class_options: [12pt,authoryear]
> 
> 
> Test sentence with regular cite cite:schuett-2018-schnet.
> 
> 
> Test sentence with citep citep:schuett-2018-schnet.
> 
> 
> bibliographystyle:elsarticle-num-names
> bibliography:~/Box/kitchingroup/jkitchin/bibliography/references.bib

> This works as advertised for me. It changes the default inserted cite type from cite:key to citep:key. Without telling the bibliography style to use author year though, these render the same with the default elsarticle style (which used bracketed numbers).

Thanks Prof. @jkitchin for a life saving input. Salute to your highly-commendable and clear efforts. You must be an adored educators among your students for your clarity in thinking. Hats off to you!
