### ISSUE TITLE
Design question for export-ipynb-keyword-cell in ox-ipynb.el

### ISSUE THREAD

**Issue by singletS** [jkitchin/scimax#38]
`export-ipynb-keyword-cell` removes the keywords in a hard-coded list when generating the keyword cell. Could this approach be inverted?  That is, build the keyword cell based on a user-configurable "keyword _include_" list rather than a "keyword _remove_" list?

Motivation: the generic org-mode export templates  (C-c C-e #) add many (often empty) keywords that get added to the ipynb keyword cell unless ox-ipynb.el or the export template is manually edited.

Thanks,
Steve

**Comment by jkitchin** [comment]
We could definitely make this list user-configurable. Do you think it makes sense to make this document specific somehow? I put this in so I could use filetags for metadata in the notebook, specifically about assignments. for other org files, that wouldn't make sense at all. I guess it could certainly be a local variable, but I was thinking more like a filetag:

#+ox-ipynb-include: key1 key2 key3

what do you think?

**Comment by singletS** [comment]
I like the document-specific approach; seems more in the spirit of org files than a local variable. Furthermore, users can add `#+ox-ipynb-include:` by configuring their org export templates.

Maybe a slightly more precise name, lest it be confused with other "includes" (like #+INCLUDE)? Spitballing: ox-ipynb-include-keys? ox-ipynb-meta-cell? These seem clunky, but I'm drawing a blank; maybe what you proposed is fine :)

For users not needing the metadata, could there be a way to not include a keyword cell? e.g., if `#+ox-ipynb-include:` is missing or has value "none"/nil, the keyword cell is not included in the ipynb. (I've used only ox-ipynb.el and scimax-org-babel-ipython.el's fixes to ob-ipython, so may be unaware of important details).

**Comment by jkitchin** [comment]
The main reason I put this on is to have a way to get metadata into the notebook. Another approach might be either a special block for metadata or to only add prefixed keys e.g.:

#+ipynb-key1: some value

The downside of that is the specificity to  Ipynb. Thoughts?

**Comment by singletS** [comment]
I agree; having several #+ipynb-keyn lines seems idiosyncratic.  Instead, how about a top-level

#+PROPERTY ipynb_keys title date author
or the slightly more tedious
#+PROPERTY ipynb-key1: title
#+PROPERTY ipynb-key2: date

Question, though: What do special prefixed keys (or #+PROPERTYs) provide that the regular export settings and #+OPTIONS don't? (see example org file below).  This question and your idea of a special block got me thinking about another approach based on my use case.

Currently, ```export-ipynb-buffer``` exports src blocks, even if they are under a heading with tag ```:noexport:```  (however text from a :noexport: heading is not converted to a markdown cell, as expected). If all children, including source blocks, were subject to the heading tags, would this be suitable for getting metadata into the ipynb?  That is, relevant metadata is included or not included in an ipynb export according to whether the heading has a :noexport: tag.   Hopefully this makes sense...here's an example org file using only standard export features:
```
* Notebook Options :export:  (or :noexport: if user doesn't want metadata)
#+OPTIONS: title:t email:t author:t  date:nil
#+TITLE: The First Law
#+DATE: 2017-02-01
#+AUTHOR: ssinglet
#+EXCLUDE_TAGS: noexport solution
#+EXPORT_SELECT_TAGS: export

* First Law of Thermo
The first law of thermo is $\Delta U = Q - W$.
Use the first law solve these problems.

** Problem 1
Use python to calculate the work done by the system.
*** Answer :solution:
    #+BEGIN_SRC ipython :session
    import numpy as np
    # my answer to the problem
    #+END_SRC

** Problem 2
...
```
I use this approach to generate both assignment and solution ipynbs from the same org file, changing only the value of #+EXCLUDE_TAGS (my feeble ipynb exporter is an md-derived backend based on https://bitbucket.org/sinayoko/org-mode-jupyter-backend/src, but lacks your cool features). Often, I or a student found a mistake or tweak and I got tired of fixing multiple files.

So back to the point of metadata in the notebook: using this heading EXPORT tags approach could be an alternative to special blocks or prefixed keys. 

Based on my personal workflow, I'd rank the various solutions discussed so far as
- export-ipynb-buffer checks/respects heading tags and export options for children (at least text and source blocks)
- a single #+PROPERTY (or #+ipynb-keys) line with multiple values
- multiple #+ipynb-keyn lines

So that's a long-winded response, and I may well be missing important considerations....thoughts?

**Comment by jkitchin** [comment]
We might be talking about two different things. 

You shouldn't use `export-ipynb-buffer` directly I think, it probably won't do what you want unless you use it on an already exported org buffer. I use C-c C-e n o to export and open the notebook, which does not include any content from sections tagged :noexport: (at least by default). This should let you do exactly what you describe with exclude_tags.

The metadata I want in my notebooks are like:

#+ASSIGNMENT: batch-2
#+POINTS: 2
#+DUEDATE: <2017-01-27 Fri>
#+CATEGORY: homework
#+RUBRIC: default

which get saved like:

```
  "org": {
   "ASSIGNMENT": "batch-2",
   "CATEGORY": "homework",
   "DUEDATE": "<2017-01-27 Fri>",
   "GRADER": "jkitchin",
   "POINTS": "2",
   "RUBRIC": "default"
  }
```

in the metadata, and which I use later during grading, and analysis of the notebooks.

Maybe we could do something like this to turn it off or on:

#+ox-ipynb-keyword-metadata: nil or list of keywords

which would determine if the keywords are saved as file-wide metadata, if it is non-nil, the list of keywords would then be what is included. That seems pretty reasonable to me, document specific, and only include what is specified. What do you think?

**Comment by singletS** [comment]
Ahh...headslap! Yes, I misunderstood the metadata you were collecting.  I cherry-picked (older) ox-ipynb.el and ob-ipython fixes from scimax-org-babel-ipython.el without checking the whole system (or noticing there is export dispatcher support).  Sorry for the noise.

Your idea of #+ox-ipynb-keyword-metadata sounds like a clean, flexible solution. Thanks!

**Comment by jkitchin** [comment]
Ok, I have implemented that solution and pushed it a little bit ago.

**Comment by singletS** [comment]
This is working fine for me.  Thanks again.

**Comment by jkitchin** [comment]
thanks for letting me know. Bit by bit this is getting pretty good ;)
