### ISSUE TITLE
ox-ipynb Jupiter notebook exporter fails silently. wrong number of arguments.

### ISSUE THREAD

**Issue by wpix** [jkitchin/scimax#380]
Thanks for the scimax configuration. 

I ran into a problem when trying to export org to Jupyter notebook. The exporter fails silently every time and the error message in mini buffer says **wrong number of arguments> (3.3), 4**

However, if I ```M-x ox-ipynb-export-org-file-to-ipynb-file``` , it did create an .ipynb file but this file contains no cell or other content at all.

environment:
macOS 10.15.5
Python 3.7.0
Emacs 26.3

Any help or suggestions will be greatly appreciated.

**Comment by jkitchin** [comment]
This sounds like an org-mode version problem. Some functions changed the arguments in some versions of org-mode. If you run M-x toggle-debug-on-error, it might give you a more detailed output of what function is getting the wrong number of arguments.

Also, what does M-x org-version tell you?

**Comment by wpix** [comment]
> This sounds like an org-mode version problem. Some functions changed the arguments in some versions of org-mode. If you run M-x toggle-debug-on-error, it might give you a more detailed output of what function is getting the wrong number of arguments.
> 
> Also, what does M-x org-version tell you?

Thanks for your help! The org version is 9.3.7
I realized that I have an org-mode installed from git repository other than the one in scimax, so I deleted that one. 
I still cannot export to notebook but now the error message says **wrong type of argument: number-or-maker-p, ni.**

After some googling, I saw posts mentioned this may result from outdated packages, so I upgraded all elpa packages, but the problem persists.

If I toggle on debug on error, there seems to be something wrong with function ```(org-html-table-row)```
I then tried to export as html file and open and everything worked fine.

**Comment by jkitchin** [comment]
Can you make a small working example that is failing? `(org-html-table-row)` is modified inside the exporter, so maybe you have an unusual table that doesn't work right with the exporter.

**Comment by wpix** [comment]
> Can you make a small working example that is failing? `(org-html-table-row)` is modified inside the exporter, so maybe you have an unusual table that doesn't work right with the exporter.

Thanks for the info. I was able to test it yesterday and found the problem. 
I was using 
```
|-----------------------+-----------------|
| ***                   |             *** |
|-----------------------+-----------------|
|         103.8         |    [5,4,15]     |
|-----------------------+-----------------|
```

instead of the typical table format
```
| ***                   |             *** |
|-----------------------+-----------------|
|         103.8         |    [5,4,15]     |
```

After I deleted the extra lines the exporter worked perfectly. 
Thanks!

**Comment by jkitchin** [comment]
I see. The first style of table isn't supported in ox-ipynb I think because of a bug in the code. I think the number of columns is not set correctly in my code. I don't have time to fix it for now, so I am going to leave this open. 

For future me, the cl-letf way I worked this out is hard to debug. I guess the solution might be some temporary advice around the org-functions, or temporarily defining the exporter functions so that there are proper functions that will work with edebug.

**Comment by jkitchin** [comment]
This should be fixed in https://github.com/jkitchin/ox-ipynb/commit/65d42f7cb0edb461dbba333d40b6d78407ebeb17.
