### ISSUE TITLE
Emacs 27.1: Package cl is deprecated

### ISSUE THREAD

**Issue by AKielhorn** [jkitchin/scimax#381]
Hello,

I installed Emacs 27.1 and now I get a warning

`Package cl is deprecated`

`cl` is used in 

```
bookmark+-1.el:(eval-when-compile (require 'cl)) ;; case, multiple-value-bind, typecase (plus, for Emacs 20: dolist, push)
bookmark+-1.el:       (eval-when-compile (when (< emacs-major-version 21) (require 'cl))) ;; 'dolist', for Emacs 20
bookmark+-bmu.el:(eval-when-compile (require 'cl)) ;; case (plus, for Emacs 20: dolist, push)
bookmark+-key.el:(eval-when-compile (require 'cl)) ;; case
bookmark+-lit.el:(eval-when-compile (require 'cl)) ;; case (plus, for Emacs 20: push)
bookmark+1.el:(eval-when-compile (require 'cl)) ;; case, multiple-value-bind, typecase (plus, for Emacs 20: dolist, push)
bookmark+1.el:       (eval-when-compile (when (< emacs-major-version 21) (require 'cl))) ;; 'dolist', for Emacs 20
help-fns+.el:(eval-when-compile (require 'cl)) ;; case, gentemp
org-db.el:(require 'cl)
scimax-dashboard.el:(require 'cl)
scimax-editmarks.el:(require 'cl)
scimax-hydra.el:	  (require 'cl)
scimax-lob.el:(require 'cl)
```

Is it possible to replace `cl` with `cl-lib` or will this cause compatibility problems with Emacs 25.2 on Windows?

Greetings
Axel

**Comment by jkitchin** [comment]
I don't think this would cause any problems. at the moment I don't have a great way to support Windows. Before the lockdown I was working on updating the windows install up to emacs 26, but I haven't tried anything really on Windows10, and don't currently have that capability. It isn't critical I guess, it is just a convenience for basically a one command install.

The bookmark+ code isn't mine, but I guess it would be ok to update the code in scimax.

**Comment by AKielhorn** [comment]
> I don't think this would cause any problems. at the moment I don't have a great way to support Windows. Before the lockdown I was working on updating the windows install up to emacs 26, but I haven't tried anything really on Windows10, and don't currently have that capability. It isn't critical I guess, it is just a convenience for basically a one command install.

It seems cl-lib was introduced with Emacs 24.5, thus the Emacs provided for Windows should be fine.
Nevertheless an Emacs 26 and working ssh for Windows would be great.

> The bookmark+ code isn't mine, but I guess it would be ok to update the code in scimax.
> 
> It looks like I don't even use bookmark+ in scimax right now, although I do have it setup in my own user file. I wonder if other people are using it in scimax?

Well, so far I didn't need it.
If it is not used in scimax, it won't need updating:-)

**Comment by jkitchin** [comment]
I think I have pushed a bunch of replacements that should eliminate all the (require 'cl) lines.

**Comment by AKielhorn** [comment]
Thanks for the quick response.

It works fine with Emacs 26.3 and 27.1.

There are still some ELPA packages that use `cl` thus the warning persists, but at least scimax is up to date now.

**Comment by zenny** [comment]
I fixed this issue by appending init.el with:

```
(setq byte-compile-warnings '(cl-functions))
```
in linux. Hope this works in Windows, too. Cheers,
