### ISSUE TITLE
Export in latex and silent mode for Inkscape links

### ISSUE THREAD

**Issue by jacquesdurden** [jkitchin/scimax#382]
I’m using scimax-inkscape and it works great! Thank you for this. 

I have two feature requests for it but I don’t know if this is easy to implement.

1) is it possible to open Inkscape in a silent mode when opening an svg image in org-mode, without to get a new emacs buffer with all internal Inkscape messages? 

2) would it be possible to ensure that a inkscape:image.svg is exported in latex according to the same mechanism than file:image.svg? That is, with this last link inserted in \includesvg{image.svg} which thanks to the svg package allows a seamless compilation of the latex file with the inserted figure.

Thank you,

Best regards,
Laurent

**Comment by jkitchin** [comment]
I pushed a few changes that might do some of this. I think that 1 will be silent now.

for 2, I added a latex exporter, but I am not sure it is what you want. if file:image.svg already exports the way you want, then you want to do this:

```
(org-open-file (let ((org-export-before-processing-hook '(scimax-inkscape-preprocess)))
  (org-latex-export-to-pdf))
```

the new latex export will output \includesvg{} but I guess it will not work all the way with captions etc.

**Comment by jkitchin** [comment]
I think this is fixed above, and will be in the master branch when I merge the homebrew branch in.
