### ISSUE TITLE
Adding Scimax to a Windows Installation

### ISSUE THREAD

**Issue by Arjay-El** [jkitchin/scimax#383]
Two Questions:

1. For a new installation, I used git to clone Scimax to a windows box per your instructions but it did not create the emacs-win directory. Have you removed that from the installation?

2. I am starting from an existing emacs 26.3 installation (Win). You advise that one can add the path to scimax and then require the necessary packages. Can I just load your init.el to load everything or must I use a require statement for each scimax-xxx.el package?

Thanks for your help.

**Comment by jkitchin** [comment]
I don't think I took that out. it is an old emacs 25 though. To get it you may have to run the command at https://github.com/jkitchin/scimax#windows-users 

It isn't as easy as just git cloning scimax.

I am pretty sure you can just load the init.el file from scimax, and it will do the rest.
