### ISSUE TITLE
fontifying ipython source blocks

### ISSUE THREAD

**Issue by chanGimeno** [jkitchin/scimax#389]
Hi John,

I tried to export the file scimax-ipython.org to HTML (C-c C-e h h) and if fails with the following message:

`font-lock-fontify-keywords-region: Invalid function: #<subr progn>`

It seems that the problems is caused by the ipython source blocks and the use of the following format syntax:
```
print('Length of t = {}'.format(len(t)))
print('x .dot. y = {}'.format(x @ y))
```

If changing the code snippet to:
```
print('Length of t = %s' % len(t))
print('x .dot. y = %s' % (x @ y))
```
it fontifies the source block properly and exports to HTML without problems.

Have you experienced this behaviour before?

Thanks!

**Comment by chanGimeno** [comment]
Same behaviour happens with the following snippet:
```
    def _repr_latex_(self):
        return r'$\mathcal{N}(\mu=%.2g, \sigma=%.2g),\ N=%d$' % (self.mean,
                                                                 self.std, self.size)
```
The problem seems to be related to curly brackets `{}`.

**Comment by jkitchin** [comment]
I see that error too.I am not sure what is causing it.

**Comment by chanGimeno** [comment]
I tried `scimax-org-toggle-colored-src-blocks` with no effect (persistent fontification problem).

I am using in both cases `emacs 27`, but I experienced similar problems in the past with `emacs 26`.

**Comment by chanGimeno** [comment]
Hi John,

i have tried to export to HTML (and fontify) the following source block:

```
#+BEGIN_SRC python :results drawer
import matplotlib.pyplot as plt
plt.plot([1,2,3])
plt.show()
a=1
print("a={}".format{a})
#+END_SRC
```

with the following setups and results:

1. scimax  -- **fail**
2. build-in package (org 9.3) -- **success**
3. elpa org-plus-contrib 20201026 -- **success**

It seems that it is a bug somewhere in `scimax `rather than in `org` self.

**Comment by jkitchin** [comment]
I guess it is related to this 

;; * better font lock on f-strings

;; (setq python-font-lock-keywords
;;       (append python-font-lock-keywords
;; 	      '(;; this is the full string.
;; 		;; group 1 is the quote type and a closing quote is matched
;; 		;; group 2 is the string part
;; 		(
;; 		 ;; "f\\(['\"]\\{1,3\\}\\)\\([^\\1]+?\\)\\1"
;; 		 "f\\(['\"]\\{1,3\\}\\)\\(.+?\\)\\1"
;; 		 ;; these are the {keywords}
;; 		 ("{[^}]*?}"
;; 		  ;; Pre-match form
;; 		  (progn (goto-char (match-beginning 0)) (match-end 0))
;; 		  ;; Post-match form
;; 		  (goto-char (match-end 0))
;; 		  ;; face for this match
;; 		  (0 font-lock-variable-name-face t))))))

in scimax-org-babel-python.el. If you comment out the addition to python-font-lock-keywords, does the problem go away for you?

**Comment by chanGimeno** [comment]
Yes, if I comment out the addition to python-font-lock-keywords the problem goes away.
