### ISSUE TITLE
Disable highlights in text and code snippets

### ISSUE THREAD

**Issue by zenny** [jkitchin/scimax#391]
Hi,

I tried to use modus-vivendi and monochrome theme with scimax. Whenever I use a dark theme, the highlighted text becomes invisible or almost difficult to read (in code snippets). Is there anyway to disable highlights in editing or improvise? Thanks!

Default look with dark theme:
![pic-selected-201119-0816-13](https://user-images.githubusercontent.com/1653166/99634578-07fa0a00-2a41-11eb-9d9a-1bc54f69b8db.png)

After selection with dark theme:
![pic-selected-201119-0816-29](https://user-images.githubusercontent.com/1653166/99634641-1ba57080-2a41-11eb-8753-27e075bdec0e.png)

**Comment by jkitchin** [comment]
Hm. That seems like a fault of those themes, they should define the faces for those highlights. You can define the faces yourself maybe. if you put your cursor on the character, and type M-x describe-face to see which ones they are. They look like the standard emacs faces for bold at least.

**Comment by zenny** [comment]
> Hm. That seems like a fault of those themes, they should define the faces for those highlights. You can define the faces yourself maybe. if you put your cursor on the character, and type M-x describe-face to see which ones they are. They look like the standard emacs faces for bold at least.

Thanks @jkitchin for the pointer.

Yet those highlights disappears in every other dark themes (tried with doom-gruvbox, doom-Iosvkem, doom-citylights, monochrome). Is there a specific dark theme, preferably monochrome, that goes together with scimax? Cheers,

**Comment by jkitchin** [comment]
I don't think scimax does anything to those faces.  I am not sure why it would be problematic. one thing that might work better for you is to create a user/preload.el file, and add `(setq scimax-theme 'monochrome)`. This should load it before leuven, which may be causing the issue.

**Comment by zenny** [comment]
> I don't think scimax does anything to those faces. I am not sure why it would be problematic. one thing that might work better for you is to create a user/preload.el file, and add `(setq scimax-theme 'monochrome)`. This should load it before leuven, which may be causing the issue.

Thanks this solved the issue.
