### ISSUE TITLE
aspell on Windows

### ISSUE THREAD

**Issue by AKielhorn** [jkitchin/scimax#393]
Hello!

I know this used to work.

I installed scimax on a Windows 10 computer.

Now every time I try to export something, it won't because it doesn't find `aspell`.
Was `aspell` included in an older version of `emacs-win`?

Shouldn't spellchecking simply be disabled when no spellchecker is found?

**Comment by AKielhorn** [comment]
Next step:

I got `hunspell` from [EZWinPorts](https://sourceforge.net/projects/ezwinports/)
and it works on the command line.

Again, I added the PATH and the path appears in `exec-path`.

I changed `aspell` to `hunspell` in `scimax-spellcheck.el`.

`File mode specification error: (file-missing Searching for program No such file or directory hunspell)`

Any ideas how to debug this?

**Comment by AKielhorn** [comment]
As seen with `jupyter` I have added a check to `packages.el`

```
(if (executable-find "aspell")
   (use-package scimax-spellcheck
    :ensure nil
    :load-path scimax-dir)
  (message "aspell was not found on your path. Spellchecking will be disabled."))

```

Nevertheless I would like to get spell checking working on Windows.

**Comment by jkitchin** [comment]
I think this will probably be fixed with the homebrew installation.
