### ISSUE TITLE
Make #+attr_org :width 300 work on Windows

### ISSUE THREAD

**Issue by jkitchin** [jkitchin/scimax#4]
There doesn't seem to be a Windows emacs with imagemagick support, so the rescaling doesn't work.

**Comment by jboes** [comment]
This new feature does not seem to be working on Gilgamesh for me.

I can't load images in windows, so I haven't tested it there yet.

**Comment by jkitchin** [comment]
hm. It works on gilgamesh for me. do you have a convert command? Mine seems to be in my bin directory.

All of these work for me.

#+attr_org: :width 40%
[[./test.png]]

#+attr_org: :width 100
[[./test.png]]

#+attr_org: :width x100
[[./test.png]]

#+attr_org: :width 100x300!
[[./test.png]]

**Comment by jboes** [comment]
Works on Gilgamesh. Waiting to test on Windows.

**Comment by jboes** [comment]
This works on windows now. Yay!

One important note for those installing Imagemagik on windows: mogrify is apparently classified as a legacy function, and thus requires the corresponding box to be checked when performing the installation. Without it, images display, but will not be correctly resized.

**Comment by jkitchin** [comment]
Super! Thanks for figuring out the legacy function issue.
