### ISSUE TITLE
Active process exists; kill them and exit anyway?

### ISSUE THREAD

**Issue by AKielhorn** [jkitchin/scimax#400]
Since updating `scimax` I get the following message whenever I close `Emacs`:

```
Active process exists; kill them and exit anyway?
```

And it is always process `emacsql-sqlite` that is still running.

Even if I didn't change the file.

I'm using Emacs 26.3 on MacOS 10.13.6
The same happens with 27.1.

Anything I can do to get rid of that error?

Greetings
Axel

**Comment by jkitchin** [comment]
This is from org-db which runs the emacsql process. I pushed a change that should make it stop querying you when you close emacs.

**Comment by AKielhorn** [comment]
Great, that works fine.

Typing `C-x C-c y` was very annoying on a german keyboard since `y` is on the left of `x`.
