### ISSUE TITLE
Suggestions for org-show

### ISSUE THREAD

**Issue by nxtruong** [jkitchin/scimax#402]
I'm using `org-show` for interactive presentations with code blocks. It works very well. Thank you for creating it. I have a few suggestions for `org-show`. I guess it might be easy to implement them, but I don't know elisp aside from basic configuration.

1. Hide all tags instead of just `:slide:` (or an option to hide either only `:slide:` or all). I often create my org slideshow for both presentation and exporting to PDF (handout). Sometimes I need to mark a headline as `:noexport:slide:` because it should not be exported but it's still a slide. The `:noexport:` tag shows up in the presentation, which is ok but doesn't look nice.
2. Option for changing the face `org-meta-line` only in presentation mode. The reason for this suggestion is that I often need to specify attributes for images (setting the width because the image can be too small or too large, and different attributes for ORG and LATEX), and also meta lines for source code blocks. Usually I don't want to make these lines too prominent since the audience should focus on the image or the source code instead of these lines. It'd be great if we can either hide these lines or make them less prominent (smaller size, blended with the background, etc.). Out of the presentation mode, the default face should be restored.

Thank you again.

**Comment by jkitchin** [comment]
check out 993d2ed. I think it does both of these.

**Comment by nxtruong** [comment]
It works very well. I just followed your code and added another option for "foreground" color and also code for checking if the "height" option is nil then don't change the height. Thank you.
