### ISSUE TITLE
scimax-contacts: No SQLite binary available on Windows

### ISSUE THREAD

**Issue by AKielhorn** [jkitchin/scimax#403]
It's me again :-)

After solving the SQLite problem on macos, I'm no back on Windows.

Since I don't have SQLite on Windows I get:

```
Scimax-contacts/:catch No EmacSQL SQLite binary available, aborting
```

I guess we need a *don't do that on Windows* condition here.

Greetings
Axel

**Comment by jkitchin** [comment]
wouldn't it be better to install sqlite on windows (https://www.sqlite.org/download.html)?
