### ISSUE TITLE
Obsolete command org-toggle-latex-fragment

### ISSUE THREAD

**Issue by Arjay-El** [jkitchin/scimax#404]
Win10 user:

When I select toggle inline latex images from the menu in scimax, I receive this error:

‘org-toggle-latex-fragment’ is an obsolete command (as of Org 9.3); use ‘org-latex-preview’ instead.

Do I need to roll back my org version? Can I just change the command in the appropriate scimax*.org file or will that mess up future updates? Thanks.

**Comment by jkitchin** [comment]
if it works, you don't have to change anything, it is just an annoying warning.

There are a lot of these now, and I am not sure what the best thing to do is. I feel like 9.3 is probably too modern to just fix them all and say we don't support older than that. on the other hand I also don't want a bunch of compatibility code that is version specific.
