### ISSUE TITLE
Start Scimax in GUI on mac

### ISSUE THREAD

**Issue by Arjay-El** [jkitchin/scimax#408]
I just did a new installation on a macbook following the instructions. However I cannot seem to get scimax start in a GUI, it starts in the 80x25 mode with text menus called by F10 using the ./scimax.sh command in teminal. How do you start scimax in a GUI on your system? Thanks.

**Comment by AKielhorn** [comment]
I have an automator script that sets up the path and calls `emacs` :

```
export PATH=/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:/opt/local/bin
/Applications/Emacs\ 26.3.app/Contents/MacOS/Emacs  -l ~/src/Emacs/scimax/init.el "$*" &amp;
```

This works as a drag target on my desktop.
I can simply take a file and drop it on the Automator icon.
When I start it without a dropped file I get an error message in emacs.
So far I've been too lazy to fix that. 

Please  note that you have to drag subsequent files onto the emcas icon, not the automator script.

As an alternative you can define an alias in your `.bashrc` (or `.zshrc`):
```
alias scimax="/Applications/Emacs\ 26.3.app/Contents/MacOS/Emacs  -l ~/src/Emacs/scimax/init.el &"
```

You need to adjust the `PATH` to your actual setting.

[Emacs 26.3 Scimax.app.zip](https://github.com/jkitchin/scimax/files/6009096/Emacs.26.3.Scimax.app.zip)

**Comment by jkitchin** [comment]
it sounds like you need to brew install an emacs to me.

**Comment by Arjay-El** [comment]
Update Using brew: Worked on an intel Mac giving a GUI. 
Using the first Mac installation method flags a brew error stating it does not accept '--with gnu-utils' (it did previously). I do not see '--with' in the help file that came up. I assume that method is now obsolete.

On my new M1 mac-mini: Following using brew for emacs-plus, it loads emacs in a terminal window, not a GUI. Searching for a solution.Can you explicitly call up a GUI interface on the Mac?

**Comment by jkitchin** [comment]
I guess there is some incompatibility on M1 with the gui libraries. These days all I use is `brew install emacs-plus` and I get a GUI on intel Mac. I haven't gotten an M1 yet, so I am not sure what the issue might be. It seems like it should work on M1 though (https://github.com/d12frosted/homebrew-emacs-plus/issues/282)

**Comment by Arjay-El** [comment]
Thanks for the link which led me to discover 'brew doctor'. I used 'brew doctor' which led me to run the brew command below. Looks like an existing emacs from an earlier attempt was selected and not emacs-plus. My mistake was in not removing my initial plain emacs install. Using your startup command, it pops into the GUI on my M1 like it should.

To force the link and overwrite all conflicting files:  brew link --overwrite emacs-plus@27
