### ISSUE TITLE
 org-qll not found

### ISSUE THREAD

**Issue by OrionRandD** [jkitchin/scimax#410]
Error (use-package): Failed to install org-ql: https://elpa.gnu.org/packagespeg-1.0.tar: Not found
Error (use-package): Cannot load org-ql

How can I fix this?

**Comment by jkitchin** [comment]
Probably you can try M-x package-refresh-contents (or something close to that) and M-x package-install org-ql.

**Comment by OrionRandD** [comment]
@jkitchin  I have already done that,
but it did not find org-ql
I have refreshed and updated all packages and
tried to install org-ql, 
this link is dead
 https://elpa.gnu.org/packagespeg-1.0.tar
:(

**Comment by jkitchin** [comment]
That link should be https://elpa.gnu.org/packages/peg-1.0.tar which doesn't seem to be dead. I don't know why you would be missing a / though (maybe typed it wrong?)

I guess org-ql is not in elpa, but in melpa.  Try this:

```
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-refresh-contents)
(package-install 'org-ql)
```

**Comment by OrionRandD** [comment]
Still did not find that.
Here is my init.el

;;; init.el --- Where all the magic begins
;;

;;; Commentary:
;;
;; This is a starter kit for scimax. This package provides a
;; customized setup for emacs that we use daily for scientific
;; programming and publication.
;;

;;; Code:
;; this makes garbage collection less frequent, which speeds up init by about 2 seconds.
(setq gc-cons-threshold 80000000)

(when (version< emacs-version "25.0")
  (warn "You probably need at least Emacs 25. You should upgrade. You may need to install leuven-theme manually."))

;; remember this directory
(defconst scimax-dir (file-name-directory (or load-file-name (buffer-file-name)))
  "Directory where the scimax is installed.")

(defvar scimax-user-dir (expand-file-name "user" scimax-dir)
  "User directory for personal code.")

(setq user-emacs-directory scimax-user-dir)

(setq package-user-dir (expand-file-name "elpa"  scimax-dir))

;; we load the user/preload.el file if it exists. This lets users define
;; variables that might affect packages when they are loaded, e.g. key-bindings,
;; etc... setup autoupdate, .

(let ((preload (expand-file-name "user/preload.el" scimax-dir)))
  (when (file-exists-p preload)
    (load preload)))

(defvar scimax-load-user-dir t
  "Controls if the user directory is loaded.")

(require 'package)

(let* ((no-ssl (and (memq system-type '(windows-nt ms-dos))
		    (not (gnutls-available-p))))
       (proto (if no-ssl "http" "https")))
  ;; Comment/uncomment these two lines to enable/disable MELPA and MELPA Stable as desired
  (add-to-list 'package-archives (cons "melpa" (concat proto "://melpa.org/packages/")) t)

  (add-to-list
   'package-archives
   (cons "org" (concat proto "://orgmode.org/elpa/")))

  (when no-ssl
    (setq package-check-signature nil)
    (setq tls-program
  	  ;; Defaults:
  	  '("gnutls-cli --insecure -p %p %h"
  	    "gnutls-cli --insecure -p %p %h --protocols ssl3"
  	    "openssl s_client -connect %h:%p -no_ssl2 -ign_eof")
  	  ;; '("gnutls-cli -p %p %h"
  	  ;;   "openssl s_client -connect %h:%p -no_ssl2 -no_ssl3 -ign_eof")
  	  ))

  (when (< emacs-major-version 24)
    ;; For important compatibility libraries like cl-lib
    (add-to-list 'package-archives '("gnu" . (concat proto "://elpa.gnu.org/packages/")))))



;; (if (file-directory-p (expand-file-name "emacs-win" scimax-dir))
;;     ;; Windows archives.
;;     (progn
;;       (add-to-list
;;        'package-archives
;;        '("org"         . "https://orgmode.org/elpa/"))

;;       ;; According to https://melpa.org/#/getting-started there may be issues with https on Windows
;;       (add-to-list
;;        'package-archives
;;        `("melpa" . "http://melpa.org/packages/")
;;        t))


;;   ;; For non-windows
;;   ;; replace the old http path with https.
(setf (cdr (assoc "gnu" package-archives)) "https://elpa.gnu.org/packages")

(add-to-list
 'package-archives
 '("org"         . "https://orgmode.org/elpa/"))

;;   ;; According to https://melpa.org/#/getting-started there may be issues with https on Windows
(add-to-list
 'package-archives
 `("melpa" . "https://melpa.org/packages/")
 t)

(add-to-list 'load-path scimax-dir)
(add-to-list 'load-path scimax-user-dir)

(let ((default-directory scimax-dir))
  (shell-command "git submodule update --init"))

(set-language-environment "UTF-8")

(require 'bootstrap)
(require 'packages)

;; it appears this help library is not loaded fully in the emacs-win
;; directory. See issue #119. This appears to fix that.
(when (file-directory-p (expand-file-name "emacs-win" scimax-dir))
  (load-library "help"))

(load-theme 'leuven-theme)

(menu-bar-mode -1)

(setq gc-cons-threshold 800000)

(provide 'init)

;;; init.el ends here

**Comment by jkitchin** [comment]
If you are using scimax, you shouldn't be having this problem, unless there is an issue with melpa (which occasionally happens, and it mysteriously clears itself up in a day or so).

why did you change the title of the question to  `org-qll` that is not a package that would found, it should be `org-ql`

**Comment by OrionRandD** [comment]
That was only a typo.
I know the package name.
Would it be because I am using chemacs?
So I have two other Emacs?
https://github.com/plexus/chemacs
