### ISSUE TITLE
dash-functional is obsolete

### ISSUE THREAD

**Issue by AKielhorn** [jkitchin/scimax#411]
Since 
```
;; Package-Version: 20210210.1449
```

`dash-functional` is obsolete. It only contains a message telling you about this fact:

```
(eval-and-compile
  (let ((msg "Package dash-functional is obsolete; use dash 2.18.0 instead"))
    (if (and noninteractive (fboundp 'byte-compile-warn))
        (byte-compile-warn msg)
      (message "%s" msg))))
```

You may want to remove it from `packages.el` to prevent it from getting reinstalled.

**Comment by jkitchin** [comment]
Thanks. I pushed a commit to remove that.
