### ISSUE TITLE
Recommended method for disabling `scimax-statistics.el`

### ISSUE THREAD

**Issue by roblem** [jkitchin/scimax#412]
I am currently using `emacs-jupyter` and it supports all of the kernels I need including R, python, and stata so I don't really need any of the features from `scimax-statistics.el`.  What is the recommended way of disabling this?

**Comment by roblem** [comment]
Looking through things, it seems like this is optional and never loaded by default.  So something else in my config must be loading it.

**Comment by jkitchin** [comment]
It should not be loaded unless you have specifically added something like `(require 'scimax-statistics)` or `(use-package scimax-statistics)` to an init file somewhere.
