### ISSUE TITLE
scimax-define-src-key error when trying to run org-capture

### ISSUE THREAD

**Issue by JSpenced** [jkitchin/scimax#415]
I just rebased to the newest Scimax commit today (I was using a version that was about 6 months old) and I am now having an issue with custom `org-capture` templates.

This is the error I get which made me think it is something to do with scimax changing some function, but I can't figure out what is going on:
```
org-capture: Capture abort: Symbol’s function definition is void: scimax-define-src-key
```

If it helps this is an example of my capture template and key bindings (these worked before the update). The bindings don't really matter because it also happens if called through the org-capture templates interface:
```
(setq org-capture-templates
	  '(("s" "Scheduled TODO" entry (file+headline "~/Dropbox/gtd.org" "Tasks")
		 "* TODO %?\nSCHEDULED: %^t")
		("w" "Work: Scheduled TODO" entry (file+headline "~/Dropbox/gtd_work.org" "Tasks")
		 "* TODO %?\nSCHEDULED: %^t")))
(define-key global-map (kbd "H-s") (lambda () (interactive) (org-capture nil "s")))
(define-key global-map (kbd "H-w") (lambda () (interactive) (org-capture nil "w")))
```

Any ideas?

**Comment by jkitchin** [comment]
I am not sure why that is getting triggered in a capture. I think that function has been renamed as `scimax-ob-define-src-key` in `scimax-ob.el`.

**Comment by JSpenced** [comment]
If I,
```
(defalias 'scimax-define-src-key 'scimax-ob-define-src-key)
```
it works fine. Also, I thought it was weird org-capture was calling that function but it must be.

I will leave this open, but at least it's working.
