### ISSUE TITLE
org-mode 9.5: org-speed-commands-user no longer exists

### ISSUE THREAD

**Issue by AKielhorn** [jkitchin/scimax#416]
Hello,

today I updated to the latest org-mode from git and I get the following errors:
```
Error (use-package): scimax-org/:init: Symbol’s value as variable is void: org-speed-commands-user
Error (use-package): scimax-journal/:catch: Symbol’s value as variable is void: org-speed-commands-user
```
The reason is commit
```
d48276b89
Replace `org-speed-commands-user' by `org-speed-commands'
03.05.2021, 16:30
```
You may want to modify `org-speed-commands` instead.

```
(make-obsolete-variable 'org-speed-commands-user
                        "configure `org-speed-commands' instead." "9.5")
```

I think this will work for older versions as well, thus you don't need a version check.

**Comment by jkitchin** [comment]
In org 9.4, there is no variable `org-speed-commands' though. does the `make-obsolete-variable' code somehow fix that?

**Comment by AKielhorn** [comment]
Sorry, should have looked at the full patch.

```
-(defconst org-speed-commands-default)
+(defcustom org-speed-commands
```

It was `org-speed-commads-default` and `org-speed-commands-user` and now it is just
`org-speed-commands`.

You need to keep `org-speed-commands-user` for org < 9.5.

**Comment by jkitchin** [comment]
I think the push above could fix this issue. If it does let me know. thx.

**Comment by AKielhorn** [comment]
Well, it is more complex.

The patch fixed it for `9.4.6 master`, but not for `9.4.6 maint`.

Since most user will probably get `org-mode` via ELPA and thus use the `maint` branch, I guess the test should be testing for version >= 9.5.

The few users who run `master` are probably able to adjust this themselves.

**Comment by jkitchin** [comment]
How about this?

**Comment by AKielhorn** [comment]
This works on my work computer (`maint`) and was an easy fix on my private computer (`master`).

Thanks for the fix.

(I'm not closing this until the 9.5 release so other users can find it.)

**Comment by jkitchin** [comment]
This seems ok on 9.5. I am going to close this.
