### ISSUE TITLE
Make the org-db log messages but not display in bottom panel

### ISSUE THREAD

**Issue by JSpenced** [jkitchin/scimax#417]
Org-db and some of the new commands are great. For my use case, I don't have that manyf org files, but it's an awesome feature. I just want the ability to have a flag for making the messages silent. 

By that I mean not in the mini-panel but only recorded to the messages buffer. If that isn't possible then at least clear these messages after processing. Also the added to org-db on every save I prefer not to be notified.

eg....this wouldn't happen but would be in the messages buffer.
![image](https://user-images.githubusercontent.com/43424787/119921456-a35dc180-bf33-11eb-8f68-c8ad5e4e7611.png)

**Comment by jkitchin** [comment]
I think I converted most of the messages to org-db-log calls. that will probably take care of this.

**Comment by JSpenced** [comment]
Yeah, that seemed to fix it as haven't seen a message since, so I'll go ahead and close this!
