### ISSUE TITLE
projectile.el failed to define function counsel-projectile-rg

### ISSUE THREAD

**Issue by roblem** [jkitchin/scimax#418]
Starting to use projectile a bit more and functions like `counsel-projectile-rg` and `councel-projectile-ag` fail with messages like this:

```
command-execute: Autoloading file ~/emacs_setup/.emacs.d/scimax/elpa/projectile-20210607.1513/projectile.elc failed to define function counsel-projectile-rg
```
I saw that [for a similar issue here](https://github.com/abo-abo/swiper/issues/1714) there was a keymap conflict [that was resolved here](projectile-command-map) in 2018.  

I re-updated all my el files and this issue remains under scimax.  Wondering if there are scimax specific keymaps that are re-inducing these conflicts.

Also, I noticed in the readme, that a similar function `helm-projectile-grep` isn't available although `counsel-git-grep` does work for searching all project files for a phrase.

**Comment by jkitchin** [comment]
I am unable to reproduce this. It sounds like something is wrong with the projectile.elc file. if you delete it, does the problem go away (you can always recompile it later if you want).

**Comment by roblem** [comment]
No luck. Get the same error in reference to `projectile.el`.  The command `counsel-rg` works, so I can use that. Thanks.

**Comment by roblem** [comment]
Complete stupidity on my part: had to install `counsel-projectile`.

**Comment by jkitchin** [comment]
thanks for letting me know. This should probably be a package required in scimax. I will add it to save someone from this in the future!
