### ISSUE TITLE
use-package error

### ISSUE THREAD

**Issue by tarihatari** [jkitchin/scimax#422]
Hello, I just installed scimax on Ubuntu 20.04 and got this

`Error (use-package): org-ref/:catch: Symbol’s value as variable is void: <!DOCTYPE`
`Error (use-package): org-ref-arxiv/:catch: Symbol’s value as variable is void: <!DOCTYPE`
`Error (use-package): scimax-org/:init: Symbol’s value as variable is void: <!DOCTYPE`
`Error (use-package): scimax-journal/:catch: Symbol’s value as variable is void: <!DOCTYPE`

GNU Emacs 27.2
org               9.4.4

Any hints on how to fix this?

**Comment by jkitchin** [comment]
how did you install it? It looks like maybe some of those packages did not get downloaded correctly. for example, what are the contents of scimax-journal.el?

**Comment by tarihatari** [comment]
I installed it via the bash curl command.
When I run ./scimax.sh I get
`(emacs:41372): Gtk-CRITICAL **: 18:57:57.477: gtk_distribute_natural_allocation: assertion 'extra_space >= 0' failed`

The packages actually look normal to me. Just changed the ending to txt in order to attach it here.
[scimax-journal.txt](https://github.com/jkitchin/scimax/files/7008937/scimax-journal.txt)

**Comment by jkitchin** [comment]
I guess that some package in elpa did not download correctly, and if you grep for "!DOCTYPE" in the elpa (or other scimax.el files) you will find it.

**Comment by jkitchin** [comment]
I thought of another possibility. Are you able to run (use-package org-ref) by itself?

**Comment by tarihatari** [comment]
Thanks! Apparently quite a lot of packages failed installing. Today I got a more specific error message related to parsebib not being installed. Eventually installing that one and a whole bunch of others via package-install did the job.
