### ISSUE TITLE
org-superstar does not load 

### ISSUE THREAD

**Issue by OrionRandD** [jkitchin/scimax#423]
I have placed org-superstar in my user.el, but it does not load when oppening an .org file.
I have to call it manually for that to work and it does only per buffer.
If I open another .org buffer I have to call it by hand again  :(
here is my org-superstar bit

(use-package org-superstar 
  :ensure t
  :after org-bullets
  :config
  (setq org-superstar-mode t)
  (setq org-superstar-remove-leading-stars t)
  (setq org-superstar-headline-bullets-list
	'("🞛" "⁖" "◉" "○" "▷"))
  (setq org-superstar-item-bullet-alist
	'((?+ . ?•)
	  (?* . ?➤)
	  (?- . ?–))) 
  )

**Comment by jkitchin** [comment]
you probably need to add a hook function liek `(add-hook 'org-mode-hook 'org-superstar-mode)` in the :config sections.

**Comment by OrionRandD** [comment]
> you probably need to add a hook function liek `(add-hook 'org-mode-hook 'org-superstar-mode)` in the :config sections.

Worked -> :)

I have another question:
In "words-hydra/body", how do I configure speak to call "eloud" for emacs or "espeak" which is linux command?
And I suggest you to use "translate-shell" for translating words, phrases or texts.
It is a command that pulls from google translate and other engines.
sudo apt install translate-shell
then,
man trans
it has got lots of wonderful options...
Probably you run macOS,
but, have a look in these suggestions, if you can...

**Comment by jkitchin** [comment]
The word-speak function isn't that flexible, and currently is written for the "say" command on a Mac.

You have a few options.

You could write your own function that speaks text using a program you want, and either modify the hydra or add it to the hydra. I think you can do this with (defhydra+) without even modifying words.el.

You could use an override advice on words-speak that runs a function you want that calls one of the programs you want to use.

thanks for the tip on translate-shell. You are right I use a mac, but that is available in homebrew. I will take a look at it.

**Comment by OrionRandD** [comment]
> The word-speak function isn't that flexible, and currently is written for the "say" command on a Mac.
> 
> You have a few options.
> 
> You could write your own function that speaks text using a program you want, and either modify the hydra or add it to the hydra. I think you can do this with (defhydra+) without even modifying words.el.
> 
> You could use an override advice on words-speak that runs a function you want that calls one of the programs you want to use.
> 
> thanks for the tip on translate-shell. You are right I use a mac, but that is available in homebrew. I will take a look at it.

O

**Comment by OrionRandD** [comment]
> The word-speak function isn't that flexible, and currently is written for the "say" command on a Mac.
> 
> You have a few options.
> 
> You could write your own function that speaks text using a program you want, and either modify the hydra or add it to the hydra. I think you can do this with (defhydra+) without even modifying words.el.
> 
> You could use an override advice on words-speak that runs a function you want that calls one of the programs you want to use.
> 
> thanks for the tip on translate-shell. You are right I use a mac, but that is available in homebrew. I will take a look at it.

--------------------
This one will be harder for me, since I am not a lisper.
Anyways, I can live without this for now...
I have just added telega to my scimax ->
https://github.com/zevlg/telega.el
It is becoming really great here...
Thx again for your time and attention...

**Comment by jkitchin** [comment]
With the commit above, you should be able to do something like:

```
(setq words-speech-program "espeak"
      words-speech-program-options "-s 120")
```
in an init file to use espeak. 

You can also do this for translate-shell

```
(setq words-translate-shell-program "trans"
      words-translate-shell-options "-p"
      words-translate-shell-native-language "en"
      words-translate-preferred-language "de")
```

**Comment by OrionRandD** [comment]
> With the commit above, you should be able to do something like:
> 
> ```
> (setq words-speech-program "espeak"
>       words-speech-program-options "-s 120")
> ```
> 
> in an init file to use espeak.
> 
> You can also do this for translate-shell
> 
> ```
> (setq words-translate-shell-program "trans"
>       words-translate-shell-options "-p"
>       words-translate-shell-native-language "en"
>       words-translate-preferred-language "de")
> ```
> 
> and then use the new `words-translate-shell` function.


Oh. Thx a lot! I will test this setup.
I forgot to tell you that there's a package in Emacs called "eloud" that uses "espeak" as a backend and is very powerful also mimicking "emacspeak" when one needs emacs to speak aloud. You can see it running "M-x package-list-packages" and then search for it...
perhaps it is worth of having a try...
I will test this bit you posted here.
By the way, I have a small function to call "xcowsay" for setting a time, say, e.g. up to 20min., for her to show up and tell me that my recording time - when in obs or simplescreensaver - or vokoscreen - has finished...
The function works greatly in doom-Emacs, but in scimax, it complains about the variable "message" and gives me a "runtime error". I have tried to fix it, but have not succeeded so far...
Here it is:

;; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; cowsayx-sclock

(defun cypher/cowsayx-sclock (in-minutes message)
  (interactive "nSet the time from now - min.: \nsWhat: ")
  (run-at-time (* in-minutes 60)
               nil
               (lambda ()
                 (message "%S" message)
                 (shell-command (format "xcowsay %s" (shell-quote-argument
                                                      message))))
               )
  )

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

**Comment by OrionRandD** [comment]
The indentation is not ok here... But Emacs will correct it...
Perhaps you can improve it and add to scimax in the future...
You have to install xcowsay and also, con install cowsay.
sudo apt install xcowsay cowsay
Sometimes debian does not find them because they go into de games folder, but you can make a symlink to "/usr/local/bin"

**Comment by jkitchin** [comment]
Hm. It seems to work fine for me. It is confusing to use a variable named message with the message function, but that is ok in elisp. you could also use a message-box, which will pop up an alert (although it will block emacs, which might be undesirable).

**Comment by OrionRandD** [comment]
> Hm. It seems to work fine for me. It is confusing to use a variable named message with the message function, but that is ok in elisp. you could also use a message-box, which will pop up an alert (although it will block emacs, which might be undesirable).

I have already solved the issue with a help from stackoverflow. It is working now... 

https://stackoverflow.com/questions/69059602/error-running-timer-void-variable-message-in-emacs-init-el/69060061?noredirect=1#comment122071224_69060061

Thx for replying and feel free to use it...
