### ISSUE TITLE
scimax-editmarks (colors highlight, contact, typo, audio) fail to export to latex

### ISSUE THREAD

**Issue by M1ndo** [jkitchin/scimax#424]
blue,yellow,green,purple-highlights , contact , typo, audio which use sem-export-default are not processed correctly thus cannot export to latex 
```(if: Symbol’s function definition is void: first)``` .
The error seem to be coming from here
```lisp
     ((eq 'latex backend)
      (setf (buffer-substring (car bounds) (cdr bounds))
	    (concat
	     (format "@@latex:\\definecolor{%s}{rgb}{%s,%s,%s}%s{%s}{\\parbox{\\textwidth}{%s:@@"
		     (or bg-color fg-color)
		     (if bg-color (first bg-rgb) (first fg-rgb))
		     (if bg-color (second bg-rgb) (second fg-rgb))
		     (if bg-color (third bg-rgb) (third fg-rgb))
		     (if bg-color
			 "\\colorbox"
		       "\\textcolor")
		     (or bg-color fg-color)
		     (get-text-property (point) 'sem-type))
```

**Comment by jkitchin** [comment]
Thanks for reporting this. I pushed a fix for these I think. these are all called cl-* functions now.

**Comment by M1ndo** [comment]
Thanks for the fix , however i'm not sure if this is intended or not .
when exporting to pdf, it does produce what we expect but with extra mark name ?
```latex
\definecolor{Darkolivegreen1}{rgb}{0.792156862745098,1.0,0.4392156862745098}\colorbox{Darkolivegreen1}{\parbox{\textwidth}{green-highlight:HEllo World }}
```
![image](https://user-images.githubusercontent.com/44820142/134713660-156c6f09-4ed1-4258-8011-d3828c7175b7.png)
If it is intended, is there a way to remove it ?

**Comment by jkitchin** [comment]
That is intended, it uses the default export mechanism. you would have to define a specific exporter for that specific editmark.
