### ISSUE TITLE
`scimax-org-babel` errors on upgrading to emacs 28 with native comp

### ISSUE THREAD

**Issue by JSpenced** [jkitchin/scimax#426]
I am not exactly sure if this is an error in scimax or not but thought I'd post it up here. I don't use the `scimax-ipython` stuff so doesn't affect me, but it might others if it is an error. When using native-comp for loading, this is the error I get: 

```
Error (use-package): scimax-org-babel-ipython-upstream/:catch: Wrong type argument: char-or-string-p, ("Execute" ["Current block" org-ctrl-c-ctrl-c t] ["Current and next" scimax-execute-and-next-block t] ["To point" scimax-execute-to-point t] ["Restart/block" scimax-ob-ipython-restart-kernel-execute-block t] ["Restart/to point" scimax-restart-ipython-and-execute-to-point t] ["Restart/buffer" scimax-ob-ipython-restart-kernel-execute-buffer t]) Disable showing Disable logging
```

Actually, I had no other issues with `native-comp` other than this.

**Comment by jkitchin** [comment]
I guess this is related to some macro expansion not working right. Thanks for reporting it.

**Comment by jkitchin** [comment]
I guess this was a bug, either something changed in the menu definition  or it has just been hidden a while. see if these commits fix it.

**Comment by JSpenced** [comment]
Okay, I will try to check over the weekend. They tried to add f-string parsing in emacs28, but I think it messed up all the python font-lock-mode stuff. I reported it but haven't heard a fix yet, but it was acknowledged. That was kind of deal breaker so moved back to emacs27, but I'll throw this on my old mac to test.

**Comment by AKielhorn** [comment]
It is fixed for me.

Emacs 29.0.50 build on 2021-11-01.

Thanks.
