### ISSUE TITLE
Allow exporting R code blocks to Jupyter notebooks with ox-ipynb 

### ISSUE THREAD

**Issue by xelibrion** [jkitchin/scimax#43]
Jupyter supports running R as a kernel, so it can be used to present research in R code as well as Python. 
At the moment ox-ipynb will export R code blocks as markdown, would be great to make it export them as code cells.

**Comment by jkitchin** [comment]
can you mix python and R in one notebook? At the moment I think ox-ipynb can only support python because of the metadata at the end that specifies python, and because it parses the org-file by python blocks. The second part is fixed pretty easily, but not the metadata part.

**Comment by xelibrion** [comment]
Don't think you can, as the kernel you specify is on notebook-level. So it's either Python or R. 

I modified my version of `ox-ipynb.el`, so it exports R blocks as code cells as well, but my limited knowledge of lisps didn't allow me to implement writing of correct metadata to the exported file.

**Comment by jkitchin** [comment]
Can you send me one of your R notebooks? The python metadata was just reverse engineered from one of my notebooks. It might not be hard to use the first codeblock to determine the language type, and then select the notebook metadata to use.

**Comment by xelibrion** [comment]
@jkitchin have sent an email to the address in your profile. Here's the metadata block from the notebook for reference

```
 "metadata": {
  "kernelspec": {
   "display_name": "R",
   "language": "R",
   "name": "ir"
  },
  "language_info": {
   "codemirror_mode": "r",
   "file_extension": ".r",
   "mimetype": "text/x-r-source",
   "name": "R",
   "pygments_lexer": "r",
   "version": "3.3.2"
  },
  "org": {}
 }
```

**Comment by jkitchin** [comment]
Cool. thanks. I pushed some code just now that I think makes it possible to export R or ipython notebooks now.  The first code block determines which one.  It is lightly tested ;)

**Comment by xelibrion** [comment]
@jkitchin finally managed to test the change - the notebook used R kernel out of the box, well done! 

Closing this issue.
