### ISSUE TITLE
eval-buffer: Cannot open load file: No such file or directory, /Users/jkitchin/Dropbox/emacs/scimax/init-emacs28.el

### ISSUE THREAD

**Issue by AKielhorn** [jkitchin/scimax#431]
Well,

c02d34ee did remove the `/` but it added

´´´
(load "/Users/jkitchin/Dropbox/emacs/scimax/init-emacs28.el")
´´´

which of course does not exist on my computer.

And it would probably not do anything, since I still use 27, which works fine without that line.

With emacs > 27.2 I get the error reported in #426.

**Comment by jkitchin** [comment]
That line is my fault. I am using emacs 28, and that file has some hacks to fix some issues I have, it should not have been committed here.
