### ISSUE TITLE
Not an issue, but a question

### ISSUE THREAD

**Issue by OrionRandD** [jkitchin/scimax#432]
Not an issue, but a question:
How do you get those beautiful bent down arrow ant the end of an orgmode file heading - when I unfold them?
Which package that come from?

**Comment by jkitchin** [comment]
I am not sure what you are talking about. Is this what you mean: https://endlessparentheses.com/changing-the-org-mode-ellipsis.html

**Comment by OrionRandD** [comment]
Definitely, thanks...
But, rephrase my question, please...
