### ISSUE TITLE
Opinion on upgrading Emacs version  (not an issue)

### ISSUE THREAD

**Issue by Arjay-El** [jkitchin/scimax#434]
I ma working in Win10 and have used your Win installation instructions. Windows is placved in the directory emacs-win.  Can I just copy a new updated emacs distribution (like 27.2) into that directory overwriting the previous one or will that cause issues with scimax? 
If not, can you suggest a safer way.
thanks for your help!

Arjay

**Comment by jkitchin** [comment]
you can use any version of emacs you want, from anywhere. You just need to update the path in the shell-script that launches emacs to the version you want to use.
