### ISSUE TITLE
pdfx.sty missing in texlive 2021 while exporting to pdf

### ISSUE THREAD

**Issue by zenny** [jkitchin/scimax#435]
Hi,

I am trying to export https://github.com/gouvinb/cv-sample without making any changes in scimax, but I get:

```
This is pdfTeX, Version 3.141592653-2.6-1.40.23 (TeX Live 2021) (preloaded format=pdflatex 2021.10.22)  10 NOV 2021 07:39
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**./curriculum-vitae.tex
(./curriculum-vitae.tex
LaTeX2e <2021-06-01> patch level 1
L3 programming layer <2021-10-18> (./altacv.cls
Document Class: altacv 2020/05/17 AltaCV v1.3.2, yet another alternative class 
for a resume/curriculum vitae.
(/opt/texlive/2021/texmf-dist/tex/latex/base/article.cls
Document Class: article 2021/02/12 v1.4n Standard LaTeX document class
(/opt/texlive/2021/texmf-dist/tex/latex/base/size10.clo
File: size10.clo 2021/02/12 v1.4n Standard LaTeX file (size option)
)
\c@part=\count182
\c@section=\count183
\c@subsection=\count184
\c@subsubsection=\count185
\c@paragraph=\count186
\c@subparagraph=\count187
\c@figure=\count188
\c@table=\count189
\abovecaptionskip=\skip47
\belowcaptionskip=\skip48
\bibindent=\dimen138
)

! LaTeX Error: File `pdfx.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.41 \RequirePackage
                    [margin=2cm]{geometry}^^M
*** (cannot \read from terminal in nonstop modes)

 
Here is how much of TeX's memory you used:
 252 strings out of 480030
 3048 string characters out of 5889895
 292176 words of memory out of 5000000
 18031 multiletter control sequences out of 15000+600000
 403430 words of font info for 27 fonts, out of 8000000 for 9000
 319 hyphenation exceptions out of 8191
 48i,0n,55p,165b,36s stack positions out of 5000i,500n,10000p,200000b,80000s
!  ==> Fatal error occurred, no output PDF file produced!
```

`pdfx.sty` is only available in `texlive-latexextra` package which is already installed, but there is no pointer to `pdfx.sty` in texlive 2021 (nor any `texlive-latexextra` package is available!) 

I have tried in vanilla sandbox emacs config as described https://github.com/gouvinb/cv-sample/issues/5#issuecomment-964821153 using @alphapapa's https://github.com/alphapapa/with-emacs.sh, but it reports a different missing file, `capt-of.sty`! What exactly is going on?

Any input appreciated. Thanks in advance.

**Comment by jkitchin** [comment]
This doesn't seem like a scimax problem, I can build the cv fine. I guess this is a latex problem where either you paths are not complete, or pdfx is not installed (or on the path).

**Comment by zenny** [comment]
> This doesn't seem like a scimax problem, I can build the cv fine. I guess this is a latex problem where either you paths are not complete, or pdfx is not installed (or on the path).

Thanks for the pointer. However, it produced a pdf after removing the distro-based latex packages and relied on tlmgr, but the 4-page pdf is nowhere near the original as the first page is garbled whereas the remaining three pages followed the article template, I guess.

![pic-selected-211112-1408-17](https://user-images.githubusercontent.com/1653166/141472303-0726faea-ce15-4384-b197-4330ee60258f.png)
![pic-selected-211112-1408-27](https://user-images.githubusercontent.com/1653166/141472306-105ba4f1-3cac-4cbd-8f36-05a0ffc34218.png)
![pic-selected-211112-1408-40](https://user-images.githubusercontent.com/1653166/141472310-ca4e4444-09c3-4100-849d-35a44f85a63f.png)
![pic-selected-211112-1408-52](https://user-images.githubusercontent.com/1653166/141472313-87b00266-0eee-4d98-acae-9d1f07d3e298.png)

**Comment by jkitchin** [comment]
That could just mean you use different org-latex-pdf-process for these. What you show is related to LaTeX, and you can build those pdfs at the command line separate from emacs and scimax.

"JSON readtable error: 76"  sounds weird, like something is downloading a file, and getting an error in download where it expected json and didn't get it.  I would first try to export the org file to LaTeX, then go to a shell and run pdflatex manually.  The output you are seeing on the first page is typical of when latex doesn't understand some commands because packages aren't installed or used, for example.

**Comment by zenny** [comment]
Thanks @jkitchin for prompt response.

> That could just mean you use different org-latex-pdf-process for these.

Can you share me your `org-latex-pdf-process` variable?

Mine says:

```
org-latex-pdf-process is a variable defined in `ox-latex.el'.
Its value is ox-manuscript-latex-pdf-process

Original value was 

("%latex -interaction nonstopmode -output-directory %o %f" "%latex
-interaction nonstopmode -output-directory %o %f" "%latex -interaction
nonstopmode -output-directory %o %f")
```

> What you show is related to LaTeX, and you can build those pdfs at the command line separate from emacs and scimax.

Sorry for my confusion? Is there a tut or some pointers howto?

> 
> "JSON readtable error: 76" sounds weird, like something is downloading a file, and getting an error in download where it expected json and didn't get it. 

But I cannot figure it out where from it is trying to fetch?!

> I would first try to export the org file to LaTeX, then go to a shell and run pdflatex manually. The output you are seeing on the first page is typical of when latex doesn't understand some commands because packages aren't installed or used, for example.

I tried to export the org to LaTeX (C-c C-e l l), but I get "JSON readtable error: 76"

**Comment by zenny** [comment]
> This doesn't seem like a scimax problem, I can build the cv fine.

The reason I dared to ask you! ;-) 

That means there maybe some glitches to my `user.el`? Do you use vanilla scimax as in gitrepo or you have customized `user.el`? If so , would you mind sharing your `user.el` - obviously anonymized? 
> I guess this is a latex problem where either you paths are not complete, or pdfx is not installed (or on the path).

`pdfx` is installed:

```
# tlmgr install pdfx
tlmgr: package repository https://ftp.acc.umu.se/mirror/CTAN/systems/texlive/tlnet (verified)
tlmgr install: package already present: pdfx

Is in the path:

```
# fd pdfx /opt/*
/opt/texlive/2020/texmf-dist/tex/latex/lwarp/lwarp-pdfx.sty
/opt/texlive/2020/texmf-dist/doc/latex/pdfmanagement-testphase/l3pdfxform.pdf
/opt/texlive/2020/texmf-dist/source/latex/pdfmanagement-testphase/l3pdfxform.dtx
/opt/texlive/2021/texmf-dist/tex/latex/pdfx
/opt/texlive/2021/texmf-dist/tex/latex/pdfx/pdfx.xmp
/opt/texlive/2021/texmf-dist/tex/latex/pdfx/pdfx.sty
/opt/texlive/2021/texmf-dist/tex/latex/lwarp/lwarp-pdfx.sty
/opt/texlive/2021/texmf-dist/doc/latex/pdfx
/opt/texlive/2021/texmf-dist/doc/latex/pdfx/pdfx.pdf
/opt/texlive/2021/texmf-dist/doc/latex/pdfx/small2e-pdfx.tex
/opt/texlive/2021/texmf-dist/doc/latex/pdfx/pdfx.xmpdata
/opt/texlive/2021/texmf-dist/doc/latex/pdfmanagement-testphase/l3pdfxform.pdf
/opt/texlive/2021/tlpkg/tlpobj/pdfx.tlpobj
/opt/texlive/2021/texmf-dist/source/latex/pdfx
/opt/texlive/2021/texmf-dist/source/latex/pdfx/pdfx.ins
/opt/texlive/2021/texmf-dist/source/latex/pdfx/pdfx.dtx
/opt/texlive/2021/texmf-dist/source/latex/pdfmanagement-testphase/l3pdfxform.dtx
```

```
# echo $PATH
/opt/haxe/:/opt/neko-2.3.0-linux64/:/home/zenny/.cask/bin:/home/zenny/Downloads/adb-fastboot/platform-tools:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/share/apache-ant/bin:/opt/texlive/2021/bin/x86_64-linux:/home/zenny/.local/bin/cron:/home/zenny/.local/bin/i3cmds:/home/zenny/.local/bin/__pycache__:/home/zenny/.local/bin/statusbar:/home/zenny/.local/bin:/usr/share/apache-ant/bin:/opt/texlive/2021/bin/x86_64-linux:/usr/share/apache-ant/bin:/opt/texlive/2021/bin/x86_64-linux
```

Or did I miss something?

Thanks again.

**Comment by jkitchin** [comment]
I guess that you are getting errors from LaTeX. There is a symlink in the cv-sample folder that points to altacv.cls in the AltaCV folder, but it did not work for me. I had to copy AltaCV/altacv.cls into the cv-sample directory.

Then this block works to export the example resume.org file for me.

```
#+BEGIN_SRC emacs-lisp :exports none :result none :exec always
(add-to-list 'load-path (concat "org-cv"))
(require 'ox-altacv)

(setq org-export-with-section-numbers nil)

(let ((org-latex-default-packages-alist '()))
  (org-export-to-file 'altacv "resume-altacv.tex"))
(org-latex-compile "resume-altacv.tex")
(org-open-file "resume-altacv.pdf")
#+END_SRC
```

**Comment by zenny** [comment]
> I guess that you are getting errors from LaTeX. There is a symlink in the cv-sample folder that points to altacv.cls in the AltaCV folder, but it did not work for me. I had to copy AltaCV/altacv.cls into the cv-sample directory.
> 
> Then this block works to export the example resume.org file for me.
> 
> ```
> #+BEGIN_SRC emacs-lisp :exports none :result none :exec always
> (add-to-list 'load-path (concat "org-cv"))
> (require 'ox-altacv)
> 
> (setq org-export-with-section-numbers nil)
> 
> (let ((org-latex-default-packages-alist '()))
>   (org-export-to-file 'altacv "resume-altacv.tex"))
> (org-latex-compile "resume-altacv.tex")
> (org-open-file "resume-altacv.pdf")
> #+END_SRC
> ```

Thanks for the code snippet. 

But I could never render something eye-catching like https://github.com/gouvinb/cv-sample/blob/main/assets/demo.gif even after inserting the snippet. I always got garbled pdf output as reported earlier https://github.com/jkitchin/scimax/issues/435#issuecomment-967107583. :(

**Comment by jkitchin** [comment]
I just cloned the cv-sample repo again, and it looks like maybe you need to update a git submodule. This block seems able to export the pdf correctly for me.

```
#+BEGIN_SRC emacs-lisp :exports none :result none :exec always
(add-to-list 'load-path (concat "org-cv"))
(require 'ox-altacv)

(setq org-export-with-section-numbers nil)

(shell-command "git submodule init")
(shell-command "git submodule update")

(let ((org-latex-default-packages-alist '()))
  (org-export-to-file 'altacv "resume-altacv.tex"))
(org-latex-compile "resume-altacv.tex")
(org-open-file "resume-altacv.pdf")
#+END_SRC
```

**Comment by zenny** [comment]
> (shell-command "git submodule init")
> (shell-command "git submodule update")

Thanks for the helpful input. Yet updated `#+NAME: onsaveblock` to your code, still exporting to pdf gave me a single page output as below:
![pic-selected-220519-1433-18](https://user-images.githubusercontent.com/1653166/169294724-410b9c99-cf9e-4307-8ea6-58f3917f10b4.png)

**Comment by jkitchin** [comment]
you should put that export code in a section tagged :noexport: so it doesn't show. Otherwise, it looks like it is working but maybe something is still wrong in LaTeX.  Try building the tex file manually with latexmk and see if there are some errors.

**Comment by jkitchin** [comment]
It looks like you do not have some latex packages you need, e.g.'

! Undefined control sequence.
l.40 \definecolor

means you need to include xcolor in your latex packages.

I guess that ! LaTeX Error: Command \cvsectionfont undefined.

means you don't have the altacv.cls file installed correctly since that is where it is defined. 

These are not scimax issues though, they are Latex/altacv issues. You should probably post these there.

**Comment by zenny** [comment]
> It looks like you do not have some latex packages you need, e.g.'
> 
> ! Undefined control sequence. l.40 \definecolor
> 
> means you need to include xcolor in your latex packages.

I have installed all the LaTeX packages including xcolor as evident from:

```
# tlmgr info xcolor
package:     xcolor
category:    Package
shortdesc:   Driver-independent color extensions for LaTeX and pdfLaTeX
longdesc:    The package starts from the basic facilities of the color package, and provides easy driver-independent access to several kinds of color tints, shades, tones, and mixes of arbitrary colors. It allows a user to select a document-wide target color model and offers complete tools for conversion between eight color models. Additionally, there is a command for alternating row colors plus repeated non-aligned material (like horizontal lines) in tables. Colors can be mixed like \color{red!30!green!40!blue}.
installed:   Yes
revision:    60925
sizes:       src: 341k, doc: 989k, run: 81k
relocatable: No
cat-version: 2.13
cat-license: lppl1.2
cat-topics:  colour
cat-contact-home: https://github.com/latex3/xcolor
cat-contact-bugs: https://github.com/latex3/xcolor/issues
collection:  collection-latexrecommended

# tlmgr install xcolor
tlmgr: package repository https://ftp.acc.umu.se/mirror/CTAN/systems/texlive/tlnet (verified)
tlmgr install: package already present: xcolor
```


> 
> I guess that ! LaTeX Error: Command \cvsectionfont undefined.
> 
> means you don't have the altacv.cls file installed correctly since that is where it is defined.

`altacv.cls` is in the root of the folder where `report.org` is
> 
> These are not scimax issues though, they are Latex/altacv issues. You should probably post these there.

To debug orgmode export to tex to pdf appears to be exhaustive it appears, so I am here. Anyway thanks for your always positive feedback! Cheers

**Comment by jkitchin** [comment]
you might have them installed, but that doesn't mean you have \usepackage{xcolor} in the tex file, for example, or in the case of altacv.cls that LaTeX is actually loading it. That is probably why you get those undefined errors.
