### ISSUE TITLE
does scimax include drag-and-drop images?

### ISSUE THREAD

**Issue by midas0441** [jkitchin/scimax#440]
John provided an excellent post and video that is somewhat dated now: https://kitchingroup.cheme.cmu.edu/blog/2015/07/10/Drag-images-and-files-onto-org-mode-and-insert-a-link-to-them/

I'm wondering if an updated version of that functionality is in scimax, and if so, where to find that snippet of code? I've tried to use the code as found on the post, but it does not work with current versions of Emacs and org mode... in my hands.

Apologies for posting this query here as it might or might not pertain to scimax specifically.

**Comment by jkitchin** [comment]
I haven't found drag and drop that useful across platforms. I don't think there is any support for it in scimax.

**Comment by midas0441** [comment]
I see. Is there an updated version of the code in the original post, or a way to get similar functionality? I'm going down the rabbit hold of `ns-drag-n-drop` and `dnd-handle-one-url` which seems to look up settings from `dnd-protocol-alist`... perhaps adding an item to `dnd-protocol-alist` to call `my-func` when REGEX matches `jpg` is going in the right direction?

**Comment by midas0441** [comment]
Here's my solution for those who might land here some day in the future:

```
  (add-to-list 'dnd-protocol-alist' ("\\(png\\|jp[e]?g\\|tif[f]\\)\\>" . aa/dnd-image))

  (defun aa/dnd-image (uri _action)
    (let* ((fname (dnd-get-local-file-name uri t)))
      (insert "#+ATTR_ORG: :width 300\n")
      (insert (concat  "#+CAPTION: " (read-string "Caption: ") "\n"))
      (insert (format "[[%s]]" fname))
      (org-display-inline-images t t))
    )
```

More code could readily be added to do the other tricks accomplished by the original snippet.
