### ISSUE TITLE
Windows: scimax-hydra requires org-mac-link

### ISSUE THREAD

**Issue by AKielhorn** [jkitchin/scimax#441]
I'm back on Windows (at work) and I discovered some new problems:

`scimax-hydra.el` has in line 465:

```
(require 'org-mac-link)
```

which I don't have on Windows. As a result, <F12> does not work.

Edit: The reason I don't have `org-mac-link` is that it is part of org-contrib.

Commenting that line did help.

Should I install `org-mac-link` on Windows (and should it be in `package.el`) or should there be a condition around that require?

**Comment by jkitchin** [comment]
You don't really need that on Windows, and it probably wouldn't do anything anyway. Commenting it out should be fine, I think there is just one function to bookmark a url in chrome that won't work. I have pushed a commit that should conditionally load that only on a Mac.
