### ISSUE TITLE
Windows: no grep (counsel-grep-or-swiper)

### ISSUE THREAD

**Issue by AKielhorn** [jkitchin/scimax#442]
My current employer is quite strict when it comes to installing software on the Windows computers.
Therefore I try to work with a minimal installation of Emacs.

Which means I don't have `grep`.

Today `C-s` stopped working, it is looking for `grep`. 

Finding the culprit without `grep` wasn't easy, but here it is:

`package.el`:
```
(use-package swiper
  :bind
  ([remap isearch-forward] . counsel-grep-or-swiper)
  ("H-s" . swiper-all)
  :diminish ivy-mode
  :config
  (ivy-mode))
```

I changed that to `([remap isearch-forward] . swiper)` and it seems to work now.

Note: The file in question is about 80 kbytes, which is well below the 300000 character threshold,
but it is on a server.

**Comment by jkitchin** [comment]
That is also the right thing to do. I pushed a commit that should avoid this issue for you, and only remap that when grep exists, and other wise stick to swiper.
