### ISSUE TITLE
ob src-blocks export configuration

### ISSUE THREAD

**Issue by tarihatari** [jkitchin/scimax#444]
Hi,

when I export to pdf or html I often want to suppress the source blocks and results I have in org.

I tried to achieve this by using the header ":exports none", but for some reason this is not working. e.g.:

```
#+BEGIN_SRC R :exports none
4+5
#+END_SRC

#+RESULTS:
: 9
```

shows both results and code in the exported documents. In this example I used R, but it also doesn't work for ipython and other.

Am I missing something?

**Comment by jkitchin** [comment]
I don't think you are missing anything, it works for me, e.g. this org file
![image](https://user-images.githubusercontent.com/1610070/150707497-4e0d99e4-a615-41c5-938c-af7e9b9c8d9f.png)

exports to this pdf
![image](https://user-images.githubusercontent.com/1610070/150707519-b24f4b6e-9a50-484e-b049-59ae7594b220.png)

I am not sure why it wouldn't do that for you.

**Comment by tarihatari** [comment]
Thanks, I found the issue! I was caused by
```
;; Do not evaluate code blocks when exporting.
(setq org-export-babel-evaluate nil)
```
in my user.el.
