### ISSUE TITLE
org-teleport not working with emacs 27.2 and potential fix

### ISSUE THREAD

**Issue by SterlingHooten** [jkitchin/scimax#445]
Calling org-teleport gives error: `avy-jump: Keyword argument nil not one of (:window-flip :beg :end :action :pred)`
This error comes from the call to avy-jump in org-teleport, specifically ` (avy-with avy-goto-line (avy-jump org-heading-regexp nil))`

On my system, removing the `nil` allows the function to work again.
` (avy-with avy-goto-line (avy-jump org-heading-regexp))`

**Comment by jkitchin** [comment]
Thanks for reporting this. fixed I think.
