### ISSUE TITLE
Jupyter kernel freezes on first execution

### ISSUE THREAD

**Issue by prtkm** [jkitchin/scimax#447]
Hi John,

Just did a fresh install of scimax on Mac OS Monterey, and emacs-plus@27, seems like if I try to start a juptyer-python or ipython block and execute it for the first time, it says kernel started in x seconds and then emacs freezes. If I Ctrl+g out of it and re-run it the code works just fine (because the kernel did indeed start on the first execution). Any thoughts on why this could be happening?

Below are some Jupyter details:
Jupyter console 6.4.3
Python 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:27:43) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.2.0 -- An enhanced Interactive Python. Type '?' for help.

**Comment by jkitchin** [comment]
I have been moving over to emacs-jupyter for a while, in part because of things like this.  I am not real sure what causes it, but it is likely related to the communication through a local web server I guess.

You could try commenting out the ob-ipython support in packages.el and add this instead.

```

(when (executable-find "jupyter")
  (use-package jupyter)
  (use-package scimax-jupyter :load-path scimax-dir)
  )
```

It is not totally perfect, but functional enough I have used it for 6-9 months now. Summer project to polish it up I hope.

**Comment by prtkm** [comment]
So I tried that, and it tries to compile ZMQ, although I already have a brew zmq installed. It also doesn't like that I don't have Julia installed I think.

**Comment by jkitchin** [comment]
I don't think is should matter if julia is installed. you can definitely comment out the julia section if you don't need it.

I feel like I had to manually build the zmq extension in the emacs-jupyter directory, it didn't build right on its own via melpa. 

however, that is not working right now, I get some cask error in the melpa code, you may need to clone that repo. these are some reasons I haven't made this standard in scimax yet...

**Comment by alaskamike** [comment]
John,
I did the same, albeit on Windows.  I commented out all references to julia
and manually added the zmq.dll file in the elpa folder.
emacs-jupyter is much faster and more stable than ipython.

Mike

**Comment by prtkm** [comment]
I think I got this to work. Seems like I didn't have automate installed so the initial zmq compilation was failing. After installing it with home-brew, the compilation worked fine within emacs.
