### ISSUE TITLE
non-ascii characters in errors, warnings, etc with emacs-jupyter 

### ISSUE THREAD

**Issue by prtkm** [jkitchin/scimax#448]
Not totally sure if this is a scimax issue or something on my end, but I get non-ascii characters with errors in jupyter-python. Its not a big deal but it makes it harder to read the messages if they are long.

:RESULTS:
# [goto error]
[0;36m  Input [0;32mIn [11][0;36m[0m
[0;31m    print a[0m
[0m          ^[0m
[0;31mSyntaxError[0m[0;31m:[0m Missing parentheses in call to 'print'. Did you mean print(a)?
:END:

**Comment by jkitchin** [comment]
Those are ansi color codes that in theory should be invisible and change the color of the text. I have been trying to find a fix for that, fix limited success so far. You could try this:

```
(defun scimax-jupyter-ansi ()
  (let* ((r (org-babel-where-is-src-block-result))
	 (result (when r
		   (save-excursion
		     (goto-char r)
		     (org-element-context)))))
    (when result
      (ansi-color-apply-on-region (org-element-property :begin result)
					       (org-element-property :end result)))
    t))



(add-to-list 'org-babel-after-execute-hook 'scimax-jupyter-ansi t)
```

**Comment by prtkm** [comment]
Awesome! That worked quite well :)
