### ISSUE TITLE
Heading levels reset by ipython src blocks when exporting to ipynb

### ISSUE THREAD

**Issue by singletS** [jkitchin/scimax#45]
When exporting to org files to ipynb,  evaluating ipython src blocks in a subheading causes the heading level to reset. Headings/subheadings that do not have intervening src blocks work as expected:
```
* Top level heading
This is a top level heading

** Second level heading
A 2nd level heading with a src block will appear as second level, but later 
subheadings at or below will be reset.

#+BEGIN_SRC ipython :session :results output drawer
import sys
print(sys.version)
#+END_SRC

#+RESULTS:
:RESULTS:
3.6.0 |Anaconda custom (64-bit)| (default, Dec 23 2016, 12:22:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
:END:

** Second level heading
This will revert to first level

*** Third level heading
    This will revert to a second level.
```
Not a big deal, so this can go in the "maybe someday" pile...
emacs26.0.50, org 9.0.5

**Comment by jkitchin** [comment]
I wonder if this is a limitation of the markdown export.

A cell is produced like this:

#+BEGIN_SRC emacs-lisp
(org-export-string-as "** second heading"
	      'md t '(:with-toc nil :with-tags nil))
#+END_SRC

#+RESULTS:
: 
: # second heading
: 

I have no idea how to fix that. Thanks for reporting it!

**Comment by jkitchin** [comment]
good news. I think I pushed a fix for this.

**Comment by singletS** [comment]
Fixes the issue.  Thanks!
