### ISSUE TITLE
do-applescript equivalent in linux

### ISSUE THREAD

**Issue by zenny** [jkitchin/scimax#454]
Hi @jkitchin,

There are mentions of `do-applescript` in many a places as grepped below, but they tend to cause `void-function` errors in GNU/Linux! How to replace an equivalent?

```
./ox-clip/ox-clip.el:501:       (do-applescript
./scimax-utils.el:317:    (do-applescript
./scimax-utils.el:403:    (do-applescript applescript)
./scimax-org-images.el:220:       (prog1 (do-applescript (format applescript path))
./deprecated/contacts.el:354:                          (do-applescript
./deprecated/contacts.el:405:                        (do-applescript
./deprecated/contacts.el:624:                       (do-applescript
./deprecated/contacts.el:740:              (do-applescript
./words.el:465:  (do-applescript (concat
```

Thanks and have a nice weekend!

**Comment by jkitchin** [comment]
There is no cross-platform equivalent of these that I know of. They should not cause errors though unless you call those functions I think. How are you getting that error?

**Comment by zenny** [comment]
> There is no cross-platform equivalent of these that I know of. They should not cause errors though unless you call those functions I think. How are you getting that error?

Whenever I try to launch emacs menu by pressing 'f10'.

**Comment by jkitchin** [comment]
f10 is found to screenshot for me, which is a mac only function in scimax-utils. What function were you expecting f10 to run?

**Comment by zenny** [comment]
> f10 is found to screenshot for me, which is a mac only function in scimax-utils. What function were you expecting f10 to run?

I just commented the following line 342 in `scimax-utils.el` (https://github.com/jkitchin/scimax/blob/f38f9e7c5c4e1f4ec66dd215e918f4d204418879/scimax-utils.el#L342) to launch emacs default menu instead.

```
;;(global-set-key (kbd "<f10>") 'screenshot)
```

:D

**Comment by jkitchin** [comment]
That is a fair point, that setting probably belongs in a user config.
