### ISSUE TITLE
*Org PDF LaTeX Output* appears blank after an error!

### ISSUE THREAD

**Issue by zenny** [jkitchin/scimax#455]
Hi,

*Org PDF LaTeX Output* does not report anything (blank) after pdflatex or xelatex runs into issues! This makes debugging pretty difficult.

Is there a way to make it verbose? Thanks!

**Comment by jkitchin** [comment]
that has also bugged me for some time. One way to handle it is `ox-manuscript-toggle-interactive-build` which will show the output of each intermediate step and prompt you for continuing. I added some code to try catching this of you are using  ox-manuscript-latex-pdf-process as the org-latex-pdf-process. An altermative might be set it to something like `'("latexmk -f -pdf -%latex -interaction=nonstopmode -output-directory=%o %f")`.

**Comment by zenny** [comment]
> '("latexmk -f -pdf -%latex -interaction=nonstopmode -output-directory=%o %f")

Thanks for confirming the issue.

After I appended the following line:

```
(setq org-latex-pdf-process (list
'("latexmk -f -pdf -%latex -interaction=nonstopmode -shell-escape -output-directory=%o %f")))
```

 I landed to another error, fyi:
```
Wrong type argument: stringp, ("latexmk -f -pdf -%latex -interaction=nonstopmode -shell-escape -output-directory=%o %f")
```

However, appending the following line:
```
(setq org-latex-pdf-process (list "latexmk -shell-escape -bibtex -f -pdf %f"))
```
produced 12k of *Org PDF LaTeX Output*, but failed to produce pdf (maybe due to other reasons).

**Comment by jkitchin** [comment]
you have to set it like this: `(setq org-latex-pdf-process '("latexmk -f -pdf -%latex -interaction=nonstopmode -shell-escape -output-directory=%o %f"))`.

Presumably the contents of _Org PDF LaTeX Output_ indicate there are some errors that lead to no pdf formed. Sometimes I find it easier to run this command in a shell to see what is happening.

**Comment by jkitchin** [comment]
Update. I think this is a bug in the current org code. At https://git.sr.ht/~bzg/org-mode/tree/main/item/lisp/ox-latex.el#L4313 there is code that erases this buffer. It is a little odd that this change seems to have been made months after your reported this, so maybe there have been multiple reasons for this issue. Anyway, commenting that line out fixes the problem for me.
