### ISSUE TITLE
[REQUEST] A video presentation on your notetaking and annotation workflow

### ISSUE THREAD

**Issue by zenny** [jkitchin/scimax#457]
Hi @jkitchin:

You have made a wonderful presentation posted in https://youtu.be/31gwvApo8zg from 01:17:15 to 01:45:00 about the citation with org-ref.

I wish you make a similar informative and useful presentation on your workflow of notetaking, annotation and capture the annotated text to org-ref. It would be helpful to a lot of scimax enthusiasts like me.

Thanks and cheers,
/z

**Comment by jkitchin** [comment]
you may find these playlists interesting: https://www.youtube.com/playlist?list=PL0sMmOaE_gs3E0OjExoI7vlCAVygj6S4I

and https://www.youtube.com/playlist?list=PL0sMmOaE_gs3GbuZV_sNjwMREw9rfElTV

**Comment by zenny** [comment]
> you may find these playlists interesting: https://www.youtube.com/playlist?list=PL0sMmOaE_gs3E0OjExoI7vlCAVygj6S4I
> 
> and https://www.youtube.com/playlist?list=PL0sMmOaE_gs3GbuZV_sNjwMREw9rfElTV

Thanks. Yet I suggest you to post a video on the way you extract the annotation from the pdfs/epubs/documents.

Actually I am trying to figure out a way to capture any annotation from any journal/book which automagically imports the DOI of the document based on metadata and further appends the bibliography.

What I meant was:

1. Say you are reading a paper which is not in your bib file. 
2. You found part of the paper relevant to your research and wanted to quote the paper. So you made an annotation.
3.  Once you made the annotation, the quote as well as the citations gets updated to your org document (to your chosen journal templates) as well as the bib file once you capture with a specific template.

A tutorial in this regard would be wonderful. Thanks anyway! Cheers,

**Comment by jkitchin** [comment]
That is not something that I do when I am writing. It is generally tricky to go from a PDF to a DOI. in version 2, there was a function for extracting DOIs from a pdf, but 1) it is hard to use a regexp to find DOIs with 100% accuracy, and 2) sometimes there are multiple DOIs in a PDF, e.g. from references. It sounds like you are looking for something like pdf-tools, with some wrapper code to do those things. That isn't something I plan to integrate into org-ref.
