### ISSUE TITLE
ws-butler missing for fresh Windows installation

### ISSUE THREAD

**Issue by jboes** [jkitchin/scimax#46]
The following error occurs from a fresh installation on Windows:

url-insert-file-contents: http://melpa.org/packages/ws-butler-20150126.759.el: Not found

Commenting out the import of the package from packages.el is a temporary solution to the problem.

**Comment by jkitchin** [comment]
I can't reproduce this. It sounds like a problem with either melpa being unavailable, or it happening to get updated while installing so that package is no longer current. The current version is http://melpa.org/packages/ws-butler-20170111.1534.el

**Comment by jkitchin** [comment]
I think this happens because use-package might be included in emacs now, and it had an outdated package archive. I pushed something that might take care of it.
