### ISSUE TITLE
Installation problems - Windows 11

### ISSUE THREAD

**Issue by castellco** [jkitchin/scimax#462]
Hi.
After installing scimax, I get the following:

`Error (use-package): Failed to install dashboard: Package ‘emacs-26.1’ is unavailable

Error (use-package): Cannot load dashboard

Error (use-package): Failed to install magithub: Package ‘emacs-26.1’ is unavailable

Error (use-package): parsebib/:catch: rx ‘not’ syntax error: ]

Error (use-package): Failed to install helm-bibtex: Package ‘emacs-26.1’ is unavailable

Error (use-package): Cannot load helm-bibtex

Error (use-package): Failed to install ivy-bibtex: Package ‘emacs-26.1’ is unavailable

Error (use-package): Cannot load ivy-bibtex

Error (use-package): Failed to install citeproc: Package ‘emacs-26’ is unavailable

Error (use-package): Cannot load citeproc

Error (use-package): org-ref/:init: rx ‘not’ syntax error: ]

Error (use-package): org-ref/:catch: rx ‘not’ syntax error: ]

Error (use-package): org-ref-ivy/:catch: rx ‘not’ syntax error: ]

Error (use-package): scimax-org/:init: Symbol’s function definition is void: org-link-set-parameters

Error (use-package): scimax-contacts/:catch: No EmacSQL SQLite binary available, aborting

Error (use-package): scimax-email/:catch: Cannot open load file: No such file or directory, citeproc

Error (use-package): Failed to install org-ql: Package ‘emacs-26.1’ is unavailable

Error (use-package): Cannot load org-ql`

And it gets stuck. It was a fresh install, I had deleted my previous emacs installation and config.  How can I resolve this?

**Comment by jkitchin** [comment]
What version of emacs are you using? The most recent build (https://github.com/jkitchin/scimax/actions/runs/3097731788/jobs/5014749883) seems to work on version 27+, but not on 26.
