### ISSUE TITLE
aggressive-indent bug

### ISSUE THREAD

**Issue by OrionRandD** [jkitchin/scimax#463]
I am having an issue with this aggressive-indent package.
I have deleted it. 
Then melp installs it again and the error does not dissapear...

Compiling file /home/vagner/scimax/elpa/aggressive-indent-20221003.2200/aggressive-indent.el at Mon Oct  3 21:45:38 2022
Entering directory ‘/home/vagner/scimax/elpa/aggressive-indent-20221003.2200/’
aggressive-indent.el:491:1: Error: Wrong type argument: stringp, :lighter

Compiling internal form(s) at Mon Oct  3 21:45:38 2022

**Comment by jkitchin** [comment]
I haven't seen this yet. You could just comment out this line in packages.el

```
(use-package aggressive-indent
  :config (add-hook 'emacs-lisp-mode-hook #'aggressive-indent-mode))
```

**Comment by OrionRandD** [comment]
> I haven't seen this yet. You could just comment out this line in packages.el
> 
> ```
> (use-package aggressive-indent
>   :config (add-hook 'emacs-lisp-mode-hook #'aggressive-indent-mode))
> ```

Yeah. 
I had already done that.
Thx again.

**Comment by OrionRandD** [comment]
> Looks like this was reported here [Malabarba/aggressive-indent-mode#158](https://github.com/Malabarba/aggressive-indent-mode/issues/158)

I will have a look on that...
By the way, do you have any plans to integrate scimax with jabref, zotero standalone and zotero plugins for firefox and chromium?
I think it would be a great add for scimax. 
I am seeing some videos about org-ref in your channel...

**Comment by jkitchin** [comment]
I don't currently have any plans to extend org-ref past its current capability. There are things like https://github.com/egh/zotxt and https://github.com/egh/zotxt-emacs. i don't have the need or time to do something like that I think.

**Comment by OrionRandD** [comment]
> I don't currently have any plans to extend org-ref past its current capability. There are things like https://github.com/egh/zotxt and https://github.com/egh/zotxt-emacs. i don't have the need or time to do something like that I think.

OK. Fair enough :)
