### ISSUE TITLE
emacs 28.2 breaks pdf image inclusion

### ISSUE THREAD

**Issue by uliw** [jkitchin/scimax#464]
this is more of a heads-up. Emacs 28.2 changes the way images are handled. If a file includes an image in pdf format it will result in a `File mode specification error: (error Invalid image type ‘imagemagick’)`. Latex export still works, but the above errors can throws a wrench into other features (e.g. image preview).  I filed a bug report on the emacs list.

**Comment by jkitchin** [comment]
This probably means you didn't build Emacs with imagemagick support.

**Comment by uliw** [comment]
Emacs dropped ImageMagick in 27.1. and replaced it with some internal mechanism. The release notes state on line 2181 that pdfs are no longer supported by default in the new code
https://github.com/emacs-mirror/emacs/blob/master/etc/NEWS.28
https://github.com/emacs-mirror/emacs/blob/master/lisp/image.el lines 1093 ff

Building with ImageMagick support is a workaround, however. thx for pointing this out

**Comment by uliw** [comment]
OK, did a bit more digging. It actually works in a plain vanilla 28.2. The culprit seems to be the following code in scimax-org.el
```
;; * Enable pdf and eps images in org-mode
;; Suggested on the org-mode maillist by Julian Burgos
(add-to-list 'image-file-name-extensions "pdf")
(add-to-list 'image-file-name-extensions "eps")

(add-to-list 'image-type-file-name-regexps '("\\.eps\\'" . imagemagick))
(add-to-list 'image-file-name-extensions "eps")
(add-to-list 'image-type-file-name-regexps '("\\.pdf\\'" . imagemagick))
(add-to-list 'image-file-name-extensions "pdf")

(setq imagemagick-types-inhibit (remove 'PDF imagemagick-types-inhibit))
```

commenting this section resolves the problem. Maybe this code block should be version specific (<28.2)?
