### ISSUE TITLE
svg images

### ISSUE THREAD

**Issue by uliw** [jkitchin/scimax#465]
Including and SVG image in an org buffer like this
```
[[./my.svg]]
```
results in the correct preview display of the file when using vanilla emacs 28.2.
However, once I load the scimax code with no local customizations, the display is garbled. This behavior is contingent on setting org-actual-image with. If unset, the image renders just fine.

It appears that the scimax? customization tries to scale the svg-file? Possibly in  scimax-org-inline-image-resize in scimax-org-images.el

**Comment by jkitchin** [comment]
weird. I wonder if this also supported by imagemagick, I don't have any issues with svg.

For me, `org-image-actual-width` is nil. What did you set yours too?

**Comment by uliw** [comment]
if set to nil, svg inline works ok. If set to `(setq org-image-actual-width '(300)` svg inlining breaks

**Comment by jkitchin** [comment]
hm. That works fine for me. 

One solution might be to toggle the image advice off with  M-x scimax-toggle-image-advice. You might also try 

`(setq org-inline-image-resize-function nil)`

**Comment by uliw** [comment]
`scimax-toggle-image-advice` does the trick, and also resolves the problem of pdf-images not being displayed as previews.
BTW,  what does this function do?

**Comment by uliw** [comment]
I see. It seems that my emacs scales the display as a fraction of the screen width. So no harm in toggling this off.
