### ISSUE TITLE
Odd installation message on Win11

### ISSUE THREAD

**Issue by Arjay-El** [jkitchin/scimax#466]
Adding scimax to a new laptop. Using Git for windows to  execute the bash command copied from the read.me file. Its always worked before. This time Git gives me these error messages. Has something changed in the bash command that Git chokes on now? Thanks.

$ bash -c "$(curl -fsSL https://raw.githubusercontent.com/jkitchin/scimax/master/install-scimax-win.sh)"
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
bash: line 19: cd: emacs-win: No such file or directory
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
scimax is installed. To use it, run this command in your terminal.
/c/emacs-win/bin/runemacs.exe -q -l /c/init.el
or
run the scimax.bat script created in this directory or as ./scimax.sh in the terminal.
bash: line 36: scimax.bat: Permission denied
bash: line 37: scimax.bat: Permission denied
bash: line 40: scimax.sh: Permission denied
Opening scimax.  Be patient.
The system cannot find the file .\emacs-win\bin\runemacs.exe.

**Comment by jkitchin** [comment]
that does seem odd. I would go to https://raw.githubusercontent.com/jkitchin/scimax/master/install-scimax-win.sh, and try running those commands line by line.  It seems like something failed early in cloning the repo, and then a bunch of subsequent git commands failed.
