### ISSUE TITLE
emacs-zmq: Segmentation fault

### ISSUE THREAD

**Issue by prairie-guy** [jkitchin/scimax#475]
- First time user of scimax
- Ubuntu 22.04
- Downloaded repo from github
- `emacs -q -l scimax/init.el` causes a segmention fault attributable to `emacs-zmq`
- `sudo apt install libzmq3-dev` did not resolve the problem

I’m working in a molecular biology lab and have been a long time user of emacs. I am tired of proprietary ELNs and would like to use a literate programming style within emacs to initially document  lab protocols and ultimately as a real ELN . I haven’t gotten babel to quite work the way I want to. I came across scimax and it looks like it might be interesting.

Thanks for any help or advice in moving past this problem.

**Comment by jkitchin** [comment]
have you tried building the emacs-zmq library by hand? Check the source, there should be a makefile and/or configure script.

**Comment by jkitchin** [comment]
You can use 
```
:results drawer
```

in a src block header. you can also set this in `org-babel-default-header-args`

**Comment by jkitchin** [comment]
In the zmq directory in your Elpa dir, there should be a Makefile.

I had to run these commands in that directory:

```
make src/configure
make
```

I think that build the library on a Mac for me.
