### ISSUE TITLE
ox-ipynb.el thows error if no src blocks exist

### ISSUE THREAD

**Issue by singletS** [jkitchin/scimax#48]
Edge case: if no src blocks are present in org file,  ox-ipynb-get-language() throws a wrong-type error.

I added a simple check to ox-ipynb-get-language(), and export-notebook produced an ipynb without specifying a kernel. Unsurprisingly, Jupyter didn't like that, so maybe an arbitrary kernel should be assumed if one isn't defined in the org file. Python?

**Comment by jkitchin** [comment]
I pushed a fix that uses ipython as a default.

**Comment by singletS** [comment]
Thanks
