### ISSUE TITLE
linux installation - some observations

### ISSUE THREAD

**Issue by uliw** [jkitchin/scimax#481]
Hi John,

using the homebrew method to install scimax I observed the following:

1. the install pulls in lot's of libraries that are already availble (and uptodate) on the host system
2. the install builds a new emacs even so an uptodate emacs is available on the host
3. the install builds a tty based emacs, rather than using the gtk backend.
4.  #1 & 2# surely help with installing on nonlinux systems, but is there a way to avoid the duplication?
5. is there a way to direct the instal process to build a emacs with a graphical frontend?

Cheers

**Comment by uliw** [comment]
1, 2, 3 no biggie, it was just a suprise. The benfits surely outweigh the cost of HD space. However, it appears building emacs on linux with homebrew does not support building with --with-x-toolkit=gtk3, so probably best to simply have a list of requirments rather than using homebrew on linux.

Doing a scimax install via git clone I noticed the following:
 - elpy seems to be required early on, but is commented in packages.el. 

Other than that startup is fine after adjusting the init files.

**Comment by jkitchin** [comment]
I don't think elpy is actually required. I guess if you are byte-compiling something like scimax-hydra maybe you could run into some warnings about undefined functions. I think I have taken out everything that used elpy functions in the commits above.

**Comment by uliw** [comment]
yup, I think those errors disappeared after deleting the eln cache and recompiling all el files.
