### ISSUE TITLE
ob-ipython

### ISSUE THREAD

**Issue by uliw** [jkitchin/scimax#482]
I removed reference to ob-ipython from my settings file, but starting complains about missing ob-ipython. Is this still a hard coded requirement in scimax?

**Comment by jkitchin** [comment]
There should not be a requirement for that. Can you paste the whole traceback?

**Comment by uliw** [comment]
restarted from scratch, and it turned out I was pointing to the wrong (odl) startup directory

**Comment by uliw** [comment]
still happening. it is triggered by `org-babel-do-load-languages` is this no longer required?
```
Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "ob-ipython")
  org-babel-do-load-languages(org-babel-load-languages ((emacs-lisp . t) (octave . t) (python . t) (ipython . t) (plantuml . t) (smiles . t) (maxima . t) (ditaa . t) (jupyter . t)))
  load-with-code-conversion("/home/uliw/.emacs.d/settings.el" "/home/uliw/.emacs.d/settings.el" nil nil)
  load-file("/home/uliw/.emacs.d/settings.el")
  org-babel-load-file("/home/uliw/.emacs.d/settings.org")
  load-with-code-conversion("/home/uliw/.emacs.d/user.el" "/home/uliw/.emacs.d/user.el" nil nil)
  load("/home/uliw/.emacs.d/user.el")
  load-with-code-conversion("/home/uliw/user/dot-files/.emacs.d/init.el" "/home/uliw/user/dot-files/.emacs.d/init.el" nil t)
  command-line-1(("-l" "/home/uliw/.emacs.d/init.el"))
  command-line()
  normal-top-level()
```

**Comment by jkitchin** [comment]
I guess it is because you have `(ipython . t)` in org-babel-load-languages. I think you can remove that.

**Comment by uliw** [comment]
ok, that solved the ob-python dependency. But I do have difficulties with the jupytr-python setup.
running a simple block like this
```
#+BEGIN_SRC jupyter-python
for i in range(3):
    print(i)
#+END_SRC
```
results in
```
zmq--subprocess-filter: Error in ZMQ subprocess: error, ("Invalid signature (861fc0cb638e59b7314ebedf7ad616ea0dcd8c4effd9c419ec38e2909263d9d3)
```
how do I debug this? Thx!

**Comment by jkitchin** [comment]
I would probably file an issue at https://github.com/emacs-jupyter/jupyter/issues to start. I haven't seen that particular error before.

**Comment by uliw** [comment]
possibly related to https://github.com/emacs-jupyter/jupyter/issues/464
