### ISSUE TITLE
sql error?

### ISSUE THREAD

**Issue by uliw** [jkitchin/scimax#483]
Not sure whether this scimax related, but I observed the following after a complete re-install of scimax. This seems to be related to the parsing of headlines in org files. 

```
Debugger entered--Lisp error: (emacsql-error "table headlines has 12 columns but 14 values were ..." 1 nil "SQL logic error")
  signal(emacsql-error ("table headlines has 12 columns but 14 values were ..." 1 nil "SQL logic error"))
  #f(compiled-function (_ errcode errmsg) "Get condition for ERRCODE and ERRMSG provided from SQLite." #<bytecode -0x5f6278107907d9>)(#<emacsql-sqlite-connection emacsql-sqlite-connection-157bed8e29cc> 1 "table headlines has 12 columns but 14 values were ...")
  apply(#f(compiled-function (_ errcode errmsg) "Get condition for ERRCODE and ERRMSG provided from SQLite." #<bytecode -0x5f6278107907d9>)
```

**Comment by jkitchin** [comment]
this is from org-db in scimax. an update to org-db added two columns, so now it is trying to write 14 values to a table with only 12 columns.

do you use org-db for anything?

If you don't, you can probably just run this in an elisp block:

```
#+BEGIN_SRC emacs-lisp
(delete-file (expand-file-name org-db-name org-db-root))
#+END_SRC
```

that will just delete the db file, and it will be re-created in the right size.

If you want to preserve your db, then probably we need to alter the table, and maybe that can fix it. that shouldn't be too hard.

**Comment by uliw** [comment]
that did the trick. Thanks

**Comment by jkitchin** [comment]
org-db is not automatically loaded in scimax now, so if you don't use it, you could comment out the lines that load it somewhere.

I find it useful enough and it is "mostly stable". I think I added deadlines and scheduled dates to enable an org-db-agenda, which caused this issue for you.
