### ISSUE TITLE
abbrev-file-name

### ISSUE THREAD

**Issue by uliw** [jkitchin/scimax#484]
scimax.el defines
```
./scimax/scimax.el:(setq abbrev-file-name (expand-file-name "user/abbrev_defs" scimax-dir))
```
when installing via git-clone the user directory is however not present.   setting `abbrev-file-name`  in the startup file  remedies the situation, just wanted to mention this in case it is an oversight

**Comment by jkitchin** [comment]
thanks for noting that. I commented these lines out for now.
