### ISSUE TITLE
org-id-locations-file

### ISSUE THREAD

**Issue by uliw** [jkitchin/scimax#487]
Currently, `scimax-org.el` defines
```
(setq org-id-locations-file
      (expand-file-name "user/.org-id-locations" scimax-dir))
```
But I seem to recall that user data should now live separate from the scimax  tree?

on a separate note, `packages.el` loads 'auto-complete` but does not otherwise initialize it, and elpy uses company as default backend. Maybe that can be dropped?

**Comment by jkitchin** [comment]
I think we can remove that setq.  The elpy code is commented out in packages.el. I don't think I use auto-complete for anything, so I commented that out for now.
