### ISSUE TITLE
Error on exporting org to beamer (solution is also suggested)

### ISSUE THREAD

**Issue by shervinsafavi** [jkitchin/scimax#488]
When I export a org file to beamer I get the erorr of `! LaTeX Error: Option clash for package hyperref.`. I noticed this comes because of the `org-latex-default-packages-alist` funciton which is defined in scimax. If I remove lines related to "hyperref" package it works. So, my question is, what would be the best way to solve the issue? Either changing the scimax function `org-latex-default-packages-alist`, or redefining `org-beamer-export-to-pdf`, such that it uses a modified `org-latex-default-packages-alist`. Which one do you think is a better solution (or a third one)? Do you think you will change it on scimax also (or I just do them locally)?

**Comment by jkitchin** [comment]
You have several options. You don't need to modify anything in scimax or org-beamer.

If you don't like the scimax setting for anything, simply redefine the variable in your user files as you see fit after scimax loads. `org-latex-default-packages-alist` is just a variable, so you can just redefine it.

If it is just a problem in a single file, you can temporarily set it in that file. That might look something like this:

```
* build :noexport:

#+BEGIN_SRC emacs-lisp
(let ((org-latex-default-packages-alist
       '(("AUTO" "inputenc" t)
	 ;; used for marking up chemical formulas
	 ("version=3" "mhchem" t)
	;; add whatever you want in here.				  
	 ("numbers,super,sort&compress" "natbib" nil)
	 ("" "natmove" nil))))
  (org-beamer-export-to-pdf))
#+END_SRC
```

**Comment by shervinsafavi** [comment]
Thanks very much, that solved the problem!
