### ISSUE TITLE
Useful bug that might be a feature? Bold delimiters and starting new cells with ox-ipynb

### ISSUE THREAD

**Issue by singletS** [jkitchin/scimax#49]
Continuing to play with the awesome ox-ipynb, I discovered it will start a new cell if the first characters on a line are org-mode bold delimiters, e.g: `**blah**`.  Turns out this is useful, but I'm wondering if there's an "official" way to start a new cell in ox-ipynb. If not, does it make sense to have something like `#+ipynb-newcell`?

Motivation: I tried the collapsible heading nbextension which, as suggested in #47 , makes long notebooks more navigable (I'm sold!).  However, the extension collapses at the cell level; i.e., text is not collapsed if it's in the same cell as a heading. Starting a new cell immediately after the heading leads to a "more collapsible" notebook. (Also more along the lines of MMA if that's important :).

Example of org bold feature-bug working with collapsible headings extension:
```
* First heading
This text won't be collapsed using the nbextention.
* Second heading
The org parser will split the text below into a new cell. Accidentally useful!

**&nbsp;** This kludge will start a new cell after the heading, enabling this
text to be collapsed. However, you get a non-breaking space indent in the text.

** A sub heading
Can also be split
**with** bold intact.
```

**Comment by jkitchin** [comment]
Wow, you are super good at finding the edge cases! I added your idea to use #+ipynb-newcell to split a cell, and to put headlines in their own cell to make folding better. Thanks for trying so many variations! Let me know how the new version works.

**Comment by singletS** [comment]
One bug: text after a src block gets lost rather than put into a md cell. If the src block is the last thing before a new heading, no problems. Example in snippet below.

The automatic "new cell after heading" addition works, and brings Jupyter notebooks another 1.1% closer to org mode with nifty folding.  It's a bit different (lots of clicky bits with headings till I grok the key bindings) but in five minutes of dinking around, it seems a good approach--meshes better with what several nbextensions expect. I'd be interested in your (and others') thoughts after using it a while.

The #+ipynb-newcell works nicely, too.

```
* First heading
Paragraphs can be collapsed with nbextention. 
Test consecutive newcells, one of which is empty:
#+ipynb-newcell

#+ipynb-newcell
This should be a new md cell.
#+BEGIN_SRC ipython :session

#+END_SRC

But this text after a src block is lost [BUG]
* Second heading
And the auto-numbering TOC extension works, too.

** A sub heading
Doesn't split with
**bold** anymore.

#+BEGIN_SRC ipython :session
# there should be a markdown cell below this code block.
#+END_SRC

This is lost.
** Another heading
#+ipynb-newcell
Behaves as expected.
```


> Wow, you are super good at finding the edge cases!

Heh...not so much...just mimicking my students' habit of doing baffling things with new toys :)

Thanks for the explanations and fixes for my issues...I'm loving this thing.

**Comment by jkitchin** [comment]
That was indeed a bug. I think it is fixed now. BTW, you can use *bold* so it is bold in org-mode too.

**Comment by singletS** [comment]
Looks good. Thanks!
