### ISSUE TITLE
emacs-jupyter

### ISSUE THREAD

**Issue by uliw** [jkitchin/scimax#491]
On Linux, the emacs-jupyter version needs to be pinned to a specific version, see https://github.com/emacs-jupyter/jupyter/issues

However, packages.el installs the version from melpa, even though the pinned version is already installed locally. Now, that is an easy fix on my end, but then I have to stash and edit packages.el every time I update via git. Is there a way to check if a local emacs-jupyter version is already present before pulling in the melpa version?

Edit: Would it be possible to use packages.el only for a minimal subset, then load settings.el, and afterward load any missing packages?

**Comment by uliw** [comment]
that still loads the elpa version, since settings.el has not yet been loaded, so featurep would not know that jupyter will be loaded at a later stage.

**Comment by jkitchin** [comment]
is settings.el your personal files? If so, scimax looks for a preload.el file in init.el (locate-user-emacs-file "preload.el") and loads that first. Maybe you can put something there to load your jupyter?

I guess it doesn't work to load your version afterwards? It seems like that should work.

**Comment by uliw** [comment]
ah I see. Yes that works with the abobe code once package managments has been initialized. Thx!
