### ISSUE TITLE
scimax-jupyter results

### ISSUE THREAD

**Issue by uliw** [jkitchin/scimax#492]
If I run 
```
#+BEGIN_SRC jupyter-python
print(2)
#+END_SRC
```
I get
```
#+RESULTS:
:RESULTS:
2
:END:
```
when I export this to LaTeX, I get `RESULTS:`  set in bold font, followed by the number two
```
\textbf{RESULTS}: 2
```

Are there options to adjust the rendering of this? 

And related, I use some python code to create graph, and I hide the src block on export with `:exports results` . In that case I end up with an orphaned `RESULTS:` text fragment. 
```
\textbf{RESULTS}: \begin{figure}[htbp]
\centering
\includegraphics[width=0.7\textwidth]{./gh_effect.png}
\caption{\label{ghe}The Greenhouse Effect on Earth is stronger than on Mars, even so there is less CO\textsubscript{2}. But compare the water content of the respective atmospheres!}
\end{figure}
```
Is there an option to avoid this? I looked at the org-manual, but no luck (or bad eyes)

**Comment by jkitchin** [comment]
hm. I don't get that.

```
#+BEGIN_SRC jupyter-python
print(2)
#+END_SRC

#+RESULTS:
:RESULTS:
2
:END:

```

exports to 

```
\begin{minted}[frame=lines,fontsize=\scriptsize,linenos=]{python}
print(2)
\end{minted}

2
```

for me. Off the top of my head I am not sure  what you might have different than me.

can you give a more complete example for the figure?

**Comment by uliw** [comment]
I  see. I had a function lurking in the depth of my config that modified the `org-latex-format-drawer-function`. Thanks for the pointer
