### ISSUE TITLE
Org-Mouse on Heading won't trigger org-cycle

### ISSUE THREAD

**Issue by dragonleopardpig** [jkitchin/scimax#494]
Downloaded latest Master branch Scimax, obesrved the following:

1. emacs -q -l /home/dummyuser/scimax/init.el, no problem.
2. Put a init.el file in .emacs.d/ which contains:
     (load  "/home/dummyuser/scimax/init.el")
and start Emacs from desktop shortcut, the mouse cursor no longer changed when hover over the bullet of the Heading, it is no longer clickable.

**Comment by jkitchin** [comment]
I can't reproduce that. I have the second setup you describe that I use every day and org-mouse works. Are there any messages when emacs opens that indicate a problem? Are you sure you can load org-mouse?

**Comment by dragonleopardpig** [comment]
To be exact, I have a backup copy of scimax in my backup folder, which downloaded using the linux bash command indicated in the instruction, that copy of scimax works, no issue. (downloaded last year). Recently I did a same linux bash command to download a fresh copy of scimax in my home folder, this issue happened (yes, I have done "mv .emacs.d .emacs.d.bak"). Org-mouse should be working becuase when I do [[somelink]], mouse hover change cursor, and the link is clickable. Message wise, I don't see particular message related to org-mouse. In summary, it happens only to the fresh copy of scimax downloaded.

**Comment by jkitchin** [comment]
That is pretty weird. I can't think of anything that would cause that. If you put your cursor at the beginning of a heading, and type M-x describe-text-properties, and then in the window that pops up click on [Show] on the keymap line, do you see something like this:

```
(keymap (C-down-mouse-1 . org-mouse-move-tree-start)
	(C-drag-mouse-1 . org-mouse-move-tree) (follow-link . mouse-face)
	(mouse-3) (mouse-2 . org-open-at-mouse))
```

**Comment by dragonleopardpig** [comment]
I am travelling this week, will try it out when I back in office next week. Thanks!

**Comment by dragonleopardpig** [comment]
Changed from NixOS back to Debian:
1) Download fresh scimax with _bash -c "$(curl -fsSL https://raw.githubusercontent.com/jkitchin/scimax/master/install-scimax-linux.sh)"_
2) _emacs -q -l scimax/init.el_, mouse on org Heading not working.
3) [[somelink]], mouse is working.
3) Put a _.emacs.d/init.el_ with (_load "/home/thinky/mountdir/emacs/scimax/init.el"_), mouse on org Heading not working as well.
3) M-x describe-text-properties, no keymap option shown in the pop-up window.

Use back the old backup scimax, observe additional files download and installed (not sure they are helpful in this case):
1) emacsql-autoloads.el
2) emacsql-sqlite-autoloads.el
3) emacsql-sqlite-autoloads.el
Mouse on org Heading is working.

**Comment by jkitchin** [comment]
That seems unusual. I don't know why that would depend on those. I have stopped using those libraries. Does adding something like 

```
(usepackage emacsql)
(usepackage pcache)
```

to your init make it work again?

**Comment by dragonleopardpig** [comment]
Tried:
(load "/home/thinky/scimax/init.el")
(use-package emacsql)
(use-package pcache)

No, it doesn't help.

**Comment by dragonleopardpig** [comment]
I diff the old scimax and new scimax directories, overwrite any diff files one by one.
After replacing _org-db.el_, the mouse is working fine.

**Comment by jkitchin** [comment]
huh. super weird. that isn't even loaded in packages. Do you load org-db somewhere else in your init?

**Comment by dragonleopardpig** [comment]
No, it is a fresh install of scimax.

**Comment by dragonleopardpig** [comment]
Redo again:

1. mv .emacs.d .emacs.d/bak
2. bash download fresh copy of scimax
3. emacs -q -l scimax/init.el
4. Org Heading mouse not working.
5. Replace org-db.el from old scimax to new scimax folder.
6. Org heading mouse **is working fine**.

**Comment by jkitchin** [comment]
I have no idea what kind of interaction this is. Maybe just delete org-db associated files in your scimax if you aren't using them. It seems very weird org-db could have any impact on org-mouse. 

Sometimes I will step through the init.el to see at what point something changes. It is pretty tedious to do that though. If you aren't using org-db, and you can solve it another way, I would probably do that.

**Comment by dragonleopardpig** [comment]
Removing org-db.el, scimax-contacts.el complains.
Removing both files, use-package complains scimax-contacts not found.

Org-mouse is working fine after org-db.el is removed. It is the scimax-contacts.el that uses org-db.

**Comment by jkitchin** [comment]
you could comment out the scimax-contacts line in packages.el so it looks like this.

```
;; (use-package scimax-contacts
;;   :ensure nil
;;   :load-path scimax-dir)
```

I pushed some updates today to that package. I noticed some residual emacsql code in that package. Hard to believe it caused the issue, but emacsql and org-db seem implicated.

**Comment by dragonleopardpig** [comment]
I commented out this session:
_;; * the hooks

(defun org-db-hook-function ()
  "Function to run after starting ‘org-mode’."
  ;; Run when we open in case it changed from some external program. Only for
  ;; org and org_archive files, and not just when we enter org-mode for some
  ;; reason.
  (when (and (buffer-file-name)
	     (or (f-ext? (buffer-file-name) "org")
		 (f-ext? (buffer-file-name) "org_archive")))

    (with-org-db
     (unless (sqlite-select org-db "select filename from queue where filename = ?"
			    (list (buffer-file-name)))
       (sqlite-execute org-db "insert into queue values (?)"
		       (list (buffer-file-name)))))

    (org-db-log "added %s to the queue." (buffer-file-name))

    ;; add local after save hook in case this is a new file.
    (add-hook 'after-save-hook 'org-db-hook-function t t)))


(add-hook 'org-mode-hook 'org-db-hook-function)_

Restart and org-mouse is working fine.
Not sure this affect the whole org-db.el function?

**Comment by dragonleopardpig** [comment]
Yes, commented out scimax-contacts solve the problem. Thanks.

**Comment by jkitchin** [comment]
I am glad that is a solution. Its a little too bad, org-db is a real game changer for me (and it all works like it should for me). I will have to be careful integrating it into other places I guess.
