### ISSUE TITLE
Cannot find flycheck in melpa upon startup

### ISSUE THREAD

**Issue by zhongnanxu** [jkitchin/scimax#5]
A recent commit resulted in a new package that could not be downloaded. Upon startup the error given is.

File error: http://melpa.org/packages/flycheck-20160711.205.tar, Not found

**Comment by jboes** [comment]
I can verify this.

```javascript
For information about GNU Emacs and the GNU system, type C-h C-a.
(Shell command succeeded with no output)
Contacting host: melpa.org:80
url-insert-file-contents: http://melpa.org/packages/flycheck-20160724.2357.tar: Not found
```

**Comment by jboes** [comment]
A fresh installation seems to resolve this.

**Comment by zhongnanxu** [comment]
That worked for me too. Thanks!

**Comment by jkitchin** [comment]
It is probable that running M-x package-refresh-contents could have fixed it too. I think the local archives were probably just out of date.
