### ISSUE TITLE
ZMQ unavailable?

### ISSUE THREAD

**Issue by peteWT** [jkitchin/scimax#501]
Running the following:

```
#+BEGIN_SRC jupyter-python :session land
import geopandas as gpd
import pandas as pd
#+END_SRC

```
I am prompted thusly:

`Check for compatible module binary to download? (y or n) `

selecting `y` i then get:

`ZMQ module not found. Build it? (y or n) `

selecting `y` i then see a compile errror as follows:

```
-*- mode: compilation; default-directory: "~/.emacs.d/elpa/zmq-20240716.2000/" -*-
Compilation started at Thu Sep  5 11:43:42

make EMACS=/opt/homebrew/Cellar/emacs-plus@29/29.4/Emacs.app/Contents/MacOS/Emacs
cd src && autoreconf -i
Can't exec "aclocal": No such file or directory at /opt/homebrew/Cellar/autoconf/2.72/share/autoconf/Autom4te/FileUtils.pm line 299.
autoreconf: error: aclocal failed with exit status: 2
make: *** [src/configure] Error 2

Compilation exited abnormally with code 2 at Thu Sep  5 11:43:44
```

I have the following versions of `zmq` and `autoconf` installed via homebew:

```
❯ brew upgrade zmq
Warning: zmq 4.3.5_1 already installed
❯ brew upgrade autoconf
Warning: autoconf 2.72 already installed
```

Thanks in advance for any hints.

**Comment by peteWT** [comment]
thanks for the response @jkitchin 
i get the same error as above:

```cd /Users/pete/.emacs.d/elpa/zmq-20240716.2000
❯ make
cd src && autoreconf -i
Can't exec "aclocal": No such file or directory at /opt/homebrew/Cellar/autoconf/2.72/share/autoconf/Autom4te/FileUtils.pm line 299.
autoreconf: error: aclocal failed with exit status: 2
make: *** [src/configure] Error 2
```

**Comment by jkitchin** [comment]
that sounds like something missing in autotools from homebrew. maybe try reinstalling `brew install autoconf`. or see what is in line 299 at /opt/homebrew/Cellar/autoconf/2.72/share/autoconf/Autom4te/FileUtils.pm line 299. maybe that will help see what is missing.

**Comment by peteWT** [comment]
Had to install `automake` per this [post](https://stackoverflow.com/questions/76852766/error-cant-exec-aclocal-with-homebrew-installed-autoreconf-on-mac)

Solved the problem...
