### ISSUE TITLE
`magithub` `git-commit` `magit` dependency issues

### ISSUE THREAD

**Issue by peteWT** [jkitchin/scimax#502]
it looks like `magithub` requires `git-commit` which has been merged into `magit`. `magit` complains if `git-commit` is loaded separately.

**Comment by peteWT** [comment]
fixed as noted in jkitchin@866ebd0 not sure how to fix in the home-brew install...

**Comment by jkitchin** [comment]
What is the issue? does this cause an error in home-brew install somehow?
