### ISSUE TITLE
`cond: Symbol’s function definition is void: jupyter-org--clear-request-id`

### ISSUE THREAD

**Issue by peteWT** [jkitchin/scimax#503]
@jkitchin 

A relatively simple source block:
```
#+BEGIN_SRC jupyter-python :session akfhwp :tangle AkfHwpCalcs.py :results none
import pandas as pd
import geopandas as gpd
import yaml, sys, sqlite3
from tqdm import tqdm
import emissionsUtilities as ut
from nfcarbontools import utilities as nfut
#importlib.reload(ut)

with open('../../config_processes.yaml', 'r') as file:
    pConf = yaml.safe_load(file)
#+END_SRC
```
Seem to execute the code but this in messages and i cant get anything to return to the org-mode buffer

**Comment by jkitchin** [comment]
I don't think this should return anything. Can you make a simpler example that doesn't have all those 3rd party libraries in it? 

why do you have :session and :tangle and :results none in the header? You shouldn't need any of those.

**Comment by peteWT** [comment]
Much simplified here:

```
#+BEGIN_SRC jupyter-python :session foobar
foo = 'bar'
print(foo)
#+END_SRC

#+RESULTS:


```
the REPL has the variable defined but somehow it is not returned to the org buffer

this is what is in the messages buffer:

```
Executing Jupyter-Python unknown at position 8881...
cond: Symbol’s function definition is void: jupyter-org--clear-request-id
Code block evaluation complete.
Error in ZMQ subprocess filter: (jupyter-publisher-subscribers-had-errors (jupyter-publisher-subscribers-had-errors (void-function jupyter-org--clear-request-id)))

```

**Comment by jkitchin** [comment]
how are you running it? Just C-c C-c in the src block? what version of emacs-jupyter are you using. This works fine for me (version 20240420.1918).

**Comment by peteWT** [comment]
`Org mode version 9.7-pre (release_9.6.6-413-ga07260 @ /Users/pete/src/emacs-reveal/org-mode/lisp/)`

**Comment by jkitchin** [comment]
The version of the jupyter package is more important. Something like this:

```
#+BEGIN_SRC emacs-lisp
(locate-library "jupyter")
#+END_SRC

#+RESULTS:
: /Users/jkitchin/.emacs.d/elpa/jupyter-20240420.1918/jupyter.elc
```

**Comment by peteWT** [comment]
Here:

```
#+BEGIN_SRC emacs-lisp
(locate-library "jupyter")
#+END_SRC

#+RESULTS:
: /Users/pete/.emacs.d/elpa/jupyter-20240716.2028/jupyter.elc
```

**Comment by jkitchin** [comment]
I tried updating to that version, and it works fine for me. It is true that `jupyter-org--clear-request-id` is not defined in that library. The question is why do you see it? I think it was defined in jupyter-20230627.163019, but now it is not. Maybe you have some old versions that are getting loaded somehow? You could try moving all the jupyter-* directories in your elpa out but the most recent one and see if it goes away.

It was defined in jupyter-org-client.el last year, but it seems to be gone (and there is no reference to it in the newest package).

**Comment by peteWT** [comment]
the only `juptyer-*` directory in `/Users/pete/.emacs.d/elpa` is `jupyter-20240716.2028`

**Comment by jkitchin** [comment]
something isn't adding up here. if you grep for `jupyter-org--clear-request-id` in that directory, probably you won't find it, which means another jupyter is getting loaded somewhere else.

**Comment by peteWT** [comment]
cleared up with clean brew install. Thanks
