### ISSUE TITLE
emacs 29.4 hangs when opening org-files

### ISSUE THREAD

**Issue by uliw** [jkitchin/scimax#510]
FYI only: scimax/packages.el installs a new org version via straight during startup. Today this resulted in emacs hanging whenever I opened an org-file. removing the entry in packages.el and using the build-in org version resolved the issue.

**Comment by uliw** [comment]
Using org org-9.7.16 from elpa, results however in the following problem when inserting a citation
```
Wrong number of arguments: #<subr parsebib-read-string>, 2
```

**Comment by jkitchin** [comment]
thanks for reporting this. there has been an update in parsebib recently that might be the cause of this (https://github.com/jkitchin/org-ref/issues/1125). I am sort of sure scimax and org-ref don't use that function, it might be something in bibtex-completion maybe (@tmalsburg)?

 @joostkremers any ideas?

**Comment by joostkremers** [comment]
Yes, `bibtex-completion` needs an update because it uses some functions from `parsebib` that were changed. I created a PR <https://github.com/tmalsburg/helm-bibtex/pull/453> to fix the incompatibilities, but unfortunately, the `bibtex-completions` maintainer hasn't merged it yet.

Best I can offer right now is to keep `parsebib` at version 4.7. The easiest way to do this is to pin it to melpa-stable:

```
(add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/") t)
(add-to-list 'package-pinned-packages '(parsebib . "melpa-stable"))
```

Or use the `:pin` keyword of `use-package`.

**Comment by tmalsburg** [comment]
It's merged now.

**Comment by uliw** [comment]
ok, so using parsebib as on elpa, appears to also affect other helm functions. Searching in a helm completion buffer it will hang the system.  For now, I reverted to parsebib 4.7, and disabled helm-bib-tex. The system appears stable for now

**Comment by joostkremers** [comment]
There seems to be something that the new `parsebib` doesn't handle correctly. If you'd be willing to share your `.bib` file(s), feel free to send them to my be e-mail, so I can take a look and hopefully figure out where it goes wrong.

**Comment by tmalsburg** [comment]
It's merged. Thank you, Joost.

**Comment by uliw** [comment]
Just to confirm, everything works as expected now (although it seems that parsing the BibTeX files now takes longer). @joostkremers

**Comment by joostkremers** [comment]
> Just to confirm, everything works as expected now 

Whew! I'm glad to hear that. :slightly_smiling_face: 

> (although it seems that parsing the BibTeX files now takes longer).

I only benchmarked my own `.bib` file, which has about 1200 entries, and found no real difference. But that's a very limited test, of course, so it's possible the effect is bigger with your `.bib` files. Maybe I'll find some time to profile the new parser, but I'm not promising anything...
