### ISSUE TITLE
Option to remove package `underscore` from Org LaTeX export

### ISSUE THREAD

**Issue by fpdotmonkey** [jkitchin/scimax#512]
The LaTeX package `underscore` causes formatting issues in typesetting engines like XeLaTeX or Tectonic and is included in exports under Scimax.  It would be nice to be able to remove it.  

It appears not to be in `'org-latex-default-packages-alist` or `'org-latex-packages-alist`.  I'm not sure if Scimax or one of the packages it imports brings in underscore, but it doesn't seem to be in the export in vanilla org-mode.  I do see that the underscore package is referenced in ox-manuscript/ox-manuscript-templates/wiley-ijqc.org.

**Comment by jkitchin** [comment]
I think it is defined in scimax-org-latex.el.

A way to do this is something like:

```
(setq org-latex-default-packages-alist
      (delete '("strings" "underscore" nil) org-latex-default-packages-alist))
```

or, just define `org-latex-default-packages-alist` to the values you want after scimax is loaded.
