### ISSUE TITLE
Add org-edit-latex to scimax

### ISSUE THREAD

**Issue by et2010** [jkitchin/scimax#52]
Hi, John
I'm the author of PR #50 
I've made that fragment editing feature into a standalone package: https://github.com/et2010/org-edit-latex (it's available on MELPA). A few bugs have been fixed since my last PR. It's more reliable now, along with some enhancements including support for inline math editing, toggle on/off with minor mode, etc.. Since I'm a big fan of scimax, so I think it's better to send a PR here too. But I'm not sure if you want to include another external package. So what's your opinion? Is that OK to add org-edit-latex.el to scimax? Please let me know. Thanks.

Regards.

**Comment by jkitchin** [comment]
Sure it would be fine to add it. The best way would be to add a (use-package 'org-edit-latex) line in the packages.el file. That file is very approximately in alphabetical order, except where some things need to be loaded first like org. Maybe that line could go right before the org-ref package. I suppose you should remove the old version too. thanks!

**Comment by et2010** [comment]
Thanks! Here's the PR: https://github.com/jkitchin/scimax/pull/53
The latest version also (partially) fixed a bug from org: https://github.com/et2010/org-edit-latex/commit/3ee3dc76f4d52da88f6d1c29b4c68571426eb72b. It will be on MELPA soon. Don't forget to update the package!
