### ISSUE TITLE
Exporting edit marks to pdf fails if there is a % in it

### ISSUE THREAD

**Issue by et2010** [jkitchin/scimax#54]
The edit mark below:
```
[[delete:some 10% edit marks]]
```
will cause latex compilation failure when export to pdf. The tex source from export looks like:

```latex
\textcolor{red}{some 10% edit marks}
```
It seems the `%` is not escaped and the rest of line will be treated as comments. The unclosed brace leads to the error.

**Comment by jkitchin** [comment]
ug.. I would have thought there was an easy way to escape these. I just pushed a function to do that. I think it covers all the special latex characters.

**Comment by et2010** [comment]
Thanks for the quick fix! It works like a charm!
