### ISSUE TITLE
when-let not available in Emacs 24

### ISSUE THREAD

**Issue by rhymer** [jkitchin/scimax#55]
Hi John,

The following files use `when-let`, which I believe is not available in Emacs 24. Does it make sense to replace them with `dash`'s `-when-let`, or replace `assert_minimal_emacs_version 24 4` by `25 1`? Thanks.

> ox-ipynb.el:349:		  (when-let ((md (export-ipynb-markdown-cell (s-trim s))))
> ox-ipynb.el:357:	      (when-let ((md (export-ipynb-markdown-cell (s-trim s))))
> ox-ipynb.el:385:		    (when-let ((md (export-ipynb-markdown-cell (s-trim s))))
> ox-ipynb.el:392:		(when-let ((md (export-ipynb-markdown-cell (s-trim s))))
> scimax-org-babel-ipython.el:221:      (when-let (ret (ob-ipython--eval
> scimax-org.el:1033:		      (when-let (f (buffer-file-name b))

**Comment by jkitchin** [comment]
Is there any chance you have already tried them with -when-let and verified they work?

**Comment by rhymer** [comment]
I add `(require 'dash)` and replace `when-let` by `-when-let` in `ox-ipynb.el` and it seems to work.

**Comment by jkitchin** [comment]
sounds good enough to try! I just pushed replacements for those. and changed the assert minimal emacs version in the linux script.
