### ISSUE TITLE
Some abbrev characters (') are not word constituents

### ISSUE THREAD

**Issue by AKielhorn** [jkitchin/scimax#57]
When I start Emacs with scimax I get the following error: 

Error (use-package): scimax-org :init: Some abbrev characters (') are not word constituents in the standard syntax

These abbreviation have been introduced by:

ad9b0ca66e0c6cff4def885cfee761f869a926b8 [ad9b0ca]

I'm using Emacs 25.1 on MacOS X with Org 9.0.5-435-g106ecb

For now I have disabled the contractions.
They aren't that useful for me since I normally write in german.

**Comment by jkitchin** [comment]
thanks for reporting that. I had seen it too. I removed the ' abbrevs.
