### ISSUE TITLE
ox-ipynb: underscores always exported as subscripts in markdown cells

### ISSUE THREAD

**Issue by singletS** [jkitchin/scimax#58]
Trying to include text with an underscore seems to always produce `<sub></sub>` in markdown cells.   I have tried 
#+OPTIONS: _:{}  
#+OPTIONS: ^:nil 
and escaping  (i.e., `'..use the pd.read\_csv() function to...`) with no luck. Is this reproducible for others? (I use only ox-ipynb from scimax, so please try to reproduce first).  Thanks

**Comment by jkitchin** [comment]
I cannot reproduce it. I don't need options or escapes to get regular _.  I do have org-export-with-sub-superscripts  set to t.

**Comment by singletS** [comment]
I tried org-export-with-subscripts-superscripts set t and nil as well, but underscores were always converted to html tags.  

It seems having both html and ipynb exporters active causes a conflict with org-use-sub-superscripts, and gives behavior I'm seeing: http://stackoverflow.com/questions/26636562/org-mode-weirdness-with-org-export-with-sub-superscripts

Thanks for checking.
