### ISSUE TITLE
Windows error: Eager macro-expansion failure

### ISSUE THREAD

**Issue by jboes** [jkitchin/scimax#6]
After attempting a new installation of Scimax on windows I got the following error when attempting to open an org file:

```sh
Eager macro-expansion failure: (void-variable path)
(Shell command succeeded with no output)
Eager macro-expansion failure: (void-variable path)
[yas] Reloaded everything (snippets will load just-in-time)....
Eager macro-expansion failure: (void-variable path) [3 times]Eager macro-expansion failure: (void-variable path)
(Shell command succeeded with no output)
Eager macro-expansion failure: (void-variable path)
[yas] Reloaded everything (snippets will load just-in-time)....
Eager macro-expansion failure: (void-variable path) [3 times]
```

This only prevents loading the file I selected directly. I can still navigate to it after this error occurs, but this is obnoxious.

**Comment by jkitchin** [comment]
These arent actually errors, just annoying messages. Do you mean you can't type this to open a file?

./scimax.bat some-org-file.org?

**Comment by jboes** [comment]
The file does not open, only the scratch pad.

**Comment by jkitchin** [comment]
I think this is fixed now. You have to use scimax.sh in the bash window.

You can use the scimax.bat file to open org-files. It doesn't appear to work from git-bash to open files at the cmd line, but it does work at a dos cmd prompt.

I also got rid of the (void-variable path) issues (they weren't causing any actual issue, but the messages are less noisy now.)

**Comment by jboes** [comment]
All startup problems seem to be resolved on my windows machine.
