### ISSUE TITLE
scimax-org-babel-ipython.el error:   mapconcat: Symbol’s function definition is void: loop

### ISSUE THREAD

**Issue by timehaven** [jkitchin/scimax#60]
Hi,

Great work!

I am trying to use only your version of `ob-ipython`, via:

```
(add-to-list 'load-path "~/.emacs.d/elisp/scimax")
(require 'scimax-org-babel-ipython)
```
and I get the error mentioned in the subject line above when running either of the following in a `.org` file:

```
#+BEGIN_SRC ipython :session :results output drawer
4 + 5
#+END_SRC

#+BEGIN_SRC ipython :session :results output drawer :async t
4 + 5
#+END_SRC
```

Here is `*Messages*` output:

```executing Ipython code block...
Contacting host: localhost:9988
Code block evaluation complete.
error in process filter: mapconcat: Symbol’s function definition is void: loop
error in process filter: Symbol’s function definition is void: loop
executing Ipython code block...
Contacting host: localhost:9988
mapconcat: Symbol’s function definition is void: loop
```

If I remove the `scimax` config lines above and simply use `ob-ipython` via

```(require 'ob-ipython)```

then both src blocks above work fine.

Any thoughts as to what might be happening with the `loop` calls in (I think)
 `org-babel-execute:ipython`?

I am using Emacs 25 and have tried two versions:

```GNU Emacs 25.1.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911)) of 2016-09-17```

and

```GNU Emacs 25.2.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911))  of 2017-02-21```

I am using `org-version`
```Org mode version 9.0.5 (9.0.5-elpa @ ~/.emacs.d/elpa/org-20170210/)```

I think the following is unrelated, but I include it anyway:

In both cases (`ob-ipython` or `scimax` version), I get the following warnings, but with no effect:

```
Warning (python): Python shell prompts cannot be detected.
If your emacs session hangs when starting python shells
recover with ‘keyboard-quit’ and then try fixing the
interactive flag for your interpreter by adjusting the
‘python-shell-interpreter-interactive-arg’ or add regexps
matching shell prompts in the directory-local friendly vars:
  + ‘python-shell-prompt-regexp’
  + ‘python-shell-prompt-block-regexp’
  + ‘python-shell-prompt-output-regexp’
Or alternatively in:
  + ‘python-shell-prompt-input-regexps’
  + ‘python-shell-prompt-output-regexps’
Warning (python): Your ‘python-shell-interpreter’ doesn’t seem to support readline, yet ‘python-shell-completion-native’ was t and "jupyter" is not part of the ‘python-shell-completion-native-disabled-interpreters’ list.  Native completions have been disabled locally. 
```
Thank you.

**Comment by jkitchin** [comment]
Probably you need to put (require 'cl) in your init file to get the loop macro to be defined.

You can probably ignore those warnings.

**Comment by timehaven** [comment]
Thank you.  Seems like installing `jedi` helped things.

Looking at `jedi-core.el`, I see the line:

```(require 'cl-lib)```

So that seems to do it.  

Again, thank you for your efforts with this.
