### ISSUE TITLE
New win10 Scimax installation not finding python(?) - Using Anaconda 

### ISSUE THREAD

**Issue by Arjay-El** [jkitchin/scimax#63]
Windows 10 64b w/ new Anaconda installation, 64b, Python 3.6  placed in C:\Ananconda3. 
Tested Jupyter notebook and Spyder. Both execute python properly.
Created c:/Emacs, used git-bash in that directory for Win version. Scimax loaded. 
Opened scimax.org,  selected python programming example and received this fail message:
-----
executing Ipython code block...
Making python-shell-interpreter local to *Python* while let-bound!
Making python-shell-interpreter-args local to *Python* while let-bound!
Sent python-shell-completion-setup-code
comint-send-string: Writing to process: invalid argument, Python
true
(Shell command succeeded with no output)
-----
Does this mean it is not finding python/ipython? Do I have to set explicit lisp commands for a path to these?

**Comment by jkitchin** [comment]
What does this command tell you: (executable-find "python")

Also, how do you run Emacs? I have found that if you don't start it from a shell, it won't have the shell environment, e.g. the path to find things.

**Comment by Arjay-El** [comment]
The command gives a single word response: True. I run scimacs from your shell command by changing to the scimax directory located in c:\Emacs and running it there.

For example, I start a session, open scimax.org, and execute a C-c C-c on the first python example.  (print hello world).

A Python buffer opens and gives this message:
======================================================
[TerminalIPythonApp] WARNING | Subcommand `ipython console` is deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter console` in the future
[ZMQTerminalIPythonApp] CRITICAL | Could not find existing kernel connection file emacs-default.json
Process Python exited abnormally with code 1
=========================================================
 
A buffer for ob-ipython-kernel-default provides this message:
=====================================================
Traceback (most recent call last):
  File "c:/Emacs/scimax/ob-ipython/driver.py", line 2, in <module>
    import jupyter_client as client
ImportError: No module named 'jupyter_client'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "c:/Emacs/scimax/ob-ipython/driver.py", line 7, in <module>
    from IPython.lib.kernel import find_connection_file
ImportError: No module named 'IPython'
Process kernel-default exited abnormally with code 1
======================================================
It looks like paths are not being found which makes me think I should just define them explicitly in my init file.  Perhaps a windows thing?

**Comment by jkitchin** [comment]
hm. It should have returned an actual path, not True. You should not need to define paths in your init files.

You can see your path settings here:
(getenv "PATH")

(getenv "HOME")

You should also be able to just run scimax.bat in the scimax directory to open it.

**Comment by Arjay-El** [comment]
Still trying to check the paths and permissions for win10. As I said everything works under Anaconda. Do you have a running version on a Win10 or win7 installation? I assume you are running linux.

**Comment by jkitchin** [comment]
I have tested scimax on a Win7 machine and Mac. It seems to work normally on both of them.

**Comment by Arjay-El** [comment]
I loaded Scimax on a laptop with Win7 Pro and it works exactly as expected so its obviously a Win10 issue, not a scimax issue. If I can figure it out, I will post my results. Thanks for your help.

**Comment by jkitchin** [comment]
Scimax works for me on a Win10 machine too.

**Comment by Arjay-El** [comment]
Yes I agree with that. I just loaded Ananconda3 64b, git and scimax on my brand new Surface Studio and it works as advertised. My Dell Win10 box is still struggling but it has had a lot of programs loaded and removed over the last year so something left behind may be the issue. Thanks John and thanks for Scimax, its a great tool.

**Comment by Arjay-El** [comment]
I was mistaken on my Win10 Surface. If I deleted the results and reran the first plotting example in Scimax.org, I get an error and no plot. Can you look at the attached text file and tell me if my system is starting up correctly? I copied the Message buffer for when I started scimax and then again when I tried to run the first plotting example. Is there anything you could suggest i can try? Thanks
[scimax buffer contents.txt](https://github.com/jkitchin/scimax/files/980695/scimax.buffer.contents.txt)

**Comment by Arjay-El** [comment]
The culprit turned out to be LibreOffice which installs a python environment. The Libreoffice paths were overriding the Anaconda paths for whatever reason (I am not a programmer so I have no insight into how Win chooses which path to use when things conflict). The Libreoffice installation is just a barebones python, no numpy or matplotlib as far as I can determine. Once removed, scimax began working properly with babel/ipython plotting.
