### ISSUE TITLE
Possible problem with Emacs 25.2

### ISSUE THREAD

**Issue by sbacelar** [jkitchin/scimax#65]
I have uninstalled the Emacs homebrew version that comes with scimax.
I am using Emacs 25.2 that works well with my `init.el`.
Now, when I try `emacs -q -l scimax/init.el` I get:
```
Contacting host: elpa.gnu.org:80
Contacting host: orgmode.org:80
Package refresh done
byte-code: Invalid byte opcode: op=183, ptr=2
```

**Comment by jkitchin** [comment]
I can't reproduce this. It sounds like there is some corrupted .elc file in /elpa maybe.
