### ISSUE TITLE
ipython src block, :var header arguments and unicode character

### ISSUE THREAD

**Issue by et2010** [jkitchin/scimax#67]
Evaluating following code block will not work. Note that the org table contains a Unicode character (ω):

``` org-mode
#+name: input
| ω |

#+header: :var var=input
#+begin_src ipython :session :results output drawer
print(var)
#+end_src
```
I'm using Python 3.6.1 and orgmode 9.0.6. 

BTW, python block seems to work:

``` org-mode
#+header: :var var=input
#+begin_src python :session :results output drawer
print(var)
#+end_src

#+RESULTS:
:RESULTS:
[['ω']]
:END:
```

**Comment by jkitchin** [comment]
This is a bug in of sorts in ob-ipython. The problem is you can't send multibyte strings to the kernel. You can redefine the function below to fix it I think.

```
(defun ob-ipython--execute-request (code name)
  (let ((url-request-data (encode-coding-string code 'utf-8))
        (url-request-method "POST"))
    (with-current-buffer (url-retrieve-synchronously
                          (format "http://%s:%d/execute/%s"
                                  ob-ipython-driver-hostname
                                  ob-ipython-driver-port
                                  name))
      (if (>= (url-http-parse-response) 400)
          (ob-ipython--dump-error (buffer-string))
        (goto-char url-http-end-of-headers)
        (let ((json-array-type 'list))
          (json-read))))))
```

**Comment by et2010** [comment]
Your fix works. Thank you! 
And thanks for taking the time to investigate. I'll report it to the upstream.

**Comment by et2010** [comment]
**UPDATE:** 
The original problem has been fixed, but now I can't use `pandas.read_csv('fname.csv')` to read my csv file. It will raise an error: `File b'fname.csv' does not exist`. If I undo the fix, `read_csv` will work as expected. Any suggestions? Thanks!

**Comment by jkitchin** [comment]
I cannot reproduce this. Can you check what the current working directory is? It is possible it is not what you think it is, and the file really doesn't exist. Alternatively, try reading an absolute path to the csv.

**Comment by jkitchin** [comment]
Is this still an issue?

**Comment by et2010** [comment]
No, I cannot reproduce it myself. Sorry for the delay.
