### ISSUE TITLE
Windows error: Invalid Parameter - /Users

### ISSUE THREAD

**Issue by jboes** [jkitchin/scimax#7]
When navigating to an org file in windows, if that org file has image links the following error is displayed:

```sh
Invalid Parameter - /Users
File mode specification error: (error "Cannot determine image type")
```

Attempting to run C-c C-x C-v in that same org file produces the following error:

```sh
Invalid Parameter - /Users
image-type: Cannot determine image type
```

Clicking on a .png image will open the figure in a new buffer. However, clicking a .gif results the display of the image as text. Attempting to use C-c C-c to produce the images results in the following error:

```sh
Type C-c C-c to view the image as an image.
Cannot display image: (Invalid image specification)
```

The first two errors occur regardless of whether there are .gif files in the org document or not. None of these errors occur on a Linux machine.

**Comment by jkitchin** [comment]
hm. I can't reproduce the first issue. 

The second issue with gifs should be resolved, I had to update the gif libs in the emacs-win directory.

The /Users looks like part of a path in windows. There wouldn't by chance be a space in the path is there?

Which windows machine has this issue?

**Comment by jboes** [comment]
Elif has this error as well, although she does not have the most recent version any longer. There is no space in my path:

```sh
$ pwd
/c/Users/jacob/Documents
```

This is likely unrelated, but I'm also getting an error when python code blocks are present in the org document:

```lisp
Warning (emacs): Python shell prompts cannot be detected.
If your emacs session hangs when starting python shells
recover with `keyboard-quit' and then try fixing the
interactive flag for your interpreter by adjusting the
`python-shell-interpreter-interactive-arg' or add regexps
matching shell prompts in the directory-local friendly vars:
  + `python-shell-prompt-regexp'
  + `python-shell-prompt-block-regexp'
  + `python-shell-prompt-output-regexp'
Or alternatively in:
  + `python-shell-prompt-input-regexps'
  + `python-shell-prompt-output-regexps'
```

Any idea how to resolve this?

**Comment by jkitchin** [comment]
This is a note for me later. See https://github.com/jorgenschaefer/elpy/issues/733

**Comment by jkitchin** [comment]
Another note for posterity. The issue here seems to be Windows has its own convert program which is not used for image resizing ;) I have updated scimax to use the mogrify command instead. It works on a windows machine for me, but mogrify does need to be installed from imagemagick and on the executable path.

**Comment by jboes** [comment]
All of these issues seem to be resolved now.
