### ISSUE TITLE
Problem with code cells in ox-ipynb and spurious indentation

### ISSUE THREAD

**Issue by fpopineau** [jkitchin/scimax#70]
Hi,

By default, Org has  `org-edit-src-content-indentation` set to 2.
This indentation is not properly removed when exporting code cells.
Actually, only the first line from the code block is trimmed from leading white spaces.
In ox-ipynb, around line 120, there is:

> (list (s-trim (org-element-property :value src-block)))

whereas I think there should be: 

> (list (car (org-export-unravel-code src-block)))

Best regards,

**Comment by jkitchin** [comment]
Thanks for reporting this, and the solution. I have pushed a fix for this.
