### ISSUE TITLE
ox-ipynb and dynamic blocks

### ISSUE THREAD

**Issue by singletS** [jkitchin/scimax#72]
Org mode dynamic blocks get exported with `#+BEGIN: foonil` at the beginning of each cell.  For example, I use dynamic blocks to auto-number exercises, each in its own cell:
```
(defun org-dblock-write:exercise (params)
  (incf exercise-counter)
  (insert (concat "#+ipynb-newcell
*Exercise " (int-to-string exercise-counter) "*")))
(setf exercise-counter 0)
```
Running `org-update-all-dblocks` shows the blocks are updated correctly in the org file, but the ipynb file will give `#+BEGIN: exercisenil` before each exercise cell.
```
#+begin: exercise
#+ipynb-newcell
*Exercise 2*
#+end
```
Maybe I'm doing auto numbering in a goofy way?

**Comment by jkitchin** [comment]
I am not sure that is goofy. I can confirm I get the same result. I am not sure what the best to do here is, maybe a preprocessing step on the temp buffer?

**Comment by singletS** [comment]
Could `ox-mrkup-filter-dynamic-block` / ` org-export-filter-dynamic-block-functions` be used?

**Comment by jkitchin** [comment]
I confirmed that #+BEGIN: exercisenil is due to a bug in org-mode. It has been fixed, but I am not sure how long it will take to propagate out.

**Comment by jkitchin** [comment]
I think I have come up with some ways to address these. I pushed them. I have not done a lot of testing on other notebooks yet.

**Comment by singletS** [comment]
This looks good for an org file with two counters/dynamic blocks ("Exercises" and "Problems").

Close the issue if you wish (or not since there's an upstream org-mode fix?).

Thanks
