### ISSUE TITLE
New Installation incomplete with request for 'emacs-25'

### ISSUE THREAD

**Issue by Arjay-El** [jkitchin/scimax#75]
I am using Win10. Created c:\emacs and used bash shell statement per your instructions. Emacs opens and begins going through its compiling process and ends with the statement 'Package emacs-25 is unavailable' in the mini-buffer. The scimax menu item is also missing (virtual env is there). I have attached the message and compile log. Is it asking for a newer version of emacs?

[message_log.txt](https://github.com/jkitchin/scimax/files/1015469/message_log.txt)
[Compile-Log.txt](https://github.com/jkitchin/scimax/files/1015468/Compile-Log.txt)

**Comment by jkitchin** [comment]
That is probably because the default emacs provided with scimax was 24.5. I have updated it to 25.2. It seems to install now. I have not tested that emacs version very much. Let me know if you find any issues with it.

**Comment by Arjay-El** [comment]
Loads as it should but evaluating the ipython block  in scimax.org give this:
------
executing Ipython code block...
apply: Spawning child process: Exec format error
-------

**Comment by Arjay-El** [comment]
As a side request: I have an emacs configuration I like but I would love to add your scimax features to it. Is there a method of adding scimax to an existing configuration without having to load the extra emacs-25 base that your bash cmd calls? I am wondering if an existing version  being merged into the version as part of the install would collide and cause issues. ie. can I do a manual install for emacs (win) of just the scimax specific components? thanks!

**Comment by jkitchin** [comment]
you can load any parts of scimax you want. Just put the root directory into your load path, and require what you want. For example, see https://github.com/jkitchin/scimax/blob/master/init.el#L52. You can also use any emacs you want, although the more recent the version probably the better. I am not sure it works with emacs 24 for example, and am only using 25+ myself.

**Comment by jkitchin** [comment]
I cannot reproduce the spawn error on windows 7.

**Comment by Arjay-El** [comment]
Win is an interesting beast. I have a win7 installation that works fine but I tried in on another win7 platform and received the same error. I will continue to experiment with it and see if I can figure out a reason. I do appreciate your work on scimax.
