### ISSUE TITLE
org-link-set-parameters missing from newest Windows installation?

### ISSUE THREAD

**Issue by jboes** [jkitchin/scimax#78]
I am getting the following error upon freshly installing Scimax onto a Windows machine for the first time.

Error (use-package): scimax-org :init: Symbol’s function definition is void: org-link-set-parameters

It's terminating the boot process, so I'm not sure if any other needed packages are not being installed as a result.

**Comment by jkitchin** [comment]
That does seem to be an issue. I think I have fixed it. There is a new emacs 25.2, and updated set of packages for it. Let me know if that works.

spell check is not currently working.

**Comment by jboes** [comment]
Now I get this:

Error in defhydra scimax-drag: (integer-or-marker-p :red)
Eager macro-expansion failure: (wrong-number-of-arguments ((t) (hydra) "Push current HYDRA to a stack.
This is a macro so I don't have to quote the hydra name." (list (quote progn) (quote (scimax-hydra-push hydra-curr-body-fn)) (list (quote call-interactively) (list (quote quote) hydra)))) 3)
Error in defhydra scimax-email: (Each head should have at least two items: ("b"))

**Comment by jkitchin** [comment]
odd. no scimax-hydra goodness for windows I guess. I have disabled that and it seems to work ok now.

**Comment by jboes** [comment]
Looks good!
