### ISSUE TITLE
Asynchronous execution of IPython blocks does not work under macOS

### ISSUE THREAD

**Issue by khinsen** [jkitchin/scimax#80]
The asynchronous execution in `scimax-org-babel-ipython.el` works fine for me under Linux, but not under macOS. Asynchronously running a single block works fine, but queuing up multiple blocks (e.g. using `org-babel-execute-ipython-buffer-async`) does not. The first block gets scheduled but its execution never terminates. The remaining blocks are put on the queue but are not processed otherwise. Even the result placeholder (async-queued ...) never appears.

I suspect this is due to a difference in how `url-retrieve` is implemented on each platform, because `url-retrieve` is the only function used in the code that permits asynchronous execution.

**Comment by jkitchin** [comment]
That is pretty odd. I did all the development on a Mac, so its the only place I know it works for sure! I have pushed a lot today to fix a few issues.

It seems to work on windows.

I tried this on an old Centos machine, and in the *ob-ipython-client-driver* buffer it looks like there is some issue with python syntax. I guess that is some system vs anaconda path issue. I won't have time to track that down for about two weeks due to some travels that are coming up tomorrow.

Feel free to post small examples that cause problems. When I get back in June I will be polishing this up some more so I can use it in research!

**Comment by khinsen** [comment]
Update: it works on the Mac with Emacs 25.1 compiled via homebrew, but not with Emacs 25.2 downloaded from [Emacs for MacOS X](https://emacsforosx.com/).

**Comment by khinsen** [comment]
Compiled 25.2 from homebrew on a Mac mini: works.
Compiled 25.2 from homebrew on a MacBook Pro: doesn't work
25.1 from homebrew works on both machines.

**Comment by jkitchin** [comment]
Do have a brew incantation that specifies the emacs version? I might be able to integrate some version specific tests on Travis.

**Comment by khinsen** [comment]
You can use

```
brew install emacs@25.1
```

to install a specific version. Currently the choice is 24.5, 25.1, or 25.2. You can then use

```
brew switch emacs 25.1
```

to make version 25.1 accessible as `emacs`, though I never do this. For testing I find it easier to run a specific version explicitly from `/usr/local/Cellar/emacs/25.1`.

**Comment by khinsen** [comment]
For various reasons, I have recomposed and modified the IPython-related code from scimax for my own needs (see https://github.com/khinsen/ob-ipython-async). For reasons that unfortunately I cannot explain, my version works with all Emacs releases I tested. I didn't change anything fundamental in the way asynchronous execution is handled, but many details are different.

**Comment by jkitchin** [comment]
One limitation I have been thinking about is the queue only supports one kernel. Maybe if that variable was made buffer local it would at least support running different kernels in different documents.  But if anyone wanted separate kernels in a single document using different sessions, it would not work well right now I think.

**Comment by khinsen** [comment]
Multi-session support would indeed be nice to have, but my impression is that even plain `ob-ipython` does not support this correctly. If that can be fixed, going async should require no more than having one queue per session. For a notebook-style one-session-per-buffer setup, one could then simply set the session name via a property at the beginning of the file.

**Comment by jkitchin** [comment]
My mods already use a per buffer kernel named as the md5 hash of the buffer file name of it has one. I think it is just the queue management that needs updating.

**Comment by jkitchin** [comment]
@khinsen do you know of any 0mq bindings for elisp? Ob-ipython wraps the kernel in a tornado web server. I am wondering if a more direct kernel communication would make it easier to extend to other languages.

**Comment by khinsen** [comment]
Apparently my memory was inaccurate - I tried multiple sessions with my version of the async code, and they just worked. I don't even see the need to reorganize the queue by session. All I did add is a modified version `ob-ipython--create-repl` that adds the session name to the name of the REPL buffer, in order to have a distinct REPL per session.

**Comment by khinsen** [comment]
@jkitchin I don't know of any 0mq bindings for Emacs. EIN uses `url-retrieve` via a Web server as well. With dynamic library support in Emacs, proper bindings should be easier to write, but as far as I know it hasn't happened yet.

**Comment by khinsen** [comment]
Restriction: it "just works" for my typical use case: one session per org buffer, with rare switches between the two. When there are tasks for more than one session in the queue, an error in one session cancels the computations in the other sessions, which is, well. suboptimal 😞

**Comment by jkitchin** [comment]
@khinsen I finally got around to trying this:

`brew install emacs@25.1`

with no luck. I got:

```
brew install emacs@25.1
Error: No available formula with the name "emacs@25.1" 
==> Searching for a previously deleted formula...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
```

Is there some trick to that?

**Comment by jkitchin** [comment]
I think we will need separate queues for the kernels, or a more complex data structure that holds queue info.

**Comment by khinsen** [comment]
@jkitchin I installed Emacs 25.1 when it was the current one in Homebrew. Then I updated Homebrew, getting the 25.2 recipe, and installed that one. I didn't uninstall 25.1, which is why I have both. I don't know if there is a way to install 25.1 today without winding back to an earlier commit of Homebrew.

**Comment by khinsen** [comment]
@jkitchin I changed my version of the code to store the queue and the current task as a hash table using the session name as the index. Seems to work fine.

**Comment by jkitchin** [comment]
Subtle choice! I usually use alists out of familiarity but:

This will not work.
#+BEGIN_SRC emacs-lisp
(setq v1 '())
(setf (cdr (assoc 'key v1)) "Test")
v1
#+END_SRC

#+BEGIN_SRC emacs-lisp
(setq h1 (make-hash-table :test 'equal))
(setf (gethash "key" h1) "test")
h1
#+END_SRC

#+RESULTS:
: #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("key" "test"))

This only works if you use symbols because it uses eql for comparisons. It adds entries for string-based keys.

#+BEGIN_SRC emacs-lisp
(setq v1 '())
(setf (alist-get 'key3 v1) "Test")
v1
#+END_SRC

#+RESULTS:
: ((key3 . Test))
