### ISSUE TITLE
Inconsistent org babel ipython header args in structure template?

### ISSUE THREAD

**Issue by timehaven** [jkitchin/scimax#81]
Should `replace` be added to `org-structure-template-alist` in 
https://github.com/jkitchin/scimax/blob/master/scimax-org-babel-ipython.el ?

Line 11:

```
(add-to-list 'org-structure-template-alist
	     '("ip" "#+BEGIN_SRC ipython :session :results output drawer\n?\n#+END_SRC"
	       "<src lang=\"python\">\n?\n</src>"))
```

vs line 14:

```
(setq org-babel-default-header-args:ipython
      '((:results . "output replace drawer")
...
```

**Comment by jkitchin** [comment]
replace is the default I think, so it doesn't have to be explicitly set I think. At least for me, I get replace behavior without specifying it in the template.
