### ISSUE TITLE
Moving the cursor to the `begin_src ipython` line leads to an error

### ISSUE THREAD

**Issue by et2010** [jkitchin/scimax#85]
Toggle on `debug-on-error` and move the cursor to the `begin_src ipython` line will raise an error:

``` text
# move cursor to the following line:
#+begin_src ipython
print('test')
#+end_src
```
Note that if I add the `:session` argument explicitly, there will be no error.

The traceback is as follows:

![image](https://cloud.githubusercontent.com/assets/11584902/26828907/fd39f126-4af5-11e7-8e0b-628530497e0f.png)

and the result of evaling expression `(org-babel-get-session)` is `t` (not `"default"`).

**Comment by jkitchin** [comment]
Thanks for reporting that. The error had to do with org-eldoc and the default session value of t. It appears it needs to be a string. I have pushed a fix for it.

**Comment by et2010** [comment]
Thanks for the fix!
