### ISSUE TITLE
Export for ipython src blocks

### ISSUE THREAD

**Issue by roblem** [jkitchin/scimax#90]
BTW, loving scimax, particulary the work around asnych ipython block execution.

Consider an org file like this:
```python
#+BEGIN_SRC ipython :session :results output :exports both
print(1)
#+END_SRC
```
3 issues:
* Code blocks not exported to latex/pdf 
`C-c C-e l o` Results are exported, but no code is in the pdf.  Further investigation after exporting tex document, shows the `minted` code in the tex document as
```latex
\begin{minted}[frame=lines,fontsize=\scriptsize,linenos]{ipython}
print(1)
\end{minted}
```  
Shouldn't the lexer be `{python}` rather than `{ipython}`?  BTW, html exports as far as code blocks exporting works fine.

* Exported results are not exported as verbatim output block text in the latex pdf or as an output block in html, but rather as normal text.  

* Plain text exported results fail to preserve line breaks (this is also a problem in html exports) if results are multi-line (e.g. `df.head()`). I suspect this issue will be solved with the previous one.

**Comment by jkitchin** [comment]
We use ipython  for the lexer. You have to update pygments with this to make it work:

pip install git+git://github.com/sanguineturtle/pygments-ipython-console

The reason you do not get verbatim blocks I think is that the default result type in scimax for ipython is a drawer. The only way I have figured out to change this is to run this command:

```
#+BEGIN_SRC emacs-lisp
(setf (cdr (assoc :results org-babel-default-header-args:ipython))
      "output replace")
#+END_SRC
```

You could also just define them the way you want:
```

(setq org-babel-default-header-args:ipython
      '((:results . "output replace drawer")
	(:session . "ipython")
	(:exports . "both")
	(:cache .   "no")
	(:noweb . "no")
	(:hlines . "no")
	(:tangle . "no")
	(:eval . "never-export")))
```

**Comment by roblem** [comment]
Thanks.  That fixed everything.
