### ISSUE TITLE
File name not being captured for plot

### ISSUE THREAD

**Issue by Arjay-El** [jkitchin/scimax#93]
I have had trouble generating plots with proper file names. I have attached a screen capture of what I see and the test file I used. The plot name appears as a 4 word sequence ( I assume that's something internal?)
and the plot file name as shown, followed by the plot, followed by ]] to close out the statement.
Is there something I can do about this as I cannot actually find the output file for the plot which I stated to be "testplot2.png".

#+RESULTS: arkansas-red-autumn-lake
:RESULTS:
[[file:<matplotlib.figure.Figure at 0x183bcee20f0> Figure is shown here followed by ]]

 (see jpg screen capture attached).

![pythonplot_org_output](https://user-images.githubusercontent.com/11245879/26906383-e2a6ac94-4bba-11e7-8c40-7cdbaceb7ceb.jpg)
[pythonplot.txt](https://github.com/jkitchin/scimax/files/1059616/pythonplot.txt)

**Comment by jkitchin** [comment]
When I run your example, I find test2.png is created in the directory with the org-file. 

I also see what you see with the [[file....]]. That happens from the :file header. I think it doesn't make sense to use that with this way of using ipython. In the jupyter notebook for example, you would get an inline figure, but it would not be the test2.png, but a base64 encoded image with the same contents. That is what happens here too. The inline image is different than the test2.png file that gets created. In fact you can have many inline images created from a single src block, which is not possible with the file header.

What is your use case for using the :file header? I can see a way to be able to use it, but it isn't clear to me it is worth doing.

**Comment by Arjay-El** [comment]
My reasoning was that if I could not get a proper plot of the data, I would give the plot an explicit file name and then insert that file name after the code so I have it all in the document. What confuses me is the creation of the extra header line #name when the code is run and the plot file references. 

I ran your one of your plots in scimax.org and received similar results. In this case, there is no specified filename and nothing is saved that I can find. The #name header is inserted when the code is run (I am curious, where do they four word names come from?).  The plot was created twice as shown in one run.

![scimax_org_example](https://user-images.githubusercontent.com/11245879/26962008-30f81c9c-4cb1-11e7-894c-89d3afce767c.jpg)

Thanks John, any help appreciated.

**Comment by jkitchin** [comment]
The inline figures are saved in a folder called ipython-inline-images with automatically generated filenames. Try toggling the image display off to see the paths. The name is automatically created. The block is executed asynchronously, and the name is how it knows where to insert the results. If you set org-babel-async-ipython to nil, that should stop happening, but you will have to wait for the code to finish before you can type again.
