### ISSUE TITLE
improve control over Adding-keymaps-to-src-blocks-via-org-font-lock-hook

### ISSUE THREAD

**Issue by malcook** [jkitchin/scimax#96]
This is continuation of issue raised in commnents to [Adding keymaps to src blocks via org-font-lock-hook](http://kitchingroup.cheme.cmu.edu/blog/2017/06/10/Adding-keymaps-to-src-blocks-via-org-font-lock-hook/)

I now find that it works if my test.org has these 3 lines:

```
#+BEGIN_SRC python 
3
#+END_SRC
```
The python-mode keybindings are available to me inside the src block only, as desired.

Further, I note that the python menu comes and goes when I enter and leave the region. BUT ONLY IF I use the mouse to do so. Arrow key, control-f, etc, do NOT toggle the menu.

AND FURTHER, if I add to test.org at the beginning of the file the following R code block (which is not known to org at this point),

```
#+BEGIN_SRC R
3
#+END_SRC

```
My old problem returns. The mode is not switched inside the python block (regardless of how I enter the block)

I am testing minimally by launching emacs simply:

`emacs -Q --load Adding-keymaps-to-src-blocks-via-org-font-lock-hook.el --file test.org -f scimax-src-keymap-mode
`
where Adding-keymaps-to-src-blocks-via-org-font-lock-hook.el is your tangled source with only the following changes:

 + fix the (setq scimax-src-block-keymaps ... by commenting out the broken emacs-lisp case 
 + add a little initialization to the beginning:

```
(require 'package)
(package-initialize)
(require 'org)
```

FWIW: All this is true regardless of whether I include `-nw` when launching emacs.

I am using:

 + GNU Emacs 24.5.4
 + Org mode version 9.0.8 (9.0.8-elpa @ /home/mec/.emacs.d/elpa/org-plus-contrib-20170606/)

**Comment by jkitchin** [comment]
I think this should be fixed in the current master. But, there might be some emacs 25 specific code for the cursor-sensor-functions that are used.

**Comment by malcook** [comment]
In fresh install of emacs-26 from git head all succeeds.  Thanks!  This is brilliant.

**Comment by jkitchin** [comment]
great! thanks for trying it out.
