### ISSUE TITLE
Spellcheck isn't functioning

### ISSUE THREAD

**Issue by jboes** [jkitchin/scimax#97]
It would be nice to have this back. If you point me at the problem I'd be happy to take a shot at fixing it too, but I'm not sure where to begin.

**Comment by jkitchin** [comment]
on Windows, mac or linux?

**Comment by jboes** [comment]
Mac and linux. The flyspell-buffer command produces no results.

**Comment by jkitchin** [comment]
it is a good chance it means hunspell is not installed. on mac maybe you can try:

brew install hunspell

**Comment by jboes** [comment]
That fixed the issue on linux, but Mac is still giving me:

ispell-parse-hunspell-affix-file: ispell-phaf: No matching entry for en_US in ‘ispell-hunspell-dict-paths-alist’.

**Comment by jkitchin** [comment]
homebrew does not install the dictionaries unfortunately. I will send them to you separately.

```
==> Caveats
Dictionary files (*.aff and *.dic) should be placed in
~/Library/Spelling/ or /Library/Spelling/.  Homebrew itself
provides no dictionaries for Hunspell, but you can download
compatible dictionaries from other sources, such as
https://wiki.openoffice.org/wiki/Dictionaries .
```

**Comment by jboes** [comment]
This works now.

**Comment by jboes** [comment]
"i" doesn't seem to function correctly when adding a word to the dictionary on a Mac. Is this possible on Mac? There's no ivy/helm menu any longer to provide options either.

**Comment by jboes** [comment]
From email conversion for future reference:

"type C-c ; which will launch an ivy correction scheme. If the word is correct, you then type M-o which gives you the action menu and type s. I think this is from flyspell-correct-ivy."
