### ISSUE TITLE
"add scimax to your load path in your init file and just require what you want" fails with scimax-org

### ISSUE THREAD

**Issue by malcook** [jkitchin/scimax#98]
While following advice from README

"add scimax to your load path in your init file and just require what you want" 

I find that 
`(require 'scimax-org)
` 
fails as it requires scimax-dir to be set.

The following works in my init.el  (and also installed a few other things I found that scimax-org required that I did not already have in my fresh install of emacs 26 from git head.)

```
(use-package org-ref)
(use-package ob-ipython)
(use-package lispy)
(push "~mec/.dotfiles/emacs/.emacs.d/add-to-load-path/scimax" load-path)
(setq scimax-dir
      ;; require fails  - 
      "~mec/.dotfiles/emacs/.emacs.d/add-to-load-path/scimax")
(require 'scimax-org)
```

(push "~mec/.dotfiles/emacs/.emacs.d/add-to-load-path/scimax" load-path)
(setq scimax-dir
      ;; require fails  - 
      "~mec/.dotfiles/emacs/.emacs.d/add-to-load-path/scimax")
(require 'scimax-org)

**Comment by jkitchin** [comment]
Thanks for pointing that out. I forgot scimax-dir gets used here and there. I added this to the README.

**Comment by malcook** [comment]
glad to help.
