### ISSUE TITLE
adding new scimax-src-block-keymaps could be easier

### ISSUE THREAD

**Issue by malcook** [jkitchin/scimax#99]
What do you think instead of using strings to key this assoc list you use symbols...

If you did, then extending a new one for R after would be as easy as

```
(require 'scimax-org)	

(setf (alist-get 'R  scimax-src-block-keymaps) 
      (let ((map (make-composed-keymap `(, ess-mode-map org-mode-map))))
	(define-key map (kbd "C-c C-c") 'org-ctrl-c-ctrl-c)
	(define-key map (kbd "C-c '") 'org-edit-special)
	map))
```

Of course, any of your code that performs the lookup would have to convert the mode name ("ipython") to a symbol (ipython) such as with lisp's intern function.

Or perhaps you have a better form for extending the keymaps?

Cheers,

Malcolm

**Comment by jkitchin** [comment]
I think it is as easy as:

```
(add-to-list 'scimax-src-block-keymaps
	     `("R"  . ,(let ((map (make-composed-keymap `(, ess-mode-map org-mode-map))))
			 (define-key map (kbd "C-c C-c") 'org-ctrl-c-ctrl-c)
			 (define-key map (kbd "C-c '") 'org-edit-special)
			 map)))

```

It is a little more old-fashioned than what you propose, but also pretty standard.
